### ISSUE TITLE
[Bug]execute task report null pointer

### ISSUE THREAD

**Issue by fusu-qa** [apache/dolphinscheduler#10019]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

[INFO] 2022-05-13 01:17:54.787 TaskLogLogger-class org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor:[113] - task ready to submit: TaskInstance{id=1, name='dataqa', taskType='DATA_QUALITY', processInstanceId=1, processInstanceName='null', state=SUBMITTED_SUCCESS, firstSubmitTime=Fri May 13 01:17:54 UTC 2022, submitTime=Fri May 13 01:17:54 UTC 2022, startTime=null, endTime=null, host='null', executePath='null', logPath='null', retryTimes=0, alertFlag=NO, processInstance=ProcessInstance{id=1, state=RUNNING_EXECUTION, recovery=NO, startTime=Fri May 13 01:17:54 UTC 2022, endTime=null, runTimes=1, name='workflow01-1-20220513011754743', host='192.168.121.222:5678', processDefinition=ProcessDefinition{id=1, code=5500700871200, name='workflow01', version=1, releaseState=ONLINE, projectCode=5500682021792, description='', globalParams='[]', globalParamList=[], globalParamMap=null, createTime=Fri May 13 01:17:05 UTC 2022, updateTime=Fri May 13 01:17:05 UTC 2022, flag=YES, userId=1, userName='null', projectName='null', locations='[{"taskCode":5500690649888,"x":114,"y":158}]', scheduleReleaseState=null, timeout=0, tenantId=1, tenantCode='null', modifyBy='null', warningGroupId=0}, commandType=START_PROCESS, commandParam='{}', taskDependType=TASK_POST, maxTryTimes=0, failureStrategy=CONTINUE, warningType=ALL, warningGroupId=2, scheduleTime=null, commandStartTime=Fri May 13 01:17:53 UTC 2022, globalParams='null', executorId=1, tenantCode='null', queue='null', isSubProcess=NO, locations='[{"taskCode":5500690649888,"x":114,"y":158}]', historyCmd='START_PROCESS', dependenceScheduleTimes='null', duration=null, processInstancePriority=HIGHEST, workerGroup='work01', timeout=0, tenantId=1, processDefinitionCode='5500700871200', processDefinitionVersion='1', dryRun='0'}, restartTime='Fri May 13 01:17:54 UTC 2022', isBlocked=false}, processDefine=ProcessDefinition{id=1, code=5500700871200, name='workflow01', version=1, releaseState=ONLINE, projectCode=5500682021792, description='', globalParams='[]', globalParamList=[], globalParamMap=null, createTime=Fri May 13 01:17:05 UTC 2022, updateTime=Fri May 13 01:17:05 UTC 2022, flag=YES, userId=1, userName='null', projectName='null', locations='[{"taskCode":5500690649888,"x":114,"y":158}]', scheduleReleaseState=null, timeout=0, tenantId=1, tenantCode='null', modifyBy='null', warningGroupId=0}, pid=0, appLink='null', flag=YES, dependency='null', duration=null, maxRetryTimes=0, retryInterval=1, taskInstancePriority=HIGHEST, processInstancePriority=HIGHEST, dependentResult='null', workerGroup='work01', environmentCode=-1, environmentConfig='null', executorId=1, executorName='null', delayTime=0, dryRun=0}
[ERROR] 2022-05-13 01:17:54.819 TaskLogLogger-class org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor:[126] - submit task error
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.getDefaultDataSource(BaseTaskProcessor.java:461)
	at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.setWriterConfig(BaseTaskProcessor.java:488)
	at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.setDataQualityTaskRelation(BaseTaskProcessor.java:388)
	at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.getTaskExecutionContext(BaseTaskProcessor.java:279)
	at org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor.dispatchTask(CommonTaskProcessor.java:119)
	at org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor.submitTask(CommonTaskProcessor.java:70)
	at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.submit(BaseTaskProcessor.java:193)
	at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.action(BaseTaskProcessor.java:179)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.submitTaskExec(WorkflowExecuteThread.java:970)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.submitStandByTask(WorkflowExecuteThread.java:1810)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.submitPostNode(WorkflowExecuteThread.java:1326)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.startProcess(WorkflowExecuteThread.java:787)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 2022-05-13 01:17:54.820 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[1715] - remove task from stand by list, id: 1 name:dataqa
[INFO] 2022-05-13 01:17:56.407 org.apache.dolphinscheduler.api.aspect.AccessLogAspect:[90] - REQUEST TRACE_ID:30a2b548-a595-401b-8d39-f2c29a31dcaf, LOGIN_USER:admin, URI:/dolphinscheduler/projects/5500682021792/process-instances, METHOD:GET, HANDLER:org.apache.dolphinscheduler.api.controller.ProcessInstanceController.queryProcessInstanceList, ARGS:{processDefineCode=0, executorName=null, searchVal=null, projectCode=5500682021792, pageNo=1, stateType=null, host=null, pageSize=10, startTime=null, endTime=null}

### What you expected to happen

提交任务成功

### How to reproduce

提交一个数据质量空值规则的任务

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Related pr: #10021

**Comment by caishunfeng** [comment]
Hi @zhenglibao168 can you submit a pr to fix this issue?

**Comment by SbloodyS** [comment]
This issue has been fixed in #9974. I will close this.
