### ISSUE TITLE
[Bug] [Module Name] Failed to create tenant

### ISSUE THREAD

**Issue by yandong001** [apache/dolphinscheduler#10599]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/37573052/175518706-f12735c9-6d6a-40b7-a89c-72c34aabd45d.png)
[INFO] 2022-06-24 10:39:47.643 +0000 org.apache.dolphinscheduler.api.aspect.AccessLogAspect:[90] - REQUEST TRACE_ID:898148b3-2c1d-4858-8360-c0c54ee66854, LOGIN_USER:admin, URI:/dolphinscheduler/tenants, METHOD:POST, HANDLER:org.apache.dolphinscheduler.api.controller.TenantController.createTenant, ARGS:{queueId=1, description=, tenantCode=hadoop}
[ERROR] 2022-06-24 10:39:47.655 +0000 org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[47] - 创建租户错误
java.lang.NullPointerException: null
        at org.apache.dolphinscheduler.common.utils.HadoopUtils.mkdir(HadoopUtils.java:281)
        at org.apache.dolphinscheduler.common.utils.HadoopUtils.createTenantDirIfNotExists(HadoopUtils.java:256)
        at org.apache.dolphinscheduler.api.service.impl.TenantServiceImpl.createTenant(TenantServiceImpl.java:133)
        at org.apache.dolphinscheduler.api.service.impl.TenantServiceImpl$$FastClassBySpringCGLIB$$fcc8d845.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
        at org.apache.dolphinscheduler.api.service.impl.TenantServiceImpl$$EnhancerBySpringCGLIB$$db8da152.createTenant(<generated>)
        at org.apache.dolphinscheduler.api.controller.TenantController.createTenant(TenantController.java:91)
        at org.apache.dolphinscheduler.api.controller.TenantController$$FastClassBySpringCGLIB$$24aaa089.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
        at org.apache.dolphinscheduler.api.aspect.AccessLogAspect.doAround(AccessLogAspect.java:101)
        at sun.reflect.GeneratedMethodAccessor193.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
        at org.apache.dolphinscheduler.api.controller.TenantController$$EnhancerBySpringCGLIB$$13a35cde.createTenant(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:517)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
        at com.github.xiaoymin.swaggerbootstrapui.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:84)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at com.github.xiaoymin.swaggerbootstrapui.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:763)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.lang.Thread.run(Thread.java:748)

### What you expected to happen

创建用户也是不行的

### How to reproduce

租户创建失败

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @yandong001 , could you provide your deployment method and system? I can not reproduce this issue in my local environment.

**Comment by yandong001** [comment]
> 

伪集群部署

**Comment by YuanHang-1020** [comment]
这个问题解决了吗

**Comment by lifehacking** [comment]
k8s helm deploy
3.1.1 version  

create tenant error

api log:
[INFO] 2022-12-06 19:56:28.187 +0800 org.apache.dolphinscheduler.api.aspect.AccessLogAspect:[91] - REQUEST TRACE_ID:b6422f89-d011-4188-86ad-43362d70e336, LOGIN_USER:admin, URI:/dolphinscheduler/tenants/verify-code, METHOD:GET, HANDLER:org.apache.dolphinscheduler.api.controller.TenantController.verifyTenantCode, ARGS:{tenantCode=test}
[INFO] 2022-12-06 19:56:28.205 +0800 org.apache.dolphinscheduler.api.aspect.AccessLogAspect:[91] - REQUEST TRACE_ID:f5682945-ee5e-454e-b8b2-2f3c661fc8cb, LOGIN_USER:admin, URI:/dolphinscheduler/tenants, METHOD:POST, HANDLER:org.apache.dolphinscheduler.api.controller.TenantController.createTenant, ARGS:{queueId=1, description=, tenantCode=test}
[ERROR] 2022-12-06 19:56:28.209 +0800 org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[53] - create tenant error
java.lang.NullPointerException: null
        at org.apache.dolphinscheduler.service.storage.impl.HadoopUtils.mkdir(HadoopUtils.java:293)
        at org.apache.dolphinscheduler.service.storage.impl.HadoopUtils.createTenantDirIfNotExists(HadoopUtils.java:268)
        at org.apache.dolphinscheduler.api.service.impl.TenantServiceImpl.createTenant(TenantServiceImpl.java:160)
        at org.apache.dolphinscheduler.api.service.impl.TenantServiceImpl$$FastClassBySpringCGLIB$$fcc8d845.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)

**Comment by xshadowlegendx** [comment]
我也是今天剛用helm安裝這到google cloud, v3.1.2的也出現這問題

安裝步驟
```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
curl -sL https://dlcdn.apache.org/dolphinscheduler/3.1.2/apache-dolphinscheduler-3.1.2-src.tar.gz > tmp/dolphinscheduler.tar.gz
cd tmp && tar -zxvf tmp/dolphinscheduler.tar.gz
kubectl create ns dolphinscheduler
cd apache-dolphinscheduler-3.1.2-src/deploy/kubernetes/dolphinscheduler\
        && helm dependency update .\
	&& helm install -n dolphinscheduler dolphinscheduler .\
		--set image.tag=3.1.2\
                --set master.replicas=1\
                --set worker.replicas=1\
		--set 'api.annotations.dapr\.io/enabled=\'true\''\
		--set 'api.annotations.dapr\.io/app-id=dolphinscheduler'\
		--set 'api.annotations.dapr\.io/app-port=\'12345\''
```

`kubectl -n dolphinscheduler get pods`

```
W1222 16:32:00.367262   86785 gcp.go:119] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.26+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
NAME                                      READY   STATUS      RESTARTS       AGE
dolphinscheduler-alert-675fb46d9b-jf25r   1/1     Running     1 (5h8m ago)   5h8m
dolphinscheduler-api-676784f46-22pcv      2/2     Running     0              171m
dolphinscheduler-db-init-job-8hw6t        0/1     Completed   0              5h8m
dolphinscheduler-master-0                 1/1     Running     1 (176m ago)   3h43m
dolphinscheduler-postgresql-0             1/1     Running     0              5h8m
dolphinscheduler-worker-0                 1/1     Running     0              174m
dolphinscheduler-zookeeper-0              1/1     Running     0              5h8m
```

更新 - 我試了 v3.0.0 沒有這問題, 安裝方式一樣就改了 `image.tag=3.0.0`

**Comment by luozhifa** [comment]
> 我也是今天刚用helm安装到google cloud, v3.1.2的也出现这个问题
> 
> 安装步骤
> 
> ```
> helm repo add bitnami https://charts.bitnami.com/bitnami
> helm repo update
> curl -sL https://dlcdn.apache.org/dolphinscheduler/3.1.2/apache-dolphinscheduler-3.1.2-src.tar.gz > tmp/dolphinscheduler.tar.gz
> cd tmp && tar -zxvf tmp/dolphinscheduler.tar.gz
> kubectl create ns dolphinscheduler
> cd apache-dolphinscheduler-3.1.2-src/deploy/kubernetes/dolphinscheduler\
>         && helm dependency update .\
> 	&& helm install -n dolphinscheduler dolphinscheduler .\
> 		--set image.tag=3.1.2\
>                 --set master.replicas=1\
>                 --set worker.replicas=1\
> 		--set 'api.annotations.dapr\.io/enabled=\'true\''\
> 		--set 'api.annotations.dapr\.io/app-id=dolphinscheduler'\
> 		--set 'api.annotations.dapr\.io/app-port=\'12345\''
> ```
> 
> `kubectl -n dolphinscheduler get pods`
> 
> ```
> W1222 16:32:00.367262   86785 gcp.go:119] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.26+; use gcloud instead.
> To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
> NAME                                      READY   STATUS      RESTARTS       AGE
> dolphinscheduler-alert-675fb46d9b-jf25r   1/1     Running     1 (5h8m ago)   5h8m
> dolphinscheduler-api-676784f46-22pcv      2/2     Running     0              171m
> dolphinscheduler-db-init-job-8hw6t        0/1     Completed   0              5h8m
> dolphinscheduler-master-0                 1/1     Running     1 (176m ago)   3h43m
> dolphinscheduler-postgresql-0             1/1     Running     0              5h8m
> dolphinscheduler-worker-0                 1/1     Running     0              174m
> dolphinscheduler-zookeeper-0              1/1     Running     0              5h8m
> ```
> 
> 更新 - 我试了v3.0.0 没有这个问题,安装方式一改了`image.tag=3.0.0`
3.0.0有任务阻塞的问题，现在出了解决方法了吗

**Comment by aiwhj** [comment]
> > 我也是今天刚用helm安装到google cloud, v3.1.2的也出现这个问题
> > 安装步骤
> > ```
> > helm repo add bitnami https://charts.bitnami.com/bitnami
> > helm repo update
> > curl -sL https://dlcdn.apache.org/dolphinscheduler/3.1.2/apache-dolphinscheduler-3.1.2-src.tar.gz > tmp/dolphinscheduler.tar.gz
> > cd tmp && tar -zxvf tmp/dolphinscheduler.tar.gz
> > kubectl create ns dolphinscheduler
> > cd apache-dolphinscheduler-3.1.2-src/deploy/kubernetes/dolphinscheduler\
> >         && helm dependency update .\
> > 	&& helm install -n dolphinscheduler dolphinscheduler .\
> > 		--set image.tag=3.1.2\
> >                 --set master.replicas=1\
> >                 --set worker.replicas=1\
> > 		--set 'api.annotations.dapr\.io/enabled=\'true\''\
> > 		--set 'api.annotations.dapr\.io/app-id=dolphinscheduler'\
> > 		--set 'api.annotations.dapr\.io/app-port=\'12345\''
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `kubectl -n dolphinscheduler get pods`
> > ```
> > W1222 16:32:00.367262   86785 gcp.go:119] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.26+; use gcloud instead.
> > To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
> > NAME                                      READY   STATUS      RESTARTS       AGE
> > dolphinscheduler-alert-675fb46d9b-jf25r   1/1     Running     1 (5h8m ago)   5h8m
> > dolphinscheduler-api-676784f46-22pcv      2/2     Running     0              171m
> > dolphinscheduler-db-init-job-8hw6t        0/1     Completed   0              5h8m
> > dolphinscheduler-master-0                 1/1     Running     1 (176m ago)   3h43m
> > dolphinscheduler-postgresql-0             1/1     Running     0              5h8m
> > dolphinscheduler-worker-0                 1/1     Running     0              174m
> > dolphinscheduler-zookeeper-0              1/1     Running     0              5h8m
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 更新 - 我试了v3.0.0 没有这个问题,安装方式一改了`image.tag=3.0.0`
> > 3.0.0有任务阻塞的问题，现在出了解决方法了吗

需要手动配置下 HDFS，3.1.4 亲测解决
![image](https://user-images.githubusercontent.com/16408168/226570661-3a2ac6cb-5f98-4a3f-9494-c10cec353808.png)
