### ISSUE TITLE
[Bug] [Master] org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[264] - state handle error: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1

### ISSUE THREAD

**Issue by Weipleasure** [apache/dolphinscheduler#11035]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

版本2.0.5提交一个工作流后，只生成了工作流实例，没有生成task实例，查看master报错日志如下：
[INFO] 2022-07-19 09:29:46.625 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[301] - process event: State Event :key: null type: TASK_STATE_CHANGE executeStatus: SUCCESS task instance id: 379862 process instance id: 66858 context: null
[INFO] 2022-07-19 09:29:46.627 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[378] - work flow 66858 task 379862 state:SUCCESS
[ERROR] 2022-07-19 09:29:46.632 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[264] - state handle error:
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at org.apache.dolphinscheduler.dao.utils.DagHelper.skipTaskNode4Switch(DagHelper.java:409)
        at org.apache.dolphinscheduler.dao.utils.DagHelper.parseSwitchTask(DagHelper.java:398)
        at org.apache.dolphinscheduler.dao.utils.DagHelper.parsePostNodes(DagHelper.java:303)
        at org.apache.dolphinscheduler.dao.utils.DagHelper.parsePostNodes(DagHelper.java:322)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.submitPostNode(WorkflowExecuteThread.java:902)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.taskFinished(WorkflowExecuteThread.java:409)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.taskStateChangeHandler(WorkflowExecuteThread.java:362)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.stateEventHandler(WorkflowExecuteThread.java:312)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.handleEvents(WorkflowExecuteThread.java:260)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.run(WorkflowExecuteThread.java:241)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

### What you expected to happen

提交工作流后，生成工作流实例，生成task任务实例，task正常运行

### How to reproduce

创建工作流后，提交工作流运行。

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by qingzheguo-flash** [comment]
I have the same problem with dolphinscheduler 2.0.3, any updates?
