### ISSUE TITLE
Running the Seatunnel 2.x task with flink failed

### ISSUE THREAD

**Issue by liuyongfei1** [apache/dolphinscheduler#11066]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Use Seatunnel 2.x task with flink failed:
1.use Seatunnel 2.x task type
<img width="728" alt="Snipaste_2022-07-20_0" src="https://user-images.githubusercontent.com/4757906/179903253-0c6662d9-8e58-441b-aa40-0a97cbe5a9ed.png">

2. create node
<img width="451" alt="Snipaste_2022-07-20_-1" src="https://user-images.githubusercontent.com/4757906/179903320-e3ddaaa0-3372-41ab-be0c-34f46fef220c.png">
3.run task failed 

task node log:

	 The program finished with the following exception:
	
	org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Execute Flink task error
		at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372)
		at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
		at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
		at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:812)
		at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:246)
		at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054)
		at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
		at java.security.AccessController.doPrivileged(Native Method)
		at javax.security.auth.Subject.doAs(Subject.java:422)
		at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1876)
		at org.apache.flink.runtime.security.contexts.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
		at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)
	Caused by: org.apache.seatunnel.core.base.exception.CommandExecuteException: Execute Flink task error
		at org.apache.seatunnel.core.flink.command.FlinkApiTaskExecuteCommand.execute(FlinkApiTaskExecuteCommand.java:85)
		at org.apache.seatunnel.core.base.Seatunnel.run(Seatunnel.java:40)
		at org.apache.seatunnel.core.flink.SeatunnelFlink.main(SeatunnelFlink.java:34)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
		... 11 more
	Caused by: org.apache.flink.util.FlinkException: Failed to execute job 'seatunnel'.
		at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.executeAsync(StreamExecutionEnvironment.java:1969)
		at org.apache.flink.client.program.StreamContextEnvironment.executeAsync(StreamContextEnvironment.java:137)
		at org.apache.flink.client.program.StreamContextEnvironment.execute(StreamContextEnvironment.java:76)
		at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.java:1833)
		at org.apache.seatunnel.flink.stream.FlinkStreamExecution.start(FlinkStreamExecution.java:75)
		at org.apache.seatunnel.core.flink.command.FlinkApiTaskExecuteCommand.execute(FlinkApiTaskExecuteCommand.java:82)
		... 18 more
	Caused by: org.apache.flink.runtime.client.JobSubmissionException: Failed to submit JobGraph.
		at org.apache.flink.client.program.rest.RestClusterClient.lambda$submitJob$9(RestClusterClient.java:405)
		at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:884)
		at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:866)
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
		at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
		at org.apache.flink.runtime.concurrent.FutureUtils.lambda$retryOperationWithDelay$9(FutureUtils.java:390)
		at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
		at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
		at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
		at org.apache.flink.runtime.rest.RestClient.lambda$submitRequest$1(RestClient.java:430)
		at org.apache.flink.shaded.netty4.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
		at org.apache.flink.shaded.netty4.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
		at org.apache.flink.shaded.netty4.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
		at org.apache.flink.shaded.netty4.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
		at org.apache.flink.shaded.netty4.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
		at org.apache.flink.shaded.netty4.io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
		at org.apache.flink.shaded.netty4.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
		at org.apache.flink.shaded.netty4.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
		at org.apache.flink.shaded.netty4.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
		at org.apache.flink.shaded.netty4.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
		at org.apache.flink.shaded.netty4.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
		at org.apache.flink.shaded.netty4.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
		at org.apache.flink.shaded.netty4.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
		at org.apache.flink.shaded.netty4.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
		at org.apache.flink.shaded.netty4.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: org.apache.flink.runtime.concurrent.FutureUtils$RetryException: Could not complete the operation. Number of retries has been exhausted.
		at org.apache.flink.runtime.concurrent.FutureUtils.lambda$retryOperationWithDelay$9(FutureUtils.java:386)
		... 21 more
	Caused by: java.util.concurrent.CompletionException: org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8081
		at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
		at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
		at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:957)
		at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
		... 19 more
	Caused by: org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8081
	Caused by: java.net.ConnectException: Connection refused
		at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
		at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
		at org.apache.flink.shaded.netty4.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
		at org.apache.flink.shaded.netty4.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
		at org.apache.flink.shaded.netty4.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
		at org.apache.flink.shaded.netty4.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
		at org.apache.flink.shaded.netty4.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
		at org.apache.flink.shaded.netty4.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
		at org.apache.flink.shaded.netty4.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
		at org.apache.flink.shaded.netty4.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at java.lang.Thread.run(Thread.java:748)
[INFO] 2022-07-20 13:08:09.365 +0800 [taskAppId=TASK-20220720-6245205626176_1-8-8] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.seatunnel.flink.SeatunnelFlinkTask:[57] - FINALIZE_SESSION

### What you expected to happen

seatunnel task can  successfully executed。

### How to reproduce

1.
<img width="728" alt="Snipaste_2022-07-20_0" src="https://user-images.githubusercontent.com/4757906/179904442-04bd1aae-432d-42c2-9379-bb7650f1b13d.png">
2.
<img width="451" alt="Snipaste_2022-07-20_-1" src="https://user-images.githubusercontent.com/4757906/179904664-6d169f6c-4b70-4d3e-a9c9-d0d7bade25c9.png">
3.
<img width="564" alt="Snipaste_2022-07-20_2-0" src="https://user-images.githubusercontent.com/4757906/179904934-ee9f963d-d772-4780-a84b-bd1d1aef8975.png">
4.
<img width="566" alt="Snipaste_2022-07-20_2" src="https://user-images.githubusercontent.com/4757906/179904679-e7831087-6b7e-4253-8e3a-e5d169a5fe9b.png">

### Anything else

No response

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
```
Connection refused: localhost/127.0.0.1:8081
```
Could you check it?

**Comment by liuyongfei1** [comment]
> 1、直接在服务器上使用命令行提交，是可以跑成功的。
2、这个8081端口是flink web服务吗？可是都没有提交到yarn集群上啊。
