### ISSUE TITLE
[Bug] [3.0.0-beta-2] custom parameter does not work in spark plugin sql task

### ISSUE THREAD

**Issue by fforever14** [apache/dolphinscheduler#11071]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I create a spark sql task to run a spark sql to insert data to another table.
I add a custom parameter and run the task, it failed, the log showed there was a null pointer exception.

> [ERROR] 2022-07-20 07:56:30.177 +0000 [taskAppId=TASK-20220720-6246094233696_12-28-70] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.spark.SparkTask:[53] - yarn process failure
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.plugin.task.api.parameters.AbstractParameters.getInputLocalParametersMap(AbstractParameters.java:96)
	at org.apache.dolphinscheduler.plugin.task.api.parser.ParamUtils.convert(ParamUtils.java:64)
	at org.apache.dolphinscheduler.plugin.task.spark.SparkTask.buildCommand(SparkTask.java:120)
	at org.apache.dolphinscheduler.plugin.task.api.AbstractYarnTask.handle(AbstractYarnTask.java:48)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:180)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

### What you expected to happen

I think It shoud run properly. But It failed, and It seemed not submit the job to yarn.

### How to reproduce

just create a spark task, set "Program Type" to "SQL", use a custom parameter, and run it.

### Anything else

I check the database to compare this task and a normally SQL task, I found that in "t_ds_task_definition" table, the json field "localParam" in task_param field lack 2 properties: direct and type
I add the properties manually and rerun the task, it works.

I think the issue is caused by the frontend, when add a custom parameter, there should have 4 properties, but spark task can only input 2 of them, the others didn't have default value.
I didn't know much about frontend, I think someone should fix it.

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @fforever14 can you add detail of the workflow and task define? which can help others to reproduce.

**Comment by fforever14** [comment]
![image](https://user-images.githubusercontent.com/4794313/180751800-0d9328a8-fee4-4107-a8a5-fd8e6a7b3926.png)
I use just this param, you can write any SQL in editor. It will run in exception before submit the task.
![image](https://user-images.githubusercontent.com/4794313/180752103-c50d7b94-e960-40a4-87f9-91345c9cfce6.png)

**Comment by caishunfeng** [comment]
I will submit a pr to fix this issue.

**Comment by caishunfeng** [comment]
I found it's just error in 3.0.0 branch and dev is ok. So I will fix in 3.0.0 branch.

**Comment by caishunfeng** [comment]
> I found it's just error in 3.0.0 branch and dev is ok. So I will fix in 3.0.0 branch.

The dev also has this issue, so keep this issue open until dev fix.
