### ISSUE TITLE
[Bug] [Worker] send kill response command error

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#11175]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

```
[INFO] 2022-07-27 17:55:06.171 +0800 TaskLogLogger-class org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor:[171] - [WorkflowInstance-33][TaskInstance-0] - master kill taskInstance name :trigger taskInstance id:67
[INFO] 2022-07-27 17:55:06.172 +0800 org.apache.dolphinscheduler.server.worker.processor.TaskKillProcessor:[90] - [WorkflowInstance-0][TaskInstance-0] - task kill command : TaskKillRequestCommand{taskInstanceId=67}
[INFO] 2022-07-27 17:55:06.172 +0800 org.apache.dolphinscheduler.server.worker.processor.TaskKillProcessor:[177] - [WorkflowInstance-0][TaskInstance-0] - kill task by cancelApplication, task id:67
[ERROR] 2022-07-27 17:55:06.172 +0800 org.apache.dolphinscheduler.remote.handler.NettyServerHandler:[131] - [WorkflowInstance-0][TaskInstance-0] - process msg Command [type=TASK_KILL_REQUEST, opaque=851, bodyLen=21] error
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.server.worker.processor.TaskKillProcessor.sendTaskKillResponseCommand(TaskKillProcessor.java:127)
	at org.apache.dolphinscheduler.server.worker.processor.TaskKillProcessor.process(TaskKillProcessor.java:106)
	at org.apache.dolphinscheduler.remote.handler.NettyServerHandler.lambda$processReceived$0(NettyServerHandler.java:129)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### What you expected to happen

send kill response command without error

### How to reproduce

1. create a long time executing workflow with a sql task
2. run workflow
3. stop the workflow instance

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
It seems caused by the appIds in TaskExecutionContext is null.
