### ISSUE TITLE
[Bug] [Task] Dependent task null point exception when check workflow instances

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#11531]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

```
[INFO] 2022-08-17 18:31:40.442 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[686] - [WorkflowInstance-67][TaskInstance-0] - workflowStatue changed to :INITIALIZE_QUEUE
[INFO] 2022-08-17 18:31:40.442 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[1713] - [WorkflowInstance-67][TaskInstance-0] - add task to stand by list, task name:dent, task id:0, task code:6566535787872
[INFO] 2022-08-17 18:31:40.444 +0800 org.apache.dolphinscheduler.service.process.ProcessServiceImpl:[1300] - [WorkflowInstance-67][TaskInstance-0] - Start save taskInstance to database : dent, processInstance id:67, state: RUNNING_EXECUTION
[INFO] 2022-08-17 18:31:40.448 +0800 org.apache.dolphinscheduler.service.process.ProcessServiceImpl:[1318] - [WorkflowInstance-67][TaskInstance-0] - End save taskInstance to db successfully:120, taskInstanceName: dent, taskInstance state:SUBMITTED_SUCCESS, processInstanceId:67, processInstanceState: RUNNING_EXECUTION
[ERROR] 2022-08-17 18:31:40.471 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[996] - [WorkflowInstance-67][TaskInstance-0] - submit standby task error, taskCode: 6566535787872, taskInstanceId: 120
java.lang.NullPointerException: null
 at org.apache.dolphinscheduler.server.utils.DependentExecute.findLastProcessInterval(DependentExecute.java:202)
 at org.apache.dolphinscheduler.server.utils.DependentExecute.calculateResultForTasks(DependentExecute.java:112)
 at org.apache.dolphinscheduler.server.utils.DependentExecute.getDependentResultForItem(DependentExecute.java:97)
 at org.apache.dolphinscheduler.server.utils.DependentExecute.getDependResultForItem(DependentExecute.java:288)
 at org.apache.dolphinscheduler.server.utils.DependentExecute.getModelDependResult(DependentExecute.java:266)
 at org.apache.dolphinscheduler.server.utils.DependentExecute.finish(DependentExecute.java:249)
 at org.apache.dolphinscheduler.server.master.runner.task.DependentTaskProcessor.allDependentTaskFinish(DependentTaskProces
```

### What you expected to happen

Dependent task keep running and check until success.

### How to reproduce

1. Create a workflow A with task a, a is a long running task.
2. Execute A manually.
3. Set a pre-min schedule and wait for one A workflow instance schedule.
4. Now, we have two A workflow instance running.
5. Create a workflow B with a dependent task b, which depend on A.a.
6. Execute B manually.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
close by #11424
