### ISSUE TITLE
[Bug] [task failed]  task of Data_Quality failed

### ISSUE THREAD

**Issue by zeaper123** [apache/dolphinscheduler#12042]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

dolphinscheduler version: 3.0.0
spark version: 2.4.6

After I installed dolphinscheduler，I can submit the normal spark parogram to yarn without any errors，
But task of Data_Quality moudle failed when I try to run 

error.log:
...
[INFO] 2022-09-19 05:53:30.749 +0000 [taskAppId=TASK-20220919-6883854994784_7-53-69] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.dq.DataQualityTask:[375] - find app id: application_1658747363765_133740
[INFO] 2022-09-19 05:53:30.749 +0000 [taskAppId=TASK-20220919-6883854994784_7-53-69] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.dq.DataQualityTask:[205] - process has exited, execute path:/data/dolphinscheduler3/datasrv/exec/process/6798312686816/6883854994784_7/53/69, processId:22623 ,exitStatusCode:1 ,processWaitForStatus:true ,processExitValue:1
[INFO] 2022-09-19 05:53:31.598 +0000 [taskAppId=TASK-20220919-6883854994784_7-53-69] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.dq.DataQualityTask:[63] -  -> 22/09/19 13:53:30 INFO Client: Application report for application_1658747363765_133740 (state: FINISHED)
	22/09/19 13:53:30 INFO Client: 
		 client token: N/A
		 diagnostics: User class threw exception: java.lang.NoSuchMethodError: org.apache.hadoop.hive.shims.HadoopShims.getHadoopConfNames()Ljava/util/Map;
		at org.apache.hadoop.hive.ql.io.orc.OrcInputFormat.<clinit>(OrcInputFormat.java:117)
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:348)
		at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
		at org.apache.spark.sql.hive.client.HiveClientImpl$.org$apache$spark$sql$hive$client$HiveClientImpl$$toInputFormat(HiveClientImpl.scala:912)
		at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$toHiveTable$6.apply(HiveClientImpl.scala:948)
		at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$toHiveTable$6.apply(HiveClientImpl.scala:948)
		at scala.Option.map(Option.scala:146)
		at org.apache.spark.sql.hive.client.HiveClientImpl$.toHiveTable(HiveClientImpl.scala:948)
		at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$getPartitionsByFilter$1.apply(HiveClientImpl.scala:680)
		at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$getPartitionsByFilter$1.apply(HiveClientImpl.scala:679)
		at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$withHiveState$1.apply(HiveClientImpl.scala:277)
...

I have confirmed that there is org.apache.hadoop.hive.shims.HadoopShims in hive-shims-common.2.3.6.jar, but org.apache.hadoop.hive.shims.HadoopShims does not have getHadoopConfNames function.

### What you expected to happen

run success

### How to reproduce

waiting for solution

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zeaper123** [comment]
I have replaced spark2.4.6 with spark2.4.0
