### ISSUE TITLE
[Bug] [k8s] pod/dolphinscheduler-alert-xx pod  deploy error

### ISSUE THREAD

**Issue by edwardhuanghz** [apache/dolphinscheduler#12240]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

kubectl get po,sts,svc,cm,deploy,secret,pvc,pv   -n jufund 
# output 
NAME                                         READY   STATUS      RESTARTS   AGE    IP               NODE     NOMINATED NODE   READINESS GATES
pod/dolphinscheduler-alert-f77d558dc-58n6m   0/1     Error       3          2m1s   10.100.242.141   cdh-02   <none>           <none>

kubectl logs pod/dolphinscheduler-xx -n jufund
[WARN] 2022-10-01 10:01:22.965 +0800 org.springframework.cloud.kubernetes.fabric8.config.Fabric8ConfigMapPropertySource:[105] - Can't read configMap with name: [alert-server] in namespace: [jufund]. Ignoring.
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/api/v1/namespaces/jufund/configmaps/alert-server. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. configmaps "alert-server" is forbidden: User "system:serviceaccount:jufund:default" cannot get resource "configmaps" in API group "" in the namespace "jufund".

### What you expected to happen

pod/dolphinscheduler-alert pod run ok

### How to reproduce

k8s deploy ,with self-hadoop ha env.

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ChenpiDog** [comment]
![7d26764688ae5a3db6e8eacd8fc378a](https://user-images.githubusercontent.com/55483982/193461344-be990146-ba3c-437e-af48-8f3d2a114066.jpg)
I also have this problem here. The Pod always has problems.

**Comment by drummerglen** [comment]
I encountered this problem too. Here is the screen shot
<img width="1909" alt="image" src="https://user-images.githubusercontent.com/42017338/193845954-06fe4001-2692-4a11-95aa-8e02a033a744.png">

other logs:
```
[INFO] 2022-10-04 22:15:23.896 +0800 org.apache.dolphinscheduler.common.utils.PropertyUtils:[69] - Overriding property from system property: java.vm.version
[INFO] 2022-10-04 22:15:23.896 +0800 org.apache.dolphinscheduler.common.utils.PropertyUtils:[69] - Overriding property from system property: java.runtime.name
[WARN] 2022-10-04 22:15:24.251 +0800 org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext:[591] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'storageOperate' defined in class path resource [org/apache/dolphinscheduler/common/config/StoreConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.dolphinscheduler.common.storage.StorageOperate]: Factory method 'storageOperate' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
[INFO] 2022-10-04 22:15:24.252 +0800 org.apache.dolphinscheduler.alert.AlertServer:[98] - Alert server is stopping, cause: alert server destroy
[ERROR] 2022-10-04 22:15:27.253 +0800 org.apache.dolphinscheduler.alert.AlertServer:[107] - Alert server stop failed, cause: alert server destroy
java.lang.NullPointerException: null
        at org.apache.dolphinscheduler.alert.AlertServer.destroy(AlertServer.java:104)
        at org.apache.dolphinscheduler.alert.AlertServer.close(AlertServer.java:80)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeDestroyMethods(InitDestroyAnnotationBeanPostProcessor.java:347)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeDestruction(InitDestroyAnnotationBeanPostProcessor.java:177)
        at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:197)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1161)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1154)
        at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1106)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:596)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164)
        at org.apache.dolphinscheduler.alert.AlertServer.main(AlertServer.java:64)
[INFO] 2022-10-04 22:15:27.259 +0800 com.zaxxer.hikari.HikariDataSource:[350] - DolphinScheduler - Shutdown initiated...
[INFO] 2022-10-04 22:15:27.273 +0800 com.zaxxer.hikari.HikariDataSource:[352] - DolphinScheduler - Shutdown completed.
[INFO] 2022-10-04 22:15:27.281 +0800 org.eclipse.jetty.server.session:[149] - node0 Stopped scavenging
[INFO] 2022-10-04 22:15:27.283 +0800 org.eclipse.jetty.server.handler.ContextHandler:[1159] - Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@2326180c{application,/,[file:///tmp/jetty-docbase.50053.2358154205542615818/],STOPPED}
[INFO] 2022-10-04 22:15:27.304 +0800 org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener:[136] - 
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[ERROR] 2022-10-04 22:15:27.346 +0800 org.springframework.boot.SpringApplication:[824] - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'storageOperate' defined in class path resource [org/apache/dolphinscheduler/common/config/StoreConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.dolphinscheduler.common.storage.StorageOperate]: Factory method 'storageOperate' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:486)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
Exception in thread "Alert-Server" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'storageOperate' defined in class path resource [org/apache/dolphinscheduler/common/config/StoreConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.dolphinscheduler.common.storage.StorageOperate]: Factory method 'storageOperate' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:486)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164)
        at org.apache.dolphinscheduler.alert.AlertServer.main(AlertServer.java:64)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.dolphinscheduler.common.storage.StorageOperate]: Factory method 'storageOperate' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
        ... 18 common frames omitted
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164)
        at org.apache.dolphinscheduler.alert.AlertServer.main(AlertServer.java:64)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.dolphinscheduler.common.storage.StorageOperate]: Factory method 'storageOperate' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
        ... 18 more
Caused by: java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
        at org.apache.dolphinscheduler.common.config.StoreConfiguration.storageOperate(StoreConfiguration.java:55)
        at org.apache.dolphinscheduler.common.config.StoreConfiguration$$EnhancerBySpringCGLIB$$93ff6242.CGLIB$storageOperate$0(<generated>)
        at org.apache.dolphinscheduler.common.config.StoreConfiguration$$EnhancerBySpringCGLIB$$93ff6242$$FastClassBySpringCGLIB$$c60139f4.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
        at org.apache.dolphinscheduler.common.config.StoreConfiguration$$EnhancerBySpringCGLIB$$93ff6242.storageOperate(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
        at org.apache.dolphinscheduler.common.config.StoreConfiguration.storageOperate(StoreConfiguration.java:55)
        at org.apache.dolphinscheduler.common.config.StoreConfiguration$$EnhancerBySpringCGLIB$$93ff6242.CGLIB$storageOperate$0(<generated>)
        at org.apache.dolphinscheduler.common.config.StoreConfiguration$$EnhancerBySpringCGLIB$$93ff6242$$FastClassBySpringCGLIB$$c60139f4.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
        at org.apache.dolphinscheduler.common.config.StoreConfiguration$$EnhancerBySpringCGLIB$$93ff6242.storageOperate(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 19 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.conf.Configuration
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 30 common frames omitted
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 19 more
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.conf.Configuration
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 30 more
```

**Comment by lgcareer** [comment]
@caishunfeng @ruanwenjun @chengshiwen  Hi,  Could you please check this issue?thx.

**Comment by caishunfeng** [comment]
I think the reason is alert-server init `StoreConfiguration`, which it doesn't need to do.

You can try to remove the common properties in `templates/deployment-dolphinscheduler-alert.yaml`.

**Comment by apache-kun** [comment]
test no use

**Comment by liqiquan** [comment]
> I think the reason is alert-server init `StoreConfiguration`, which it doesn't need to do.
> 
> You can try to remove the common properties in `templates/deployment-dolphinscheduler-alert.yaml`.

@caishunfeng 

If RESOURCE_STORAGE_TYPE=HDFS is set, the master fails to operate init storageOperate:
java.lang.NoClassDefFoundError: com/amazonaws/services/s3/model/AmazonS3Exception

1. In the common module, there is init StoreConfiguration.

2. If RESOURCE_STORAGE_TYPE=HDFS, hadoop-related packages are required: hadoop-common&hadoop-client; RESOURCE_STORAGE_TYPE=S3, the jar of aws-java-sdk-s3 is required.

3. However, in the pom of the common module, hadoop-common&hadoop-client and aws-java-sdk-s3 have scope set to provided, thus losing transitionality. Therefore, if the packages that reference the common module need the hadoop and aws-java-sdk-s3 packages, they need to be added again separately.



May I ask which way will be used to solve this problem?

1. The jars of hadoops-Common&Hadoop-Client and aws-java-sdk-s3 are added separately for modules such as master and alter.

2.common module pom, scope without provided

3. StoreConfiguration is no longer init in the master and alter modules

----------------------------
如果设置RESOURCE_STORAGE_TYPE=HDFS，master也会出现init storageOperate失败：
java.lang.NoClassDefFoundError: com/amazonaws/services/s3/model/AmazonS3Exception

在common模块中，有init StoreConfiguration的操作。
如果RESOURCE_STORAGE_TYPE=HDFS，需要hadoop相关的包: hadoop-common&hadoop-client；RESOURCE_STORAGE_TYPE=S3，则需要aws-java-sdk-s3的jar。
但是在common模块的pom中，hadoop-common&hadoop-client和aws-java-sdk-s3的scope被设置为provided，失去了传递性，所以引用common模块的包如果需要hadoop和aws-java-sdk-s3包，需要单独再次添加。

请问针此问题，后面会采用那种方式解决：
1.master和alter等模块单独添加，hadoop-common&hadoop-client和aws-java-sdk-s3的jar。
2.common模块的pom中，scope去掉provided
3.master和alter等模块中不再init StoreConfiguration

**Comment by xfworld** [comment]
3.0.5 currently also has this problem, more pit
***
3.0.5 目前也有这个问题，比较坑
