### ISSUE TITLE
[Bug] [Workflow Definition] copy workflow error

### ISSUE THREAD

**Issue by jamescheng16** [apache/dolphinscheduler#12274]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

press copy workflow button get an error. here's log
![Screen Shot 2022-10-09 at 14 18 46](https://user-images.githubusercontent.com/4263914/194741387-8e829736-54a7-4b40-af3b-5d4fd6a6c5f2.png)
`[ERROR] 2022-10-09 06:18:41.012 +0000 org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[53] - 复制工作流错误
org.springframework.dao.DuplicateKeyException: 
### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "t_ds_schedules_pkey"
  Detail: Key (id)=(2) already exists.
### Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "t_ds_schedules_pkey"
  Detail: Key (id)=(2) already exists.
; ERROR: duplicate key value violates unique constraint "t_ds_schedules_pkey"
  Detail: Key (id)=(2) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "t_ds_schedules_pkey"
  Detail: Key (id)=(2) already exists.
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:247)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy138.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:59)`

### What you expected to happen

successfully copy workflow

### How to reproduce

just press copy workflow

### Anything else

user pg as database

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jackfanwan** [comment]
@SbloodyS Hi, can you assign it to me?
