### ISSUE TITLE
[Bug] [k8s] null exception when submitting k8s task plugin

### ISSUE THREAD

**Issue by rickchengx** [apache/dolphinscheduler#12356]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

* Null exception in master's log
```
[ERROR] 2022-10-13 15:51:10.327 +0800 TaskLogLogger-class org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor:[135] - Task dd is submitted to priority queue error
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.service.process.ProcessServiceImpl.findConfigYamlByName(ProcessServiceImpl.java:3175)
	at org.apache.dolphinscheduler.service.process.ProcessServiceImpl$$FastClassBySpringCGLIB$$9d3e18f9.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.apache.dolphinscheduler.service.process.ProcessServiceImpl$$EnhancerBySpringCGLIB$$e4fb2474.findConfigYamlByName(<generated>)
	at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.setK8sTaskRelation(BaseTaskProcessor.java:659)
	at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.getTaskExecutionContext(BaseTaskProcessor.java:329)
	at org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor.dispatchTask(CommonTaskProcessor.java:123)
	at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.dispatch(BaseTaskProcessor.java:241)
	at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.action(BaseTaskProcessor.java:212)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitTaskExec(WorkflowExecuteRunnable.java:980)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitStandByTask(WorkflowExecuteRunnable.java:1832)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitPostNode(WorkflowExecuteRunnable.java:1360)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.call(WorkflowExecuteRunnable.java:695)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### What you expected to happen

submit k8s task plugin without null exception

### How to reproduce

* create cluster
<img width="1456" alt="截屏2022-10-13 16 03 56" src="https://user-images.githubusercontent.com/38122586/195538282-f36e1fbd-fb2e-4867-8741-7913d2c4f4d4.png">

* create k8s namespace
<img width="1453" alt="截屏2022-10-13 16 04 01" src="https://user-images.githubusercontent.com/38122586/195538294-6107919b-24c1-4e5a-80d6-e0ab85bb38da.png">

* run a k8s task plugin, and failed
<img width="367" alt="image" src="https://user-images.githubusercontent.com/38122586/195538992-f9568903-8ccf-4be9-a57a-50c062ea8605.png">

### Anything else

version: dev, 3.1.0

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by rickchengx** [comment]
It seems that `ProcessServiceImpl.findConfigYamlByName` wants to query the table `t_ds_k8s`, but actually this table is empty.

https://github.com/apache/dolphinscheduler/blob/22103f975ebe3d3697c9173013356cab8548a1c6/dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java#L3168-L3176

After my check, `t_ds_cluster` is inserted when creating cluster (step 1) and `t_ds_k8s_namespace` is inserted when creating k8s namespace (step 2).

But I don't know what's the usage of table `t_ds_k8s`, could anyone help me?

**Comment by songjianet** [comment]
Please confirm if this issue exists in 30x.

**Comment by caishunfeng** [comment]
> Please confirm if this issue exists in 30x.

No, the k8s task plugin does not exist in 30x.
