### ISSUE TITLE
Schedulered process with custom params fails

### ISSUE THREAD

**Issue by KINGGUOKUN** [apache/dolphinscheduler#12370]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When task craeted with custom params, and set process with timescheduler, the process instance fail; 
manully trigger it, and success.
Schedulered process without custom params als success.

Master exception log as follows：
 TaskLogLogger-class org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor:[125] - [WorkflowInstance-54][TaskInstance-0] - submit task error
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "cmdParam" is null
        at org.apache.dolphinscheduler.service.expand.CuringGlobalParams.paramParsingPreparation(CuringGlobalParams.java:154)
        at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.getTaskExecutionContext(BaseTaskProcessor.java:336)
        at org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor.dispatchTask(CommonTaskProcessor.java:113)
        at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.dispatch(BaseTaskProcessor.java:241)
        at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.action(BaseTaskProcessor.java:212)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitTaskExec(WorkflowExecuteRunnable.java:976)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitStandByTask(WorkflowExecuteRunnable.java:1816)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitPostNode(WorkflowExecuteRunnable.java:1349)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.call(WorkflowExecuteRunnable.java:695)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)

### What you expected to happen

Process with custom params can run successfully.

### How to reproduce

1、Create a process；
2、Drag a Sql task in the process definition, and add some custom parameters to the task;
3、Save the process；
4、Set the process with a scheduler；

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
English is needed, please add the title and update content

**Comment by KINGGUOKUN** [comment]
> English is needed, please add the title and update content

Thanks for your reply. I have update the content, please review again.

**Comment by hstdream** [comment]
<img width="446" alt="1665736953404" src="https://user-images.githubusercontent.com/33045461/195803289-60c11410-a34d-4124-8bdd-76b7f6565056.png">
<img width="572" alt="1665737023343" src="https://user-images.githubusercontent.com/33045461/195803558-cc067c19-4a7d-4861-b83a-6458b2fcd3e1.png">

I didn't find any problems here. It is recommended to provide the following specific operation steps. thanks

**Comment by KINGGUOKUN** [comment]
![image](https://user-images.githubusercontent.com/12315104/196067466-ac185ec6-ca1b-4424-b11e-13a22402902b.png)

And do add cron based scheduler to the process.
![image](https://user-images.githubusercontent.com/12315104/196067552-6dad54d4-e201-49cc-badc-3fcb69c53553.png)

Then the result like this:
![image](https://user-images.githubusercontent.com/12315104/196067688-e9425eaa-ec8a-4212-8b24-aed836a71ff7.png)
![image](https://user-images.githubusercontent.com/12315104/196067711-18846caa-dc77-425f-871c-13e734e6c3ad.png)

**Comment by zhuangchong** [comment]
I understand your question is the same issue as this issue #12408, which has been fixed.

**Comment by KINGGUOKUN** [comment]
Yes, exactly. So, I'll close it.
