### ISSUE TITLE
[Bug] [Alert] Send script alert NPE

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#12439]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

```
[ERROR] 2022-10-19 16:41:53.938 +0800 org.apache.dolphinscheduler.alert.AlertSenderService:[272] - send alert error alert data id :48,
java.lang.NullPointerException: null
        at org.apache.dolphinscheduler.plugin.alert.script.ScriptSender.executeShellScript(ScriptSender.java:75)
        at org.apache.dolphinscheduler.plugin.alert.script.ScriptSender.sendScriptAlert(ScriptSender.java:47)
        at org.apache.dolphinscheduler.plugin.alert.script.ScriptAlertChannel.process(ScriptAlertChannel.java:35)
        at org.apache.dolphinscheduler.alert.AlertSenderService.alertResultHandler(AlertSenderService.java:252)
        at org.apache.dolphinscheduler.alert.AlertSenderService.send(AlertSenderService.java:112)
        at org.apache.dolphinscheduler.alert.AlertSenderService.run(AlertSenderService.java:79)
```
![image](https://user-images.githubusercontent.com/11962619/196652722-448814d5-6eb1-45b2-a201-f2e43e44c7ac.png)

### What you expected to happen

can run script alert success.

### How to reproduce

add a script alert plugin without setting user params.
![image](https://user-images.githubusercontent.com/11962619/196653015-fcf896b1-3c0d-4807-8643-6fcd73f1ef3f.png)

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
If no one is in charge, i'd like to try it!

**Comment by caishunfeng** [comment]
> If no one is in charge, i'd like to try it!

OK, had assigned to you.
