### ISSUE TITLE
[Bug] [service.expand] submit task error java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by xfworld** [apache/dolphinscheduler#12527]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

`
[INFO] 2022-10-25 18:20:00.719 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[687] - [WorkflowInstance-66][TaskInstance-0] - workflowStatue changed to :INITIALIZE_DAG
[INFO] 2022-10-25 18:20:00.719 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[1952] - [WorkflowInstance-66][TaskInstance-0] - The workflowInstance has been executed before, this execution is to reRun, processInstance status: WorkflowExecutionStatus{code=0, desc='submit success'}, runTimes: 1
[INFO] 2022-10-25 18:20:00.719 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[813] - [WorkflowInstance-66][TaskInstance-0] - The workflowInstance is not a newly running instance, runtimes: 1, recover flag: NO
[INFO] 2022-10-25 18:20:00.720 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[908] - [WorkflowInstance-66][TaskInstance-0] - Initialize task queue, dependFailedTaskSet: [], completeTaskMap: {}, errorTaskMap: {}
[INFO] 2022-10-25 18:20:00.720 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[692] - [WorkflowInstance-66][TaskInstance-0] - workflowStatue changed to :INITIALIZE_QUEUE
[INFO] 2022-10-25 18:20:00.720 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[1714] - [WorkflowInstance-66][TaskInstance-0] - add task to stand by list, task name:bi_unopen_outbound_report全量, task id:null, task code:7326187784256
[INFO] 2022-10-25 18:20:00.721 +0800 org.apache.dolphinscheduler.service.process.ProcessServiceImpl:[1308] - [WorkflowInstance-66][TaskInstance-0] - Start save taskInstance to database : bi_unopen_outbound_report全量, processInstance id:66, state: WorkflowExecutionStatus{code=0, desc='submit success'}
[INFO] 2022-10-25 18:20:00.724 +0800 org.apache.dolphinscheduler.service.process.ProcessServiceImpl:[1326] - [WorkflowInstance-66][TaskInstance-0] - End save taskInstance to db successfully:95, taskInstanceName: bi_unopen_outbound_report全量, taskInstance state:TaskExecutionStatus{code=0, desc='submit success'}, processInstanceId:66, processInstanceState: WorkflowExecutionStatus{code=0, desc='submit success'}
[INFO] 2022-10-25 18:20:00.734 +0800 org.apache.dolphinscheduler.service.process.ProcessServiceImpl:[2979] - [WorkflowInstance-66][TaskInstance-0] - Success rob taskGroup, taskInstanceId: 95, taskGroupId: 1
[INFO] 2022-10-25 18:20:00.737 +0800 org.apache.dolphinscheduler.service.process.ProcessServiceImpl:[2961] - [WorkflowInstance-66][TaskInstance-0] - Success acquire taskGroup, taskInstanceId: 95, taskGroupId: 1
[INFO] 2022-10-25 18:20:00.738 +0800 TaskLogLogger-class org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor:[106] - [WorkflowInstance-66][TaskInstance-0] - task ready to dispatch to worker: taskInstanceId: 95
[ERROR] 2022-10-25 18:20:00.741 +0800 TaskLogLogger-class org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor:[125] - [WorkflowInstance-66][TaskInstance-0] - submit task error
java.lang.NullPointerException: null
        at org.apache.dolphinscheduler.service.expand.CuringGlobalParams.paramParsingPreparation(CuringGlobalParams.java:154)
        at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.getTaskExecutionContext(BaseTaskProcessor.java:336)
        at org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor.dispatchTask(CommonTaskProcessor.java:113)
        at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.dispatch(BaseTaskProcessor.java:241)
        at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.action(BaseTaskProcessor.java:212)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitTaskExec(WorkflowExecuteRunnable.java:976)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitStandByTask(WorkflowExecuteRunnable.java:1816)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitPostNode(WorkflowExecuteRunnable.java:1349)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.call(WorkflowExecuteRunnable.java:695)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
`

### What you expected to happen

Define a process instance, then start the scheduled task, and observe whether the task runs at the specified time. The above error occurs after running

### How to reproduce

version 3.1.0
K8S Env
Mysql 8.0.30
helm Chart install

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
hi @xfworld ， this PR:https://github.com/apache/dolphinscheduler/pull/12419 may has fixed this case

**Comment by xfworld** [comment]
3Q~ 
wait to  publish new version....
