### ISSUE TITLE
[Bug] [Module Name] Scheduled scheduling failure  

### ISSUE THREAD

**Issue by Sky-Gu** [apache/dolphinscheduler#12557]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

If a workflow is upgraded from 3.0.0 to 3.1.0 and global parameters are set, the scheduled scheduling of the workflow fails。

### What you expected to happen

A scheduled task can be executed properly

### How to reproduce

The emergence process is as follows:

1. Set a global parameter for the workflow, the storage field in the database is t_ds_process_definition.global_params = [{"prop":"param1","value":"$[yyyy-MM-dd -1]","direct":"IN","type":"VARCHAR"}]
2. The data records for different versions of this workflow are t_ds_process_definition_log.global_params  = t_ds_process_definition.global_params 
3. A scheduled task triggers the execution workflow
4. The stored data for this workflow instance is  t_ds_process_instance.command_param=null
5. This will lead to the following NPE, which cannot proceed normally

[ERROR] 2022-10-26 22:40:00.678 +0800 TaskLogLogger-class org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor:[125] - [WorkflowInstance-41564][TaskInstance-0] - submit task error
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.service.expand.CuringGlobalParams.paramParsingPreparation(CuringGlobalParams.java:154)
	at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.getTaskExecutionContext(BaseTaskProcessor.java:336)
	at org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor.dispatchTask(CommonTaskProcessor.java:113)
	at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.dispatch(BaseTaskProcessor.java:241)
	at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.action(BaseTaskProcessor.java:212)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitTaskExec(WorkflowExecuteRunnable.java:976)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitStandByTask(WorkflowExecuteRunnable.java:1816)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitPostNode(WorkflowExecuteRunnable.java:1349)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.call(WorkflowExecuteRunnable.java:695)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
 

### Anything else

This is an extremely serious problem, and no temporary solution is in sight

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
This issue has been resolved in pr #12419, I will close this issue, if you still have problems, you can open this issue again.

**Comment by Sky-Gu** [comment]
@zhuangchong Is there a way to temporarily handle the problem?  The current situation would result in abandoning version 3.1.0 and falling back to version 3.0.0

**Comment by zhuangchong** [comment]
> @zhuangchong Is there a way to temporarily handle the problem? The current situation would result in abandoning version 3.1.0 and falling back to version 3.0.0

There are two ways: 
1. cherry-pick this pr to the 3.1.0 branch for packaging; 
2. directly use the 3.1.1-prepare branch to package;

**Comment by Sky-Gu** [comment]
Thanks for the support, temporarily rollback to version 3.0.0. Look forward to the next release.

**Comment by zhuangchong** [comment]
> Thanks for the support, temporarily rollback to version 3.0.0. Look forward to the next release.

Version 3.1.1 will be officially released in early November.

**Comment by ChewJ404** [comment]
[process.zip](https://github.com/apache/dolphinscheduler/files/9929624/process.zip)

replace  is right
