### ISSUE TITLE
[Bug] [dolphinscheduler-server] dependent task keep retry even there is runtime exception thow out

### ISSUE THREAD

**Issue by lordk911** [apache/dolphinscheduler#12561]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

upgrade from 2.0.5 to dolphin 2.0.7

![image](https://user-images.githubusercontent.com/19989300/198186299-4fd65dd6-d8b7-4d5a-8bfa-d954d9219a3a.png)

the task submit 02:35 , and keep retry even there is runtime exception thow out , untill restart dolphin and kill the task.
actually the depended on process have been success already.

the log looks like :
![image](https://user-images.githubusercontent.com/19989300/198187053-280b3562-6e3d-4ba2-b68d-e44f1c62575f.png)

the exception is : 

`[ERROR] 2022-10-27 02:35:02.289 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[750] - submit standby task error
java.lang.IllegalStateException: Duplicate key load_data
        at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
        at java.util.HashMap.merge(HashMap.java:1254)
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.apache.dolphinscheduler.server.utils.DependentExecute.dependResultByProcessInstance(DependentExecute.java:150)
        at org.apache.dolphinscheduler.server.utils.DependentExecute.calculateResultForTasks(DependentExecute.java:126)
        at org.apache.dolphinscheduler.server.utils.DependentExecute.getDependentResultForItem(DependentExecute.java:100)
        at org.apache.dolphinscheduler.server.utils.DependentExecute.getDependResultForItem(DependentExecute.java:314)
        at org.apache.dolphinscheduler.server.utils.DependentExecute.getModelDependResult(DependentExecute.java:292)
        at org.apache.dolphinscheduler.server.utils.DependentExecute.finish(DependentExecute.java:275)
        at org.apache.dolphinscheduler.server.master.runner.task.DependentTaskProcessor.allDependentTaskFinish(DependentTaskProcessor.java:194)
        at org.apache.dolphinscheduler.server.master.runner.task.DependentTaskProcessor.runTask(DependentTaskProcessor.java:106)
        at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.run(BaseTaskProcessor.java:194)
        at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.action(BaseTaskProcessor.java:173)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.submitTaskExec(WorkflowExecuteThread.java:726)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.submitStandByTask(WorkflowExecuteThread.java:1495)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.submitPostNode(WorkflowExecuteThread.java:1001)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.startProcess(WorkflowExecuteThread.java:604)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.run(WorkflowExecuteThread.java:248)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`

### What you expected to happen

faild when a runtime exception happen , if it faild, at least I can force it to success.

### How to reproduce

I don't know what data is Duplicated , but it's well in dolphin 2.0.5.

### Version

2.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lordk911** [comment]
- the root reason is **https://github.com/apache/dolphinscheduler/issues/8790#issuecomment-1098620438**

- the [https://dolphinscheduler.apache.org/zh-cn/docs/release/faq.html](url) about : `Q：Update process definition error: Duplicate key TaskDefinition`  **method can't resolve this scenario** 

two way to resove this issue maybe : 

1.  https://github.com/apache/dolphinscheduler/blob/873cbc75c6dc9da16e3e1e61abb751fab8fd009f/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/DependentExecute.java#L142

    **taskRelations build from t_ds_process_definition not from t_ds_process_task_relation_log**

2. join t_ds_process_task_relation_log and t_ds_process_definition get the difference set from t_ds_process_task_relation_log and delete.
   sql like :  
```
DELETE  FROM  t_ds_process_task_relation_log 
WHERE  id IN 
    (   SELECT 
            rl.id 
        FROM
            dolphinscheduler.t_ds_process_task_relation_log rl 
        LEFT JOIN 
            dolphinscheduler.t_ds_process_task_relation r
        ON
            rl.process_definition_code = r.process_definition_code
        AND rl.process_definition_version = r.process_definition_version
        AND rl.pre_task_code = r.pre_task_code
        AND rl.pre_task_version = r.pre_task_version
        AND rl.post_task_code = r.post_task_code
        AND rl.post_task_version = r.post_task_version
        WHERE 
            r.id IS NULL
        AND rl.process_definition_code=3755309715595 
        AND rl.process_definition_version=1 )
```
@JinyLeeChina @caishunfeng @SbloodyS
