### ISSUE TITLE
[Bug] [v3.1.0] SP task cannot be triggered by normally

### ISSUE THREAD

**Issue by jim6745** [apache/dolphinscheduler#12745]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when I create a workflow , and want to let it run by schedule , but the first job (sp job) can not by triggered

### What you expected to happen

I expected the first job on the workflow can be triggered auto

### How to reproduce

when I try to create  workflow , and the workflow contain some  sqlserver sp jobs , and I create a schedule job on it by time , 
but it cannot be  triggered by time

### Anything else

I try to find some logs  , it is below

[ERROR] 2022-11-07 01:55:00.732 +0000 TaskLogLogger-class org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor:[125] - [WorkflowInstance
-95][TaskInstance-0] - submit task error
java.lang.NullPointerException: null
        at org.apache.dolphinscheduler.service.expand.CuringGlobalParams.paramParsingPreparation(CuringGlobalParams.java:154)
        at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.getTaskExecutionContext(BaseTaskProcessor.java:336)
        at org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor.dispatchTask(CommonTaskProcessor.java:113)
        at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.dispatch(BaseTaskProcessor.java:241)
        at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.action(BaseTaskProcessor.java:212)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitTaskExec(WorkflowExecuteRunnable.java:976)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitStandByTask(WorkflowExecuteRunnable.java:1816)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitPostNode(WorkflowExecuteRunnable.java:1349)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.call(WorkflowExecuteRunnable.java:695)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[ERROR] 2022-11-07 01:55:00.732 +0000 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[978] - [WorkflowInstance-95][TaskInstance-0]
- process id:95 name:wf_dws_ps_hps-13-20221107015500540 dispatch standby task id:231 name:sp_dim_organization_hier_d failed!
[ERROR] 2022-11-07 01:55:00.732 +0000 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[1830] - [WorkflowInstance-95][TaskInstance-0]
 - Task submitted failed, workflowInstanceId: 95, taskInstanceId: 231, taskCode: 7328366703744
[INFO] 2022-11-07 01:55:00.733 +0000 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[1498] - [WorkflowInstance-95][TaskInstance-0]
- The current process has failed task, the current process failed
[INFO] 2022-11-07 01:55:00.733 +0000 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[1601] - [WorkflowInstance-95][TaskInstance-0]
- The workflowInstance is failed, the workflow status is WorkflowExecutionStatus{code=6, desc='failure'}
[INFO] 2022-11-07 01:55:00.733 +0000 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[1645] - [WorkflowInstance-95][TaskInstance-0]
- Update workflowInstance states, origin state: WorkflowExecutionStatus{code=0, desc='submit success'}, target state: WorkflowExecutionStatus{code=6, desc='f
ailure'}

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ikiwixx** [comment]
I also encountered this problem. I tried to remove the custom parameters in the task node, so that the task can run. This may provide some help.

**Comment by jim6745** [comment]
thanks ikiwixx ， yes ， after I removed the custom parameters ， the job can be triggered normally ， but I still need the custom parameters in project ， I also the issue also happen on sql task node
