### ISSUE TITLE
[Bug]An error is reported when running data_quality: extraneous input 'FROM' expecting<EOF>(line 1, pos 25)

### ISSUE THREAD

**Issue by FE-wangjb** [apache/dolphinscheduler#12778]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I encountered the same problem as #12235  . I simply executed a [nullcheck] and could not pass in the src_ table.
The error is reported as follows:
2022-11-07 16:15:18 INFO  HiveClientImpl:54 - Warehouse location for Hive client (version 1.2.2) is /user/hive/warehouse
	Exception in thread "main" org.apache.spark.sql.catalyst.parser.ParseException: 
	extraneous input 'FROM' expecting <EOF>(line 1, pos 25)
	
	== SQL ==
	SELECT COUNT(*) AS total FROM  
	-------------------------^^^
	
		at org.apache.spark.sql.catalyst.parser.ParseException.withCommand(ParseDriver.scala:241)
		at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:117)
		at org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:48)
		at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parsePlan(ParseDriver.scala:69)
		at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:642)
		at org.apache.dolphinscheduler.data.quality.flow.batch.transformer.SqlTransformer.transform(SqlTransformer.java:60)
		at org.apache.dolphinscheduler.data.quality.execution.SparkBatchExecution.executeTransformer(SparkBatchExecution.java:112)
		at org.apache.dolphinscheduler.data.quality.execution.SparkBatchExecution.execute(SparkBatchExecution.java:53)
		at org.apache.dolphinscheduler.data.quality.context.DataQualityContext.execute(DataQualityContext.java:62)
		at org.apache.dolphinscheduler.data.quality.DataQualityApplication.main(DataQualityApplication.java:70)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
		at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
		at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
		at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
		at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
		at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
		at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
		at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
	2022-11-07 16:15:19 INFO  SparkContext:54 - Invoking stop() from shutdown hook
	2022-11-07 16:15:19 INFO  AbstractConnector:318 - Stopped Spark@7bef452c{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}

### What you expected to happen

I use the cluster set up by CDH6.3.2, but Dolphinscheduler submits Spark jobs using the native Spark2.4.0 that I integrate later. I don't know whether this has any impact

### How to reproduce

1. Configure the hive data source
2. Configure workflow definition in project management
3. Select DATA_ QUALITY
4. Configure a NullCheck according to the official document example
5. Save and launch the workflow, and then run it

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lugela** [comment]
I'm also getting the same error

**Comment by FE-wangjb** [comment]
The cause of the problem was found. It was caused by the wrong type of the expected value calculated by myself. Close the questionnaire!
