### ISSUE TITLE
[Bug] [server] task retry throws NullPointerException

### ISSUE THREAD

**Issue by ChPi** [apache/dolphinscheduler#12870]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened
```
[INFO] 2022-11-11 09:49:41.677 +0000 org.apache.dolphinscheduler.server.master.runner.StateWheelExecuteThread:[344] - [TaskInstance-null]The task instance can
 retry, will retry this task instance
[ERROR] 2022-11-11 09:49:41.678 +0000 org.apache.dolphinscheduler.server.master.runner.StateWheelExecuteThread:[353] - Check task retry error, taskInstanceKey
: TaskInstanceKey(processInstanceId=2, taskCode=7517199067616, taskVersion=2)
java.lang.NullPointerException: null
        at org.apache.dolphinscheduler.server.master.runner.StateWheelExecuteThread.addTaskRetryEvent(StateWheelExecuteThread.java:422)
        at org.apache.dolphinscheduler.server.master.runner.StateWheelExecuteThread.checkTask4Retry(StateWheelExecuteThread.java:349)
        at org.apache.dolphinscheduler.server.master.runner.StateWheelExecuteThread.run(StateWheelExecuteThread.java:105)
[INFO] 2022-11-11 09:49:46.680 +0000 org.apache.dolphinscheduler.server.master.runner.StateWheelExecuteThread:[344] - [TaskInstance-null]The task instance can
 retry, will retry this task instance
[ERROR] 2022-11-11 09:49:46.681 +0000 org.apache.dolphinscheduler.server.master.runner.StateWheelExecuteThread:[353] - Check task retry error, taskInstanceKey
: TaskInstanceKey(processInstanceId=2, taskCode=7517199067616, taskVersion=2)
java.lang.NullPointerException: null
        at org.apache.dolphinscheduler.server.master.runner.StateWheelExecuteThread.addTaskRetryEvent(StateWheelExecuteThread.java:422)
        at org.apache.dolphinscheduler.server.master.runner.StateWheelExecuteThread.checkTask4Retry(StateWheelExecuteThread.java:349)
        at org.apache.dolphinscheduler.server.master.runner.StateWheelExecuteThread.run(StateWheelExecuteThread.java:105)
```

 task retry throws NullPointerException。
the `taskInstanceId` type  of class `TaskStateEvent` is int, but set null when retry a task, should it be Integer？

### What you expected to happen

retry success

### How to reproduce

create a http retry task， then run

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hstdream** [comment]
Please provide detailed error log.

**Comment by ChPi** [comment]
> Please provide detailed error log.

```
[INFO] 2022-11-11 09:49:41.677 +0000 org.apache.dolphinscheduler.server.master.runner.StateWheelExecuteThread:[344] - [TaskInstance-null]The task instance can
 retry, will retry this task instance
[ERROR] 2022-11-11 09:49:41.678 +0000 org.apache.dolphinscheduler.server.master.runner.StateWheelExecuteThread:[353] - Check task retry error, taskInstanceKey
: TaskInstanceKey(processInstanceId=2, taskCode=7517199067616, taskVersion=2)
java.lang.NullPointerException: null
        at org.apache.dolphinscheduler.server.master.runner.StateWheelExecuteThread.addTaskRetryEvent(StateWheelExecuteThread.java:422)
        at org.apache.dolphinscheduler.server.master.runner.StateWheelExecuteThread.checkTask4Retry(StateWheelExecuteThread.java:349)
        at org.apache.dolphinscheduler.server.master.runner.StateWheelExecuteThread.run(StateWheelExecuteThread.java:105)
[INFO] 2022-11-11 09:49:46.680 +0000 org.apache.dolphinscheduler.server.master.runner.StateWheelExecuteThread:[344] - [TaskInstance-null]The task instance can
 retry, will retry this task instance
[ERROR] 2022-11-11 09:49:46.681 +0000 org.apache.dolphinscheduler.server.master.runner.StateWheelExecuteThread:[353] - Check task retry error, taskInstanceKey
: TaskInstanceKey(processInstanceId=2, taskCode=7517199067616, taskVersion=2)
java.lang.NullPointerException: null
        at org.apache.dolphinscheduler.server.master.runner.StateWheelExecuteThread.addTaskRetryEvent(StateWheelExecuteThread.java:422)
        at org.apache.dolphinscheduler.server.master.runner.StateWheelExecuteThread.checkTask4Retry(StateWheelExecuteThread.java:349)
        at org.apache.dolphinscheduler.server.master.runner.StateWheelExecuteThread.run(StateWheelExecuteThread.java:105)
```

**Comment by ruanwenjun** [comment]
If the task instance Id is null, means the task instance has not been submit, it shouldn't retry.

**Comment by ChPi** [comment]
> If the task instance Id is null, means the task instance has not been submit, it shouldn't retry.

retry task will `cloneRetryTaskInstance` that do not set id.
will retry task generate a new id and insert into table  `t_ds_task_instance` rather than updating the old record?

**Comment by ruanwenjun** [comment]
> > If the task instance Id is null, means the task instance has not been submit, it shouldn't retry.
> 
> retry task will `cloneRetryTaskInstance` that do not set id. will retry task generate a new id and insert into table `t_ds_task_instance` rather than updating the old record?

Yes, it will insert a new task instance
