### ISSUE TITLE
SQL task prepareStatementAndBind error

### ISSUE THREAD

**Issue by yandong001** [apache/dolphinscheduler#13085]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

升级3.0.2版本后，执行工作流报错
[INFO] 2022-12-03 21:37:31.579 +0800 - can't find udf function resource
[ERROR] 2022-12-03 21:38:01.634 +0800 - execute sql error: SQL task prepareStatementAndBind error
[ERROR] 2022-12-03 21:38:01.634 +0800 - sql task error
org.apache.dolphinscheduler.plugin.task.api.TaskException: SQL task prepareStatementAndBind error
	at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.prepareStatementAndBind(SqlTask.java:395)
	at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.executeUpdate(SqlTask.java:329)
	at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.executeFuncAndSql(SqlTask.java:202)
	at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.handle(SqlTask.java:158)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:208)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.prepareStatementAndBind(SqlTask.java:381)
	... 11 common frames omitted

### What you expected to happen

是否存在超时问题

### How to reproduce

历史数据为1.x版本，之后升级3.0.2，升级完成后执行历史数据的任务

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
English is needed

**Comment by yandong001** [comment]
The historical data is 1.x, and 3.0.2 is later upgraded. After the upgrade, the historical data is executed

**Comment by yandong001** [comment]
> 需要英语

Where do you need me to translate English

**Comment by yandong001** [comment]
Changing the configuration file /conf/application.yaml does not take effect, and an error is still reported

java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30059ms.

**Comment by Guojcc** [comment]
哈喽，问题解决了嘛，我也遇到了相同的问题

**Comment by yandong001** [comment]
解决了，那得看你的问题了，SQL task prepareStatementAndBind error这是个笼统的报错，你看下你的worker服务的日志




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dolphinscheduler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月15日(星期四) 晚上11:12
***@***.***&gt;;
抄送:&nbsp;"笗 *^_^* ***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dolphinscheduler] SQL task prepareStatementAndBind error (Issue #13085)





 
哈喽，问题解决了嘛，我也遇到了相同的问题

**Comment by Guojcc** [comment]
[WorkflowInstance-3185][TaskInstance-9802] - get druidDataSource Connection fail SQLException: HikariPool-2 - Connection is not available, request timed out after 30000ms.

我这边看了，跟您的问题一样，我是连接Oracle。我怀疑是jdbc有问题，我用的是jdbc8

**Comment by Guojcc** [comment]
我设置了，work 的并行度，设置为8之后，就不会有这个报错了，但是我没找到问题在哪里

**Comment by yandong001** [comment]
我的问题是会一直连接，导致超时，你可以试一下，重编打包





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dolphinscheduler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月20日(星期二) 下午5:26
***@***.***&gt;;
抄送:&nbsp;"笗 *^_^* ***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dolphinscheduler] SQL task prepareStatementAndBind error (Issue #13085)





 
[WorkflowInstance-3185][TaskInstance-9802] - get druidDataSource Connection fail SQLException: HikariPool-2 - Connection is not available, request timed out after 30000ms.
 
我这边看了，跟您的问题一样，我是连接Oracle。我怀疑是jdbc有问题，我用的是jdbc8

**Comment by Guojcc** [comment]
我不会重新打包 ,我是直接拿来用的 0.o

**Comment by hjfrank1991** [comment]
org.apache.dolphinscheduler.plugin.datasource.hive.HiveDataSourceClient:[156] - get oneSessionDataSource Connection fail SQLException: HikariPool-3 - Connection is not available, request timed out after 35560ms.
java.sql.SQLTransientConnectionException: HikariPool-3 - Connection is not available, request timed out after 35560ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at org.apache.dolphinscheduler.plugin.datasource.hive.HiveDataSourceClient.getConnection(HiveDataSourceClient.java:154)
	at org.apache.dolphinscheduler.plugin.datasource.api.plugin.DataSourceClientProvider.getConnection(DataSourceClientProvider.java:66)
	at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.executeFuncAndSql(SqlTask.java:254)
	at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.handle(SqlTask.java:228)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:250)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLTimeoutException: Query timed out after 5 seconds
	at org.apache.hive.jdbc.HiveStatement.waitForOperationToComplete(HiveStatement.java:375)
	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:254)
	at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:169)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
	... 14 common frames omitted

**Comment by liushuaihang** [comment]
I wonder if anyone has solved this problem?
