### ISSUE TITLE
Task Execution : SQL task prepareStatementAndBind error

### ISSUE THREAD

**Issue by yandong001** [apache/dolphinscheduler#13119]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### **An error occurred during task execution**
[INFO] 2022-12-06 20:10:30.129 +0800 - can't find udf function resource
[ERROR] 2022-12-06 20:11:00.179 +0800 - execute sql error: SQL task prepareStatementAndBind error
[ERROR] 2022-12-06 20:11:00.179 +0800 - sql task error
org.apache.dolphinscheduler.plugin.task.api.TaskException: SQL task prepareStatementAndBind error
	at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.prepareStatementAndBind(SqlTask.java:395)
	at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.executeUpdate(SqlTask.java:329)
	at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.executeFuncAndSql(SqlTask.java:192)
	at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.handle(SqlTask.java:158)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:208)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.prepareStatementAndBind(SqlTask.java:381)
	... 11 common frames omitted

### Check error information reported in worker logs
[ERROR] 2022-12-06 20:11:00.133 +0800 org.apache.dolphinscheduler.plugin.datasource.hive.HiveDataSourceClient:[162] - [WorkflowInstance-1287][TaskInstance-1885] - get oneSessionDataSource Connection fail SQLException: HikariPool-1 - Connection is not available, request timed out after 30059ms.
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30059ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
        at org.apache.dolphinscheduler.plugin.datasource.hive.HiveDataSourceClient.getConnection(HiveDataSourceClient.java:152)
        at org.apache.dolphinscheduler.plugin.datasource.api.plugin.DataSourceClientProvider.getConnection(DataSourceClientProvider.java:81)
        at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.executeFuncAndSql(SqlTask.java:185)
        at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.handle(SqlTask.java:158)
        at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:208)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLTimeoutException: Query timed out after 5 seconds
        at org.apache.hive.jdbc.HiveStatement.waitForOperationToComplete(HiveStatement.java:345)
        at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:251)
        at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:169)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
        ... 14 common frames omitted

### What you expected to happen

The /conf/application.yaml file of each service was modified. Hikari link timeout configuration did not take effect. After bin/env/dolphinscheduler_env.sh was configured, Will application.yaml file not take effect? Looks like it.

### How to reproduce

Configure hive data sources, create multiple workflows, and execute them in sequence

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yandong001** [comment]
Why does the HikariPool configuration in the conf/application.yaml file not take effect

**Comment by DarkAssassinator** [comment]
because system env will override yml file in Springboot

**Comment by ChewJ404** [comment]
The same problem
version:3.1.0 
`
localParams : [],udfs : ,showType : null,connParams : null,varPool : [] 


org.apache.dolphinscheduler.plugin.task.api.TaskException: SQL task prepareStatementAndBind error
	at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.prepareStatementAndBind(SqlTask.java:367)
	at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.executeUpdate(SqlTask.java:301)
	at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.executeFuncAndSql(SqlTask.java:200)
	at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.handle(SqlTask.java:156)

Caused by: org.apache.dolphinscheduler.plugin.task.api.TaskException: SQL task prepareStatementAndBind error
Caused by: java.lang.NullPointerException: null
`
Please help me how to find the cause of parameter failure

**Comment by pijiupapa** [comment]
face the same problem.
When running a spark sql task and yarn hasn't enough resource to allocated, i got this error after 30s.
so i have to avoid multiple tasks running in the same time,it's really confusing me.

**Comment by zhaohehuhu** [comment]
not working after increasing the timeout

**Comment by gzqcason** [comment]
Hey guys, I've also encountered the same problem. any good solution？ BR！

**Comment by bluewaterstar** [comment]
Is there a solution? I have the same problem

**Comment by devhh** [comment]
Is there a solution? I have the same problem
