### ISSUE TITLE
[Bug] [Workflow] Schedule Timing trigger workflow definition with global variables execute failed

### ISSUE THREAD

**Issue by zuzuviewer** [apache/dolphinscheduler#13156]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Schedule Timing trigger workflow definition with global variables execute failed

### What you expected to happen

Schedule Timing trigger workflow definition with global variables execute  success 

### How to reproduce

1. Create workflow definition with global variables, e.x key is 'a',value is 'b'
2. Timing for this workflow definition, e.x '* * * * * ? *'
3. Wait schedule trigger it, and workflow instance will execute failed

### Anything else

exception：

`[INFO] TaskLogLgger-class org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor:[106] - [WorkflowInstance-69][TaskInstance-0] - task ready to dispatch to worker: taskInstanceId:71
[ERROR] TaskLogLgger-class org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor:[125] - [WorkflowInstance-69][TaskInstance-0] - submit task error java.lang.Nul1PointerException: null
at org.apache.dolphinscheduler.service.expand.CuringGlobalParams.paramParsinPreparation(CuringGlobalParams.java:154)
at org.apache.dolphinscheduler.server.master .runner.task.BaseTaskProcessor.getTaskExecutionContext (BaseTaskProcessor.java:336)
at org.apache.dolphinscheduler.server .master.runner.task.CommonTaskProcessor.dispatchTask(CommonTaskProcessor.java:1l3)
at org.apache.dolphinscheduler.server.master. runner.task.BaseTaskProcessor.dispatch(BaseTaskProcessor.java:241)
at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.action(BaseTaskProcessor.java:212)
at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitTaskExec(WorkflowExecuteRunnable. java:976)
at org.apache.dolphinscheduler.server.master.runner. WorkflowExecuteRunnable.submitStandByTask(Wor kflowExecuteRunNable.iava:1816)
at org.apache.dolphinscheduler.server.master.runner .WorkflowExecuteRunnable.submitPostNode(WorkflowExecuteRunnable.java:1349)
at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.call(WorkflowExecuteRunnable.java:695)
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:l604)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
at java.lang.Thread.run (Thread.java : 750)
[ERROR] org.apache.dolphinscheduler.server.amster.runner.WorkflowExecuteRunnable:[978] - [WorkflowInstance-69][TaskInstance-0] - process id:69 name:testpost4-3-20221207160501014 dispatch standby task id:71 name:metadata-ingestion-task failed!
[ERROR]org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[1830] - [WorkflowInstance-69][TaskInstance-0] - Task submitted failed,workflowInstanceId: 69, taskInstanceId: 71,taskCode: 7803022243712
`

### Version

3.1.x

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zuzuviewer** [comment]
anyone track it? It is a block issue.@Amy0104
