### ISSUE TITLE
[Bug] java.lang.NoSuchFieldException: pid

### ISSUE THREAD

**Issue by VanHelxing** [apache/dolphinscheduler#13307]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

on windows 10 , jdk 1.8.0_351：

 when run a task， worker Always report an error:

`[ERROR] 2022-12-30 16:22:19.430 +0800 - pid
java.lang.NoSuchFieldException: pid
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor.getProcessId(AbstractCommandExecutor.java:431)
	at org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor.run(AbstractCommandExecutor.java:205)
	at org.apache.dolphinscheduler.plugin.task.shell.ShellTask.handle(ShellTask.java:96)
	at org.apache.dolphinscheduler.server.worker.runner.DefaultWorkerDelayTaskExecuteRunnable.executeTask(DefaultWorkerDelayTaskExecuteRunnable.java:49)
	at org.apache.dolphinscheduler.server.worker.runner.WorkerTaskExecuteRunnable.run(WorkerTaskExecuteRunnable.java:174)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)`

### What you expected to happen

Changing jdk version still appears。

### How to reproduce

step1: create a simple shell task；
step2: run 

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by VanHelxing** [comment]
`/**
     * get process id
     *
     * @param process process
     * @return process id
     */
    private int getProcessId(Process process) {
        int processId = 0;

        try {
            // Error in this position
            Field f = process.getClass().getDeclaredField(TaskConstants.PID);
            f.setAccessible(true);

            processId = f.getInt(process);
        } catch (Throwable e) {
            logger.error(e.getMessage(), e);
        }

        return processId;
    }`

**Comment by Radeity** [comment]
Hi, @VanHelxing , process here should be a UNIX process, running in windows is not supported currently.

**Comment by zhongjiajie** [comment]
> Hi, @VanHelxing , process here should be a UNIX process, running in windows is not supported currently.

Hi @VanHelxing , you can refer this comment

**Comment by zhongjiajie** [comment]
if have further question, you can re-open it or add comment to tell us
