### ISSUE TITLE
Master or worker down

### ISSUE THREAD

**Issue by JaayYoung** [apache/dolphinscheduler#13315]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened
 After checking that each node of zk is working normally, and the service is running normally, the master suddenly down a node, this is the log：
[INFO] 2022-12-31 05:20:38.546 +0800 org.apache.zookeeper.ClientCnxn:[1158] - [WorkflowInstance-0][TaskInstance-0] - Unable to read additional data from server sessionid 0x300716329500002, likely server has closed socket, closing socket connection and attempting reconnect
[INFO] 2022-12-31 05:20:38.648 +0800 org.apache.curator.framework.state.ConnectionStateManager:[251] - [WorkflowInstance-0][TaskInstance-0] - State change: SUSPENDED
[WARN] 2022-12-31 05:20:38.649 +0800 org.apache.dolphinscheduler.plugin.registry.zookeeper.ZookeeperConnectionStateListener:[52] - [WorkflowInstance-0][TaskInstance-0] - Registry suspended
[WARN] 2022-12-31 05:20:38.650 +0800 org.apache.dolphinscheduler.server.master.registry.MasterConnectionStateListener:[48] - [WorkflowInstance-0][TaskInstance-0] - registry connection state is SUSPENDED, ready to retry connection
[INFO] 2022-12-31 05:20:39.064 +0800 org.apache.zookeeper.ClientCnxn:[1025] - [WorkflowInstance-0][TaskInstance-0] - Opening socket connection to server nm-bigdata-coordinate-01.e.189.cn/192.168.142.187:12181. Will not attempt to authenticate using SASL (unknown error)
[INFO] 2022-12-31 05:20:39.065 +0800 org.apache.zookeeper.ClientCnxn:[879] - [WorkflowInstance-0][TaskInstance-0] - Socket connection established to nm-bigdata-coordinate-01.e.189.cn/192.168.142.187:12181, initiating session
[INFO] 2022-12-31 05:20:39.067 +0800 org.apache.zookeeper.ClientCnxn:[1299] - [WorkflowInstance-0][TaskInstance-0] - Session establishment complete on server nm-bigdata-coordinate-01.e.189.cn/192.168.142.187:12181, sessionid = 0x300716329500002, negotiated timeout = 30000
[INFO] 2022-12-31 05:20:39.067 +0800 org.apache.curator.framework.state.ConnectionStateManager:[251] - [WorkflowInstance-0][TaskInstance-0] - State change: RECONNECTED
[INFO] 2022-12-31 05:20:39.068 +0800 org.apache.dolphinscheduler.plugin.registry.zookeeper.ZookeeperConnectionStateListener:[48] - [WorkflowInstance-0][TaskInstance-0] - Registry reconnected
[INFO] 2022-12-31 05:20:39.072 +0800 org.apache.dolphinscheduler.server.master.registry.MasterRegistryClient:[125] - [WorkflowInstance-0][TaskInstance-0] - MASTER node deleted : /nodes/master/192.168.142.20:5678
[INFO] 2022-12-31 05:20:39.072 +0800 org.apache.dolphinscheduler.server.master.registry.ServerNodeManager:[302] - [WorkflowInstance-0][TaskInstance-0] - master node : /nodes/master/192.168.142.20:5678 down.
[INFO] 2022-12-31 05:20:39.072 +0800 org.apache.dolphinscheduler.server.master.registry.MasterRegistryClient:[140] - [WorkflowInstance-0][TaskInstance-0] - path: /nodes/master/192.168.142.20:5678 not exists
[INFO] 2022-12-31 05:20:39.077 +0800 org.apache.dolphinscheduler.service.registry.RegistryClient:[160] - [WorkflowInstance-0][TaskInstance-0] - MASTER server dead , and /nodes/master/192.168.142.20:5678 added to zk dead server path success
[INFO] 2022-12-31 05:20:39.077 +0800 org.apache.dolphinscheduler.server.master.service.FailoverService:[53] - [WorkflowInstance-0][TaskInstance-0] - Master failover starting, masterServer: 192.168.142.20:5678
[WARN] 2022-12-31 05:20:39.084 +0800 org.apache.dolphinscheduler.server.master.registry.ServerNodeManager:[362] - [WorkflowInstance-0][TaskInstance-0] - current addr:192.168.142.20:5678 is not in active master list
[INFO] 2022-12-31 05:20:39.084 +0800 org.apache.dolphinscheduler.server.master.registry.ServerNodeManager:[364] - [WorkflowInstance-0][TaskInstance-0] - update master nodes, master size: 0, slot: 0, addr: 192.168.142.20:5678
[INFO] 2022-12-31 05:20:39.096 +0800 org.apache.dolphinscheduler.server.master.registry.ServerNodeManager:[298] - [WorkflowInstance-0][TaskInstance-0] - master node : /nodes/master/192.168.142.20:5678 added.
[INFO] 2022-12-31 05:20:39.099 +0800 org.apache.dolphinscheduler.server.master.service.FailoverService:[55] - [WorkflowInstance-0][TaskInstance-0] - Master failover finished, masterServer: 192.168.142.20:5678
[INFO] 2022-12-31 05:20:39.099 +0800 org.apache.dolphinscheduler.server.master.registry.MasterRegistryDataListener:[63] - [WorkflowInstance-0][TaskInstance-0] - master node added : /nodes/master/192.168.142.20:5678
[WARN] 2022-12-31 05:20:39.105 +0800 org.apache.dolphinscheduler.server.master.registry.ServerNodeManager:[362] - [WorkflowInstance-0][TaskInstance-0] - current addr:192.168.142.20:5678 is not in active master list
[INFO] 2022-12-31 05:20:39.105 +0800 org.apache.dolphinscheduler.server.master.registry.ServerNodeManager:[364] - [WorkflowInstance-0][TaskInstance-0] - update master nodes, master size: 0, slot: 0, addr: 192.168.142.20:5678
[WARN] 2022-12-31 05:20:39.294 +0800 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerBootstrap:[226] - [WorkflowInstance-0][TaskInstance-0] - Master count: 0 is invalid, the current slot: 0
[WARN] 2022-12-31 05:20:40.296 +0800 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerBootstrap:[226] - [WorkflowInstance-0][TaskInstance-0] - Master count: 0 is invalid, the current slot: 0
[WARN] 2022-12-31 05:20:41.299 +0800 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerBootstrap:[226] - [WorkflowInstance-0][TaskInstance-0] - Master count: 0 is invalid, the current slot: 0
[INFO] 2022-12-31 05:20:44.951 +0800 org.apache.dolphinscheduler.server.master.MasterServer:[133] - [WorkflowInstance-0][TaskInstance-0] - Master server is stopping, current cause : i was judged to death, release resources and stop myself
[INFO] 2022-12-31 05:20:44.955 +0800 org.quartz.core.QuartzScheduler:[585] - [WorkflowInstance-0][TaskInstance-0] - Scheduler DolphinScheduler_$_nm-bigdata-coordinate-02.e.189.cn1670922000594 paused.
[INFO] 2022-12-31 05:20:44.973 +0800 org.eclipse.jetty.server.AbstractConnector:[381] - [WorkflowInstance-0][TaskInstance-0] - Stopped ServerConnector@5b02a984{HTTP/1.1, (http/1.1)}{0.0.0.0:5679}
[INFO] 2022-12-31 05:20:44.973 +0800 org.eclipse.jetty.server.session:[149] - [WorkflowInstance-0][TaskInstance-0] - node0 Stopped scavenging
[INFO] 2022-12-31 05:20:44.974 +0800 org.eclipse.jetty.server.handler.ContextHandler.application:[2347] - [WorkflowInstance-0][TaskInstance-0] - Destroying Spring FrameworkServlet 'dispatcherServlet'
[INFO] 2022-12-31 05:20:44.975 +0800 org.eclipse.jetty.server.handler.ContextHandler:[1153] - [WorkflowInstance-0][TaskInstance-0] - Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@1537e43{application,/,[file:///tmp/jetty-docbase.5679.6266739556647265934/],STOPPED}
[INFO] 2022-12-31 05:20:44.983 +0800 org.apache.dolphinscheduler.server.master.rpc.MasterRPCServer:[109] - [WorkflowInstance-0][TaskInstance-0] - Closing Master RPC Server...
[INFO] 2022-12-31 05:20:44.985 +0800 org.apache.dolphinscheduler.remote.NettyRemotingServer:[212] - [WorkflowInstance-0][TaskInstance-0] - netty server closed
[INFO] 2022-12-31 05:20:44.985 +0800 org.apache.dolphinscheduler.server.master.rpc.MasterRPCServer:[111] - [WorkflowInstance-0][TaskInstance-0] - Closed Master RPC Server...
[INFO] 2022-12-31 05:20:44.986 +0800 org.springframework.scheduling.quartz.SchedulerFactoryBean:[845] - [WorkflowInstance-0][TaskInstance-0] - Shutting down Quartz Scheduler
[INFO] 2022-12-31 05:20:44.986 +0800 org.quartz.core.QuartzScheduler:[666] - [WorkflowInstance-0][TaskInstance-0] - Scheduler DolphinScheduler_$_nm-bigdata-coordinate-02.e.189.cn1670922000594 shutting down.
[INFO] 2022-12-31 05:20:44.986 +0800 org.quartz.core.QuartzScheduler:[585] - [WorkflowInstance-0][TaskInstance-0] - Scheduler DolphinScheduler_$_nm-bigdata-coordinate-02.e.189.cn1670922000594 paused.
[WARN] 2022-12-31 05:20:44.989 +0800 org.apache.dolphinscheduler.server.master.processor.queue.StateEventResponseService:[125] - [WorkflowInstance-0][TaskInstance-0] - State event loop service interrupted, will stop this loop
java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at org.apache.dolphinscheduler.server.master.processor.queue.StateEventResponseService$StateEventResponseWorker.run(StateEventResponseService.java:121)
[INFO] 2022-12-31 05:20:44.989 +0800 org.quartz.core.QuartzScheduler:[740] - [WorkflowInstance-0][TaskInstance-0] - Scheduler DolphinScheduler_$_nm-bigdata-coordinate-02.e.189.cn1670922000594 shutdown complete.
[INFO] 2022-12-31 05:20:44.990 +0800 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerBootstrap:[117] - [WorkflowInstance-0][TaskInstance-0] - Master schedule bootstrap stopping...
[INFO] 2022-12-31 05:20:44.990 +0800 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerBootstrap:[118] - [WorkflowInstance-0][TaskInstance-0] - Master schedule bootstrap stopped...
[INFO] 2022-12-31 05:20:44.991 +0800 org.apache.dolphinscheduler.server.master.processor.queue.StateEventResponseService:[132] - [WorkflowInstance-0][TaskInstance-0] - State event loop service stopped
[INFO] 2022-12-31 05:20:44.996 +0800 org.apache.dolphinscheduler.server.master.registry.MasterRegistryClient:[226] - [WorkflowInstance-0][TaskInstance-0] - Master node : 192.168.142.20:5678 unRegistry to register center.
[INFO] 2022-12-31 05:20:44.996 +0800 org.apache.dolphinscheduler.server.master.registry.ServerNodeManager:[302] - [WorkflowInstance-0][TaskInstance-0] - master node : /nodes/master/192.168.142.20:5678 down.
[INFO] 2022-12-31 05:20:44.996 +0800 org.apache.dolphinscheduler.server.master.registry.MasterRegistryClient:[228] - [WorkflowInstance-0][TaskInstance-0] - MasterServer heartbeat executor shutdown
[INFO] 2022-12-31 05:20:44.997 +0800 org.apache.dolphinscheduler.server.master.registry.MasterRegistryClient:[125] - [WorkflowInstance-0][TaskInstance-0] - MASTER node deleted : /nodes/master/192.168.142.20:5678
[INFO] 2022-12-31 05:20:44.999 +0800 org.apache.curator.framework.imps.CuratorFrameworkImpl:[955] - [WorkflowInstance-0][TaskInstance-0] - backgroundOperationsLoop exiting
[INFO] 2022-12-31 05:20:45.000 +0800 org.apache.dolphinscheduler.server.master.registry.MasterRegistryClient:[140] - [WorkflowInstance-0][TaskInstance-0] - path: /nodes/master/192.168.142.20:5678 not exists
[ERROR] 2022-12-31 05:20:45.000 +0800 org.apache.dolphinscheduler.server.master.registry.ServerNodeManager:[324] - [WorkflowInstance-0][TaskInstance-0] - update master nodes error
org.apache.dolphinscheduler.registry.api.RegistryException: zookeeper release lock error
	at org.apache.dolphinscheduler.plugin.registry.zookeeper.ZookeeperRegistry.acquireLock(ZookeeperRegistry.java:215)
	at org.apache.dolphinscheduler.service.registry.RegistryClient.getLock(RegistryClient.java:231)
	at org.apache.dolphinscheduler.server.master.registry.ServerNodeManager.updateMasterNodes(ServerNodeManager.java:319)
	at org.apache.dolphinscheduler.server.master.registry.ServerNodeManager.access$800(ServerNodeManager.java:68)
	at org.apache.dolphinscheduler.server.master.registry.ServerNodeManager$MasterDataListener.notify(ServerNodeManager.java:303)
	at org.apache.dolphinscheduler.plugin.registry.zookeeper.ZookeeperRegistry.lambda$subscribe$1(ZookeeperRegistry.java:128)
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:760)
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:754)
	at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:100)
	at org.apache.curator.shaded.com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:92)
	at org.apache.curator.framework.recipes.cache.TreeCache.callListeners(TreeCache.java:753)
	at org.apache.curator.framework.recipes.cache.TreeCache.access$1900(TreeCache.java:75)
	at org.apache.curator.framework.recipes.cache.TreeCache$4.run(TreeCache.java:865)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Lost connection while trying to acquire lock: /lock/masters
	at org.apache.curator.framework.recipes.locks.InterProcessMutex.acquire(InterProcessMutex.java:91)
	at org.apache.dolphinscheduler.plugin.registry.zookeeper.ZookeeperRegistry.acquireLock(ZookeeperRegistry.java:204)
	... 18 common frames omitted
[ERROR] 2022-12-31 05:20:45.000 +0800 org.apache.dolphinscheduler.server.master.registry.MasterRegistryClient:[150] - [WorkflowInstance-0][TaskInstance-0] - MASTER server failover failed, host:192.168.142.20:5678
org.apache.dolphinscheduler.registry.api.RegistryException: Failed to put registry key: /dead-servers/master_192.168.142.20:5678
	at org.apache.dolphinscheduler.plugin.registry.zookeeper.ZookeeperRegistry.put(ZookeeperRegistry.java:172)
	at org.apache.dolphinscheduler.service.registry.RegistryClient.lambda$handleDeadServer$1(RegistryClient.java:159)
	at java.util.Collections$SingletonSet.forEach(Collections.java:4767)
	at org.apache.dolphinscheduler.service.registry.RegistryClient.handleDeadServer(RegistryClient.java:150)
	at org.apache.dolphinscheduler.server.master.registry.MasterRegistryClient.removeMasterNodePath(MasterRegistryClient.java:142)
	at org.apache.dolphinscheduler.server.master.registry.MasterRegistryDataListener.handleMasterEvent(MasterRegistryDataListener.java:66)
	at org.apache.dolphinscheduler.server.master.registry.MasterRegistryDataListener.notify(MasterRegistryDataListener.java:52)
	at org.apache.dolphinscheduler.plugin.registry.zookeeper.ZookeeperRegistry.lambda$subscribe$1(ZookeeperRegistry.java:128)
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:760)
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:754)
	at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:100)
	at org.apache.curator.shaded.com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:92)
	at org.apache.curator.framework.recipes.cache.TreeCache.callListeners(TreeCache.java:753)
	at org.apache.curator.framework.recipes.cache.TreeCache.access$1900(TreeCache.java:75)
	at org.apache.curator.framework.recipes.cache.TreeCache$4.run(TreeCache.java:865)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:823)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkState(CuratorFrameworkImpl.java:432)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.create(CuratorFrameworkImpl.java:445)
	at org.apache.dolphinscheduler.plugin.registry.zookeeper.ZookeeperRegistry.put(ZookeeperRegistry.java:166)
	... 20 common frames omitted
[ERROR] 2022-12-31 05:20:45.000 +0800 org.apache.dolphinscheduler.server.master.registry.ServerNodeManager:[307] - [WorkflowInstance-0][TaskInstance-0] - MasterNodeListener capture data change and get data failed.
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.plugin.registry.zookeeper.ZookeeperRegistry.releaseLock(ZookeeperRegistry.java:222)
	at org.apache.dolphinscheduler.service.registry.RegistryClient.releaseLock(RegistryClient.java:235)
	at org.apache.dolphinscheduler.server.master.registry.ServerNodeManager.updateMasterNodes(ServerNodeManager.java:326)
	at org.apache.dolphinscheduler.server.master.registry.ServerNodeManager.access$800(ServerNodeManager.java:68)
	at org.apache.dolphinscheduler.server.master.registry.ServerNodeManager$MasterDataListener.notify(ServerNodeManager.java:303)
	at org.apache.dolphinscheduler.plugin.registry.zookeeper.ZookeeperRegistry.lambda$subscribe$1(ZookeeperRegistry.java:128)
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:760)
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:754)
	at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:100)
	at org.apache.curator.shaded.com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:92)
	at org.apache.curator.framework.recipes.cache.TreeCache.callListeners(TreeCache.java:753)
	at org.apache.curator.framework.recipes.cache.TreeCache.access$1900(TreeCache.java:75)
	at org.apache.curator.framework.recipes.cache.TreeCache$4.run(TreeCache.java:865)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### What you expected to happen

master and worker works fine

### How to reproduce

please refer to the log

### Version

3.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mxq-151** [comment]
assigned this bug to me @SbloodyS

**Comment by davidzollo** [comment]
> assigned this bug to me @SbloodyS

hi @JaayYoung, this issue assigned to you two weeks ago, I think you are busy, and @mxq-151 can submit the PR, I will assign this issue to @mxq-151 for PR

**Comment by mxq-151** [comment]
pr for this issue would be here https://github.com/apache/dolphinscheduler/pull/13404
