### ISSUE TITLE
[Bug] [api] The same code and version in table t_ds_process_definition_log causes an error in the list interface

### ISSUE THREAD

**Issue by ChPi** [apache/dolphinscheduler#13467]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

version 3.1.2
a duplicate of #12504， it has been fixed in 3.0.x. 
master throws exception 
```
[ERROR] 2023-01-31 16:13:44.842 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[694] - [WorkflowInstance-215650][TaskInstance-0] - Start workflow error

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 2

at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:96)

at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)

at com.sun.proxy.$Proxy135.selectOne(Unknown Source)

at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:160)

at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:89)

at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)

at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)

at com.sun.proxy.$Proxy165.queryByDefinitionCodeAndVersion(Unknown Source)

at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)

at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)

at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)

at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:54)

at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:366)

at org.springframework.cache.interceptor.CacheAspectSupport.lambda$handleSynchronizedGet$1(CacheAspectSupport.java:447)

at org.springframework.cache.support.NoOpCache.get(NoOpCache.java:76)

at org.springframework.cache.interceptor.CacheAspectSupport.handleSynchronizedGet(CacheAspectSupport.java:442)

at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:382)

at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345)

at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:64)

at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)

at com.sun.proxy.$Proxy166.queryByDefinitionCodeAndVersion(Unknown Source)

at org.apache.dolphinscheduler.service.process.ProcessServiceImpl.findTaskDefinition(ProcessServiceImpl.java:2749)

at org.apache.dolphinscheduler.service.process.ProcessServiceImpl.lambda$getTaskDefineLogListByRelation$7(ProcessServiceImpl.java:2739)

at java.util.HashMap.forEach(HashMap.java:1290)
```

### What you expected to happen

fine

### How to reproduce

no

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Will cp to 3.1.4.

**Comment by jiayuqiu** [comment]
I have encountered the same problem, where can I continue to pay attention to this issue.

```
[INFO] 2023-04-25 11:19:46.596 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowEventLooper:[78] - [WorkflowInstance-14550][TaskInstance-0] - Workflow event looper receive a workflow event: WorkflowEvent(workflowEventType=START_WORKFLOW, workflowInstanceId=14550), will handle this
[INFO] 2023-04-25 11:19:46.597 +0800 org.apache.dolphinscheduler.server.master.event.WorkflowStartEventHandler:[54] - [WorkflowInstance-14550][TaskInstance-0] - Handle workflow start event, begin to start a workflow, event: WorkflowEvent(workflowEventType=START_WORKFLOW, workflowInstanceId=14550)
[ERROR] 2023-04-25 11:19:46.600 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[701] - [WorkflowInstance-14550][TaskInstance-0] - Start workflow error
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 2
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:96)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy126.selectOne(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:160)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:89)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy156.queryByDefinitionCodeAndVersion(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor162.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)

```
