### ISSUE TITLE
ERROR yarn.Client: Application diagnostics message: Max number of executor failures (4) reached

### ISSUE THREAD

**Issue by TheWindIsRising** [apache/dolphinscheduler#13556]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

K8s deploys ds and uses the external hdp cluster for task scheduling error information
23/02/13 11:31:34 ERROR yarn.Client: Application diagnostics message: Max number of executor failures (4) reached
	Exception in thread "main" org.apache.spark.SparkException: Application application_1675841615889_0042 finished with failed status
		at org.apache.spark.deploy.yarn.Client.run(Client.scala:1150)
		at org.apache.spark.deploy.yarn.YarnClusterApplication.start(Client.scala:1530)
		at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
		at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
		at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
		at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
		at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
		at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
		at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
	23/02/13 11:31:34 INFO util.ShutdownHookManager: Shutdown hook called

### What you expected to happen

K8s deploys ds and uses the external hdp cluster for task scheduling error information

### How to reproduce

23/02/13 11:31:34 ERROR yarn.Client: Application diagnostics message: Max number of executor failures (4) reached
	Exception in thread "main" org.apache.spark.SparkException: Application application_1675841615889_0042 finished with failed status
		at org.apache.spark.deploy.yarn.Client.run(Client.scala:1150)
		at org.apache.spark.deploy.yarn.YarnClusterApplication.start(Client.scala:1530)
		at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
		at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
		at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
		at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
		at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
		at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
		at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
	23/02/13 11:31:34 INFO util.ShutdownHookManager: Shutdown hook called

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
It looks like a spark issue. Please send it to the spark community.
