### ISSUE TITLE
[Bug] [Module Name] shell task error

### ISSUE THREAD

**Issue by novice-gamer** [apache/dolphinscheduler#13617]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

According to the installation document on the official website, the cluster mode is deployed. During this period, everything is normal and there is no error, but there is an error when running the workflow.
```shell
[INFO] 2023-02-24 08:03:57.822 +0000 - Set task envFile: /application/dolphinscheduler/worker-server/conf/dolphinscheduler_env.sh
[INFO] 2023-02-24 08:03:57.822 +0000 - Set task appId: 4_7
[INFO] 2023-02-24 08:03:57.822 +0000 - End initialize task
[INFO] 2023-02-24 08:03:57.823 +0000 - Set task status to TaskExecutionStatus{code=1, desc='running'}
[INFO] 2023-02-24 08:03:57.824 +0000 - TenantCode:dolphinscheduler check success
[INFO] 2023-02-24 08:03:57.825 +0000 - ProcessExecDir:/tmp/dolphinscheduler/exec/process/dolphinscheduler/8677663757088/8677668557472_2/4/7 check success
[INFO] 2023-02-24 08:03:57.825 +0000 - Resources:{} check success
[INFO] 2023-02-24 08:03:57.826 +0000 - Task plugin: SHELL create success
[INFO] 2023-02-24 08:03:57.826 +0000 - shell task params {"localParams":[],"rawScript":"echo \"123\"","resourceList":[]}
[INFO] 2023-02-24 08:03:57.826 +0000 - Success initialized task plugin instance success
[INFO] 2023-02-24 08:03:57.826 +0000 - Success set taskVarPool: null
[INFO] 2023-02-24 08:03:57.827 +0000 - raw script : echo "123"
[INFO] 2023-02-24 08:03:57.827 +0000 - task execute path : /tmp/dolphinscheduler/exec/process/dolphinscheduler/8677663757088/8677668557472_2/4/7
[INFO] 2023-02-24 08:03:57.828 +0000 - Begin to create command file:/tmp/dolphinscheduler/exec/process/dolphinscheduler/8677663757088/8677668557472_2/4/7/4_7.command
[INFO] 2023-02-24 08:03:57.828 +0000 - Success create command file, command: #!/bin/bash
BASEDIR=$(cd `dirname $0`; pwd)
cd $BASEDIR
export PYTHON_HOME=/usr/bin/python3.9
/tmp/dolphinscheduler/exec/process/dolphinscheduler/8677663757088/8677668557472_2/4/7/4_7_node.sh
[ERROR] 2023-02-24 08:03:57.838 +0000 - shell task error
java.io.IOException: Cannot run program "sudo" (in directory "/tmp/dolphinscheduler/exec/process/dolphinscheduler/8677663757088/8677668557472_2/4/7"): error=40, 符号连接的层数过多
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor.buildProcess(AbstractCommandExecutor.java:144)
	at org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor.run(AbstractCommandExecutor.java:200)
	at org.apache.dolphinscheduler.plugin.task.shell.ShellTask.handle(ShellTask.java:96)
	at org.apache.dolphinscheduler.server.worker.runner.DefaultWorkerDelayTaskExecuteRunnable.executeTask(DefaultWorkerDelayTaskExecuteRunnable.java:49)
	at org.apache.dolphinscheduler.server.worker.runner.WorkerTaskExecuteRunnable.run(WorkerTaskExecuteRunnable.java:174)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=40, 符号连接的层数过多
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 12 common frames omitted
[ERROR] 2023-02-24 08:03:57.838 +0000 - Task execute failed, due to meet an exception
org.apache.dolphinscheduler.plugin.task.api.TaskException: Execute shell task error
	at org.apache.dolphinscheduler.plugin.task.shell.ShellTask.handle(ShellTask.java:108)
	at org.apache.dolphinscheduler.server.worker.runner.DefaultWorkerDelayTaskExecuteRunnable.executeTask(DefaultWorkerDelayTaskExecuteRunnable.java:49)
	at org.apache.dolphinscheduler.server.worker.runner.WorkerTaskExecuteRunnable.run(WorkerTaskExecuteRunnable.java:174)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### What you expected to happen

I found the generated script under the path shown in the log, but found no exception

### How to reproduce

According to the document installation cluster mode on the official website, create a simple shell node in the workflow definition, and an error occurs after running

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by boy-xiaozhang** [comment]
After trying according to your content, no problems were found. What is the operating system? Can ulimit -n post it?
<img width="1270" alt="image" src="https://github.com/apache/dolphinscheduler/assets/60912722/c48707ee-ed45-491f-9e15-ca7574795f36">

**Comment by zhongjiajie** [comment]
Hi @novice-gamer are you still find some solution of this issue?
