### ISSUE TITLE
[Bug] [NettyRemotingClient]  The worker can't get the task from the master, Mayber It gets the hostname rather not IP.

### ISSUE THREAD

**Issue by wllzhang** [apache/dolphinscheduler#13714]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

我用集群部署发现始终无法下发任务。
```
[WARN] 2023-03-09 15:02:30.594 +0000 org.apache.dolphinscheduler.remote.NettyRemotingClient:[315] - [WorkflowInstance-0][TaskInstance-0] - connect to Host{hostWeight=100, workerGroup='release'} error
java.net.UnknownHostException: dolphinscheduler-worker-0
        at java.net.InetAddress$CachedAddresses.get(InetAddress.java:764)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1282)
        at java.net.InetAddress.getAllByName(InetAddress.java:1140)
        at java.net.InetAddress.getAllByName(InetAddress.java:1064)
        at java.net.InetAddress.getByName(InetAddress.java:1014)
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
        at java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
        at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
        at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
        at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:989)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:504)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:417)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:474)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:750)
```
worker分组是
<img width="910" alt="image" src="https://user-images.githubusercontent.com/25928906/224064334-03a24dcc-52b7-44c1-a468-8bddada34a70.png">
注册的地址是
```
[INFO] 2023-03-10 02:34:11.478 +0000 org.apache.dolphinscheduler.server.master.config.MasterConfig:[169] - [WorkflowInstance-0][TaskInstance-0] - Master config: masterRegistryPath -> /nodes/master/dolphinscheduler-master-0:5678 
```

zookeeper 注册信息是
```
[zk: localhost:2181(CONNECTED) 3] ls /dolphinscheduler/nodes/master
[dolphinscheduler-master-0:5678]
[zk: localhost:2181(CONNECTED) 4] ls /dolphinscheduler/nodes/worker
[dolphinscheduler-worker-0:1234, dolphinscheduler-worker-1:1234, dolphinscheduler-worker-2:1234]
```
然而我用Standalone部署，可以下发任务。
worker分组是
<img width="940" alt="image" src="https://user-images.githubusercontent.com/25928906/224065301-ebc9bdb8-247d-4d05-9349-f1a656077834.png">
注册的地址是
```
[INFO] 2023-03-09 14:30:37.182 +0000 org.apache.dolphinscheduler.server.worker.config.WorkerConfig:[101] - Worker config: workerRegistryPath: /nodes/worker/172.17.0.2:1234
```

### What you expected to happen

master可以下发任务到worker

### How to reproduce

My dockerfile
```
FROM csighub.tencentyun.com/tjdk/tencentkona8-tlinux
RUN yum install -y  vim tar zip unzip procps psmisc pbzip2 lsof pigz
RUN yum install -y centos-release-scl
RUN yum install -y rh-python38
RUN yum install -y hostname
RUN rm /bin/python
RUN ln -s /opt/rh/rh-python38/root/bin/python3 /bin/python
RUN ln -s /opt/rh/rh-python38/root/bin/pip /bin/pip
RUN ln -s /opt/jdk/bin/java /bin/java
COPY ./requirements.txt /root/requirements.txt
RUN  pip install --ignore-installed PyYAML==6.0 &&  pip install apollo-python-client==2.1.2 --extra-index-url http://pypi.woa.com/ --trusted-host pypi.woa.com \
     && python -m pip install -r /root/requirements.txt 

RUN mkdir  /app
COPY . /app/
WORKDIR /app
ENV TZ=Asia/Shanghai
CMD ["bash","/app/run.sh"] 
```

app/run.sh
```
if [ -z "$TYPE" ]; then
    echo "[run.sh] environment variable TYPE not exist"
    exit 255
fi

if [ "$TYPE" == "zookeeper" ];then
    bash /app/apache-zookeeper-3.8.0-bin/bin/zkServer.sh start
fi
prefix="/app/apache-dolphinscheduler-3.1.4-bin"
if [ "$TYPE" == "master" ];then
 bash $prefix/bin/dolphinscheduler-daemon.sh start master-server
fi
if [ "$TYPE" == "worker" ];then
  bash $prefix/bin/dolphinscheduler-daemon.sh start worker-server
fi
if [ "$TYPE" == "alert" ];then
  bash $prefix/bin/dolphinscheduler-daemon.sh start alert-server
fi
if [ "$TYPE" == "api" ];then
  bash $prefix/bin/dolphinscheduler-daemon.sh start api-server
fi
sleep 99999999999
```

### Anything else

我更改了 /apache-dolphinscheduler-3.1.4-bin/bin/dolphinscheduler-daemon.sh

export HOSTNAME=`hostname`  
为

export HOSTNAME=`hostname -I`  
仍然不行

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wllzhang** [comment]
<img width="922" alt="image" src="https://user-images.githubusercontent.com/25928906/224075557-f00bd715-66ed-4a3b-8a36-0e7a0eec324d.png">
为什么获取到的不是ip而是pod的名字？

**Comment by wllzhang** [comment]
这样好了。
`awk '{ $2 = $1 }1' /etc/hosts > temp  && cat temp >  /etc/hosts`

**Comment by klaokai** [comment]
我发现了这样一段代码
```java
/**
     * get host
     * @return host
     */
    public static String getHost(InetAddress inetAddress) {
        if (inetAddress != null) {
            if (Constants.KUBERNETES_MODE) {
                String canonicalHost = inetAddress.getCanonicalHostName();
                String[] items = canonicalHost.split("\\.");
                if (items.length == 6 && "svc".equals(items[3])) {
                    return String.format("%s.%s", items[0], items[1]);
                }
                return canonicalHost;
            }
            return inetAddress.getHostAddress();
        }
        return null;
    }
```

为什么在K8s模式下，获取的是hostName？k8s应该需要做怎么样的配置？
