### ISSUE TITLE
[Improvement][Master] The master service should optimize exception handling

### ISSUE THREAD

**Issue by vinnielhj** [apache/dolphinscheduler#13759]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When I stop all the workers and manually run the workflow in the UI, the workflow instance will be generated, matser keeps printing logs, the UI workflow instance is always running, but the task instance will not be generated, and the user does not get any feedback information , which is unreasonable. In extreme cases, the master may be fully loaded (there are many similar situations, I just cite the case where the worker does not exist)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vinnielhj** [comment]
The master log is as follows:



[ERROR] 2023-03-16 11:41:26.648 +0800 org.apache.dolphinscheduler.server.master.dispatch.executor.NettyExecutorManager:[154] - [WorkflowInstance-0][TaskInstance-0] - Send command to Host{hostWeight=100, workerGroup='default'} error, command: Command [type=TASK_DISPATCH_REQUEST, opaque=1009, bodyLen=1185]
org.apache.dolphinscheduler.remote.exceptions.RemotingException: connect to : Host{hostWeight=100, workerGroup='default'} fail
	at org.apache.dolphinscheduler.remote.NettyRemotingClient.send(NettyRemotingClient.java:227)
	at org.apache.dolphinscheduler.server.master.dispatch.executor.NettyExecutorManager.doExecute(NettyExecutorManager.java:151)
	at org.apache.dolphinscheduler.server.master.dispatch.executor.NettyExecutorManager.execute(NettyExecutorManager.java:104)
	at org.apache.dolphinscheduler.server.master.dispatch.executor.NettyExecutorManager.execute(NettyExecutorManager.java:48)
	at org.apache.dolphinscheduler.server.master.dispatch.ExecutorDispatcher.dispatch(ExecutorDispatcher.java:93)
	at org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer.dispatchTask(TaskPriorityQueueConsumer.java:216)
	at org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer.lambda$batchDispatch$0(TaskPriorityQueueConsumer.java:161)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] 2023-03-16 11:41:26.648 +0800 org.apache.dolphinscheduler.server.master.dispatch.executor.NettyExecutorManager:[154] - [WorkflowInstance-0][TaskInstance-0] - Send command to Host{hostWeight=100, workerGroup='default'} error, command: Command [type=TASK_DISPATCH_REQUEST, opaque=1007, bodyLen=1185]
org.apache.dolphinscheduler.remote.exceptions.RemotingException: connect to : Host{hostWeight=100, workerGroup='default'} fail
	at org.apache.dolphinscheduler.remote.NettyRemotingClient.send(NettyRemotingClient.java:227)
	at org.apache.dolphinscheduler.server.master.dispatch.executor.NettyExecutorManager.doExecute(NettyExecutorManager.java:151)
	at org.apache.dolphinscheduler.server.master.dispatch.executor.NettyExecutorManager.execute(NettyExecutorManager.java:104)
	at org.apache.dolphinscheduler.server.master.dispatch.executor.NettyExecutorManager.execute(NettyExecutorManager.java:48)
	at org.apache.dolphinscheduler.server.master.dispatch.ExecutorDispatcher.dispatch(ExecutorDispatcher.java:93)
	at org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer.dispatchTask(TaskPriorityQueueConsumer.java:216)
	at org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer.lambda$batchDispatch$0(TaskPriorityQueueConsumer.java:161)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] 2023-03-16 11:41:26.648 +0800 org.apache.dolphinscheduler.server.master.dispatch.executor.NettyExecutorManager:[154] - [WorkflowInstance-0][TaskInstance-0] - Send command to Host{hostWeight=100, workerGroup='default'} error, command: Command [type=TASK_DISPATCH_REQUEST, opaque=1008, bodyLen=1185]
org.apache.dolphinscheduler.remote.exceptions.RemotingException: connect to : Host{hostWeight=100, workerGroup='default'} fail
	at org.apache.dolphinscheduler.remote.NettyRemotingClient.send(NettyRemotingClient.java:227)
	at org.apache.dolphinscheduler.server.master.dispatch.executor.NettyExecutorManager.doExecute(NettyExecutorManager.java:151)
	at org.apache.dolphinscheduler.server.master.dispatch.executor.NettyExecutorManager.execute(NettyExecutorManager.java:104)
	at org.apache.dolphinscheduler.server.master.dispatch.executor.NettyExecutorManager.execute(NettyExecutorManager.java:48)
	at org.apache.dolphinscheduler.server.master.dispatch.ExecutorDispatcher.dispatch(ExecutorDispatcher.java:93)
	at org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer.dispatchTask(TaskPriorityQueueConsumer.java:216)
	at org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer.lambda$batchDispatch$0(TaskPriorityQueueConsumer.java:161)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vinnielhj** [comment]
version:3.1.4

**Comment by EricGao888** [comment]
@lhjzmn Good catch. May I ask whether you have worked out a design for the improvement?
