### ISSUE TITLE
[Bug] [DATAX] can't find bin/datax.py when using datax in standalone mode

### ISSUE THREAD

**Issue by hantmac** [apache/dolphinscheduler#13883]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I want to use datax on my local machine. And I have set the `env` in `dolphinscheduler_env.sh`

```
export DATAX_HOME=/Users/nam/DataX/target/datax/datax/bin/datax.py
export JAVA_HOME=/Users/name/zulu8.68.0.21-ca-jdk8.0.362-macosx_aarch64/zulu-8.jdk/Contents/Home
export PYTHON_HOME=/opt/homebrew/bin/python3
export PATH=$DATAX_HOME/bin:$JAVA_HOME/bin:$PYTHON_HOME/bin:$PATH

```

 but got the folloing error:

```
[INFO] 2023-04-07 12:05:33.993 +0800 -  -> /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/bin/datax.py': [Errno 2] No such file or directory
[INFO] 2023-04-07 12:05:34.016 +0800 - process has exited. execute 
```

### What you expected to happen

Run datax correctly.

### How to reproduce

Using datax to sync data from mysql to mysql.

### Anything else

According this doc: https://dolphinscheduler.apache.org/zh-cn/docs/3.1.4/guide/task/datax

more logs:

```
[INFO] 2023-04-07 12:23:22.723 +0800 - Success initialized task plugin instance success
[INFO] 2023-04-07 12:23:22.723 +0800 - Success set taskVarPool: null
[INFO] 2023-04-07 12:23:22.724 +0800 - ***********************************************************************************************
[INFO] 2023-04-07 12:23:22.724 +0800 - *********************************  Execute task instance  *************************************
[INFO] 2023-04-07 12:23:22.724 +0800 - ***********************************************************************************************
[INFO] 2023-04-07 12:23:22.728 +0800 - Begin to create command file:/tmp/dolphinscheduler/exec/process/default/9140463137472/9140470506048_1/2/2/2_2.command
[INFO] 2023-04-07 12:23:22.728 +0800 - Success create command file, command: #!/bin/bash
BASEDIR=$(cd `dirname $0`; pwd)
cd $BASEDIR
/tmp/dolphinscheduler/exec/process/default/9140463137472/9140470506048_1/2/2/2_2_node.sh
[INFO] 2023-04-07 12:23:22.740 +0800 - task run command: bash /tmp/dolphinscheduler/exec/process/default/9140463137472/9140470506048_1/2/2/2_2.command
[ERROR] 2023-04-07 12:23:22.741 +0800 - Get task pid failed
java.lang.reflect.InaccessibleObjectException: Unable to make field private final int java.lang.ProcessImpl.pid accessible: module java.base does not "opens java.lang" to unnamed module @5af3afd9
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
	at org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor.getProcessId(AbstractCommandExecutor.java:389)
	at org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor.run(AbstractCommandExecutor.java:218)
	at org.apache.dolphinscheduler.plugin.task.datax.DataxTask.handle(DataxTask.java:164)
	at org.apache.dolphinscheduler.server.worker.runner.DefaultWorkerDelayTaskExecuteRunnable.executeTask(DefaultWorkerDelayTaskExecuteRunnable.java:54)
	at org.apache.dolphinscheduler.server.worker.runner.WorkerTaskExecuteRunnable.run(WorkerTaskExecuteRunnable.java:163)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
[INFO] 2023-04-07 12:23:22.743 +0800 - process start, process id is: 0
[INFO] 2023-04-07 12:23:23.742 +0800 -  -> /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/bin/datax.py': [Errno 2] No such file or directory
[INFO] 2023-04-07 12:23:23.744 +0800 - process has exited. execute path:/tmp/dolphinscheduler/exec/process/default/9140463137472/9140470506048_1/2/2, processId:0 ,exitStatusCode:2 ,processWaitForStatus:true ,processExitValue:2
[INFO] 2023-04-07 12:23:23.744 +0800 - ***********************************************************************************************
[INFO] 2023-04-07 12:23:23.744 +0800 - *********************************  Finalize task instance  ************************************
[INFO] 2023-04-07 12:23:23.744 +0800 - ***********************************************************************************************
[INFO] 2023-04-07 12:23:23.757 +0800 - Send task execute resu
```

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hantmac** [comment]
Fixed. If start dolphinscheduler in standalone mode we should set `DATAX_HOME` and `PYTHON_HOME` env on local machine.
