### ISSUE TITLE
[Bug] [Master] Could not find class when using etcd as the registration center

### ISSUE THREAD

**Issue by eye-gu** [apache/dolphinscheduler#13987]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'registryClient': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 61 more

### What you expected to happen

master could use etcd as the registration center

### How to reproduce

use etcd as the registration center

### Anything else

I found `protobuf-java` in master module is 2.x version, worker module is 3.x version. So worker can start success but master failed. Maybe should use `maven-shade-plugin` in etcd module to fix it.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Looking forward your contribution, when change dependence, you should also change the license related file. Such as in  https://github.com/apache/dolphinscheduler/blob/119f08d2bafd7d280dd9d323dae21ead2e08147f/dolphinscheduler-dist/release-docs/LICENSE#L576

https://github.com/apache/dolphinscheduler/blob/119f08d2bafd7d280dd9d323dae21ead2e08147f/dolphinscheduler-dist/release-docs/LICENSE#L585

it is better to search all project files

**Comment by eye-gu** [comment]
> Looking forward your contribution, when change dependence, you should also change the license related file. Such as in
> 
> https://github.com/apache/dolphinscheduler/blob/119f08d2bafd7d280dd9d323dae21ead2e08147f/dolphinscheduler-dist/release-docs/LICENSE#L576
> 
> https://github.com/apache/dolphinscheduler/blob/119f08d2bafd7d280dd9d323dae21ead2e08147f/dolphinscheduler-dist/release-docs/LICENSE#L585
> 
> it is better to search all project files

One solution is to properly configure the dependencies of the master module pom file, and another solution is to use the shade plugin. I think the shade plugin can avoid potential dependency issues in the future.

**Comment by kezhenxu94** [comment]
> > Looking forward your contribution, when change dependence, you should also change the license related file. Such as in
> > https://github.com/apache/dolphinscheduler/blob/119f08d2bafd7d280dd9d323dae21ead2e08147f/dolphinscheduler-dist/release-docs/LICENSE#L576
> > 
> > https://github.com/apache/dolphinscheduler/blob/119f08d2bafd7d280dd9d323dae21ead2e08147f/dolphinscheduler-dist/release-docs/LICENSE#L585
> > 
> > it is better to search all project files
> 
> One solution is to properly configure the dependencies of the master module pom file, and another solution is to use the shade plugin. I think the shade plugin can avoid potential dependency issues in the future.

If it's possible to unify the versions of the dependencies (not only grpc ones), we should do that, shade plugin should be the last resort to consider as it hide the dependencies (and the licenses can not be automatically dealt with)

**Comment by eye-gu** [comment]
> > > Looking forward your contribution, when change dependence, you should also change the license related file. Such as in
> > > https://github.com/apache/dolphinscheduler/blob/119f08d2bafd7d280dd9d323dae21ead2e08147f/dolphinscheduler-dist/release-docs/LICENSE#L576
> > > 
> > > https://github.com/apache/dolphinscheduler/blob/119f08d2bafd7d280dd9d323dae21ead2e08147f/dolphinscheduler-dist/release-docs/LICENSE#L585
> > > 
> > > it is better to search all project files
> > 
> > 
> > One solution is to properly configure the dependencies of the master module pom file, and another solution is to use the shade plugin. I think the shade plugin can avoid potential dependency issues in the future.
> 
> If it's possible to unify the versions of the dependencies (not only grpc ones), we should do that, shade plugin should be the last resort to consider as it hide the dependencies (and the licenses can not be automatically dealt with)

I will change my pr.
