### ISSUE TITLE
[Bug] [dolphinscheduler-master]  stop workflow but state always ready stop

### ISSUE THREAD

**Issue by maketubu7** [apache/dolphinscheduler#14077]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

stop workflow but state always ready stop
![image](https://github.com/apache/dolphinscheduler/assets/39480244/63f35954-063c-43b3-80cd-023f9c575358)

master.log
`[WARN] 2023-05-10 16:08:25.143 +0800 org.apache.dolphinscheduler.service.process.ProcessServiceImpl:[1578] - [WorkflowInstance-1641][TaskInstance-8397] - processInstance: 1641 state was: WorkflowExecutionStatus{code=4, desc='ready stop'}, skip submit this task, taskCode: 9506653273632
[ERROR] 2023-05-10 16:08:25.143 +0800 org.apache.dolphinscheduler.service.process.ProcessServiceImpl:[1319] - [WorkflowInstance-1641][TaskInstance-8397] - Save taskInstance to db error, task name:修改云硬盘快照策略, process id:1641 state: WorkflowExecutionStatus{code=4, desc='ready stop'} 
[ERROR] 2023-05-10 16:08:25.143 +0800 org.apache.dolphinscheduler.service.process.ProcessServiceImpl:[1286] - [WorkflowInstance-1641][TaskInstance-8397] - task commit to db failed , taskCode: 9506653273632 has already retry 2 times, please check the database
[INFO] 2023-05-10 16:08:25.874 +0800 org.apache.dolphinscheduler.server.master.task.MasterHeartBeatTask:[70] - [WorkflowInstance-0][TaskInstance-0] - Success write master heartBeatInfo into registry, masterRegistryPath: /nodes/master/master03.sugon.local:5678, heartBeatInfo: {"startupTime":1683622511397,"reportTime":1683706105872,"cpuUsage":0.05,"memoryUsage":0.15,"loadAverage":4.11,"availablePhysicalMemorySize":645.85,"maxCpuloadAvg":12.0,"reservedMemory":0.3,"diskAvailable":178.83,"processId":20}
[ERROR] 2023-05-10 16:08:25.997 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[944] - [WorkflowInstance-1635][TaskInstance-8235] - Submit standby task failed!, taskCode: 9503896630816, taskName: 云服务器绑定安全组
[ERROR] 2023-05-10 16:08:25.999 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[427] - [WorkflowInstance-0][TaskInstance-0] - Task finish failed, get a exception, will remove this taskInstance from completeTaskMap
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitStandByTask(WorkflowExecuteRunnable.java:1847)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitPostNode(WorkflowExecuteRunnable.java:1362)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.taskFinished(WorkflowExecuteRunnable.java:399)
	at org.apache.dolphinscheduler.server.master.event.TaskStateEventHandler.handleStateEvent(TaskStateEventHandler.java:78)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.handleEvents(WorkflowExecuteRunnable.java:288)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] 2023-05-10 16:08:25.999 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[303] - [WorkflowInstance-0][TaskInstance-0] - State event handle error, get a unknown exception, will retry this event: TaskStateEvent(processInstanceId=1635, taskInstanceId=8235, taskCode=0, status=TaskExecutionStatus{code=7, desc='success'}, type=TASK_STATE_CHANGE, key=null, channel=null, context=null)
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitStandByTask(WorkflowExecuteRunnable.java:1847)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitPostNode(WorkflowExecuteRunnable.java:1362)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.taskFinished(WorkflowExecuteRunnable.java:399)
	at org.apache.dolphinscheduler.server.master.event.TaskStateEventHandler.handleStateEvent(TaskStateEventHandler.java:78)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.handleEvents(WorkflowExecuteRunnable.java:288)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

### What you expected to happen

stop success

### How to reproduce

create workflow and stop it

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Littlehhao** [comment]
楼主解了吗？

**Comment by chenshuai1995** [comment]
mark
