### ISSUE TITLE
[Bug] [Master] In v3.1.3, SubProcess stuck at submit success, inner task instance is all success. 

### ISSUE THREAD

**Issue by ORuteMa** [apache/dolphinscheduler#14215]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![img_v2_9a5c71c2-58c7-49a8-853b-07a1621cd14g](https://github.com/apache/dolphinscheduler/assets/30034544/06568783-3e44-418d-b102-09c153a7b5de)

There is a subprocess stuck at submit success state for 20 minutes, but its inner task instance is all success.

### What you expected to happen

The SubProcess instance should change its state to success as soon as its task instances is all success.

### How to reproduce

Run a dag with subProcess in it.

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ORuteMa** [comment]
I find a similar issue https://github.com/apache/dolphinscheduler/issues/13776, we also got log like
`[ERROR] 2023-05-25 20:27:39.599 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[292] - [WorkflowInstance-73][TaskInstance-274] - State event handle error, will remove this event: TaskStateEvent(processInstanceId=73, taskInstanceId=274, taskCode=9664499146053, status=TaskExecutionStatus{code=1, desc='running'}, type=TASK_STATE_CHANGE, key=null, channel=null, context=null)
org.apache.dolphinscheduler.server.master.event.StateEventHandleError: Task state event handle error, due to the task is not in activeTaskProcessorMaps
	at org.apache.dolphinscheduler.server.master.event.TaskStateEventHandler.handleStateEvent(TaskStateEventHandler.java:89)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.handleEvents(WorkflowExecuteRunnable.java:288)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)`
@Chris-Arith good day, do you have any clue about this issue?

**Comment by ORuteMa** [comment]
Duplicated with https://github.com/apache/dolphinscheduler/issues/14262#top. Close.
