### ISSUE TITLE
[Improvement][docker-compose deploy] Caused by: org.postgresql.util.PSQLException: ERROR: relation "t_ds_worker_group" does not exist

### ISSUE THREAD

**Issue by pigeon2049** [apache/dolphinscheduler#14247]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

docker-compose  --profile all  up -d

got docker-dolphinscheduler-master-1 exited after start

error info:
         ### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: relation "t_ds_worker_group" does not exist
2023-06-01 09:49:18   Position: 23
2023-06-01 09:49:18 ### The error may exist in class path resource [org/apache/dolphinscheduler/dao/mapper/WorkerGroupMapper.xml]
2023-06-01 09:49:18 ### The error may involve defaultParameterMap
2023-06-01 09:49:18 ### The error occurred while setting parameters
2023-06-01 09:49:18 ### SQL: select *         from t_ds_worker_group         order by update_time desc
2023-06-01 09:49:18 ### Cause: org.postgresql.util.PSQLException: ERROR: relation "t_ds_worker_group" does not exist
2023-06-01 09:49:18   Position: 23
2023-06-01 09:49:18 ; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: relation "t_ds_worker_group" does not exist
2023-06-01 09:49:18   Position: 23
2023-06-01 09:49:18     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
2023-06-01 09:49:18     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
2023-06-01 09:49:18     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
2023-06-01 09:49:18     at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
2023-06-01 09:49:18     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
2023-06-01 09:49:18     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
2023-06-01 09:49:18     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
2023-06-01 09:49:18     at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
2023-06-01 09:49:18     at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
2023-06-01 09:49:18     at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
2023-06-01 09:49:18     at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656)
2023-06-01 09:49:18     ... 76 more
2023-06-01 09:49:18 Caused by: org.springframework.jdbc.BadSqlGrammarException: 
2023-06-01 09:49:18 ### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: relation "t_ds_worker_group" does not exist
2023-06-01 09:49:18   Position: 23
2023-06-01 09:49:18 ### The error may exist in class path resource [org/apache/dolphinscheduler/dao/mapper/WorkerGroupMapper.xml]
2023-06-01 09:49:18 ### The error may involve defaultParameterMap
2023-06-01 09:49:18 ### The error occurred while setting parameters
2023-06-01 09:49:18 ### SQL: select *         from t_ds_worker_group         order by update_time desc
2023-06-01 09:49:18 ### Cause: org.postgresql.util.PSQLException: ERROR: relation "t_ds_worker_group" does not exist
2023-06-01 09:49:18   Position: 23
2023-06-01 09:49:18 ; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: relation "t_ds_worker_group" does not exist
2023-06-01 09:49:18   Position: 23
2023-06-01 09:49:18     at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
2023-06-01 09:49:18     at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
2023-06-01 09:49:18     at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
2023-06-01 09:49:18     at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
2023-06-01 09:49:18     at com.sun.proxy.$Proxy127.selectList(Unknown Source)
2023-06-01 09:49:18     at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
2023-06-01 09:49:18     at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:166)
2023-06-01 09:49:18     at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:77)
2023-06-01 09:49:18     at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
2023-06-01 09:49:18     at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
2023-06-01 09:49:18     at com.sun.proxy.$Proxy168.queryAllWorkerGroup(Unknown Source)
2023-06-01 09:49:18     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-06-01 09:49:18     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2023-06-01 09:49:18     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-06-01 09:49:18     at java.lang.reflect.Method.invoke(Method.java:498)
2023-06-01 09:49:18     at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
2023-06-01 09:49:18     at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
2023-06-01 09:49:18     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
2023-06-01 09:49:18     at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:54)
2023-06-01 09:49:18     at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:351)
2023-06-01 09:49:18     at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:64)
2023-06-01 09:49:18     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
2023-06-01 09:49:18     at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
2023-06-01 09:49:18     at com.sun.proxy.$Proxy169.queryAllWorkerGroup(Unknown Source)
2023-06-01 09:49:18     at org.apache.dolphinscheduler.server.master.registry.ServerNodeManager.updateWorkerGroupMappings(ServerNodeManager.java:267)
2023-06-01 09:49:18     at org.apache.dolphinscheduler.server.master.registry.ServerNodeManager.afterPropertiesSet(ServerNodeManager.java:133)
2023-06-01 09:49:18     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
2023-06-01 09:49:18     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
2023-06-01 09:49:18     ... 86 more
2023-06-01 09:49:18 Caused by: org.postgresql.util.PSQLException: ERROR: relation "t_ds_worker_group" does not exist
2023-06-01 09:49:18   Position: 23
2023-06-01 09:49:18     at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
2023-06-01 09:49:18     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
2023-06-01 09:49:18     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
2023-06-01 09:49:18     at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
2023-06-01 09:49:18     at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
2023-06-01 09:49:18     at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
2023-06-01 09:49:18     at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:170)
2023-06-01 09:49:18     at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
2023-06-01 09:49:18     at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
2023-06-01 09:49:18     at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
2023-06-01 09:49:18     at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
2023-06-01 09:49:18     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-06-01 09:49:18     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2023-06-01 09:49:18     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-06-01 09:49:18     at java.lang.reflect.Method.invoke(Method.java:498)
2023-06-01 09:49:18     at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64)
2023-06-01 09:49:18     at com.sun.proxy.$Proxy175.query(Unknown Source)
2023-06-01 09:49:18     at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
2023-06-01 09:49:18     at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
2023-06-01 09:49:18     at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
2023-06-01 09:49:18     at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:81)
2023-06-01 09:49:18     at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
2023-06-01 09:49:18     at com.sun.proxy.$Proxy174.query(Unknown Source)
2023-06-01 09:49:18     at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151)
2023-06-01 09:49:18     at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:145)
2023-06-01 09:49:18     at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
2023-06-01 09:49:18     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-06-01 09:49:18     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2023-06-01 09:49:18     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-06-01 09:49:18     at java.lang.reflect.Method.invoke(Method.java:498)
2023-06-01 09:49:18     at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
2023-06-01 09:49:18     ... 110 more

the issue seems like table t_ds_worker_group not exists 
why not init it in code? judge if table exists on start,if not ,init it!

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pigeon2049** [comment]
sorry , forgot docker-compose --profile schema up -d first
