### ISSUE TITLE
[Bug] [dolphinscheduler-api] Get dqRules entry failed in postgres database

### ISSUE THREAD

**Issue by hoey94** [apache/dolphinscheduler#14515]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

MAC OS & IDEA & JDK1.8
GitBranch:  origin/3.2.0-prepare
Database: `PostgreSQL 15.3`
When accessing the data quality rule management in the UI interface, the terminal receives an error message, as follows:
```xml
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "`"
  位置：102
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:170)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at sun.reflect.GeneratedMethodAccessor173.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64)
	at com.sun.proxy.$Proxy854.query(Unknown Source)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:81)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy853.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:145)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at sun.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
	... 82 common frames omitted
```

### What you expected to happen

I checked the code and found a special character a.`value` in DqRuleInputEntryMapper, which is not supported in Postgres.

### How to reproduce

1. Visit homepage
2. Visit data quality
3. Visit rule management
<img width="1116" alt="image" src="https://github.com/apache/dolphinscheduler/assets/13510799/23539576-7e49-4bba-870b-a82fa020375e">

### Anything else

No

### Version

3.2.0-prepare

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hoey94** [comment]
I removed the character in the development environment and retried, and verified that there is no problem in the postgres15.3` environment.

**Comment by hoey94** [comment]
I removed the character ` in the development environment and retried, and verified that there is no problem in the postgres15.3 environment.

**Comment by hoey94** [comment]
@SbloodyS Hi. How to link this is issue to pr(https://github.com/apache/dolphinscheduler/pull/14516)

**Comment by hoey94** [comment]
I have confirmed that the impact extends to three databases: MySQL, H2, and PostgreSQL. Remarkably, the provided SQL query successfully executes in both MySQL and PostgreSQL databases without encountering any exceptions.
```sql
 SELECT a.id,
               a.field,
               a.type,
               a.title,
               a.value,
               a.options,
               a.placeholder,
               a.option_source_type,
               a.value_type,
               a.input_type,
               a.is_show,
               a.can_edit,
               a.is_emit,
               a.is_validate,
               b.values_map,
               b.index
        FROM t_ds_dq_rule_input_entry a join ( SELECT *
        FROM t_ds_relation_rule_input_entry where rule_id = 1 )  b
        on a.id = b.rule_input_entry_id order by b.index;
```

Nevertheless, the query execution encounters an unfortunate failure when executed in the H2 database. In an effort to address this compatibility issue, I made an attempt to resolve it by appending ";NON_KEYWORDS=value" to the H2 URL. What are your thoughts on this, @SbloodyS?
