### ISSUE TITLE
[Bug] [FLINK_STREAM] Many NPEs

### ISSUE THREAD

**Issue by xiaohei88** [apache/dolphinscheduler#14564]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I execute the real-time task button in the task definition menu, and the background keeps reporting NPE

### What you expected to happen

```java
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.server.master.runner.StreamTaskExecuteRunnable.run(StreamTaskExecuteRunnable.java:155)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
```java
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.server.master.runner.execute.DefaultTaskExecuteRunnableFactory.createTaskExecuteRunnable(DefaultTaskExecuteRunnableFactory.java:51)
```

### How to reproduce

Creating FLinkstream tasks is enough

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xiaohei88** [comment]
- The first NPE, I solved it through constructor injection.
- But for the second NPE, why does the execStreamTaskInstance method not insert data into the command, resulting in no data in the cache. Don't you need it

**Comment by xiaohei88** [comment]
When will this problem be fixed. @SbloodyS

**Comment by zxtheend** [comment]
same problem

**Comment by HejiaHo** [comment]
same problem
