### ISSUE TITLE
[Bug] [Helm] helm upgrade error on db-init-job

### ISSUE THREAD

**Issue by Gallardot** [apache/dolphinscheduler#14585]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

On the dev branch, I built a ds image using mysql.
First helm install, everything is ok.
but after helm upgrade, db-init-job failed.

```
helm upgrade --install --create-namespace --namespace dolphinscheduler  dolphinscheduler dolphinscheduler -f helm/values-dev.yaml
```
db-init-job error logs
```
2023-07-19 16:23:02.266 ERROR 7 --- [           main] o.a.d.common.utils.ScriptRunner          : SQLException

java.sql.SQLSyntaxErrorException: Table 't_ds_trigger_relation' already exists
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121) ~[mysql-connector-j-8.0.33.jar:8.0.33]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-j-8.0.33.jar:8.0.33]
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763) ~[mysql-connector-j-8.0.33.jar:8.0.33]
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648) ~[mysql-connector-j-8.0.33.jar:8.0.33]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94) ~[HikariCP-4.0.3.jar:na]
```

### What you expected to happen

no error

### How to reproduce

as mentioned above

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Gallardot** [comment]
problem solving!

Thanks @zhongjiajie .

PS: If someone wants to build a production-ready build from dev, they can refer to the [release documentation](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/release.md).
