### ISSUE TITLE
[docker-compose run failed] [zookeeper] EndOfStreamException: Unable to read additional data from client, it probably closed the socket

### ISSUE THREAD

**Issue by linlin-coder** [apache/dolphinscheduler#14960]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

docker version: 24.0.6
docker-compose:v2.21.0
dolphinscheduler: v3.1.8

when i use file:deploy/docker/docker-compose.yml, and run command:`docker-compose -f docker-compose.yml  --profile schema up -d` and `docker-compose -f docker-compose.yml  --profile all up -d`, dolphinscheduler ui create failed, and something error are found in container of zookeeper,container log as follows:
```
2023-09-25 07:19:23,063 [myid:1] - INFO  [main:ContainerManager@84] - Using checkIntervalMs=60000 maxPerMinute=10000 maxNeverUsedIntervalMs=0
2023-09-25 07:19:23,064 [myid:1] - INFO  [main:ZKAuditProvider@42] - ZooKeeper audit is disabled.
2023-09-25 07:19:27,009 [myid:1] - WARN  [NIOWorkerThread-1:NIOServerCnxn@371] - Unexpected exception
EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:46234, session = 0x0
	at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:170)
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:333)
	at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:508)
	at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-09-25 07:19:32,080 [myid:1] - WARN  [NIOWorkerThread-2:NIOServerCnxn@371] - Unexpected exception
EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:46256, session = 0x0
	at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:170)
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:333)
	at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:508)
	at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### What you expected to happen

i dont know, beacause of i am a new java user, and i think zookeeper error happen  to cause this bug.

### How to reproduce

i need a manuscipt of this error fixed, if developer can provide this document

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by linlin-coder** [comment]
i have annother question, dolphinscheduler worker running in docker-container, how can i register the host ip of computer to zookeeper, becuase i found that dolphinscheduler worker register itself using docker0-ip , some logs as follows.
```
[INFO] 2023-09-27 02:53:39.665 +0000 org.apache.dolphinscheduler.server.worker.config.WorkerConfig:[89] - [WorkflowInstance-0][TaskInstance-0] - Worker config: listenPort -> 1234
[INFO] 2023-09-27 02:53:39.666 +0000 org.apache.dolphinscheduler.server.worker.config.WorkerConfig:[90] - [WorkflowInstance-0][TaskInstance-0] - Worker config: execThreads -> 100
[INFO] 2023-09-27 02:53:39.666 +0000 org.apache.dolphinscheduler.server.worker.config.WorkerConfig:[91] - [WorkflowInstance-0][TaskInstance-0] - Worker config: heartbeatInterval -> PT10S
[INFO] 2023-09-27 02:53:39.666 +0000 org.apache.dolphinscheduler.server.worker.config.WorkerConfig:[92] - [WorkflowInstance-0][TaskInstance-0] - Worker config: hostWeight -> 100
[INFO] 2023-09-27 02:53:39.667 +0000 org.apache.dolphinscheduler.server.worker.config.WorkerConfig:[93] - [WorkflowInstance-0][TaskInstance-0] - Worker config: tenantAutoCreate -> true
[INFO] 2023-09-27 02:53:39.667 +0000 org.apache.dolphinscheduler.server.worker.config.WorkerConfig:[94] - [WorkflowInstance-0][TaskInstance-0] - Worker config: tenantDistributedUser -> false
[INFO] 2023-09-27 02:53:39.667 +0000 org.apache.dolphinscheduler.server.worker.config.WorkerConfig:[95] - [WorkflowInstance-0][TaskInstance-0] - Worker config: maxCpuLoadAvg -> 32
[INFO] 2023-09-27 02:53:39.667 +0000 org.apache.dolphinscheduler.server.worker.config.WorkerConfig:[96] - [WorkflowInstance-0][TaskInstance-0] - Worker config: reservedMemory -> 0.3
[INFO] 2023-09-27 02:53:39.668 +0000 org.apache.dolphinscheduler.server.worker.config.WorkerConfig:[97] - [WorkflowInstance-0][TaskInstance-0] - Worker config: alertListenHost -> 20.xx.xx.xx
[INFO] 2023-09-27 02:53:39.668 +0000 org.apache.dolphinscheduler.server.worker.config.WorkerConfig:[98] - [WorkflowInstance-0][TaskInstance-0] - Worker config: alertListenPort -> 50052
[INFO] 2023-09-27 02:53:39.668 +0000 org.apache.dolphinscheduler.server.worker.config.WorkerConfig:[99] - [WorkflowInstance-0][TaskInstance-0] - Worker config: registryDisconnectStrategy -> ConnectStrategyProperties(strategy=WAITING, maxWaitingTime=PT1M40S)
[INFO] 2023-09-27 02:53:39.668 +0000 org.apache.dolphinscheduler.server.worker.config.WorkerConfig:[100] - [WorkflowInstance-0][TaskInstance-0] - Worker config: workerAddress -> 172.17.2.1:1234
[INFO] 2023-09-27 02:53:39.669 +0000 org.apache.dolphinscheduler.server.worker.config.WorkerConfig:[101] - [WorkflowInstance-0][TaskInstance-0] - Worker config: workerRegistryPath: /nodes/worker/172.17.2.1:1234
[INFO] 2023-09-27 02:53:39.670 +0000 org.apache.dolphinscheduler.server.worker.config.WorkerConfig:[102] - [WorkflowInstance-0][TaskInstance-0] - Worker config: taskExecuteThreadsFullPolicy: REJECT
[INFO] 2023-09-27 02:53:40.118 +0000 org.apache.curator.framework.imps.CuratorFrameworkImpl:[338] - [WorkflowInstance-0][TaskInstance-0] - Starting
```

**Comment by LoveFishoO** [comment]
how to solve this problem？
