### ISSUE TITLE
[Bug] [Master] task_execute_type column should not be nullable column

### ISSUE THREAD

**Issue by dufeng1010** [apache/dolphinscheduler#15055]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when i execute a workflow, i find a task to need failover loop. not success.
i can view a log, below error info:
```
[ERROR] 2023-10-20 10:11:27.735 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[317] - [WorkflowInstance-3][TaskInstance-0] - State event handle error, get a unknown exception, will retry this event: TaskStateEvent(processInstanceId=3, taskInstanceId=132, taskCode=0, status=TaskExecutionStatus{code=7, desc='success'}, type=TASK_STATE_CHANGE, key=null, channel=null, context=null)
java.lang.NullPointerException: null
        at org.apache.dolphinscheduler.server.master.utils.WorkflowInstanceUtils.logTaskInstanceInDetail(WorkflowInstanceUtils.java:74)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.taskFinished(WorkflowExecuteRunnable.java:440)
        at org.apache.dolphinscheduler.server.master.event.TaskStateEventHandler.handleStateEvent(TaskStateEventHandler.java:74)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.handleEvents(WorkflowExecuteRunnable.java:293)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

i view table data in ds, task_execute_type column is null, cause to loop execute task.

当我在执行一个工作流时，发现工作流中的某个任务一直循环执行，该任务的所有历史实例都是需要容错。查看日志，发现如下错误：
```
[ERROR] 2023-10-20 10:11:27.735 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[317] - [WorkflowInstance-3][TaskInstance-0] - State event handle error, get a unknown exception, will retry this event: TaskStateEvent(processInstanceId=3, taskInstanceId=132, taskCode=0, status=TaskExecutionStatus{code=7, desc='success'}, type=TASK_STATE_CHANGE, key=null, channel=null, context=null)
java.lang.NullPointerException: null
        at org.apache.dolphinscheduler.server.master.utils.WorkflowInstanceUtils.logTaskInstanceInDetail(WorkflowInstanceUtils.java:74)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.taskFinished(WorkflowExecuteRunnable.java:440)
        at org.apache.dolphinscheduler.server.master.event.TaskStateEventHandler.handleStateEvent(TaskStateEventHandler.java:74)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.handleEvents(WorkflowExecuteRunnable.java:293)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
发现是因为task_execute_type字段的值为空导致的。我将task_execute_type的值设置为0，工作流中的所有任务就成功了。

### What you expected to happen

if task_execute_type column should not be nullable, it be changed to not null column in ds database

如果task_execute_type列的值不能为空，那么最好将该字段设置为非NULL列。

### How to reproduce

i dont' know how and why to generated task_execute_type column's value is null, but it can exists.

我忘记操作什么导致task_execute_type的值为null了。但是ds界面的确存在导致task_execute_type的值为NULL的操作。

### Anything else

[ERROR] 2023-10-20 10:11:27.735 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[317] - [WorkflowInstance-3][TaskInstance-0] - State event handle error, get a unknown exception, will retry this event: TaskStateEvent(processInstanceId=3, taskInstanceId=132, taskCode=0, status=TaskExecutionStatus{code=7, desc='success'}, type=TASK_STATE_CHANGE, key=null, channel=null, context=null)
java.lang.NullPointerException: null
        at org.apache.dolphinscheduler.server.master.utils.WorkflowInstanceUtils.logTaskInstanceInDetail(WorkflowInstanceUtils.java:74)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.taskFinished(WorkflowExecuteRunnable.java:440)
        at org.apache.dolphinscheduler.server.master.event.TaskStateEventHandler.handleStateEvent(TaskStateEventHandler.java:74)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.handleEvents(WorkflowExecuteRunnable.java:293)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

### Version

3.2.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Could you find out which interface will cause the task_execute_type is null? I am not clear if this is caused by the upgrade error, but is a good idea to set the default value of task_execute_type to 0.

**Comment by dufeng1010** [comment]
sorry, i don't know which interface cause task_execute_type is null. next time i encounter this problem, i will record it.  @ruanwenjun

**Comment by liangjihua** [comment]
Had the same problem, for me I used `pydolphinscheduler==4.0.4` which doesn't seem to support dolphinscheduler 3.2.0 yet

**Comment by ylq5126** [comment]
had same problem too，when update task_execute_type to 0 and restart server ,is seem ok now

**Comment by ylq5126** [comment]
@ruanwenjun 
I found a reproducing step
1：export Workflow json from version 3.1.8
2：import Workflow json at version  3.2.0
in db，task_execute_type column is null

**Comment by leachli** [comment]
I also have this error, but it is caused by the empty status. I have no problem in pseudo-cluster mode. This problem occurs in production cluster, could you please tell me how to solve it?


[ERROR] 2024-02-01 15:26:04.471 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[317] - [WorkflowInstance-265][TaskInstance-837] - State event handle error, get a unknown exception, will retry this event: TaskStateEvent(processInstanceId=265, taskInstanceId=837, taskCode=0, status=null, type=TASK_STATE_CHANGE, key=267-0-265-837, channel=null, context=null)
java.lang.NullPointerException: null

**Comment by ylq5126** [comment]
> I also have this error, but it is caused by the empty status. I have no problem in pseudo-cluster mode. This problem occurs in production cluster, could you please tell me how to solve it?
> 
> [ERROR] 2024-02-01 15:26:04.471 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[317] - [WorkflowInstance-265][TaskInstance-837] - State event handle error, get a unknown exception, will retry this event: TaskStateEvent(processInstanceId=265, taskInstanceId=837, taskCode=0, status=null, type=TASK_STATE_CHANGE, key=267-0-265-837, channel=null, context=null) java.lang.NullPointerException: null
you can try this step
update t_ds_task_instance set task_execute_type =0 where task_execute_type is null;
update t_ds_task_definition set task_execute_type =0 where task_execute_type is null;
update t_ds_task_definition_log set task_execute_type =0 where task_execute_type is null;
