### ISSUE TITLE
[Bug] [api-master] Failed to obtain JDBC Connection

### ISSUE THREAD

**Issue by zengxiaosong** [apache/dolphinscheduler#15108]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

启动一个子流程比较复杂的任务后，master总是重复出现数据库连接获取不到的情况。导致新的任务不能启动，需要重启dolphin才行。错误日志如下：
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: DolphinScheduler - Connection is not available, request timed out after 30000ms.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:153)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:145)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at sun.reflect.GeneratedMethodAccessor352.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
	... 34 common frames omitted
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: DolphinScheduler - Connection is not available, request timed out after 30000ms.

### What you expected to happen

如何解决

### How to reproduce

使用一个复杂，嵌套比较深的子流程任务

### Anything else

暂时没有

### Version

3.1.x
### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JueLance** [comment]
You need remove backquote in sql script:

![WXWorkCapture_17049640255929](https://github.com/apache/dolphinscheduler/assets/5292953/216b7227-f6df-4d28-ae6a-a97fe9e76501)


reference link: https://github.com/apache/dolphinscheduler/pull/14992
