### ISSUE TITLE
[Bug][dolphinscheduler-api] 3.2.0 data-quality/rule page error

### ISSUE THREAD

**Issue by jianchengwang** [apache/dolphinscheduler#15166]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="926" alt="image" src="https://github.com/apache/dolphinscheduler/assets/15951975/333046af-129a-499a-9ed7-e9cbf1ab4384">

### What you expected to happen

here  is dolphinscheduler-api console log

```
### The error may exist in class path resource [org/apache/dolphinscheduler/dao/mapper/DqRuleInputEntryMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT a.id,                a.field,                a.type,                a.title,                a.`value`,                a.options,                a.placeholder,                a.option_source_type,                a.value_type,                a.input_type,                a.is_show,                a.can_edit,                a.is_emit,                a.is_validate,                b.values_map,                b.index         FROM t_ds_dq_rule_input_entry a join ( SELECT *         FROM t_ds_relation_rule_input_entry where rule_id = ? )  b         on a.id = b.rule_input_entry_id order by b.index
### Cause: org.postgresql.util.PSQLException: ERROR: syntax error at or near "`"
  Position: 102
; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: syntax error at or near "`"
  Position: 102
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)

```

maybe sql error?

### How to reproduce

docker deploy 3.2.0

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jianchengwang** [comment]
i am sorry, it is fix on `[Fix][Data Quality] Change t_ds_dq_rule_input_entry field name fix PostgreSQL not support value issue #14992`
