### ISSUE TITLE
[Bug] [master] workflow instance blocking caused by TaskStateEventHandler::handleStateEvent NullPointerException

### ISSUE THREAD

**Issue by jerves** [apache/dolphinscheduler#15222]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

another similar issue: https://github.com/apache/dolphinscheduler/issues/14855

workflow instance blocking caused by TaskStateEventHandler::handleStateEvent NullPointerException

workflow contain subprocessess

master exception log:
![log1](https://github.com/apache/dolphinscheduler/assets/19341235/ad544c20-38f0-41e2-a551-6a92c4485c05)

exception code here:
![code1](https://github.com/apache/dolphinscheduler/assets/19341235/22d9b828-8017-4ac2-b3f4-db0bcbb74f82)

it might be caused by here:
![code2](https://github.com/apache/dolphinscheduler/assets/19341235/7b41f757-b184-4b29-b8b3-86315f2e10e2)

the event come from another master, might be here:
![code3](https://github.com/apache/dolphinscheduler/assets/19341235/3c6c708f-776d-4fe8-92f3-5325d7197688)

my question is: is the event is necessary? if it is necessary, please fix it， if it is not necessary , please drop it .

### What you expected to happen

Running as expect。

### How to reproduce

Needs two or more masters, only one master can not reproduce this bug.

The reason is when a subprocess, will dispatch to different masters, And when the task(sub process) running is finished. Masters notify logic has an issue, not updating the task's end-time field will cause this bug.

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerves** [comment]
Another NullPointerException throwed by WorkflowExecuteThreadPool::crossWorkflowParameterPassing when workflow contain SubProcess task:
```
[ERROR] 2023-11-23 18:03:14.942 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThreadPool:[197] - [WorkflowInstance-77][TaskInstance-0] - Cross workflow parameter passing error, finishProcessInstanceId: 77, taskIn
stanceId: 151
java.lang.NullPointerException: null
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThreadPool.crossWorkflowParameterPassing(WorkflowExecuteThreadPool.java:192)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThreadPool.notifyProcessChanged(WorkflowExecuteThreadPool.java:172)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThreadPool.access$100(WorkflowExecuteThreadPool.java:59)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThreadPool$1.onSuccess(WorkflowExecuteThreadPool.java:146)
        at org.springframework.util.concurrent.ListenableFutureCallbackRegistry.notifySuccess(ListenableFutureCallbackRegistry.java:76)
        at org.springframework.util.concurrent.ListenableFutureCallbackRegistry.success(ListenableFutureCallbackRegistry.java:142)
        at org.springframework.util.concurrent.ListenableFutureTask.done(ListenableFutureTask.java:84)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384)
        at java.util.concurrent.FutureTask.set(FutureTask.java:233)
        at java.util.concurrent.FutureTask.run(FutureTask.java:274)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Is that means Cross workflow parameter passing failed? What is the impact?

**Comment by jerves** [comment]
Already fix on dev branch：https://github.com/apache/dolphinscheduler/pull/15057
