### ISSUE TITLE
[Bug] [dolphinscheduler-2.0.9] Overwrites the historical task instance when a retry fails, which leads to the retry fails immediately

### ISSUE THREAD

**Issue by TongWenbin** [apache/dolphinscheduler#15283]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

We update dolphinscheduler from 2.0.5 to 2.0.9, and then we found that when we set a retry, The latest taskInstance overwrites the old one,  And at the same time, our retry in shell task will  fails immediately with an error :
[ERROR] 2023-12-05 04:11:57.460 [TaskLogInfo- - [taskAppId=TASK-6940937559220_144-2498526-10848428]]  - shell task error
java.lang.RuntimeException: task execution time out
	at org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor.getRemainTime(AbstractCommandExecutor.java:431)
	at org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor.run(AbstractCommandExecutor.java:181)
	at org.apache.dolphinscheduler.plugin.task.shell.ShellTask.handle(ShellTask.java:97)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:198)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### What you expected to happen

something went wrong when the new instance overwrites the old，This reply is a possible cause：https://github.com/apache/dolphinscheduler/pull/10541#issuecomment-1840233590

### How to reproduce

use shell node which exec "java -jar XXXX.jar" and trigger failed retry, then there will be only one taskInstance of the latest, and report "shell task error java.lang.RuntimeException: task execution time out"

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Reply in (https://github.com/apache/dolphinscheduler/pull/10541#issuecomment-1842011064).

**Comment by TongWenbin** [comment]
i just run a test shell node which sleep 61s and set timeout = 1min, the number of retry times is 3, and the retry interval is 1 min
and there are logs of each time
**origin:**
```
[LOG-PATH]: /opt/apache-dolphinscheduler-2.0.9-bin/logs/11829436092416_1/2508353/10894304.log, [HOST]:  7.212.150.146 [INFO] 2023-12-06 15:39:38.213 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - shell task params {"resourceList":[],"localParams":[],"rawScript":"sleep 61s","dependence":{"dependTaskList":[],"relation":"AND"},"conditionResult":{"successNode":[],"failedNode":[]},"waitStartTimeout":{},"switchResult":{}} [INFO] 2023-12-06 15:39:38.214 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - raw script : sleep 61s [INFO] 2023-12-06 15:39:38.214 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - task execute path : /tmp/dolphinscheduler/exec/process/7149515337600/11829436092416_1/2508353/10894304 [INFO] 2023-12-06 15:39:38.214 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - tenantCode user:root, task dir:2508353_10894304 [INFO] 2023-12-06 15:39:38.214 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - create command file:/tmp/dolphinscheduler/exec/process/7149515337600/11829436092416_1/2508353/10894304/2508353_10894304.command [INFO] 2023-12-06 15:39:38.214 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - command : #!/bin/sh BASEDIR=$(cd dirname $0; pwd) cd $BASEDIR source /opt/apache-dolphinscheduler-2.0.9-bin/conf/env/dolphinscheduler_env.sh /tmp/dolphinscheduler/exec/process/7149515337600/11829436092416_1/2508353/10894304/2508353_10894304_node.sh [INFO] 2023-12-06 15:39:38.216 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - task run command: sudo -u root sh /tmp/dolphinscheduler/exec/process/7149515337600/11829436092416_1/2508353/10894304/2508353_10894304.command [INFO] 2023-12-06 15:39:38.217 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - process start, process id is: 105015 [INFO] 2023-12-06 15:39:39.218 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]-getOutputLogService]  -  -> welcome to use bigdata scheduling system... [ERROR] 2023-12-06 15:40:38.217 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - shell task error java.lang.IllegalThreadStateException: process hasn't exited at java.lang.UNIXProcess.exitValue(UNIXProcess.java:421) at org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor.run(AbstractCommandExecutor.java:197) at org.apache.dolphinscheduler.plugin.task.shell.ShellTask.handle(ShellTask.java:97) at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:198) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125) at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57) at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) [INFO] 2023-12-06 15:40:38.217 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - FINALIZE_SESSION [INFO] 2023-12-06 15:40:38.217 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - cancel process: 105015 [INFO] 2023-12-06 15:40:38.217 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - soft kill task:2508353_10894304, process id:105015, cmd:sudo -u root kill 105015
```

**first retry:**
```
[LOG-PATH]: /opt/apache-dolphinscheduler-2.0.9-bin/logs/11829436092416_1/2508353/10894304.log, [HOST]:  7.212.150.146 [INFO] 2023-12-06 15:39:38.213 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - shell task params {"resourceList":[],"localParams":[],"rawScript":"sleep 61s","dependence":{"dependTaskList":[],"relation":"AND"},"conditionResult":{"successNode":[],"failedNode":[]},"waitStartTimeout":{},"switchResult":{}} [INFO] 2023-12-06 15:39:38.214 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - raw script : sleep 61s [INFO] 2023-12-06 15:39:38.214 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - task execute path : /tmp/dolphinscheduler/exec/process/7149515337600/11829436092416_1/2508353/10894304 [INFO] 2023-12-06 15:39:38.214 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - tenantCode user:root, task dir:2508353_10894304 [INFO] 2023-12-06 15:39:38.214 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - create command file:/tmp/dolphinscheduler/exec/process/7149515337600/11829436092416_1/2508353/10894304/2508353_10894304.command [INFO] 2023-12-06 15:39:38.214 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - command : #!/bin/sh BASEDIR=$(cd dirname $0; pwd) cd $BASEDIR source /opt/apache-dolphinscheduler-2.0.9-bin/conf/env/dolphinscheduler_env.sh /tmp/dolphinscheduler/exec/process/7149515337600/11829436092416_1/2508353/10894304/2508353_10894304_node.sh [INFO] 2023-12-06 15:39:38.216 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - task run command: sudo -u root sh /tmp/dolphinscheduler/exec/process/7149515337600/11829436092416_1/2508353/10894304/2508353_10894304.command [INFO] 2023-12-06 15:39:38.217 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - process start, process id is: 105015 [INFO] 2023-12-06 15:39:39.218 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]-getOutputLogService]  -  -> welcome to use bigdata scheduling system... [ERROR] 2023-12-06 15:40:38.217 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - shell task error java.lang.IllegalThreadStateException: process hasn't exited at java.lang.UNIXProcess.exitValue(UNIXProcess.java:421) at org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor.run(AbstractCommandExecutor.java:197) at org.apache.dolphinscheduler.plugin.task.shell.ShellTask.handle(ShellTask.java:97) at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:198) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125) at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57) at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) [INFO] 2023-12-06 15:40:38.217 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - FINALIZE_SESSION [INFO] 2023-12-06 15:40:38.217 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - cancel process: 105015 [INFO] 2023-12-06 15:40:38.217 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - soft kill task:2508353_10894304, process id:105015, cmd:sudo -u root kill 105015 [INFO] 2023-12-06 15:40:39.225 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]-getOutputLogService]  - FINALIZE_SESSION [INFO] 2023-12-06 15:41:40.372 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - shell task params {"resourceList":[],"localParams":[],"rawScript":"sleep 61s","dependence":{"dependTaskList":[],"relation":"AND"},"conditionResult":{"successNode":[],"failedNode":[]},"waitStartTimeout":{},"switchResult":{}} [INFO] 2023-12-06 15:41:40.373 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - raw script : sleep 61s [INFO] 2023-12-06 15:41:40.373 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - task execute path : /tmp/dolphinscheduler/exec/process/7149515337600/11829436092416_1/2508353/10894304 [INFO] 2023-12-06 15:41:40.373 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - tenantCode user:root, task dir:2508353_10894304 [INFO] 2023-12-06 15:41:40.373 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - create command file:/tmp/dolphinscheduler/exec/process/7149515337600/11829436092416_1/2508353/10894304/2508353_10894304.command [INFO] 2023-12-06 15:41:40.373 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - command : #!/bin/sh BASEDIR=$(cd dirname $0; pwd) cd $BASEDIR source /opt/apache-dolphinscheduler-2.0.9-bin/conf/env/dolphinscheduler_env.sh /tmp/dolphinscheduler/exec/process/7149515337600/11829436092416_1/2508353/10894304/2508353_10894304_node.sh [INFO] 2023-12-06 15:41:40.375 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - task run command: sudo -u root sh /tmp/dolphinscheduler/exec/process/7149515337600/11829436092416_1/2508353/10894304/2508353_10894304.command [INFO] 2023-12-06 15:41:40.376 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - process start, process id is: 105632 [ERROR] 2023-12-06 15:41:40.376 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - shell task error java.lang.RuntimeException: task execution time out at org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor.getRemainTime(AbstractCommandExecutor.java:431) at org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor.run(AbstractCommandExecutor.java:181) at org.apache.dolphinscheduler.plugin.task.shell.ShellTask.handle(ShellTask.java:97) at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:198) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125) at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57) at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) [INFO] 2023-12-06 15:41:40.376 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  -  -> welcome to use bigdata scheduling system... [INFO] 2023-12-06 15:41:40.376 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - FINALIZE_SESSION [INFO] 2023-12-06 15:41:40.376 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - cancel process: 105632 [INFO] 2023-12-06 15:41:40.376 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - soft kill task:2508353_10894304, process id:105632, cmd:sudo -u root kill 105632
```

**second retry:**
```
[LOG-PATH]: /opt/apache-dolphinscheduler-2.0.9-bin/logs/11829436092416_1/2508353/10894304.log, [HOST]:  7.212.150.151 [INFO] 2023-12-06 15:42:45.506 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - shell task params {"resourceList":[],"localParams":[],"rawScript":"sleep 61s","dependence":{"dependTaskList":[],"relation":"AND"},"conditionResult":{"successNode":[],"failedNode":[]},"waitStartTimeout":{},"switchResult":{}} [INFO] 2023-12-06 15:42:45.506 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - raw script : sleep 61s [INFO] 2023-12-06 15:42:45.507 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - task execute path : /tmp/dolphinscheduler/exec/process/7149515337600/11829436092416_1/2508353/10894304 [INFO] 2023-12-06 15:42:45.507 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - tenantCode user:root, task dir:2508353_10894304 [INFO] 2023-12-06 15:42:45.507 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - create command file:/tmp/dolphinscheduler/exec/process/7149515337600/11829436092416_1/2508353/10894304/2508353_10894304.command [INFO] 2023-12-06 15:42:45.507 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - command : #!/bin/sh BASEDIR=$(cd dirname $0; pwd) cd $BASEDIR source /opt/apache-dolphinscheduler-2.0.9-bin/conf/env/dolphinscheduler_env.sh /tmp/dolphinscheduler/exec/process/7149515337600/11829436092416_1/2508353/10894304/2508353_10894304_node.sh [INFO] 2023-12-06 15:42:45.509 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - task run command: sudo -u root sh /tmp/dolphinscheduler/exec/process/7149515337600/11829436092416_1/2508353/10894304/2508353_10894304.command [INFO] 2023-12-06 15:42:45.510 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - process start, process id is: 3850 [ERROR] 2023-12-06 15:42:45.510 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - shell task error java.lang.RuntimeException: task execution time out at org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor.getRemainTime(AbstractCommandExecutor.java:431) at org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor.run(AbstractCommandExecutor.java:181) at org.apache.dolphinscheduler.plugin.task.shell.ShellTask.handle(ShellTask.java:97) at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:198) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125) at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57) at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) [INFO] 2023-12-06 15:42:45.510 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  -  -> welcome to use bigdata scheduling system... [INFO] 2023-12-06 15:42:45.510 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - FINALIZE_SESSION [INFO] 2023-12-06 15:42:45.510 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - cancel process: 3850 [INFO] 2023-12-06 15:42:45.510 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - soft kill task:2508353_10894304, process id:3850, cmd:sudo -u root kill 3850
```

**third retry:**
```
[LOG-PATH]: /opt/apache-dolphinscheduler-2.0.9-bin/logs/11829436092416_1/2508353/10894304.log, [HOST]:  7.212.150.223 [INFO] 2023-12-06 15:43:50.443 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - shell task params {"resourceList":[],"localParams":[],"rawScript":"sleep 61s","dependence":{"dependTaskList":[],"relation":"AND"},"conditionResult":{"successNode":[],"failedNode":[]},"waitStartTimeout":{},"switchResult":{}} [INFO] 2023-12-06 15:43:50.444 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - raw script : sleep 61s [INFO] 2023-12-06 15:43:50.444 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - task execute path : /tmp/dolphinscheduler/exec/process/7149515337600/11829436092416_1/2508353/10894304 [INFO] 2023-12-06 15:43:50.444 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - tenantCode user:root, task dir:2508353_10894304 [INFO] 2023-12-06 15:43:50.444 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - create command file:/tmp/dolphinscheduler/exec/process/7149515337600/11829436092416_1/2508353/10894304/2508353_10894304.command [INFO] 2023-12-06 15:43:50.444 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - command : #!/bin/sh BASEDIR=$(cd dirname $0; pwd) cd $BASEDIR source /opt/apache-dolphinscheduler-2.0.9-bin/conf/env/dolphinscheduler_env.sh /tmp/dolphinscheduler/exec/process/7149515337600/11829436092416_1/2508353/10894304/2508353_10894304_node.sh [INFO] 2023-12-06 15:43:50.447 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - task run command: sudo -u root sh /tmp/dolphinscheduler/exec/process/7149515337600/11829436092416_1/2508353/10894304/2508353_10894304.command [INFO] 2023-12-06 15:43:50.447 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - process start, process id is: 113359 [ERROR] 2023-12-06 15:43:50.447 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - shell task error java.lang.RuntimeException: task execution time out at org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor.getRemainTime(AbstractCommandExecutor.java:431) at org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor.run(AbstractCommandExecutor.java:181) at org.apache.dolphinscheduler.plugin.task.shell.ShellTask.handle(ShellTask.java:97) at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:198) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125) at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57) at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) [INFO] 2023-12-06 15:43:50.448 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  -  -> welcome to use bigdata scheduling system... [INFO] 2023-12-06 15:43:50.448 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - FINALIZE_SESSION [INFO] 2023-12-06 15:43:50.448 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - cancel process: 113359 [INFO] 2023-12-06 15:43:50.448 [TaskLogInfo- - [taskAppId=TASK-11829436092416_1-2508353-10894304]]  - soft kill task:2508353_10894304, process id:113359, cmd:sudo -u root kill 113359 
```

**Comment by TongWenbin** [comment]
as you can see, only the first retry append the log because first retry was executed by the same executor, 
the second and third lose the history because the retry task was send to other executor, and for user, the only thing i can see is the latest log without any history.
**and the retry failed immdiately, no retry was made actually**

so there are two problem,
first, when retry is send to another excutor, history log lost
second, retry will failed immdiately, it means there is no retry at all
