### ISSUE TITLE
[Bug] [Process] task instance host is null. When I was just running to get the logs

### ISSUE THREAD

**Issue by zerokiller007** [apache/dolphinscheduler#15297]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

[Bug] [Process] task instance host is null. When I was just running to get the logs

### What you expected to happen

no error report 

### How to reproduce

a single sql task,run and get log quickly

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by woshiwuxiaofei** [comment]
Do you need my help to solve this bug?

**Comment by zerokiller007** [comment]
![企业微信截图_17022825759517](https://github.com/apache/dolphinscheduler/assets/32101592/f6c3e673-172b-4578-a769-a249f6971206)
[ERROR] 2023-12-11 17:27:49.618 +0800 org.apache.dolphinscheduler.common.utils.JSONUtils:[151] - Parse object exception, jsonStr: "", class: class org.apache.dolphinscheduler.plugin.task.api.parameters.SwitchParameters
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot coerce empty String ("") to `org.apache.dolphinscheduler.plugin.task.api.parameters.SwitchParameters` value (but could if coercion was enabled using `CoercionConfig`)
 at [Source: (String)""""; line: 1, column: 1]
        at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
        at com.fasterxml.jackson.databind.DeserializationContext.reportBadCoercion(DeserializationContext.java:1806)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._checkCoercionFail(StdDeserializer.java:1477)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromEmptyString(StdDeserializer.java:325)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromString(StdDeserializer.java:270)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1495)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:197)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)
        at org.apache.dolphinscheduler.common.utils.JSONUtils.parseObject(JSONUtils.java:149)
        at org.apache.dolphinscheduler.dao.entity.TaskInstance.getSwitchDependency(TaskInstance.java:330)
        at sun.reflect.GeneratedMethodAccessor355.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.commons.beanutils.BeanMap.get(BeanMap.java:415)
        at org.apache.commons.beanutils.BeanMap$12.next(BeanMap.java:606)
        at org.apache.commons.beanutils.BeanMap$12.next(BeanMap.java:600)
        at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1044)
        at org.apache.dolphinscheduler.common.utils.CollectionUtils.getListByExclusion(CollectionUtils.java:64)
        at org.apache.dolphinscheduler.api.service.impl.TaskInstanceServiceImpl.queryTaskListPaging(TaskInstanceServiceImpl.java:176)
        at org.apache.dolphinscheduler.api.service.impl.TaskInstanceServiceImpl$$FastClassBySpringCGLIB$$a1a6235.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
        at org.apache.dolphinscheduler.api.service.impl.TaskInstanceServiceImpl$$EnhancerBySpringCGLIB$$44e7314.queryTaskListPaging(<generated>)
        at org.apache.dolphinscheduler.api.controller.TaskInstanceController.queryTaskListPaging(TaskInstanceController.java:123)
        at org.apache.dolphinscheduler.api.controller.TaskInstanceController$$FastClassBySpringCGLIB$$f052d6d9.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
        at org.apache.dolphinscheduler.api.aspect.AccessLogAspect.doAround(AccessLogAspect.java:102)
        at sun.reflect.GeneratedMethodAccessor191.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.jav
