### ISSUE TITLE
[Bug] [Master, Worker and Alarm Server]  Pseudo-Cluster Mode: Master, Worker and Alarm Server Crash on startup 

### ISSUE THREAD

**Issue by xkilhor** [apache/dolphinscheduler#15436]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Platform:  CentOS Linux 7 
Dolphin Version: 3.2.0
zookeeper Version: 3.9.1
Database: postgresql

On a fresh installation of dolphin in pseudo-cluster mode for evaluation purposes, I can't get the worker and the master server to run. API Server is running fine. I can access the UI and I can see the postgres DB was created. 
The alert server crashes most of the time on startup - yet sometimes it runs while throwing non-lethal exceptions until it eventually crashes again. 

I have searched through the documentation and the issues here but have yet to find a solution. The java stacktrace looks as follows in the logs:

```
JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.392.b08-2.el7_9.x86_64/jre
JAVA_OPTS=-server -Xms4g -Xmx4g -Xmn2g -XX:+IgnoreUnrecognizedVMOptions -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:gc.log -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=dump.hprof

Exception in thread "Worker-Server" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'workerServer': Invocation of init method failed; nested exception is org.apache.dolphinscheduler.registry.api.RegistryException: Worker registry client start up error
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
        at org.apache.dolphinscheduler.server.worker.WorkerServer.main(WorkerServer.java:90)
Caused by: org.apache.dolphinscheduler.registry.api.RegistryException: Worker registry client start up error
        at org.apache.dolphinscheduler.server.worker.registry.WorkerRegistryClient.start(WorkerRegistryClient.java:83)
        at org.apache.dolphinscheduler.server.worker.WorkerServer.run(WorkerServer.java:100)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
        ... 18 more
Caused by: java.lang.NumberFormatException: For input string: "0,12"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at org.apache.dolphinscheduler.common.utils.OSUtils.cpuUsagePercentage(OSUtils.java:150)
        at org.apache.dolphinscheduler.server.worker.task.WorkerHeartBeatTask.getHeartBeat(WorkerHeartBeatTask.java:57)
        at org.apache.dolphinscheduler.server.worker.registry.WorkerRegistryClient.registry(WorkerRegistryClient.java:91)
        at org.apache.dolphinscheduler.server.worker.registry.WorkerRegistryClient.start(WorkerRegistryClient.java:79)
        ... 26 more
```
I've attached the full logs for master and worker to this post. The errors are exactly the same. I have no idea why there would be a number format exception as i don't know where the OSUtils class gets that value from. I assume the real error occurs somewhere else.

[master-server-startup-error.log](https://github.com/apache/dolphinscheduler/files/13844458/master-server-startup-error.log)
[worker-server-error.log](https://github.com/apache/dolphinscheduler/files/13844459/worker-server-error.log)

### What you expected to happen

Worker, master and alert server start up normally

### How to reproduce

Follow the instructions for pseudo-cluster deployment here: https://dolphinscheduler.apache.org/en-us/docs/3.2.0/guide/installation/pseudo-cluster
Then try to start the servers via bin/start-all.sh

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
The current maximum version supported by zk is 3.8.0. 3.9.1 is not supported yet.
