### ISSUE TITLE
[Bug] [K8s] Spark on k8s ERROR <org.apache.spark.SparkException: Must specify the executor container image>

### ISSUE THREAD

**Issue by hugh018** [apache/dolphinscheduler#15535]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Spark 3.2.2   
dolphinscheduler 3.2.0
Run Spark on K8s task, ERROR :
	2513 [kubernetes-executor-snapshots-subscribers-0] WARN  org.apache.spark.scheduler.cluster.k8s.ExecutorPodsSnapshotsStoreImpl  - Exception when notifying snapshot subscriber.
	org.apache.spark.SparkException: Must specify the executor container image
		at org.apache.spark.deploy.k8s.features.BasicExecutorFeatureStep.$anonfun$executorContainerImage$1(BasicExecutorFeatureStep.scala:44)
		at scala.Option.getOrElse(Option.scala:189)
		at org.apache.spark.deploy.k8s.features.BasicExecutorFeatureStep.<init>(BasicExecutorFeatureStep.scala:44)
		at org.apache.spark.scheduler.cluster.k8s.KubernetesExecutorBuilder.buildFromFeatures(KubernetesExecutorBuilder.scala:50)
		at org.apache.spark.scheduler.cluster.k8s.ExecutorPodsAllocator.$anonfun$requestNewExecutors$1(ExecutorPodsAllocator.scala:391)
		at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
		at org.apache.spark.scheduler.cluster.k8s.ExecutorPodsAllocator.requestNewExecutors(ExecutorPodsAllocator.scala:382)
		at org.apache.spark.scheduler.cluster.k8s.ExecutorPodsAllocator.$anonfun$onNewSnapshots$36(ExecutorPodsAllocator.scala:346)
		at org.apache.spark.scheduler.cluster.k8s.ExecutorPodsAllocator.$anonfun$onNewSnapshots$36$adapted(ExecutorPodsAllocator.scala:339)
		at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
		at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
		at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
		at org.apache.spark.scheduler.cluster.k8s.ExecutorPodsAllocator.onNewSnapshots(ExecutorPodsAllocator.scala:339)
		at org.apache.spark.scheduler.cluster.k8s.ExecutorPodsAllocator.$anonfun$start$3(ExecutorPodsAllocator.scala:117)
		at org.apache.spark.scheduler.cluster.k8s.ExecutorPodsAllocator.$anonfun$start$3$adapted(ExecutorPodsAllocator.scala:117)
		at 

### What you expected to happen

org.apache.spark.SparkException: Must specify the executor container image
Frontend can select container image location

### How to reproduce

Spark 3.2.2   
dolphinscheduler 3.2.0
Run Spark on K8s task

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
hi @hugh018 i don't think ```Frontend can select container image location```  is a good idea ,maybe you can modify script add parameter ```spark.kubernetes.container.image```to fix it  .because the k8s task plugin is not specifically designed to handle spark tasks. maybe we can add a ``` spark on k8s ``` task plugin cc @zhongjiajie @Gallardot @EricGao888 @rickchengx WDYT?
