### ISSUE TITLE
[Bug] [ApiServer-3.2.1]  Error creating bean with name 'cloudServiceImpl' ,The apiserver cannot be started 

### ISSUE THREAD

**Issue by liu-hai** [apache/dolphinscheduler#15604]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

[WARN] 2024-02-21 02:13:01.291 +0000 o.s.c.k.c.p.AbstractKubernetesProfileEnvironmentPostProcessor:[258] - Not running inside kubernetes. Skipping 'kubernetes' profile activation.
[WARN] 2024-02-21 02:13:02.348 +0000 o.s.c.k.c.p.AbstractKubernetesProfileEnvironmentPostProcessor:[258] - Not running inside kubernetes. Skipping 'kubernetes' profile activation.
[INFO] 2024-02-21 02:13:02.350 +0000 o.a.d.a.ApiApplicationServer:[640] - The following 1 profile is active: "mysql"
[INFO] 2024-02-21 02:13:06.642 +0000 o.s.c.c.s.GenericScope:[283] - BeanFactory id=824909f4-2b81-3747-9027-3e040b008ebf
[INFO] 2024-02-21 02:13:07.721 +0000 o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:[376] - Bean 'io.kubernetes.client.spring.extended.manifests.config.KubernetesManifestsAutoConfiguration' of type [io.kubernetes.client.spring.extended.manifests.config.KubernetesManifestsAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO] 2024-02-21 02:13:07.777 +0000 o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:[376] - Bean 'org.springframework.cloud.commons.config.CommonsConfigAutoConfiguration' of type [org.springframework.cloud.commons.config.CommonsConfigAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO] 2024-02-21 02:13:07.786 +0000 o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:[376] - Bean 'org.springframework.cloud.client.loadbalancer.LoadBalancerDefaultMappingsProviderAutoConfiguration' of type [org.springframework.cloud.client.loadbalancer.LoadBalancerDefaultMappingsProviderAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO] 2024-02-21 02:13:07.791 +0000 o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:[376] - Bean 'loadBalancerClientsDefaultsMappingsProvider' of type [org.springframework.cloud.client.loadbalancer.LoadBalancerDefaultMappingsProviderAutoConfiguration$$Lambda$465/2011639997] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO] 2024-02-21 02:13:07.802 +0000 o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:[376] - Bean 'defaultsBindHandlerAdvisor' of type [org.springframework.cloud.commons.config.DefaultsBindHandlerAdvisor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO] 2024-02-21 02:13:07.817 +0000 o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:[376] - Bean 'kubernetes.manifests-io.kubernetes.client.spring.extended.manifests.config.KubernetesManifestsProperties' of type [io.kubernetes.client.spring.extended.manifests.config.KubernetesManifestsProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO] 2024-02-21 02:13:07.843 +0000 o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:[376] - Bean 'io.kubernetes.client.spring.extended.controller.config.KubernetesInformerAutoConfiguration' of type [io.kubernetes.client.spring.extended.controller.config.KubernetesInformerAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO] 2024-02-21 02:13:07.870 +0000 o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:[376] - Bean 'defaultApiClient' of type [io.kubernetes.client.openapi.ApiClient] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO] 2024-02-21 02:13:08.316 +0000 o.e.j.u.log:[170] - Logging initialized @11547ms to org.eclipse.jetty.util.log.Slf4jLog
[INFO] 2024-02-21 02:13:08.953 +0000 o.s.b.w.e.j.JettyServletWebServerFactory:[166] - Server initialized with port: 12345
[INFO] 2024-02-21 02:13:09.007 +0000 o.e.j.s.Server:[375] - jetty-9.4.48.v20220622; built: 2022-06-21T20:42:25.880Z; git: 6b67c5719d1f4371b33655ff2d047d24e171e49a; jvm 1.8.0_333-b02
[INFO] 2024-02-21 02:13:09.117 +0000 o.e.j.s.h.C.application:[2368] - Initializing Spring embedded WebApplicationContext
[INFO] 2024-02-21 02:13:09.118 +0000 o.s.b.w.s.c.ServletWebServerApplicationContext:[292] - Root WebApplicationContext: initialization completed in 6720 ms
[INFO] 2024-02-21 02:13:12.051 +0000 o.a.d.a.c.ApiConfig:[58] - API config: auditEnable -> false 
[INFO] 2024-02-21 02:13:12.052 +0000 o.a.d.a.c.ApiConfig:[59] - API config: trafficControl -> ApiConfig.TrafficConfiguration(globalSwitch=false, maxGlobalQpsRate=300, tenantSwitch=false, defaultTenantQpsRate=10, customizeTenantQpsRate={}) 
[INFO] 2024-02-21 02:13:12.052 +0000 o.a.d.a.c.ApiConfig:[60] - API config: pythonGateway -> ApiConfig.PythonGatewayConfiguration(enabled=true, gatewayServerAddress=0.0.0.0, gatewayServerPort=25333, pythonAddress=127.0.0.1, pythonPort=25334, connectTimeout=0, readTimeout=0, authToken=jwUDzpLsNKEFER4*a8gruBH_GsAurNxU7A@Xc) 
[INFO] 2024-02-21 02:13:12.377 +0000 o.e.j.s.session:[334] - DefaultSessionIdManager workerName=node0
[INFO] 2024-02-21 02:13:12.382 +0000 o.e.j.s.session:[339] - No SessionScavenger set, using defaults
[INFO] 2024-02-21 02:13:12.387 +0000 o.e.j.s.session:[132] - node0 Scavenging every 660000ms
[INFO] 2024-02-21 02:13:12.410 +0000 o.e.j.s.h.ContextHandler:[921] - Started o.s.b.w.e.j.JettyEmbeddedWebAppContext@59043741{application,/dolphinscheduler,[file:///tmp/jetty-docbase.12345.5266964206157535312/, jar:file:/opt/datasophon/dolphinscheduler-3.2.1/api-server/libs/swagger-ui-4.11.1.jar!/META-INF/resources],AVAILABLE}
[INFO] 2024-02-21 02:13:12.411 +0000 o.e.j.s.Server:[415] - Started @15645ms
[INFO] 2024-02-21 02:13:13.742 +0000 c.z.h.HikariDataSource:[110] - DolphinScheduler - Starting...
[INFO] 2024-02-21 02:13:14.712 +0000 c.z.h.HikariDataSource:[123] - DolphinScheduler - Start completed.
[INFO] 2024-02-21 02:13:20.218 +0000 o.a.c.u.Compatibility:[48] - Running in ZooKeeper 3.4.x compatibility mode
[INFO] 2024-02-21 02:13:20.221 +0000 o.a.c.u.Compatibility:[61] - Using emulated InjectSessionExpiration
[INFO] 2024-02-21 02:13:20.310 +0000 o.a.c.f.i.CuratorFrameworkImpl:[308] - Starting
[INFO] 2024-02-21 02:13:20.411 +0000 o.a.c.f.i.CuratorFrameworkImpl:[356] - Default schema
[INFO] 2024-02-21 02:13:20.448 +0000 o.a.c.f.s.ConnectionStateManager:[251] - State change: CONNECTED
[INFO] 2024-02-21 02:13:23.342 +0000 c.a.c.i.ReflectionUtils:[542] - Unable to create MethodHandles to use Java 9+ MethodHandles.privateLookupIn. Will attempt to fallback to using the package-private constructor.
[WARN] 2024-02-21 02:13:23.345 +0000 c.a.i.ClientSecretCredentialBuilder:[500] - Must provide non-null values for clientId, tenantId, clientSecret properties in ClientSecretCredentialBuilder
[WARN] 2024-02-21 02:13:23.347 +0000 o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext:[591] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cloudController': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cloudServiceImpl' defined in URL [jar:file:/opt/datasophon/dolphinscheduler-3.2.1/api-server/libs/dolphinscheduler-api-3.2.1.jar!/org/apache/dolphinscheduler/api/service/impl/CloudServiceImpl.class]: Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError
[INFO] 2024-02-21 02:13:23.354 +0000 o.a.c.f.i.CuratorFrameworkImpl:[955] - backgroundOperationsLoop exiting
[INFO] 2024-02-21 02:13:23.404 +0000 c.z.h.HikariDataSource:[350] - DolphinScheduler - Shutdown initiated...
[INFO] 2024-02-21 02:13:23.704 +0000 c.z.h.HikariDataSource:[352] - DolphinScheduler - Shutdown completed.
[INFO] 2024-02-21 02:13:23.717 +0000 o.e.j.s.session:[149] - node0 Stopped scavenging
[INFO] 2024-02-21 02:13:23.718 +0000 o.e.j.s.h.ContextHandler:[1159] - Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@59043741{application,/dolphinscheduler,[file:///tmp/jetty-docbase.12345.5266964206157535312/, jar:file:/opt/datasophon/dolphinscheduler-3.2.1/api-server/libs/swagger-ui-4.11.1.jar!/META-INF/resources],STOPPED}
[INFO] 2024-02-21 02:13:23.804 +0000 o.s.b.a.l.ConditionEvaluationReportLoggingListener:[136] - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[ERROR] 2024-02-21 02:13:23.887 +0000 o.s.b.SpringApplication:[824] - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cloudController': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cloudServiceImpl' defined in URL [jar:file:/opt/datasophon/dolphinscheduler-3.2.1/api-server/libs/dolphinscheduler-api-3.2.1.jar!/org/apache/dolphinscheduler/api/service/impl/CloudServiceImpl.class]: Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:332)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at org.apache.dolphinscheduler.api.ApiApplicationServer.main(ApiApplicationServer.java:58)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cloudServiceImpl' defined in URL [jar:file:/opt/datasophon/dolphinscheduler-3.2.1/api-server/libs/dolphinscheduler-api-3.2.1.jar!/org/apache/dolphinscheduler/api/service/impl/CloudServiceImpl.class]: Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1232)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:544)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:520)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:673)
	at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:228)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:329)
	... 17 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1326)
	... 33 common frames omitted
Caused by: java.lang.IllegalArgumentException: Must provide non-null values for clientId, tenantId, clientSecret properties in ClientSecretCredentialBuilder
	at com.azure.identity.implementation.util.ValidationUtil.validate(ValidationUtil.java:27)
	at com.azure.identity.ClientSecretCredentialBuilder.build(ClientSecretCredentialBuilder.java:74)
	at org.apache.dolphinscheduler.api.service.impl.CloudServiceImpl.<clinit>(CloudServiceImpl.java:55)
	... 40 common frames omitted

### What you expected to happen

Deployment 3.2.1 Cluster Mode apiserver fails to start

### How to reproduce

Normal deployment

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liu-hai** [comment]
java version "1.8.0_333"

**Comment by SbloodyS** [comment]
The root cause is `Must provide non-null values for clientId, tenantId, clientSecret properties in ClientSecretCredentialBuilder`

**Comment by Littlehhao** [comment]
Add it to the common.properties configuration file

  Resource.azure.client.id=minioadmin
  Resource.azure.client.secret=minioadmin
  resource.azure.subId=minioadmin
  Resource.azure.tenant.id=minioadmin
  resource.query.interval=10000

The default configuration is enough
