### ISSUE TITLE
[Bug] [flinkStream] The FlinkStream component cannot be started

### ISSUE THREAD

**Issue by caiyt2001** [apache/dolphinscheduler#15653]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

environment

Dolphinscheduler: Version 1.2.1

Flink1.17.1

Local mode operation

### What you expected to happen

[ERROR] 2024-02-29 08:54:09.959 +0800 o.a.d.e.b.s.JsonSerializer:[117] - deserialize exception!
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.apache.dolphinscheduler.extract.master.transportor.StreamingTaskTriggerResponse` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"success":true,"message":null}"; line: 1, column: 2]
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
        at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1904)
        at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1349)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1415)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)
        at org.apache.dolphinscheduler.extract.base.serialize.JsonSerializer.deserialize(JsonSerializer.java:115)
        at org.apache.dolphinscheduler.extract.base.client.SyncClientMethodInvoker.invoke(SyncClientMethodInvoker.java:54)
        at org.apache.dolphinscheduler.extract.base.client.ClientInvocationHandler.invoke(ClientInvocationHandler.java:55)
        at com.sun.proxy.$Proxy847.triggerStreamingTask(Unknown Source)
        at org.apache.dolphinscheduler.api.service.impl.ExecutorServiceImpl.execStreamTaskInstance(ExecutorServiceImpl.java:1164)
        at org.apache.dolphinscheduler.api.service.impl.ExecutorServiceImpl$$FastClassBySpringCGLIB$$ff5175fc.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
        at org.apache.dolphinscheduler.api.service.impl.ExecutorServiceImpl$$EnhancerBySpringCGLIB$$f8f79097.execStreamTaskInstance(<generated>)
        at org.apache.dolphinscheduler.api.controller.ExecutorController.startStreamTaskInstance(ExecutorController.java:461)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1070)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:517)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)

### How to reproduce

SET 'execution.checkpointing.interval' = '10s';

create table source_tab_001(id bigint, update_time TIMESTAMP,PRIMARY KEY (id) NOT ENFORCED)
with(
  'connector' = 'mysql-cdc',
  'hostname' = 'xxxx',
  'port' = 'xxx',
  'username' = 'meta',
  'password' = 'xxx',
  'database-name' = 'dw',
  'table-name' = 'tab_001'
);

CREATE TABLE sink_tab_001 ( id bigint , update_time TIMESTAMP ) WITH (
  'connector' = 'doris',
  'fenodes' = 'xxxx',
  'table.identifier' = 'db_test.tab_001',
  'username' = 'xxx',
  'password' = '',
  'sink.enable-2pc' = 'false',
  'sink.label-prefix' = 'doris_label' 
);

insert into sink_tab_001 select * from source_tab_001;

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
hi @caiyt2001 maybe we should add this annotation 
<img width="1102" alt="image" src="https://github.com/apache/dolphinscheduler/assets/33984497/3f789b93-b3ce-4082-acdd-94b426df94cc">

cc @ruanwenjun WDYT？

**Comment by ruanwenjun** [comment]
> hi @caiyt2001 maybe we should add this annotation <img alt="image" width="1102" src="https://private-user-images.githubusercontent.com/33984497/309550246-3f789b93-b3ce-4082-acdd-94b426df94cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MTc1NjksIm5iZiI6MTcwOTUxNzI2OSwicGF0aCI6Ii8zMzk4NDQ5Ny8zMDk1NTAyNDYtM2Y3ODliOTMtYjNjZS00MDgyLWFjZGQtOTRiNDI2ZGY5NGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDAxNTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NjZjNzcyZjUzZDQzZTBlNzg2MDQ5YmU5NGE2NDM0ZmU2NDY3ZDgyNmMzYjhhNmNmNWU4MzAwZjVhNTYyYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.olAszoJgZSNTKv6pdtFacAfMSq_aHDtmCGuf5DDZ9Gk">
> 
> cc @ruanwenjun WDYT？

Yes, if we use JSON format to serialize/deserialize the object/jsonstring, we need to make sure the object contains a empty constructor.

**Comment by caiyt2001** [comment]
I added this comment last time, but there are still other issues. The log is shown in the attachment






蔡
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dolphinscheduler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月4日(星期一) 上午9:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dolphinscheduler] [Bug] [flinkStream] The FlinkStream component cannot be started (Issue #15653)





  
hi @caiyt2001 maybe we should add this annotation 
 
cc @ruanwenjun WDYT？
  
Yes, if we use JSON format to serialize/deserialize the object/jsonstring, we need to make sure the object contains a empty constructor.

**Comment by caiyt2001** [comment]
I added this comment last time, but there are still other issues. The log is shown in the attachment
[dolphinscheduler-api.2024-02-29_10.0.log](https://github.com/apache/dolphinscheduler/files/14475741/dolphinscheduler-api.2024-02-29_10.0.log)
