### ISSUE TITLE
[Bug] [Worker] DataX task failed but displayed as successful.

### ISSUE THREAD

**Issue by adonis-lau-work** [apache/dolphinscheduler#15821]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

DataX task failed but displayed as successful.

### What you expected to happen

The DataX task was executed using the Shell component. The task failed internally due to field exceptions, but the Shell component reported a successful status.

### How to reproduce

You can create a shell component by yourself, call a DataX task that fails to run due to field type issues, and reproduce it.

### Version

3.2.x

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Can you provide some execution logs? @adonis-lau-work

**Comment by adonis-lau** [comment]
> Can you provide some execution logs? @adonis-lau-work

	经DataX智能分析,该任务最可能的错误原因是:
	com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-07], Description:[读取数据库数据失败. 请检查您的配置的 column/table/where/querySql或者向 DBA 寻求帮助.].  - 执行的SQL为: select id,PH产品编码,产品代码,hdsp_batch_id,产品规格,产品名称,城市,出货方代码,出货方等级,出货方名称,出货类型(流向单),创建日期,纯销or调拨,单价,单位,金额,进货方代码,进货方代码（流向单）,进货方地址,进货方名称,进货方名称（流向单）,客户类型,罗氏机构编码,罗氏经销商编码,批号,区县,省份,数量,所属大区,销售ID,销售公司,销售日期,业务月,原始产品规格,原始产品名称,原始单位,执行月,中外经销商编码,中外客户机构编码,'2024-04-09 21:47:38' from `dm`.`offline_chugai_s`  具体错误信息为：com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: FUNCTION dm.出货类型 does not exist - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: FUNCTION dm.出货类型 does not exist
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
		at com.mysql.jdbc.Util.getInstance(Util.java:408)
		at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
		at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
		at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
		at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
		at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
		at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491)
		at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2449)
		at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)
		at com.alibaba.datax.plugin.rdbms.util.DBUtil.query(DBUtil.java:446)
		at com.alibaba.datax.plugin.rdbms.util.DBUtil.query(DBUtil.java:433)
		at com.alibaba.datax.plugin.rdbms.util.DBUtil.query(DBUtil.java:412)
		at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:195)
		at com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader$Task.startRead(MysqlReader.java:81)
		at com.alibaba.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:57)
		at java.lang.Thread.run(Thread.java:748)
	
		at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:41)
		at com.alibaba.datax.plugin.rdbms.util.RdbmsException.asQueryException(RdbmsException.java:81)
		at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:220)
		at com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader$Task.startRead(MysqlReader.java:81)
		at com.alibaba.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:57)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: FUNCTION dm.出货类型 does not exist
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
		at com.mysql.jdbc.Util.getInstance(Util.java:408)
		at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
		at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
		at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
		at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
		at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
		at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491)
		at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2449)
		at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)
		at com.alibaba.datax.plugin.rdbms.util.DBUtil.query(DBUtil.java:446)
		at com.alibaba.datax.plugin.rdbms.util.DBUtil.query(DBUtil.java:433)
		at com.alibaba.datax.plugin.rdbms.util.DBUtil.query(DBUtil.java:412)
		at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:195)
		... 3 more
	
[INFO] 2024-04-09 21:48:07.987 +0800 -  -> 
	DataX任务已经完成

[INFO] 2024-04-09 21:48:07.987 +0800 - process has exited. execute path:/tmp/dolphinscheduler/exec/process/default/12316956401472/12438093636288_17/20391/41539, processId:20875 ,exitStatusCode:0 ,processWaitForStatus:true ,processExitValue:0
[INFO] 2024-04-09 21:48:07.988 +0800 - ***********************************************************************************************
[INFO] 2024-04-09 21:48:07.988 +0800 - *********************************  Finalize task instance  ************************************
[INFO] 2024-04-09 21:48:07.988 +0800 - ***********************************************************************************************
[INFO] 2024-04-09 21:48:07.988 +0800 - Upload output files: [] successfully
[INFO] 2024-04-09 21:48:07.988 +0800 - Send task execute status: SUCCESS to master : ipipipip:1234
[INFO] 2024-04-09 21:48:07.989 +0800 - Remove the current task execute context from worker cache
[INFO] 2024-04-09 21:48:07.989 +0800 - The current execute mode isn't develop mode, will clear the task execute file: /tmp/dolphinscheduler/exec/process/default/12316956401472/12438093636288_17/20391/41539
[INFO] 2024-04-09 21:48:07.989 +0800 - Success clear the task execute file: /tmp/dolphinscheduler/exec/process/default/12316956401472/12438093636288_17/20391/41539
[INFO] 2024-04-09 21:48:07.989 +0800 - FINALIZE_SESSION

**Comment by SbloodyS** [comment]
According to the logs, the cause can be identified as DataX exit code is 0. This is a question for DataX, please go to the DataX community to ask questions. @adonis-lau

**Comment by adonis-lau** [comment]
@SbloodyS 
OK
The one asking the question is my other account, you can close this question now. 
Thank you.
