### ISSUE TITLE
[Bug] [masterserver] when reboot mysql ,  suffered java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 

### ISSUE THREAD

**Issue by XiaoZhiSnow** [apache/dolphinscheduler#15863]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when reboot mysql which dolphinscheduler used, I run any process, i did not find the process instance, then I checked the master server log , I find these error message: 
[ERROR] 2024-04-17 15:54:22.168 +0800 o.a.d.s.m.r.MasterSchedulerBootstrap:[166] - Master schedule workflow error
org.springframework.dao.DuplicateKeyException:
### Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '5' for key 'PRIMARY'
; Duplicate entry '5' for key 'PRIMARY'; nested exception is java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '5' for key 'PRIMARY'
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:247)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
        at com.sun.proxy.$Proxy136.insert(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
        at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:59)
        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
        at com.sun.proxy.$Proxy167.insert(Unknown Source)
        at org.apache.dolphinscheduler.service.command.CommandServiceImpl.moveToErrorCommand(CommandServiceImpl.java:85)
        at org.apache.dolphinscheduler.service.command.CommandServiceImpl$$FastClassBySpringCGLIB$$299af041.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)

I have suffered these error messages manty times .  when reboot mysql ,it will appear again.

### What you expected to happen

when reboot mysql which ds used , dolphinscheduler should run normally.

### How to reproduce

reboot the mysql which ds used,  and you will suffer it

### Anything else

nothing

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by XiaoZhiSnow** [comment]
The mysql version  I used is 5.7.36-log. When reboot mysql, AUTO_INCRETEMENT will lost if the table does not have any data. 

So I change the mysql version into 8.0, it will resolve the problem of the auto_increament lost.
