### ISSUE TITLE
[Bug] [Module Name] when springboot  integrate  with seata,    Exception is occured     Caused by: io.seata.common.exception.NotSupportYetException: not support registry type: zookeeper

### ISSUE THREAD

**Issue by binbin0915** [apache/dolphinscheduler#15926]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when springboot  integrate  with seata,    Exception is occured     Caused by: io.seata.common.exception.NotSupportYetException: not support registry type: zookeeper
 Caused by: java.lang.ExceptionInInitializerError
                at io.seata.discovery.registry.RegistryFactory.getInstance(RegistryFactory.java:38) ~[seata-all-1.6.1.jar!/:1.6.1]
                at io.seata.core.rpc.netty.NettyClientChannelManager.getAvailServerList(NettyClientChannelManager.java:256) ~[seata-all-1.6.1.jar!/:1.6.1]
                at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:171) ~[seata-all-1.6.1.jar!/:1.6.1]
                at io.seata.core.rpc.netty.TmNettyRemotingClient.init(TmNettyRemotingClient.java:198) ~[seata-all-1.6.1.jar!/:1.6.1]
                at io.seata.tm.TMClient.init(TMClient.java:47) ~[seata-all-1.6.1.jar!/:1.6.1]
                at io.seata.spring.annotation.GlobalTransactionScanner.initClient(GlobalTransactionScanner.java:220) ~[seata-all-1.6.1.jar!/:1.6.1]
                at io.seata.spring.annotation.GlobalTransactionScanner.afterPropertiesSet(GlobalTransactionScanner.java:512) ~[seata-all-1.6.1.jar!/:1.6.1]
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.31.jar!/:5.3.31]
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.31.jar!/:5.3.31]
                ... 23 more
        Caused by: io.seata.common.exception.NotSupportYetException: not support registry type: zookeeper
                at io.seata.discovery.registry.RegistryFactory.buildRegistryService(RegistryFactory.java:49) ~[seata-all-1.6.1.jar!/:1.6.1]
                at io.seata.discovery.registry.RegistryFactory.access$100(RegistryFactory.java:30) ~[seata-all-1.6.1.jar!/:1.6.1]
                at io.seata.discovery.registry.RegistryFactory$RegistryFactoryHolder.<clinit>(RegistryFactory.java:56) ~[seata-all-1.6.1.jar!/:1.6.1]
                at io.seata.discovery.registry.RegistryFactory.getInstance(RegistryFactory.java:38) ~[seata-all-1.6.1.jar!/:1.6.1]
                at io.seata.core.rpc.netty.NettyClientChannelManager.getAvailServerList(NettyClientChannelManager.java:256) ~[seata-all-1.6.1.jar!/:1.6.1]
                at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:171) ~[seata-all-1.6.1.jar!/:1.6.1]
                at io.seata.core.rpc.netty.TmNettyRemotingClient.init(TmNettyRemotingClient.java:198) ~[seata-all-1.6.1.jar!/:1.6.1]
                at io.seata.tm.TMClient.init(TMClient.java:47) ~[seata-all-1.6.1.jar!/:1.6.1]
                at io.seata.spring.annotation.GlobalTransactionScanner.initClient(GlobalTransactionScanner.java:220) ~[seata-all-1.6.1.jar!/:1.6.1]
                at io.seata.spring.annotation.GlobalTransactionScanner.afterPropertiesSet(GlobalTransactionScanner.java:512) ~[seata-all-1.6.1.jar!/:1.6.1]
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.31.jar!/:5.3.31]
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.31.jar!/:5.3.31]
                ... 23 more

it is probably something   mixed with dolphin's  zookeeper's ip env  variables  , seata and dolphin 's zookeeper is different. how can i solve this problem

### What you expected to happen

 seata and dolphin 's zookeeper is different. how can i solve this problem

### How to reproduce

springboot with  seata

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Is this related to DS? I am not clear your question.
