### ISSUE TITLE
[Bug] [dolphinscheduler-tool]  insert t_ds_process_definition_log sql error

### ISSUE THREAD

**Issue by lyyprean** [apache/dolphinscheduler#16251]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

String insertLogSql =
                "insert into t_ds_process_definition_log (code,name,version,description,project_code,release_state,user_id,"
                        + "global_params,flag,locations,timeout,operator,operate_time,create_time,update_time) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

sql error, 15 fields, 16 question marks

### What you expected to happen

<img width="1134" alt="image" src="https://github.com/apache/dolphinscheduler/assets/51843122/20e26e5d-db9c-4112-865a-1298f5a0abf3">
sql error

### How to reproduce

sql error

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please provide more error logs.

**Comment by lyyprean** [comment]
This is an obvious sql error. The SQL has 15 fcolumn，but it has 16 （？）placeholders

**Comment by SbloodyS** [comment]
Need the error logs to check if it's deprecated. @lyyprean

**Comment by lyyprean** [comment]
![Uploading image.png…]()
        at org.apache.dolphinscheduler.tools.datasource.UpgradeDolphinScheduler.main(UpgradeDolphinScheduler.java:36)
[ERROR] 2024-07-02 09:13:36.482 org.apache.dolphinscheduler.tools.datasource.upgrader.v200.V200DolphinSchedulerUpgrader:[131] - json split error
java.lang.RuntimeException: java.sql.SQLException: No value specified for parameter 16
        at org.apache.dolphinscheduler.tools.datasource.dao.JsonSplitDao.executeJsonSplitProcessDefinition(JsonSplitDao.java:95)
        at org.apache.dolphinscheduler.tools.datasource.upgrader.v200.V200DolphinSchedulerUpgrader.processDefinitionJsonSplit(V200DolphinSchedulerUpgrader.java:127)
        at org.apache.dolphinscheduler.tools.datasource.upgrader.v200.V200DolphinSchedulerUpgrader.doUpgrade(V200DolphinSchedulerUpgrader.java:89)
        at org.apache.dolphinscheduler.tools.datasource.upgrader.v200.V200DolphinSchedulerUpgrader$$FastClassBySpringCGLIB$$1b4ba684.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at org.apache.dolphinscheduler.tools.datasource.upgrader.v200.V200DolphinSchedulerUpgrader$$EnhancerBySpringCGLIB$$9e6a8fff.doUpgrade(<generated>)
        at org.apache.dolphinscheduler.tools.datasource.DolphinSchedulerManager.lambda$upgradeDolphinScheduler$0(DolphinSchedulerManager.java:117)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.apache.dolphinscheduler.tools.datasource.DolphinSchedulerManager.upgradeDolphinScheduler(DolphinSchedulerManager.java:115)
        at org.apache.dolphinscheduler.tools.datasource.UpgradeDolphinScheduler$UpgradeRunner.run(UpgradeDolphinScheduler.java:53)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
        at org.apache.dolphinscheduler.tools.datasource.UpgradeDolphinScheduler.main(UpgradeDolphinScheduler.java:36)
Caused by: java.sql.SQLException: No value specified for parameter 16
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.addBatch(ClientPreparedStatement.java:252)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.addBatch(HikariProxyPreparedStatement.java)
        at org.apache.dolphinscheduler.tools.datasource.dao.JsonSplitDao.executeJsonSplitProcessDefinition(JsonSplitDao.java:79)
        ... 24 common frames omitted
[INFO] 2024-07-02 09:13:36.579 org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener:[136] - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[ERROR] 2024-07-02 09:13:36.605 org.springframework.boot.SpringApplication:[824] - Application run failed
java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:774)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
        at org.apache.dolphinscheduler.tools.datasource.UpgradeDolphinScheduler.main(UpgradeDolphinScheduler.java:36)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.sql.SQLException: No value specified for parameter 16
        at org.apache.dolphinscheduler.tools.datasource.DolphinSchedulerManager.lambda$upgradeDolphinScheduler$0(DolphinSchedulerManager.java:119)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.apache.dolphinscheduler.tools.datasource.DolphinSchedulerManager.upgradeDolphinScheduler(DolphinSchedulerManager.java:115)
        at org.apache.dolphinscheduler.tools.datasource.UpgradeDolphinScheduler$UpgradeRunner.run(UpgradeDolphinScheduler.java:53)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771)
        ... 5 common frames omitted
Caused by: java.lang.RuntimeException: java.sql.SQLException: No value specified for parameter 16
        at org.apache.dolphinscheduler.tools.datasource.dao.JsonSplitDao.executeJsonSplitProcessDefinition(JsonSplitDao.java:95)
        at org.apache.dolphinscheduler.tools.datasource.upgrader.v200.V200DolphinSchedulerUpgrader.processDefinitionJsonSplit(V200DolphinSchedulerUpgrader.java:127)
        at org.apache.dolphinscheduler.tools.datasource.upgrader.v200.V200DolphinSchedulerUpgrader.doUpgrade(V200DolphinSchedulerUpgrader.java:89)
        at org.apache.dolphinscheduler.tools.datasource.upgrader.v200.V200DolphinSchedulerUpgrader$$FastClassBySpringCGLIB$$1b4ba684.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at org.apache.dolphinscheduler.tools.datasource.upgrader.v200.V200DolphinSchedulerUpgrader$$EnhancerBySpringCGLIB$$9e6a8fff.doUpgrade(<generated>)
        at org.apache.dolphinscheduler.tools.datasource.DolphinSchedulerManager.lambda$upgradeDolphinScheduler$0(DolphinSchedulerManager.java:117)
        ... 9 common frames omitted
Caused by: java.sql.SQLException: No value specified for parameter 16
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.addBatch(ClientPreparedStatement.java:252)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.addBatch(HikariProxyPreparedStatement.java)
        at org.apache.dolphinscheduler.tools.datasource.dao.JsonSplitDao.executeJsonSplitProcessDefinition(JsonSplitDao.java:79)

**Comment by SbloodyS** [comment]
Which version you want to upgrade to? @lyyprean

**Comment by lyyprean** [comment]
1.20 to 3.2.1

**Comment by SbloodyS** [comment]
This is indeed a bug. However, the minimum support for upgrading to 3.2.1 is 1.3.0. And it is no longer maintained for versions earlier than 2.0.8.

**Comment by lyyprean** [comment]
ok
