### ISSUE TITLE
[Doc][Module Name] Documentation bug or improvement：3.2.1 adding oceanbase datasource "compatiblemode" parameter

### ISSUE THREAD

**Issue by 2u0ta0** [apache/dolphinscheduler#16254]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When adding Oceanbase as a new data source, there is a "compatiblemode" input, I did some search in both dolphin and oceanbase, but it seems no clear definition about it. Please give some advice. 

I have tried to input: 
- MYSQL
- ORACLE
- mysql
- oceanbase
- OCEANBASE
- 5
- 6
- 8
nothing works

ERR LOG
[INFO] 2024-07-02 08:23:10.716 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[INFO] 2024-07-02 08:23:12.321 +0800 o.a.d.p.d.a.u.DataSourceUtils:[57] - Parameters map:OceanBaseConnectionParam(compatibleMode=MYSQL)
[ERROR] 2024-07-02 08:23:12.322 +0800 o.a.d.p.d.a.d.AbstractDataSourceProcessor:[130] - Check datasource connectivity for: OCEANBASE error
java.lang.ClassNotFoundException: com.oceanbase.jdbc.Driver
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)

![图片](https://github.com/apache/dolphinscheduler/assets/31498851/d51da73f-2b53-48fd-b0fa-277525c0ba6a)

Thanks

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 2u0ta0** [comment]
ISSUE RESOLVED


doc: https://kkgithub.com/apache/dolphinscheduler/blob/3.2.1-release/docs/docs/en/guide/howto/datasource-setting.md
need to import correct version of oceanbase jdbc driver
