### ISSUE TITLE
[Bug] [dolphinscheduler-alert] When HTTP alarm is triggered, the test alarm is normal, but there is an MismatchedInputException when the alarm task occurs

### ISSUE THREAD

**Issue by StarInitial** [apache/dolphinscheduler#16405]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When HTTP alarm is triggered, the test alarm is normal, but there is an MismatchedInputException when the alarm task occurs

### What you expected to happen

The alarm HTTP call should be triggered normally

### How to reproduce

Create an HTTP alarm instance, connect to the workflow, and prompt the workflow to trigger the alarm

### Anything else

[ERROR] 2024-07-31 15:23:10.241 +0800 o.a.d.c.u.JSONUtils:[186] - parse list exception!
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<org.apache.dolphinscheduler.spi.params.base.PluginParams>` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (String)"{"headerParams":"{}","requestType":"POST","bodyParams":"{}","url":"http://star.center/MessageSend","contentField":"alert","timeout":"120"}"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1462)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:392)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:252)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
	at org.apache.dolphinscheduler.common.utils.JSONUtils.toList(JSONUtils.java:184)
	at org.apache.dolphinscheduler.spi.params.PluginParamsTransfer.transferJsonToParamsList(PluginParamsTransfer.java:42)
	at org.apache.dolphinscheduler.spi.params.PluginParamsTransfer.getPluginParamsMap(PluginParamsTransfer.java:49)
	at org.apache.dolphinscheduler.alert.service.AbstractEventSender.doSendEvent(AbstractEventSender.java:125)
	at org.apache.dolphinscheduler.alert.service.AbstractEventSender.sendEvent(AbstractEventSender.java:73)
	at org.apache.dolphinscheduler.alert.service.AlertEventLoop.handleEvent(AlertEventLoop.java:43)
	at org.apache.dolphinscheduler.alert.service.AlertEventLoop.handleEvent(AlertEventLoop.java:27)
	at org.apache.dolphinscheduler.alert.service.AbstractEventLoop.lambda$run$0(AbstractEventLoop.java:73)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ahululu** [comment]
hello, How did you solve the problem？

**Comment by StarInitial** [comment]
> hello, How did you solve the problem？

I haven't solve the problem. I found that this product does not meet my needs, so I am considering implementing the logic I need myself.

**Comment by likun1210** [comment]
> hello, How did you solve the problem？

你好，我也碰到了这个问题，你怎么解决的？
