### ISSUE TITLE
[Bug] [alert server] Unable to send alert.

### ISSUE THREAD

**Issue by a3sroot** [apache/dolphinscheduler#16448]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

version 3.2.2
[ERROR] 2024-08-13 16:37:50.471 +0800 org.apache.dolphinscheduler.common.utils.JSONUtils:[186] - parse list exception!
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<org.apache.dolphinscheduler.spi.params.base.PluginParams>` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (String)"{"headerParams":"{}","requestType":"POST","bodyParams":null,"url":"http://127.0.0.1:8888","contentField":"alert","timeout":"120"}"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1462)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:392)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:252)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
	at org.apache.dolphinscheduler.common.utils.JSONUtils.toList(JSONUtils.java:184)
	at org.apache.dolphinscheduler.spi.params.PluginParamsTransfer.transferJsonToParamsList(PluginParamsTransfer.java:42)
	at org.apache.dolphinscheduler.spi.params.PluginParamsTransfer.getPluginParamsMap(PluginParamsTransfer.java:49)
	at org.apache.dolphinscheduler.alert.service.AbstractEventSender.doSendEvent(AbstractEventSender.java:125)
	at org.apache.dolphinscheduler.alert.service.AbstractEventSender.sendEvent(AbstractEventSender.java:73)
	at org.apache.dolphinscheduler.alert.service.ListenerEventLoop.handleEvent(ListenerEventLoop.java:38)
	at org.apache.dolphinscheduler.alert.service.ListenerEventLoop.handleEvent(ListenerEventLoop.java:24)
	at org.apache.dolphinscheduler.alert.service.AbstractEventLoop.lambda$run$0(AbstractEventLoop.java:73)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

### What you expected to happen

The alarm service is working properly.

### How to reproduce

Add an alert instance and test it.

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Already fixed in dev.

**Comment by likun1210** [comment]
> Already fixed in dev.

I  also meet this problem, did you have solved this problem?How can I use the modified jar package now？

**Comment by likun1210** [comment]
> Already fixed in dev.

I  also meet this problem with version 3.3.0, do you solve this problem?

**Comment by liuyuanzhi-cn** [comment]
> > Already fixed in dev.
> 
> I also meet this problem, did you have solved this problem?How can I use the modified jar package now？

You can fix it like [this commit](https://github.com/apache/dolphinscheduler/commit/b53994206714d48a07e87fb9a60c641dadc686db)
