### ISSUE TITLE
[Bug] [plugin] Failed start seatunnel task

### ISSUE THREAD

**Issue by hanhanzhang** [apache/dolphinscheduler#16582]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When deploying flink task in run-application mode, config file not found.
2024-09-04 09:27:44,885 ERROR org.apache.seatunnel.core.starter.SeaTunnel                  [] - Fatal Error, 

2024-09-04 09:27:44,885 ERROR org.apache.seatunnel.core.starter.SeaTunnel                  [] - Please submit bug report in https://github.com/apache/seatunnel/issues

2024-09-04 09:27:44,885 ERROR org.apache.seatunnel.core.starter.SeaTunnel                  [] - Reason:ErrorCode:[COMMON-22], ErrorDescription:[SeaTunnel read file '/data/dolphinScheduler/exec/process/video/118325094409344/118678805354560_9/47/83/seatunnel_47_83.conf' failed, because it not existed.] 

2024-09-04 09:27:44,887 ERROR org.apache.seatunnel.core.starter.SeaTunnel                  [] - Exception StackTrace:org.apache.seatunnel.common.exception.SeaTunnelRuntimeException: ErrorCode:[COMMON-22], ErrorDescription:[SeaTunnel read file '/data/dolphinScheduler/exec/process/video/118325094409344/118678805354560_9/47/83/seatunnel_47_83.conf' failed, because it not existed.]
	at org.apache.seatunnel.common.exception.CommonError.fileNotExistFailed(CommonError.java:86)
	at org.apache.seatunnel.core.starter.utils.FileUtils.checkConfigExist(FileUtils.java:66)
	at org.apache.seatunnel.core.starter.flink.command.FlinkTaskExecuteCommand.execute(FlinkTaskExecuteCommand.java:50)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.flink.SeaTunnelFlink.main(SeaTunnelFlink.java:34)

### What you expected to happen

For application mode, external cluster needs to have access to the configuration file of the Seatunnel task.

### How to reproduce

Configuration file of Seatunnel task can be stored by Dolphin's storage mechanism, and the file can be deleted after the task is submitted.

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by agp5050** [comment]
Caused by: org.apache.seatunnel.common.exception.SeaTunnelRuntimeException: ErrorCode:[COMMON-22], ErrorDescription:[SeaTunnel read file '/tmp/dolphinscheduler/exec/process/root/15945285955616/15945293083168_12/9/12/seatunnel_9_12.conf' failed, because it not existed.]
	at org.apache.seatunnel.common.exception.CommonError.fileNotExistFailed(CommonError.java:86) ~[seatunnel-flink-13-starter.jar:2.3.8]
	at org.apache.seatunnel.core.starter.utils.FileUtils.checkConfigExist(FileUtils.java:66) ~[seatunnel-flink-13-starter.jar:2.3.8]
	at org.apache.seatunnel.core.starter.flink.command.FlinkTaskExecuteCommand.execute(FlinkTaskExecuteCommand.java:50) ~[seatunnel-flink-13-starter.jar:2.3.8]
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40) ~[seatunnel-flink-13-starter.jar:2.3.8]
	at org.apache.seatunnel.core.starter.flink.SeaTunnelFlink.main(SeaTunnelFlink.java:34) ~[seatunnel-flink-13-starter.jar:2.3.8]
