### ISSUE TITLE
[Bug] [tenant] this will not affect the task status, but you need to clear this manually org.apache.commons.io.IOExceptionList xxx

### ISSUE THREAD

**Issue by wangchao732** [apache/dolphinscheduler#16604]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

[LOG-PATH]: /opt/dolphinscheduler3.19/worker-server/logs/20240911/26_1-239277-364644.log, [HOST]:  Host{address='192.168.11.156:1234', ip='192.168.11.156', port=1234}
[INFO] 2024-09-11 11:26:37.167 +0800 - Begin to pulling task
[INFO] 2024-09-11 11:26:37.170 +0800 - Begin to initialize task
[INFO] 2024-09-11 11:26:37.170 +0800 - Set task startTime: Wed Sep 11 11:26:37 GMT+08:00 2024
[INFO] 2024-09-11 11:26:37.171 +0800 - Set task envFile: /opt/dolphinscheduler3.19/worker-server/conf/dolphinscheduler_env.sh
[INFO] 2024-09-11 11:26:37.171 +0800 - Set task appId: 239277_364644
[INFO] 2024-09-11 11:26:37.171 +0800 - End initialize task
[INFO] 2024-09-11 11:26:37.172 +0800 - Set task status to TaskExecutionStatus{code=1, desc='running'}
[INFO] 2024-09-11 11:26:37.172 +0800 - TenantCode:bclduser check success
[INFO] 2024-09-11 11:26:37.172 +0800 - ProcessExecDir:/tmp/dolphinscheduler/exec/process/bclduser/1/26_1/239277/364644 check success
[INFO] 2024-09-11 11:26:37.173 +0800 - Resources:{} check success
[INFO] 2024-09-11 11:26:37.173 +0800 - Task plugin: SHELL create success
[INFO] 2024-09-11 11:26:37.173 +0800 - shell task params {"resourceList":[],"localParams":[],"rawScript":"java -jar /opt/data/scripts/hunan-repeat/syn-block-info-farm-1.0.0.jar 1 11","conditionResult":{"successNode":[""],"failedNode":[""]},"dependence":{}}
[INFO] 2024-09-11 11:26:37.173 +0800 - Success initialized task plugin instance success
[INFO] 2024-09-11 11:26:37.174 +0800 - Success set taskVarPool: []
[INFO] 2024-09-11 11:26:37.174 +0800 - raw script : java -jar /opt/data/scripts/hunan-repeat/syn-block-info-farm-1.0.0.jar 1 11
[INFO] 2024-09-11 11:26:37.174 +0800 - task execute path : /tmp/dolphinscheduler/exec/process/bclduser/1/26_1/239277/364644
[INFO] 2024-09-11 11:26:37.174 +0800 - Begin to create command file:/tmp/dolphinscheduler/exec/process/bclduser/1/26_1/239277/364644/239277_364644.command
[INFO] 2024-09-11 11:26:37.175 +0800 - Success create command file, command: #!/bin/bash
BASEDIR=$(cd `dirname $0`; pwd)
cd $BASEDIR
source /opt/dolphinscheduler3.19/worker-server/conf/dolphinscheduler_env.sh
/tmp/dolphinscheduler/exec/process/bclduser/1/26_1/239277/364644/239277_364644_node.sh
[INFO] 2024-09-11 11:26:37.180 +0800 - task run command: sudo -u bclduser -i bash /tmp/dolphinscheduler/exec/process/bclduser/1/26_1/239277/364644/239277_364644.command
[INFO] 2024-09-11 11:26:37.181 +0800 - process start, process id is: 5063
[INFO] 2024-09-11 11:26:38.182 +0800 -  -> mysql mysql jdbc:mysql://192.168.11.198:3306/dolphinscheduler
	SLF4J: Class path contains multiple SLF4J bindings.
	SLF4J: Found binding in [jar:file:/opt/data/scripts/hunan-repeat/syn-block-info-farm-1.0.0.jar!/BOOT-INF/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
	SLF4J: Found binding in [jar:file:/opt/data/scripts/hunan-repeat/syn-block-info-farm-1.0.0.jar!/BOOT-INF/lib/toolkit-hbase-CDH5-20210122.jar!/org/slf4j/impl/StaticLoggerBinder.class]
	SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
	SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[INFO] 2024-09-11 11:26:39.183 +0800 -  -> 
	  .   ____          _            __ _ _
	 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
	( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
	 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
	  '  |____| .__|_| |_|_| |_\__, | / / / /
	 =========|_|==============|___/=/_/_/_/
	 :: Spring Boot ::        (v2.1.5.RELEASE)
	
	2024-09-11 11:26:38.807  INFO 5091 --- [           main] uml.tech.App                             : Starting App v1.0.0 on cdh-slave6 with PID 5091 (/opt/data/scripts/hunan-repeat/syn-block-info-farm-1.0.0.jar started by bclduser in /tmp/dolphinscheduler/exec/process/bclduser/1/26_1/239277/364644)
	2024-09-11 11:26:38.808 DEBUG 5091 --- [           main] uml.tech.App                             : Running with Spring Boot v2.1.5.RELEASE, Spring v5.1.7.RELEASE
	2024-09-11 11:26:38.808  INFO 5091 --- [           main] uml.tech.App                             : The following profiles are active: mysql
[INFO] 2024-09-11 11:26:43.184 +0800 -  -> log4j:WARN No appenders could be found for logger (org.apache.htrace.core.Tracer).
	log4j:WARN Please initialize the log4j system properly.
	log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[INFO] 2024-09-11 11:26:44.185 +0800 -  -> 2024-09-11 11:26:43.685  INFO 5091 --- [           main] uml.tech.App                             : Started App in 5.466 seconds (JVM running for 6.435)
	开始更新湖南重复地块
	2024-09-11 11:26:44.125 DEBUG 5091 --- [           main] u.t.m.f.F.getHunanWorkInfo60Days         : ==>  Preparing: select id, did, jobStartLat, jobStartLon, currentBlockNumber, jobEndTime, province, city, district, jobArea as area, jobStartTime, jobType, jobEquipment, wkt_poly as wktPoly, 0 as dataSource, repeatFlag from farm_work where (did like 'NJ%' OR did like 'EC%') and fixFlag !=1 and jobType= '3' and (jobEquipment ='3' or jobEquipment = '7') and DATEDIFF(now(), insertTime) < 60 and wkt_poly is not null and wkt_poly !='' and province = 11 union all select id, did, jobStartLat, jobStartLon, currentBlockNumber, jobEndTime, province, city, district, jobArea as area, jobStartTime, jobType, jobEquipment, wkt_poly as wktPoly, 1 as dataSource, repeatFlag from farm_work_split where (did like 'NJ%' OR did like 'EC%') and jobType= '3' and (jobEquipment ='3' or jobEquipment = '7') and DATEDIFF(now(), insertTime) < 60 and wkt_poly is not null and wkt_poly !='' and province = 11 order by jobEndTime desc; 
	2024-09-11 11:26:44.154 DEBUG 5091 --- [           main] u.t.m.f.F.getHunanWorkInfo60Days         : ==> Parameters: 
[INFO] 2024-09-11 11:26:44.444 +0800 - process has exited. execute path:/tmp/dolphinscheduler/exec/process/bclduser/1/26_1/239277/364644, processId:5063 ,exitStatusCode:0 ,processWaitForStatus:true ,processExitValue:0
[INFO] 2024-09-11 11:26:44.447 +0800 - Send task execute result to master, the current task status: TaskExecutionStatus{code=7, desc='success'}
[INFO] 2024-09-11 11:26:44.447 +0800 - Remove the current task execute context from worker cache
[INFO] 2024-09-11 11:26:44.448 +0800 - The current execute mode isn't develop mode, will clear the task execute file: /tmp/dolphinscheduler/exec/process/bclduser/1/26_1/239277/364644
[ERROR] 2024-09-11 11:26:44.450 +0800 - Delete task execute file: /tmp/dolphinscheduler/exec/process/bclduser/1/26_1/239277/364644 failed, this will not affect the task status, but you need to clear this manually
org.apache.commons.io.IOExceptionList: /tmp/dolphinscheduler/exec/process/bclduser/1/26_1/239277/364644
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:331)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1192)
	at org.apache.dolphinscheduler.server.worker.runner.WorkerTaskExecuteRunnable.clearTaskExecPathIfNeeded(WorkerTaskExecuteRunnable.java:283)
	at org.apache.dolphinscheduler.server.worker.runner.WorkerTaskExecuteRunnable.afterExecute(WorkerTaskExecuteRunnable.java:115)
	at org.apache.dolphinscheduler.server.worker.runner.DefaultWorkerDelayTaskExecuteRunnable.afterExecute(DefaultWorkerDelayTaskExecuteRunnable.java:54)
	at org.apache.dolphinscheduler.server.worker.runner.WorkerTaskExecuteRunnable.run(WorkerTaskExecuteRunnable.java:176)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot delete file: /tmp/dolphinscheduler/exec/process/bclduser/1/26_1/239277/364644/bin
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1344)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:324)
	... 12 common frames omitted
Caused by: java.nio.file.AccessDeniedException: /tmp/dolphinscheduler/exec/process/bclduser/1/26_1/239277/364644/bin/winutils.exe
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
	at java.nio.file.Files.deleteIfExists(Files.java:1165)
	at org.apache.commons.io.file.DeletingPathVisitor.visitFile(DeletingPathVisitor.java:161)
	at org.apache.commons.io.file.DeletingPathVisitor.visitFile(DeletingPathVisitor.java:37)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.apache.commons.io.file.PathUtils.visitFileTree(PathUtils.java:971)
	at org.apache.commons.io.file.PathUtils.deleteDirectory(PathUtils.java:434)
	at org.apache.commons.io.file.PathUtils.delete(PathUtils.java:391)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1341)
	... 13 common frames omitted
[INFO] 2024-09-11 11:26:45.186 +0800 -  -> 2024-09-11 11:26:44.210 DEBUG 5091 --- [           main] u.t.m.f.F.getHunanWorkInfo60Days         : <==      Total: 0
[INFO] 2024-09-11 11:26:45.186 +0800 - FINALIZE_SESSION

### What you expected to happen

shell process
![4b803876682121623df7e00833fdc82](https://github.com/user-attachments/assets/2f141efd-ede9-49a7-a9b8-93aaac0c3f82)
![1726027729487](https://github.com/user-attachments/assets/55d3aa64-7c8d-478b-9561-c65236887ca9)

### How to reproduce

run shell process with  tenant.

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Windows is not supported right now.

**Comment by wangchao732** [comment]
> Windows is not supported right now.

Sorry, i'm not see.  Where did you see it running on Windows?

**Comment by SbloodyS** [comment]
> Caused by: java.nio.file.AccessDeniedException: 
> /tmp/dolphinscheduler/exec/process/bclduser/1/26_1/239277/364644/bin/winutils.exe

@wangchao732

**Comment by wangchao732** [comment]
> > Caused by: java.nio.file.AccessDeniedException:
> > /tmp/dolphinscheduler/exec/process/bclduser/1/26_1/239277/364644/bin/winutils.exe
> 
> @wangchao732

Please ignore this, it has nothing to do with this.

**Comment by wangchao732** [comment]
> > > Caused by: java.nio.file.AccessDeniedException:
> > > /tmp/dolphinscheduler/exec/process/bclduser/1/26_1/239277/364644/bin/winutils.exe
> > 
> > 
> > @wangchao732
> 
> Please ignore this, it has nothing to do with this.

Also, just because it has a .exe file underneath it, you think it's running under Windows. Currently running on Linux CentOS 6.x.

**Comment by SbloodyS** [comment]
Then you should provide the corresponding reproduction steps and the correct log information.

**Comment by wangchao732** [comment]
> Then you should provide the corresponding reproduction steps and the correct log information.

[LOG-PATH]: /opt/dolphinscheduler3.19/worker-server/logs/20240911/11_1-239613-365122.log, [HOST]:  Host{address='192.168.11.156:1234', ip='192.168.11.156', port=1234}
[INFO] 2024-09-11 18:00:00.694 +0800 - Begin to pulling task
[INFO] 2024-09-11 18:00:00.697 +0800 - Begin to initialize task
[INFO] 2024-09-11 18:00:00.697 +0800 - Set task startTime: Wed Sep 11 18:00:00 GMT+08:00 2024
[INFO] 2024-09-11 18:00:00.697 +0800 - Set task envFile: /opt/dolphinscheduler3.19/worker-server/conf/dolphinscheduler_env.sh
[INFO] 2024-09-11 18:00:00.698 +0800 - Set task appId: 239613_365122
[INFO] 2024-09-11 18:00:00.698 +0800 - End initialize task
[INFO] 2024-09-11 18:00:00.698 +0800 - Set task status to TaskExecutionStatus{code=1, desc='running'}
[INFO] 2024-09-11 18:00:00.699 +0800 - TenantCode:bclduser check success
[INFO] 2024-09-11 18:00:00.701 +0800 - ProcessExecDir:/tmp/dolphinscheduler/exec/process/bclduser/1/11_1/239613/365122 check success
[INFO] 2024-09-11 18:00:00.702 +0800 - Resources:{} check success
[INFO] 2024-09-11 18:00:00.703 +0800 - Task plugin: SHELL create success
[INFO] 2024-09-11 18:00:00.703 +0800 - shell task params {"resourceList":[],"localParams":[],"rawScript":"java -jar /opt/data/scripts/azkaban-timesync-tdenige-tag/azkaban-timesync-tdenige-tag-1.0.0.jar --spring.profiles.active=dev --onlyVin=0 --runnerName=TdengineTagNullRunner","conditionResult":{"successNode":[""],"failedNode":[""]},"dependence":{}}
[INFO] 2024-09-11 18:00:00.703 +0800 - Success initialized task plugin instance success
[INFO] 2024-09-11 18:00:00.704 +0800 - Success set taskVarPool: null
[INFO] 2024-09-11 18:00:00.704 +0800 - raw script : java -jar /opt/data/scripts/azkaban-timesync-tdenige-tag/azkaban-timesync-tdenige-tag-1.0.0.jar --spring.profiles.active=dev --onlyVin=0 --runnerName=TdengineTagNullRunner
[INFO] 2024-09-11 18:00:00.705 +0800 - task execute path : /tmp/dolphinscheduler/exec/process/bclduser/1/11_1/239613/365122
[INFO] 2024-09-11 18:00:00.705 +0800 - Begin to create command file:/tmp/dolphinscheduler/exec/process/bclduser/1/11_1/239613/365122/239613_365122.command
[INFO] 2024-09-11 18:00:00.705 +0800 - Success create command file, command: #!/bin/bash
BASEDIR=$(cd `dirname $0`; pwd)
cd $BASEDIR
source /opt/dolphinscheduler3.19/worker-server/conf/dolphinscheduler_env.sh
/tmp/dolphinscheduler/exec/process/bclduser/1/11_1/239613/365122/239613_365122_node.sh
[INFO] 2024-09-11 18:00:00.708 +0800 - task run command: sudo -u bclduser -i bash /tmp/dolphinscheduler/exec/process/bclduser/1/11_1/239613/365122/239613_365122.command
[INFO] 2024-09-11 18:00:00.709 +0800 - process start, process id is: 14325
[INFO] 2024-09-11 18:00:01.710 +0800 -  -> mysql mysql jdbc:mysql://192.168.11.198:3306/dolphinscheduler
	SLF4J: Class path contains multiple SLF4J bindings.
	SLF4J: Found binding in [jar:file:/opt/data/scripts/azkaban-timesync-tdenige-tag/azkaban-timesync-tdenige-tag-1.0.0.jar!/BOOT-INF/lib/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
	SLF4J: Found binding in [jar:file:/opt/data/scripts/azkaban-timesync-tdenige-tag/azkaban-timesync-tdenige-tag-1.0.0.jar!/BOOT-INF/lib/sdk-tdengine-3.3.0-jdk8.jar!/org/slf4j/impl/StaticLoggerBinder.class]
	SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
	SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[INFO] 2024-09-11 18:00:02.711 +0800 -  -> 
	  .   ____          _            __ _ _
	 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
	( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
	 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
	  '  |____| .__|_| |_|_| |_\__, | / / / /
	 =========|_|==============|___/=/_/_/_/
	 :: Spring Boot ::                (v2.6.6)
	
	2024-09-11 18:00:02.008  INFO 14485 --- [           main] uml.tech.bigdata.TdengineApplication     : Starting TdengineApplication v1.0.0 using Java 1.8.0_111 on cdh-slave6 with PID 14485 (/opt/data/scripts/azkaban-timesync-tdenige-tag/azkaban-timesync-tdenige-tag-1.0.0.jar started by bclduser in /tmp/dolphinscheduler/exec/process/bclduser/1/11_1/239613/365122)
	2024-09-11 18:00:02.012  INFO 14485 --- [           main] uml.tech.bigdata.TdengineApplication     : The following 1 profile is active: "dev"
[INFO] 2024-09-11 18:00:03.712 +0800 -  -> 2024-09-11 18:00:03.630  INFO 14485 --- [           main] com.zaxxer.hikari.HikariDataSource       : relation - Starting...
[INFO] 2024-09-11 18:00:04.713 +0800 -  -> 2024-09-11 18:00:04.011  INFO 14485 --- [           main] com.zaxxer.hikari.HikariDataSource       : relation - Start completed.
	2024-09-11 18:00:04.023  INFO 14485 --- [           main] com.zaxxer.hikari.HikariDataSource       : tdengine - Starting...
	2024-09-11 18:00:04.382  INFO 14485 --- [           main] com.zaxxer.hikari.HikariDataSource       : tdengine - Start completed.
	2024-09-11 18:00:04.383  INFO 14485 --- [           main] c.b.d.d.DynamicRoutingDataSource         : dynamic-datasource - add a datasource named [tdengine] success
	2024-09-11 18:00:04.383  INFO 14485 --- [           main] c.b.d.d.DynamicRoutingDataSource         : dynamic-datasource - add a datasource named [relation] success
	2024-09-11 18:00:04.383  INFO 14485 --- [           main] c.b.d.d.DynamicRoutingDataSource         : dynamic-datasource initial loaded [2] datasource,primary datasource named [relation]
	 _ _   |_  _ _|_. ___ _ |    _ 
	| | |\/|_)(_| | |_\  |_)||_|_\ 
	     /               |         
	                        3.5.3.1 
[INFO] 2024-09-11 18:00:05.714 +0800 -  -> 2024-09-11 18:00:05.314  INFO 14485 --- [           main] uml.tech.bigdata.TdengineApplication     : Started TdengineApplication in 3.946 seconds (JVM running for 4.53)
[INFO] 2024-09-11 18:00:31.691 +0800 - process has exited. execute path:/tmp/dolphinscheduler/exec/process/bclduser/1/11_1/239613/365122, processId:14325 ,exitStatusCode:0 ,processWaitForStatus:true ,processExitValue:0
[INFO] 2024-09-11 18:00:31.693 +0800 - Send task execute result to master, the current task status: TaskExecutionStatus{code=7, desc='success'}
[INFO] 2024-09-11 18:00:31.693 +0800 - Remove the current task execute context from worker cache
[INFO] 2024-09-11 18:00:31.693 +0800 - The current execute mode isn't develop mode, will clear the task execute file: /tmp/dolphinscheduler/exec/process/bclduser/1/11_1/239613/365122
[ERROR] 2024-09-11 18:00:31.694 +0800 - Delete task execute file: /tmp/dolphinscheduler/exec/process/bclduser/1/11_1/239613/365122 failed, this will not affect the task status, but you need to clear this manually
org.apache.commons.io.IOExceptionList: /tmp/dolphinscheduler/exec/process/bclduser/1/11_1/239613/365122
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:331)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1192)
	at org.apache.dolphinscheduler.server.worker.runner.WorkerTaskExecuteRunnable.clearTaskExecPathIfNeeded(WorkerTaskExecuteRunnable.java:283)
	at org.apache.dolphinscheduler.server.worker.runner.WorkerTaskExecuteRunnable.afterExecute(WorkerTaskExecuteRunnable.java:115)
	at org.apache.dolphinscheduler.server.worker.runner.DefaultWorkerDelayTaskExecuteRunnable.afterExecute(DefaultWorkerDelayTaskExecuteRunnable.java:54)
	at org.apache.dolphinscheduler.server.worker.runner.WorkerTaskExecuteRunnable.run(WorkerTaskExecuteRunnable.java:176)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot delete file: /tmp/dolphinscheduler/exec/process/bclduser/1/11_1/239613/365122/logs
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1344)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:324)
	... 12 common frames omitted
Caused by: java.nio.file.AccessDeniedException: /tmp/dolphinscheduler/exec/process/bclduser/1/11_1/239613/365122/logs/azkaban-timesync-tdenige-tag_8080.log
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
	at java.nio.file.Files.deleteIfExists(Files.java:1165)
	at org.apache.commons.io.file.DeletingPathVisitor.visitFile(DeletingPathVisitor.java:161)
	at org.apache.commons.io.file.DeletingPathVisitor.visitFile(DeletingPathVisitor.java:37)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.apache.commons.io.file.PathUtils.visitFileTree(PathUtils.java:971)
	at org.apache.commons.io.file.PathUtils.deleteDirectory(PathUtils.java:434)
	at org.apache.commons.io.file.PathUtils.delete(PathUtils.java:391)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1341)
	... 13 common frames omitted
[INFO] 2024-09-11 18:00:31.743 +0800 -  -> 2024-09-11 18:00:30.958  INFO 14485 --- [           main] u.t.b.runner.TdengineTagNullRunner       : 需刷新库名:statistics,超级表名为:tg,tag:user_nature_code,需刷新条数:20
	2024-09-11 18:00:31.569  INFO 14485 --- [           main] u.t.b.runner.TdengineTagNullRunner       : runner == 根据设备号刷新tag-结束
	2024-09-11 18:00:31.580  INFO 14485 --- [ionShutdownHook] c.b.d.d.DynamicRoutingDataSource         : dynamic-datasource start closing ....
	2024-09-11 18:00:31.581  INFO 14485 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : tdengine - Shutdown initiated...
	2024-09-11 18:00:31.593  INFO 14485 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : tdengine - Shutdown completed.
	2024-09-11 18:00:31.593  INFO 14485 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : relation - Shutdown initiated...
	2024-09-11 18:00:31.603  INFO 14485 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : relation - Shutdown completed.
	2024-09-11 18:00:31.603  INFO 14485 --- [ionShutdownHook] c.b.d.d.DynamicRoutingDataSource         : dynamic-datasource all closed success,bye
[INFO] 2024-09-11 18:00:31.743 +0800 - FINALIZE_SESSION

**Comment by wangchao732** [comment]
![image](https://github.com/user-attachments/assets/9082acd1-1c97-4191-9c07-924b88e1dfc5)

**Comment by wangchao732** [comment]
> > > > Caused by: java.nio.file.AccessDeniedException:
> > > > /tmp/dolphinscheduler/exec/process/bclduser/1/26_1/239277/364644/bin/winutils.exe
> > > 
> > > 
> > > @wangchao732
> > 
> > 
> > Please ignore this, it has nothing to do with this.
> 
> Also, just because it has a .exe file underneath it, you think it's running under Windows. Currently running on Linux CentOS 6.x.

There is a problem with the current logic, the maximum permission of the file created by the Linux user is 666, there is no execution permission, and the DolphinScheduler task is completed to delete the file (tenant), you must sudo or use the file owner to delete it.
