### ISSUE TITLE
[Bug] [ALERT] send msg Cannot deserialize value

### ISSUE THREAD

**Issue by happyBluebirds** [apache/dolphinscheduler#16653]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

发送http告警的时候报错
![image](https://github.com/user-attachments/assets/d79376db-de1a-4175-9fc2-8c5e4555777e)
[ERROR] 2024-09-24 14:01:25.630 +0800 o.a.d.c.u.JSONUtils:[186] - parse list exception!
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<org.apache.dolphinscheduler.spi.params.base.PluginParams>` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (String)"{"headerParams":" {\"Content-Type\": \"application/json\"}","requestType":"POST","bodyParams":"{ \"msgtype\": \"text\",   \"text\": {\"content\": 'test' } }","url":"https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=key","contentField":"text.content","timeout":"120"}"; line: 1, column: 1]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1462)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:392)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:252)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
        at org.apache.dolphinscheduler.common.utils.JSONUtils.toList(JSONUtils.java:184)
        at org.apache.dolphinscheduler.spi.params.PluginParamsTransfer.transferJsonToParamsList(PluginParamsTransfer.java:42)
        at org.apache.dolphinscheduler.spi.params.PluginParamsTransfer.getPluginParamsMap(PluginParamsTransfer.java:49)
        at org.apache.dolphinscheduler.alert.service.AbstractEventSender.doSendEvent(AbstractEventSender.java:125)
        at org.apache.dolphinscheduler.alert.service.AbstractEventSender.sendEvent(AbstractEventSender.java:73)
        at org.apache.dolphinscheduler.alert.service.ListenerEventLoop.handleEvent(ListenerEventLoop.java:38)
        at org.apache.dolphinscheduler.alert.service.ListenerEventLoop.handleEvent(ListenerEventLoop.java:24)
        at org.apache.dolphinscheduler.alert.service.AbstractEventLoop.lambda$run$0(AbstractEventLoop.java:73)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

### What you expected to happen

期望正确请求接口

### How to reproduce

![image](https://github.com/user-attachments/assets/7679a85f-42a0-457d-87fc-29796fb30661)
![image](https://github.com/user-attachments/assets/44bfbb17-75e0-406e-8ff6-dbaf41490d7d)

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Fixed in `dev`. Will be release in the version 3.3.0.

**Comment by happyBluebirds** [comment]
Approximately when can we expect it

**Comment by SbloodyS** [comment]
> Approximately when can we expect it

Maybe in the first quarter of 2025.

**Comment by sixly** [comment]
How can I fix this problem without upgrading? I am using version 3.2.2

**Comment by williamlin88** [comment]
How can I fix this problem without upgrading? I am using version 3.2.2

**Comment by wingowen** [comment]
How can I fix this problem without upgrading? I am using version 3.2.2

**Comment by typing-developer** [comment]
3.3.0 仍然有这个错误
![Image](https://github.com/user-attachments/assets/c8cc2cf0-9119-4fff-aaaa-535c46cf26a5)

```
[ERROR] 2026-03-16 16:30:59.214 +0800 org.apache.dolphinscheduler.common.utils.JSONUtils:[186] - parse list exception!
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<org.apache.dolphinscheduler.spi.params.base.PluginParams>` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (String)"{"Proxy":null,"User":"admin","IsEnableProxy":"false","Port":null,"WebHook":"https://open.feishu.cn/open-apis/bot/v2/hook/42-------","Password":"xxxxxxxxx"}"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1462)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:392)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:252)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
	at org.apache.dolphinscheduler.common.utils.JSONUtils.toList(JSONUtils.java:184)
	at org.apache.dolphinscheduler.spi.params.PluginParamsTransfer.transferJsonToParamsList(PluginParamsTransfer.java:42)
	at org.apache.dolphinscheduler.spi.params.PluginParamsTransfer.getPluginParamsMap(PluginParamsTransfer.java:49)
	at org.apache.dolphinscheduler.alert.service.AbstractEventSender.doSendEvent(AbstractEventSender.java:125)
	at org.apache.dolphinscheduler.alert.service.AbstractEventSender.sendEvent(AbstractEventSender.java:73)
	at org.apache.dolphinscheduler.alert.service.AlertEventLoop.handleEvent(AlertEventLoop.java:43)
	at org.apache.dolphinscheduler.alert.service.AlertEventLoop.handleEvent(AlertEventLoop.java:27)
	at org.apache.dolphinscheduler.alert.service.AbstractEventLoop.lambda$run$0(AbstractEventLoop.java:73)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
[INFO] 2026-03-16 16:30:59.215 +0800 org.apache.dolphinscheduler.plugin.alert.feishu.FeiShuSender:[137] - send fei shu alert msg  exception : null
```

**Comment by SbloodyS** [comment]
You are still using `3.2.2` since we mistakenly marked the version of `t_ds_version` as `3.3.0` in `3.2.2`. You can see that the version of jar under libs should be `3.2.2`. @typing-developer

**Comment by matthewwalker1621-star** [comment]
Not stale
