### ISSUE TITLE
[Bug] [Worker] The sub workflow instance doesn't created

### ISSUE THREAD

**Issue by LuxSun** [apache/dolphinscheduler#16651]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

```
  | September 24th 2024, 10:54:04.511 | [WI-0][TI-0] - [ERROR] 2024-09-24 10:54:04.373 +0800 o.a.d.e.b.s.JdkDynamicServerHandler:[84] - Cannot find the ServerMethodInvoker of : Transporter(header=TransporterHeader(methodIdentifier=public abstract void org.apache.dolphinscheduler.extract.worker.ITaskInstanceExecutionEventAckListener.handleTaskInstanceExecutionRunningEventAck(org.apache.dolphinscheduler.extract.worker.transportor.TaskInstanceExecutionRunningEventAck), opaque=308510), body=[123, 34, 97, 114, 103, 115, 34, 58, 91, 34, 101, 121, 74, 48, 89, 88, 78, 114, 83, 87, 53, 122, 100, 71, 70, 117, 89, 50, 86, 74, 90, 67, 73, 54, 77, 106, 77, 53, 77, 68, 107, 119, 79, 67, 119, 105, 99, 51, 86, 106, 89, 50, 86, 122, 99, 121, 73, 54, 100, 72, 74, 49, 90, 88, 48, 61, 34, 93, 44, 34, 97, 114, 103, 115, 84, 121, 112, 101, 115, 34, 58, 91, 34, 111, 114, 103, 46, 97, 112, 97, 99, 104, 101, 46, 100, 111, 108, 112, 104, 105, 110, 115, 99, 104, 101, 100, 117, 108, 101, 114, 46, 101, 120, 116, 114, 97, 99, 116, 46, 119, 111, 114, 107, 101, 114, 46, 116, 114, 97, 110, 115, 112, 111, 114, 116, 111, 114, 46, 84, 97, 115, 107, 73, 110, 115, 116, 97, 110, 99, 101, 69, 120, 101, 99, 117, 116, 105, 111, 110, 82, 117, 110, 110, 105, 110, 103, 69, 118, 101, 110, 116, 65, 99, 107, 34, 93, 125])

  | September 24th 2024, 10:54:04.511 | [WI-1023497][TI-2390908] - [ERROR] 2024-09-24 10:54:04.374 +0800 o.a.d.s.m.p.q.TaskExecuteRunnable:[64] - Handle task event error, this event will be removed, event: TaskEvent(taskInstanceId=2390908, workerAddress=192.168.209.102:5678, state=TaskExecutionStatus{code=1, desc='running'}, startTime=Tue Sep 24 10:54:03 GMT+08:00 2024, endTime=null, executePath=null, logPath=/data/dolphinscheduler/master-server/logs/20240924/14208489646688/13/1023497/2390908.log, processId=0, appIds=null, event=RUNNING, varPool=null, cacheTaskInstanceId=0, processInstanceId=1023497)

  | September 24th 2024, 10:54:04.511 | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

  | September 24th 2024, 10:54:04.511 | at java.util.concurrent.FutureTask.run(FutureTask.java:266)

  | September 24th 2024, 10:54:04.511 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

  | September 24th 2024, 10:54:04.511 | at com.sun.proxy.$Proxy265.handleTaskInstanceExecutionRunningEventAck(Unknown Source)

  | September 24th 2024, 10:54:04.511 | [WI-1023497][TI-2390908] - [INFO] 2024-09-24 10:54:03.920 +0800 o.a.d.p.t.a.l.TaskInstanceLogHeader:[1259] - ***********************************************************************************************

  | September 24th 2024, 10:54:04.511 | [WI-0][TI-2390908] - [INFO] 2024-09-24 10:54:03.921 +0800 o.a.d.s.m.r.t.s.SubWorkflowAsyncTaskExecuteFunction:[53] - The sub workflow instance doesn't created

  | September 24th 2024, 10:54:04.511 | [WI-1023497][TI-2390908] - [INFO] 2024-09-24 10:54:04.365 +0800 o.a.d.s.m.p.q.TaskExecuteRunnable:[55] - Handle task event begin: TaskEvent(taskInstanceId=2390908, workerAddress=192.168.209.102:5678, state=null, startTime=null, endTime=null, executePath=null, logPath=null, processId=0, appIds=null, event=DISPATCH, varPool=null, cacheTaskInstanceId=0, processInstanceId=1023497)

  | September 24th 2024, 10:54:04.511 | org.apache.dolphinscheduler.server.master.event.TaskEventHandleError: Handle task running event error, update taskInstance to db failed

  | September 24th 2024, 10:54:04.511 | at org.apache.dolphinscheduler.server.master.event.TaskRunningEventHandler.handleTaskEvent(TaskRunningEventHandler.java:98)

  | September 24th 2024, 10:54:04.511 | at org.apache.dolphinscheduler.server.master.processor.queue.TaskExecuteRunnable.run(TaskExecuteRunnable.java:56)

  | September 24th 2024, 10:54:04.511 | at java.lang.Thread.run(Thread.java:748)

  | September 24th 2024, 10:54:04.511 | at org.apache.dolphinscheduler.extract.base.client.SyncClientMethodInvoker.invoke(SyncClientMethodInvoker.java:48)

  | September 24th 2024, 10:54:04.511 | at org.apache.dolphinscheduler.extract.base.client.ClientInvocationHandler.invoke(ClientInvocationHandler.java:55)

  | September 24th 2024, 10:54:04.511 | at org.apache.dolphinscheduler.server.master.event.TaskRunningEventHandler.sendAckToWorker(TaskRunningEventHandler.java:115)

  | September 24th 2024, 10:54:04.511 | ... 6 common frames omitted

  | September 24th 2024, 10:54:04.511 | [WI-1023497][TI-2390908] - [INFO] 2024-09-24 10:54:03.920 +0800 o.a.d.p.t.a.l.TaskInstanceLogHeader:[1259] - *********************************  Execute task instance  *************************************

  | September 24th 2024, 10:54:04.511 | [WI-1023497][TI-2390908] - [INFO] 2024-09-24 10:54:04.370 +0800 o.a.d.s.m.p.q.TaskExecuteRunnable:[58] - Handle task event finished: TaskEvent(taskInstanceId=2390908, workerAddress=192.168.209.102:5678, state=null, startTime=null, endTime=null, executePath=null, logPath=null, processId=0, appIds=null, event=DISPATCH, varPool=null, cacheTaskInstanceId=0, processInstanceId=1023497)

  | September 24th 2024, 10:54:04.511 | [WI-1023497][TI-2390908] - [INFO] 2024-09-24 10:54:04.370 +0800 o.a.d.s.m.p.q.TaskExecuteRunnable:[55] - Handle task event begin: TaskEvent(taskInstanceId=2390908, workerAddress=192.168.209.102:5678, state=TaskExecutionStatus{code=1, desc='running'}, startTime=Tue Sep 24 10:54:03 GMT+08:00 2024, endTime=null, executePath=null, logPath=/data/dolphinscheduler/master-server/logs/20240924/14208489646688/13/1023497/2390908.log, processId=0, appIds=null, event=RUNNING, varPool=null, cacheTaskInstanceId=0, processInstanceId=1023497)

  | September 24th 2024, 10:54:04.511 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

  | September 24th 2024, 10:54:04.511 | Caused by: org.apache.dolphinscheduler.extract.base.exception.MethodInvocationException: Cannot find the ServerMethodInvoker of public abstract void org.apache.dolphinscheduler.extract.worker.ITaskInstanceExecutionEventAckListener.handleTaskInstanceExecutionRunningEventAck(org.apache.dolphinscheduler.extract.worker.transportor.TaskInstanceExecutionRunningEventAck)

  | September 24th 2024, 10:54:04.511 | at org.apache.dolphinscheduler.extract.base.exception.MethodInvocationException.of(MethodInvocationException.java:27)

  | September 24th 2024, 10:54:04.891 | at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)

  | September 24th 2024, 10:54:04.891 | at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)

  | September 24th 2024, 10:54:04.891 | at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)

  | September 24th 2024, 10:54:04.891 | at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)

  | September 24th 2024, 10:54:04.891 | Caused by: java.lang.NullPointerException: null

  | September 24th 2024, 10:54:04.891 | at org.apache.dolphinscheduler.service.process.ProcessServiceImpl$$FastClassBySpringCGLIB$$9d3e18f9.invoke(<generated>)

  | September 24th 2024, 10:54:04.891 | at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)

  | September 24th 2024, 10:54:04.891 | at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)

  | September 24th 2024, 10:54:04.891 | [WI-0][TI-0] - [INFO] 2024-09-24 10:54:03.959 +0800 o.a.d.s.m.r.MasterSchedulerBootstrap:[187] - Master schedule bootstrap loop command success, fetch command size: 1, cost: 2ms, current slot: 1, total slot size: 2

  | September 24th 2024, 10:54:04.891 | org.apache.dolphinscheduler.server.master.exception.WorkflowCreateException: Create WorkflowExecuteRunnable failed

  | September 24th 2024, 10:54:04.891 | at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)

  | September 24th 2024, 10:54:04.891 | at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)

  | September 24th 2024, 10:54:04.891 | at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)

  | September 24th 2024, 10:54:04.891 | at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)

  | September 24th 2024, 10:54:04.891 | at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)

  | September 24th 2024, 10:54:04.891 | at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)

  | September 24th 2024, 10:54:04.891 | at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)

  | September 24th 2024, 10:54:04.891 | at org.apache.dolphinscheduler.service.expand.CuringParamsServiceImpl.curingGlobalParams(CuringParamsServiceImpl.java:133)

  | September 24th 2024, 10:54:04.891 | at org.apache.dolphinscheduler.service.process.ProcessServiceImpl.generateNewProcessInstance(ProcessServiceImpl.java:577)

  | September 24th 2024, 10:54:04.891 | at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)

  | September 24th 2024, 10:54:04.891 | at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)

  | September 24th 2024, 10:54:04.891 | at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)

  | September 24th 2024, 10:54:04.891 | [WI-0][TI-0] - [ERROR] 2024-09-24 10:54:03.963 +0800 o.a.d.s.m.r.MasterSchedulerBootstrap:[156] - Master handle command 1013473 error

  | September 24th 2024, 10:54:04.891 | at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnableFactory.createWorkflowExecuteRunnable(WorkflowExecuteRunnableFactory.java:98)

  | September 24th 2024, 10:54:04.891 | at org.apache.dolphinscheduler.server.master.runner.MasterSchedulerBootstrap.lambda$run$0(MasterSchedulerBootstrap.java:139)

  | September 24th 2024, 10:54:04.891 | at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)

  | September 24th 2024, 10:54:04.891 | at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)

  | September 24th 2024, 10:54:04.891 | at org.apache.dolphinscheduler.server.master.runner.MasterSchedulerBootstrap.run(MasterSchedulerBootstrap.java:136)

  | September 24th 2024, 10:54:04.891 | at org.apache.dolphinscheduler.service.process.ProcessServiceImpl.constructProcessInstance(ProcessServiceImpl.java:714)

  | September 24th 2024, 10:54:04.891 | at org.apache.dolphinscheduler.service.process.ProcessServiceImpl.handleCommand(ProcessServiceImpl.java:291)

  | September 24th 2024, 10:54:04.891 | at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)

  | September 24th 2024, 10:54:04.891 | at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)

  | September 24th 2024, 10:54:04.891 | at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

  | September 24th 2024, 10:54:04.892 | at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnableFactory.createWorkflowExecuteRunnable(WorkflowExecuteRunnableFactory.java:83)

  | September 24th 2024, 10:54:04.892 | at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)

  | September 24th 2024, 10:54:04.892 | at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)

  | September 24th 2024, 10:54:04.892 | at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteContextFactory.createWorkflowInstance(WorkflowExecuteContextFactory.java:81)

  | September 24th 2024, 10:54:04.892 | at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteContextFactory.createWorkflowExecuteRunnableContext(WorkflowExecuteContextFactory.java:56)

  | September 24th 2024, 10:54:04.892 | at org.apache.dolphinscheduler.service.process.ProcessServiceImpl$$EnhancerBySpringCGLIB$$48e7ef15.handleCommand(<generated>)

  | September 24th 2024, 10:54:04.892 | ... 15 common frames omitted

  | September 24th 2024, 10:54:05.893 | [WI-0][TI-0] - [INFO] 2024-09-24 10:54:05.835 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 18/ms

  | September 24th 2024, 10:54:07.512 | [WI-0][TI-0] - [INFO] 2024-09-24 10:54:06.205 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 19/ms

  | September 24th 2024, 10:54:12.525 | setTaskGroupPriority: TaskDefinition(id=114024, code=14208481368032, name=新作业, version=13, description=, projectCode=10367400686272, userId=1, taskType=SUB_PROCESS, taskParams={"localParams":[{"prop":"v_jobid","direct":"IN","type":"VARCHAR","value":"$[''yyyyMMddHHmm'']","boolGlobal":false},{"prop":"resourceId","direct":"IN","type":"VARCHAR","value":"3d12446685c11dc83fbe37f49f95b660","boolGlobal":false},{"prop":"schema","direct":"IN","type":"VARCHAR","value":"construction","boolGlobal":false},{"prop":"topic","direct":"IN","type":"VARCHAR","value":"equity_transaction","boolGlobal":false},{"prop":"global_key","direct":"IN","type":"VARCHAR","value":"$[yyyyMMddHHmmss]-85302","boolGlobal":false}],"resourceList":[],"processDefinitionCode":14163872752096,"minCpuCores":0.0,"minMemorySpace":0.0,"ableToContinue":false,"modulePath":false}, taskParamList=[Property{prop='v_jobid', direct=IN, type=VARCHAR, value='$[''yyyyMMddHHmm'']'}, Property{prop='resourceId', direct=IN, type=VARCHAR, value='3d12446685c11dc83fbe37f49f95b660'}, Property{prop='schema', direct=IN, type=VARCHAR, value='construction'}, Property{prop='topic', direct=IN, type=VARCHAR, value='equity_transaction'}, Property{prop='global_key', direct=IN, type=VARCHAR, value='$[yyyyMMddHHmmss]-85302'}], taskParamMap={schema=construction, resourceId=3d12446685c11dc83fbe37f49f95b660, global_key=$[yyyyMMddHHmmss]-85302, topic=equity_transaction, v_jobid=$[''yyyyMMddHHmm'']}, flag=YES, isCache=NO, taskPriority=MEDIUM, userName=null, projectName=null, workerGroup=default, environmentCode=-1, failRetryTimes=0, failRetryInterval=0, timeoutFlag=CLOSE, timeoutNotifyStrategy=WARN, timeout=0, delayTime=0, resourceIds=null, createTime=Tue Sep 24 10:48:50 GMT+08:00 2024, updateTime=Tue Sep 24 10:48:50 GMT+08:00 2024, modifyBy=null, taskGroupId=0, taskGroupPriority=0, cpuQuota=-1, memoryMax=-1, taskExecuteType=BATCH)

  | September 24th 2024, 10:54:12.525 | setTaskGroupPriority: TaskDefinition(id=114026, code=14208481159008, name=新作业2, version=13, description=, projectCode=10367400686272, userId=1, taskType=SUB_PROCESS, taskParams={"localParams":[{"prop":"v_jobid","direct":"IN","type":"VARCHAR","value":"$[yyyyMMddHHmm]","boolGlobal":false},{"prop":"global_key","direct":"IN","type":"VARCHAR","value":"$[yyyyMMddHHmmss]-57037","boolGlobal":false}],"resourceList":[],"processDefinitionCode":14208457841376,"minCpuCores":0.0,"minMemorySpace":0.0,"ableToContinue":false,"modulePath":false}, taskParamList=[Property{prop='v_jobid', direct=IN, type=VARCHAR, value='$[yyyyMMddHHmm]'}, Property{prop='global_key', direct=IN, type=VARCHAR, value='$[yyyyMMddHHmmss]-57037'}], taskParamMap={global_key=$[yyyyMMddHHmmss]-57037, v_jobid=$[yyyyMMddHHmm]}, flag=YES, isCache=NO, taskPriority=MEDIUM, userName=null, projectName=null, workerGroup=default, environmentCode=-1, failRetryTimes=0, failRetryInterval=0, timeoutFlag=CLOSE, timeoutNotifyStrategy=WARN, timeout=0, delayTime=0, resourceIds=null, createTime=Tue Sep 24 10:48:50 GMT+08:00 2024, updateTime=Tue Sep 24 10:48:50 GMT+08:00 2024, modifyBy=null, taskGroupId=0, taskGroupPriority=0, cpuQuota=-1, memoryMax=-1, taskExecuteType=BATCH)

  | September 24th 2024, 10:54:12.894 | [WI-0][TI-0] - [INFO] 2024-09-24 10:54:10.874 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 19/ms

  | September 24th 2024, 10:54:14.513 | [WI-0][TI-0] - [INFO] 2024-09-24 10:54:11.259 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 19/ms

  | September 24th 2024, 10:54:14.514 | [WI-0][TI-2390908] - [INFO] 2024-09-24 10:54:13.924 +0800 o.a.d.s.m.r.t.s.SubWorkflowAsyncTaskExecuteFunction:[53] - The sub workflow instance doesn't created

  | September 24th 2024, 10:54:17.514 | [WI-0][TI-0] - [INFO] 2024-09-24 10:54:16.338 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 19/ms

  | September 24th 2024, 10:54:19.895 | [WI-0][TI-0] - [INFO] 2024-09-24 10:54:15.913 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 18/ms

  | September 24th 2024, 10:54:22.896 | [WI-0][TI-0] - [INFO] 2024-09-24 10:54:20.950 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 19/ms

  | September 24th 2024, 10:54:24.516 | [WI-0][TI-0] - [INFO] 2024-09-24 10:54:21.379 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 18/ms

  | September 24th 2024, 10:54:24.516 | [WI-0][TI-2390908] - [INFO] 2024-09-24 10:54:23.927 +0800 o.a.d.s.m.r.t.s.SubWorkflowAsyncTaskExecuteFunction:[53] - The sub workflow instance doesn't created

  | September 24th 2024, 10:54:27.516 | [WI-0][TI-0] - [INFO] 2024-09-24 10:54:26.413 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 19/ms

  | September 24th 2024, 10:54:29.898 | [WI-0][TI-0] - [INFO] 2024-09-24 10:54:25.987 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 16/ms

  | September 24th 2024, 10:54:32.899 | [WI-0][TI-0] - [INFO] 2024-09-24 10:54:31.021 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 17/ms

  | September 24th 2024, 10:54:34.518 | [WI-0][TI-2390908] - [INFO] 2024-09-24 10:54:33.929 +0800 o.a.d.s.m.r.t.s.SubWorkflowAsyncTaskExecuteFunction:[53] - The sub workflow instance doesn't created

  | September 24th 2024, 10:54:34.518 | [WI-0][TI-0] - [WARN] 2024-09-24 10:54:33.283 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=2259924, workerAddress=192.168.209.108:1234, state=TaskExecutionStatus{code=7, desc='success'}, startTime=Fri Sep 20 13:41:20 GMT+08:00 2024, endTime=Fri Sep 20 13:42:48 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/10422728450624/13707382179040_362/966326/2259924, logPath=/data/dolphinscheduler/worker-server/logs/20240920/13707382179040/362/966326/2259924.log, processId=0, appIds=null, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=966326)

  | September 24th 2024, 10:54:34.518 | [WI-0][TI-0] - [INFO] 2024-09-24 10:54:31.448 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 20/ms

  | September 24th 2024, 10:54:34.518 | [WI-966326][TI-2259924] - [INFO] 2024-09-24 10:54:33.282 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=2259924, workerAddress=192.168.209.108:1234, state=TaskExecutionStatus{code=7, desc='success'}, startTime=Fri Sep 20 13:41:20 GMT+08:00 2024, endTime=Fri Sep 20 13:42:48 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/10422728450624/13707382179040_362/966326/2259924, logPath=/data/dolphinscheduler/worker-server/logs/20240920/13707382179040/362/966326/2259924.log, processId=0, appIds=null, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=966326)

```

### What you expected to happen

不报错。

### How to reproduce

点击工作流运行或者重跑都有可能复现，版本：3.2.1，但是属于偶现。

### Version

3.2.x

**Comment by SbloodyS** [comment]
This issue have been fixed in `dev`.

**Comment by LuxSun** [comment]
3.2.1 fixed？

**Comment by LuxSun** [comment]
有没具体位置？

**Comment by ozh123** [comment]
同问，同求解决办法
