### ISSUE TITLE
[Question] [install] Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/DefaultParser

### ISSUE THREAD

**Issue by bunenghulai** [apache/dolphinscheduler#16675]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.安装apache-dolphinscheduler-3.1.9，配置文件配置好的情况下，执行install.sh部署脚本，在安装过程中报：
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/DefaultParser
at org.apache.zookeeper.cli.DeleteAllCommand.parse(DeleteAllCommand.java:52)
at org.apache.zookeeper.ZooKeeperMain.processZKCmd(ZooKeeperMain.java:438)
at org.apache.zookeeper.ZooKeeperMain.processCmd(ZooKeeperMain.java:367)
at org.apache.zookeeper.ZooKeeperMain.run(ZooKeeperMain.java:350)
at org.apache.zookeeper.ZooKeeperMain.main(ZooKeeperMain.java:293)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.DefaultParser
at java.net.URLClassLoader.findClass(URLClassLoader.java:407)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
... 5 more

### What you expected to happen

如何解决？

### How to reproduce

手动安装apache-dolphinscheduler-3.1.9，配置dolphinscheduler_env.sh、install_env.sh、common.properties，文件
hadoop为高可用模式

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Ishani-Gupta** [comment]
I have seem simialr error :

03:42:25.011 [main] INFO org.apache.zookeeper.common.X509Util - Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
03:42:25.018 [main] INFO org.apache.zookeeper.ClientCnxnSocket - jute.maxbuffer value is 1048575 Bytes
03:42:25.031 [main] INFO org.apache.zookeeper.ClientCnxn - zookeeper.request.timeout value is 0. feature enabled=false
03:42:25.031 [main] DEBUG org.apache.zookeeper.ZooKeeperMain - Processing deleteall
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/DefaultParser
	at org.apache.zookeeper.cli.DeleteAllCommand.parse(DeleteAllCommand.java:52)
	at org.apache.zookeeper.ZooKeeperMain.processZKCmd(ZooKeeperMain.java:438)
	at org.apache.zookeeper.ZooKeeperMain.processCmd(ZooKeeperMain.java:367)
	at org.apache.zookeeper.ZooKeeperMain.run(ZooKeeperMain.java:350)
	at org.apache.zookeeper.ZooKeeperMain.main(ZooKeeperMain.java:293)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.DefaultParser
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 5 more

**Comment by bunenghulai** [comment]
> I have seem simialr error :
> 
> 03:42:25.011 [main] INFO org.apache.zookeeper.common.X509Util - Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation 03:42:25.018 [main] INFO org.apache.zookeeper.ClientCnxnSocket - jute.maxbuffer value is 1048575 Bytes 03:42:25.031 [main] INFO org.apache.zookeeper.ClientCnxn - zookeeper.request.timeout value is 0. feature enabled=false 03:42:25.031 [main] DEBUG org.apache.zookeeper.ZooKeeperMain - Processing deleteall Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/DefaultParser at org.apache.zookeeper.cli.DeleteAllCommand.parse(DeleteAllCommand.java:52) at org.apache.zookeeper.ZooKeeperMain.processZKCmd(ZooKeeperMain.java:438) at org.apache.zookeeper.ZooKeeperMain.processCmd(ZooKeeperMain.java:367) at org.apache.zookeeper.ZooKeeperMain.run(ZooKeeperMain.java:350) at org.apache.zookeeper.ZooKeeperMain.main(ZooKeeperMain.java:293) Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.DefaultParser at java.net.URLClassLoader.findClass(URLClassLoader.java:387) at java.lang.ClassLoader.loadClass(ClassLoader.java:418) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ... 5 more

我看api-server、master-server、worker-server中的libs目录有commons-cli-1.2.jar，alert-server和tools中没有，于是将commons-cli-1.2.jar包拷贝到alert-server和tools中的libs目录，然后重新安装还是报这个错，但是现在阶段使用没问题，不知道后续有没有影响

**Comment by zheng-zy** [comment]
我也遇到这个情况，解决方式：替换api-server、master-server、worker-server libs目录下commons-cli-1.2.jar，替换成commons-cli-1.4.jar
