### ISSUE TITLE
[Question] dolphinscheduler-1.3 error when running workflow instance

### ISSUE THREAD

**Issue by Perxiu** [apache/dolphinscheduler#16694]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

说一下我的操作操作步骤
1.部署dolphinscheduler 1.3.3环境并启动

2.在工作流中创建一个仅包含一个shell任务的DAG，shell脚本内容是打印一些常量
(即使将脚本shell内容替换为空也会发生第三步的报错)

3.在运行工作流时报错，dolphinscheduler-api-server.log对应的内容如下：
[INFO] 2024-10-14 16:48:22.796 org.apache.dolphinscheduler.api.controller.ProcessDefinitionController:[180] - login user admin, update process define, project name: project_test, process define name: dag, process_definition_json: {"globalParams":[],"tasks":[{"type":"SHELL","id":"tasks-43985","name":"shell","params":{"resourceList":[],"localParams":[],"rawScript":" "},"description":"","timeout":{"strategy":"","interval":null,"enable":false},"runFlag":"NORMAL","conditionResult":{"successNode":[""],"failedNode":[""]},"dependence":{},"maxRetryTimes":"1","retryInterval":"1","taskInstancePriority":"MEDIUM","workerGroup":"default","preTasks":[]}],"tenantId":2,"timeout":0}, desc: , locations:{"tasks-43985":{"name":"shell","targetarr":"","nodenumber":"0","x":418,"y":174}}, connects:[]
[INFO] 2024-10-14 16:48:24.248 org.apache.dolphinscheduler.api.controller.ProcessDefinitionController:[290] - query process definition list paging, login user:admin, project name:project_test
[INFO] 2024-10-14 16:48:34.424 org.apache.dolphinscheduler.api.controller.ProcessDefinitionController:[212] - login user admin, release process definition, project name: project_test, release state: 1
[INFO] 2024-10-14 16:48:34.613 org.apache.dolphinscheduler.api.controller.ProcessDefinitionController:[290] - query process definition list paging, login user:admin, project name:project_test
[INFO] 2024-10-14 16:48:36.152 org.apache.dolphinscheduler.api.controller.WorkerGroupController:[100] - query all worker group: login user admin
[INFO] 2024-10-14 16:48:36.281 org.apache.dolphinscheduler.api.controller.ExecutorController:[173] - login user admin, check process definition 4
[INFO] 2024-10-14 16:48:36.381 org.apache.dolphinscheduler.api.controller.ExecutorController:[199] - login user admin, get process definition receiver and cc
[INFO] 2024-10-14 16:48:36.382 org.apache.dolphinscheduler.api.service.ExecutorService:[436] - processInstanceId null[INFO] 2024-10-14 16:48:37.847 org.apache.dolphinscheduler.api.controller.ExecutorController:[111] - login user admin, start process instance, project name: project_test, process definition id: 4, schedule time: , failure policy: CONTINUE, node name: , node dep: TASK_POST, notify type: NONE, notify group id: default,receivers:,receiversCc:, run mode: RUN_MODE_SERIAL,process instance priority:MEDIUM, workerGroup: default, timeout: null
[ERROR] 2024-10-14 16:48:37.851 org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[45] - 运行工作流实例
错误
java.lang.NumberFormatException: For input string: "{"startupTime":1726131628063"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at org.apache.dolphinscheduler.common.utils.ResInfo.parseHeartbeatForZKInfo(ResInfo.java:105)
        at org.apache.dolphinscheduler.service.zk.AbstractZKClient.getServersList(AbstractZKClient.java:127)
        at org.apache.dolphinscheduler.api.service.MonitorService.getServerListFromZK(MonitorService.java:153)
        at org.apache.dolphinscheduler.api.service.ExecutorService.checkMasterExists(ExecutorService.java:160)
        at org.apache.dolphinscheduler.api.service.ExecutorService.execProcessInstance(ExecutorService.java:128)
        at org.apache.dolphinscheduler.api.controller.ExecutorController.startProcessInstance(ExecutorController.java:122)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:867)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
        at com.github.xiaoymin.swaggerbootstrapui.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:84)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at com.github.xiaoymin.swaggerbootstrapui.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:502)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:750)

### What you expected to happen

无论是工作流的任务，还是dolphinscheduler的环境配置中都没有startupTime参数，有关startupTime的格式转换问题有可能是bug吗？

### How to reproduce

1.参照此文档部署dolphinscheduler-1.3.3环境(3节点)
https://dolphinscheduler.apache.org/zh-cn/docs/1.3.3/cluster-deployment
2.在工作流中创建一个仅包含shell任务的DAG，运行此工作流。

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Perxiu** [comment]
dolphinscheduler-1.3.3无法运行基础的shell任务，有人可以告知原因吗，非常感谢

**Comment by SbloodyS** [comment]
Version 1.3 is no longer being maintained. You can try using version 2.X or 3.X. @Perxiu

**Comment by Perxiu** [comment]
> Version 1.3 is no longer being maintained. You can try using version 2.X or 3.X. @Perxiu

我明白旧版本不再维护，请问可以确认此现象由组件自身导致吗，有看到其他人在3.2.x提版本的类似问题:https://github.com/apache/dolphinscheduler/issues/16581
或者是环境部署，任务配置问题引起？

**Comment by SbloodyS** [comment]
Please using english to describe.

**Comment by Perxiu** [comment]
> Please using english to describe.

I understand that the old version is no longer maintained, can you confirm that this phenomenon is caused by the component itself? Have you seen similar problems mentioned by others in version 3.2.x :https://github.com/apache/dolphinscheduler/issues/16581
Or is it caused by an environment deployment or task configuration problem?
If it is the former, I can try to upgrade the version.
If it is the latter, I can improve the configuration.Thanks for your help.

**Comment by SbloodyS** [comment]
Issue 16581 describes a problem with the remoteshell task plugin. It was introduced in 3.0.0 and did not exist in 1.3.
