### ISSUE TITLE
[Bug] org.apache.dolphinscheduler.server.master.event.TaskEventHandleError: Handle task running event error, update taskInstance to db failed

### ISSUE THREAD

**Issue by lslcoded** [apache/dolphinscheduler#16747]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

 [WI-0][TI-0] - [ERROR] 2024-10-29 13:28:42.588 +0800 o.a.d.e.b.s.JdkDynamicServerHandler:[84] - Cannot find the ServerMethodInvoker of : Transporter(header=TransporterHeader(methodIdentifier=public abstract void org.apache.dolphinscheduler.extract.worker.ITaskInstanceExecutionEventAckListener.handleTaskInstanceExecutionRunningEventAck(org.apache.dolphinscheduler.extract.worker.transportor.TaskInstanceExecutionRunningEventAck), opaque=5939), body=[123, 34, 97, 114, 103, 115, 34, 58, 91, 34, 101, 121, 74, 48, 89, 88, 78, 114, 83, 87, 53, 122, 100, 71, 70, 117, 89, 50, 86, 74, 90, 67, 73, 54, 77, 122, 103, 51, 78, 106, 65, 115, 73, 110, 78, 49, 89, 50, 78, 108, 99, 51, 77, 105, 79, 110, 82, 121, 100, 87, 86, 57, 34, 93, 44, 34, 97, 114, 103, 115, 84, 121, 112, 101, 115, 34, 58, 91, 34, 111, 114, 103, 46, 97, 112, 97, 99, 104, 101, 46, 100, 111, 108, 112, 104, 105, 110, 115, 99, 104, 101, 100, 117, 108, 101, 114, 46, 101, 120, 116, 114, 97, 99, 116, 46, 119, 111, 114, 107, 101, 114, 46, 116, 114, 97, 110, 115, 112, 111, 114, 116, 111, 114, 46, 84, 97, 115, 107, 73, 110, 115, 116, 97, 110, 99, 101, 69, 120, 101, 99, 117, 116, 105, 111, 110, 82, 117, 110, 110, 105, 110, 103, 69, 118, 101, 110, 116, 65, 99, 107, 34, 93, 125])

 [WI-20301][TI-38760] - [ERROR] 2024-10-29 13:28:42.588 +0800 o.a.d.s.m.p.q.TaskExecuteRunnable:[64] - Handle task event error, this event will be removed, event: TaskEvent(taskInstanceId=38760, workerAddress=dolphin-kksvpq-master-0.dolphin-kksvpq-master-headless:5678, state=TaskExecutionStatus{code=1, desc='running'}, startTime=Tue Oct 29 13:28:41 CST 2024, endTime=null, executePath=null, logPath=/opt/dolphinscheduler/logs/20241029/15426921096672/159/20301/38760.log, processId=0, appIds=null, event=RUNNING, varPool=null, cacheTaskInstanceId=0, processInstanceId=20301)

 org.apache.dolphinscheduler.server.master.event.TaskEventHandleError: Handle task running event error, update taskInstance to db failed

 	at org.apache.dolphinscheduler.server.master.event.TaskRunningEventHandler.handleTaskEvent(TaskRunningEventHandler.java:98)

 	at org.apache.dolphinscheduler.server.master.processor.queue.TaskExecuteRunnable.run(TaskExecuteRunnable.java:56)

 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

 	at java.lang.Thread.run(Thread.java:750)

 Caused by: org.apache.dolphinscheduler.extract.base.exception.MethodInvocationException: Cannot find the ServerMethodInvoker of public abstract void org.apache.dolphinscheduler.extract.worker.ITaskInstanceExecutionEventAckListener.handleTaskInstanceExecutionRunningEventAck(org.apache.dolphinscheduler.extract.worker.transportor.TaskInstanceExecutionRunningEventAck)

 	at org.apache.dolphinscheduler.extract.base.exception.MethodInvocationException.of(MethodInvocationException.java:27)

 	at org.apache.dolphinscheduler.extract.base.client.SyncClientMethodInvoker.invoke(SyncClientMethodInvoker.java:48)

 	at org.apache.dolphinscheduler.extract.base.client.ClientInvocationHandler.invoke(ClientInvocationHandler.java:55)

 	at com.sun.proxy.$Proxy238.handleTaskInstanceExecutionRunningEventAck(Unknown Source)

 	at org.apache.dolphinscheduler.server.master.event.TaskRunningEventHandler.sendAckToWorker(TaskRunningEventHandler.java:115)

 	at org.apache.dolphinscheduler.server.master.event.TaskRunningEventHandler.handleTaskEvent(TaskRunningEventHandler.java:92)

 	... 6 common frames omitted

 [WI-20303][TI-38773] - [ERROR] 2024-10-29 13:28:44.586 +0800 o.a.d.s.m.p.q.TaskExecuteRunnable:[64] - Handle task event error, this event will be removed, event: TaskEvent(taskInstanceId=38773, workerAddress=dolphin-kksvpq-worker-0.dolphin-kksvpq-worker-headless:1234, state=TaskExecutionStatus{code=7, desc='success'}, startTime=Tue Oct 29 13:28:42 CST 2024, endTime=Tue Oct 29 13:28:43 CST 2024, executePath=/tmp/dolphinscheduler/exec/process/root/15067524653824/15426920977376_174/20303/38773, logPath=/opt/dolphinscheduler/logs/20241029/15426920977376/174/20303/38773.log, processId=45955, appIds=null, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=20303)

 org.apache.dolphinscheduler.server.master.event.TaskEventHandleError: Handle task result event error, the task instance is already finished, will discord this event

 	at org.apache.dolphinscheduler.server.master.event.TaskResultEventHandler.handleTaskEvent(TaskResultEventHandler.java:86)

 	at org.apache.dolphinscheduler.server.master.processor.queue.TaskExecuteRunnable.run(TaskExecuteRunnable.java:56)

 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

 	at java.lang.Thread.run(Thread.java:750)
 	

### What you expected to happen

 [WI-0][TI-0] - [ERROR] 2024-10-29 13:28:42.588 +0800 o.a.d.e.b.s.JdkDynamicServerHandler:[84] - Cannot find the ServerMethodInvoker of : Transporter(header=TransporterHeader(methodIdentifier=public abstract void org.apache.dolphinscheduler.extract.worker.ITaskInstanceExecutionEventAckListener.handleTaskInstanceExecutionRunningEventAck(org.apache.dolphinscheduler.extract.worker.transportor.TaskInstanceExecutionRunningEventAck), opaque=5939), body=[123, 34, 97, 114, 103, 115, 34, 58, 91, 34, 101, 121, 74, 48, 89, 88, 78, 114, 83, 87, 53, 122, 100, 71, 70, 117, 89, 50, 86, 74, 90, 67, 73, 54, 77, 122, 103, 51, 78, 106, 65, 115, 73, 110, 78, 49, 89, 50, 78, 108, 99, 51, 77, 105, 79, 110, 82, 121, 100, 87, 86, 57, 34, 93, 44, 34, 97, 114, 103, 115, 84, 121, 112, 101, 115, 34, 58, 91, 34, 111, 114, 103, 46, 97, 112, 97, 99, 104, 101, 46, 100, 111, 108, 112, 104, 105, 110, 115, 99, 104, 101, 100, 117, 108, 101, 114, 46, 101, 120, 116, 114, 97, 99, 116, 46, 119, 111, 114, 107, 101, 114, 46, 116, 114, 97, 110, 115, 112, 111, 114, 116, 111, 114, 46, 84, 97, 115, 107, 73, 110, 115, 116, 97, 110, 99, 101, 69, 120, 101, 99, 117, 116, 105, 111, 110, 82, 117, 110, 110, 105, 110, 103, 69, 118, 101, 110, 116, 65, 99, 107, 34, 93, 125])

 [WI-20301][TI-38760] - [ERROR] 2024-10-29 13:28:42.588 +0800 o.a.d.s.m.p.q.TaskExecuteRunnable:[64] - Handle task event error, this event will be removed, event: TaskEvent(taskInstanceId=38760, workerAddress=dolphin-kksvpq-master-0.dolphin-kksvpq-master-headless:5678, state=TaskExecutionStatus{code=1, desc='running'}, startTime=Tue Oct 29 13:28:41 CST 2024, endTime=null, executePath=null, logPath=/opt/dolphinscheduler/logs/20241029/15426921096672/159/20301/38760.log, processId=0, appIds=null, event=RUNNING, varPool=null, cacheTaskInstanceId=0, processInstanceId=20301)

 org.apache.dolphinscheduler.server.master.event.TaskEventHandleError: Handle task running event error, update taskInstance to db failed

 	at org.apache.dolphinscheduler.server.master.event.TaskRunningEventHandler.handleTaskEvent(TaskRunningEventHandler.java:98)

 	at org.apache.dolphinscheduler.server.master.processor.queue.TaskExecuteRunnable.run(TaskExecuteRunnable.java:56)

 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

 	at java.lang.Thread.run(Thread.java:750)

 Caused by: org.apache.dolphinscheduler.extract.base.exception.MethodInvocationException: Cannot find the ServerMethodInvoker of public abstract void org.apache.dolphinscheduler.extract.worker.ITaskInstanceExecutionEventAckListener.handleTaskInstanceExecutionRunningEventAck(org.apache.dolphinscheduler.extract.worker.transportor.TaskInstanceExecutionRunningEventAck)

 	at org.apache.dolphinscheduler.extract.base.exception.MethodInvocationException.of(MethodInvocationException.java:27)

 	at org.apache.dolphinscheduler.extract.base.client.SyncClientMethodInvoker.invoke(SyncClientMethodInvoker.java:48)

 	at org.apache.dolphinscheduler.extract.base.client.ClientInvocationHandler.invoke(ClientInvocationHandler.java:55)

 	at com.sun.proxy.$Proxy238.handleTaskInstanceExecutionRunningEventAck(Unknown Source)

 	at org.apache.dolphinscheduler.server.master.event.TaskRunningEventHandler.sendAckToWorker(TaskRunningEventHandler.java:115)

 	at org.apache.dolphinscheduler.server.master.event.TaskRunningEventHandler.handleTaskEvent(TaskRunningEventHandler.java:92)

 	... 6 common frames omitted

 [WI-20303][TI-38773] - [ERROR] 2024-10-29 13:28:44.586 +0800 o.a.d.s.m.p.q.TaskExecuteRunnable:[64] - Handle task event error, this event will be removed, event: TaskEvent(taskInstanceId=38773, workerAddress=dolphin-kksvpq-worker-0.dolphin-kksvpq-worker-headless:1234, state=TaskExecutionStatus{code=7, desc='success'}, startTime=Tue Oct 29 13:28:42 CST 2024, endTime=Tue Oct 29 13:28:43 CST 2024, executePath=/tmp/dolphinscheduler/exec/process/root/15067524653824/15426920977376_174/20303/38773, logPath=/opt/dolphinscheduler/logs/20241029/15426920977376/174/20303/38773.log, processId=45955, appIds=null, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=20303)

 org.apache.dolphinscheduler.server.master.event.TaskEventHandleError: Handle task result event error, the task instance is already finished, will discord this event

 	at org.apache.dolphinscheduler.server.master.event.TaskResultEventHandler.handleTaskEvent(TaskResultEventHandler.java:86)

 	at org.apache.dolphinscheduler.server.master.processor.queue.TaskExecuteRunnable.run(TaskExecuteRunnable.java:56)

 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

 	at java.lang.Thread.run(Thread.java:750)
 	

### How to reproduce

 [WI-0][TI-0] - [ERROR] 2024-10-29 13:28:42.588 +0800 o.a.d.e.b.s.JdkDynamicServerHandler:[84] - Cannot find the ServerMethodInvoker of : Transporter(header=TransporterHeader(methodIdentifier=public abstract void org.apache.dolphinscheduler.extract.worker.ITaskInstanceExecutionEventAckListener.handleTaskInstanceExecutionRunningEventAck(org.apache.dolphinscheduler.extract.worker.transportor.TaskInstanceExecutionRunningEventAck), opaque=5939), body=[123, 34, 97, 114, 103, 115, 34, 58, 91, 34, 101, 121, 74, 48, 89, 88, 78, 114, 83, 87, 53, 122, 100, 71, 70, 117, 89, 50, 86, 74, 90, 67, 73, 54, 77, 122, 103, 51, 78, 106, 65, 115, 73, 110, 78, 49, 89, 50, 78, 108, 99, 51, 77, 105, 79, 110, 82, 121, 100, 87, 86, 57, 34, 93, 44, 34, 97, 114, 103, 115, 84, 121, 112, 101, 115, 34, 58, 91, 34, 111, 114, 103, 46, 97, 112, 97, 99, 104, 101, 46, 100, 111, 108, 112, 104, 105, 110, 115, 99, 104, 101, 100, 117, 108, 101, 114, 46, 101, 120, 116, 114, 97, 99, 116, 46, 119, 111, 114, 107, 101, 114, 46, 116, 114, 97, 110, 115, 112, 111, 114, 116, 111, 114, 46, 84, 97, 115, 107, 73, 110, 115, 116, 97, 110, 99, 101, 69, 120, 101, 99, 117, 116, 105, 111, 110, 82, 117, 110, 110, 105, 110, 103, 69, 118, 101, 110, 116, 65, 99, 107, 34, 93, 125])

 [WI-20301][TI-38760] - [ERROR] 2024-10-29 13:28:42.588 +0800 o.a.d.s.m.p.q.TaskExecuteRunnable:[64] - Handle task event error, this event will be removed, event: TaskEvent(taskInstanceId=38760, workerAddress=dolphin-kksvpq-master-0.dolphin-kksvpq-master-headless:5678, state=TaskExecutionStatus{code=1, desc='running'}, startTime=Tue Oct 29 13:28:41 CST 2024, endTime=null, executePath=null, logPath=/opt/dolphinscheduler/logs/20241029/15426921096672/159/20301/38760.log, processId=0, appIds=null, event=RUNNING, varPool=null, cacheTaskInstanceId=0, processInstanceId=20301)

 org.apache.dolphinscheduler.server.master.event.TaskEventHandleError: Handle task running event error, update taskInstance to db failed

 	at org.apache.dolphinscheduler.server.master.event.TaskRunningEventHandler.handleTaskEvent(TaskRunningEventHandler.java:98)

 	at org.apache.dolphinscheduler.server.master.processor.queue.TaskExecuteRunnable.run(TaskExecuteRunnable.java:56)

 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

 	at java.lang.Thread.run(Thread.java:750)

 Caused by: org.apache.dolphinscheduler.extract.base.exception.MethodInvocationException: Cannot find the ServerMethodInvoker of public abstract void org.apache.dolphinscheduler.extract.worker.ITaskInstanceExecutionEventAckListener.handleTaskInstanceExecutionRunningEventAck(org.apache.dolphinscheduler.extract.worker.transportor.TaskInstanceExecutionRunningEventAck)

 	at org.apache.dolphinscheduler.extract.base.exception.MethodInvocationException.of(MethodInvocationException.java:27)

 	at org.apache.dolphinscheduler.extract.base.client.SyncClientMethodInvoker.invoke(SyncClientMethodInvoker.java:48)

 	at org.apache.dolphinscheduler.extract.base.client.ClientInvocationHandler.invoke(ClientInvocationHandler.java:55)

 	at com.sun.proxy.$Proxy238.handleTaskInstanceExecutionRunningEventAck(Unknown Source)

 	at org.apache.dolphinscheduler.server.master.event.TaskRunningEventHandler.sendAckToWorker(TaskRunningEventHandler.java:115)

 	at org.apache.dolphinscheduler.server.master.event.TaskRunningEventHandler.handleTaskEvent(TaskRunningEventHandler.java:92)

 	... 6 common frames omitted

 [WI-20303][TI-38773] - [ERROR] 2024-10-29 13:28:44.586 +0800 o.a.d.s.m.p.q.TaskExecuteRunnable:[64] - Handle task event error, this event will be removed, event: TaskEvent(taskInstanceId=38773, workerAddress=dolphin-kksvpq-worker-0.dolphin-kksvpq-worker-headless:1234, state=TaskExecutionStatus{code=7, desc='success'}, startTime=Tue Oct 29 13:28:42 CST 2024, endTime=Tue Oct 29 13:28:43 CST 2024, executePath=/tmp/dolphinscheduler/exec/process/root/15067524653824/15426920977376_174/20303/38773, logPath=/opt/dolphinscheduler/logs/20241029/15426920977376/174/20303/38773.log, processId=45955, appIds=null, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=20303)

 org.apache.dolphinscheduler.server.master.event.TaskEventHandleError: Handle task result event error, the task instance is already finished, will discord this event

 	at org.apache.dolphinscheduler.server.master.event.TaskResultEventHandler.handleTaskEvent(TaskResultEventHandler.java:86)

 	at org.apache.dolphinscheduler.server.master.processor.queue.TaskExecuteRunnable.run(TaskExecuteRunnable.java:56)

 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

 	at java.lang.Thread.run(Thread.java:750)
 	

### Anything else

 [WI-0][TI-0] - [ERROR] 2024-10-29 13:28:42.588 +0800 o.a.d.e.b.s.JdkDynamicServerHandler:[84] - Cannot find the ServerMethodInvoker of : Transporter(header=TransporterHeader(methodIdentifier=public abstract void org.apache.dolphinscheduler.extract.worker.ITaskInstanceExecutionEventAckListener.handleTaskInstanceExecutionRunningEventAck(org.apache.dolphinscheduler.extract.worker.transportor.TaskInstanceExecutionRunningEventAck), opaque=5939), body=[123, 34, 97, 114, 103, 115, 34, 58, 91, 34, 101, 121, 74, 48, 89, 88, 78, 114, 83, 87, 53, 122, 100, 71, 70, 117, 89, 50, 86, 74, 90, 67, 73, 54, 77, 122, 103, 51, 78, 106, 65, 115, 73, 110, 78, 49, 89, 50, 78, 108, 99, 51, 77, 105, 79, 110, 82, 121, 100, 87, 86, 57, 34, 93, 44, 34, 97, 114, 103, 115, 84, 121, 112, 101, 115, 34, 58, 91, 34, 111, 114, 103, 46, 97, 112, 97, 99, 104, 101, 46, 100, 111, 108, 112, 104, 105, 110, 115, 99, 104, 101, 100, 117, 108, 101, 114, 46, 101, 120, 116, 114, 97, 99, 116, 46, 119, 111, 114, 107, 101, 114, 46, 116, 114, 97, 110, 115, 112, 111, 114, 116, 111, 114, 46, 84, 97, 115, 107, 73, 110, 115, 116, 97, 110, 99, 101, 69, 120, 101, 99, 117, 116, 105, 111, 110, 82, 117, 110, 110, 105, 110, 103, 69, 118, 101, 110, 116, 65, 99, 107, 34, 93, 125])

 [WI-20301][TI-38760] - [ERROR] 2024-10-29 13:28:42.588 +0800 o.a.d.s.m.p.q.TaskExecuteRunnable:[64] - Handle task event error, this event will be removed, event: TaskEvent(taskInstanceId=38760, workerAddress=dolphin-kksvpq-master-0.dolphin-kksvpq-master-headless:5678, state=TaskExecutionStatus{code=1, desc='running'}, startTime=Tue Oct 29 13:28:41 CST 2024, endTime=null, executePath=null, logPath=/opt/dolphinscheduler/logs/20241029/15426921096672/159/20301/38760.log, processId=0, appIds=null, event=RUNNING, varPool=null, cacheTaskInstanceId=0, processInstanceId=20301)

 org.apache.dolphinscheduler.server.master.event.TaskEventHandleError: Handle task running event error, update taskInstance to db failed

 	at org.apache.dolphinscheduler.server.master.event.TaskRunningEventHandler.handleTaskEvent(TaskRunningEventHandler.java:98)

 	at org.apache.dolphinscheduler.server.master.processor.queue.TaskExecuteRunnable.run(TaskExecuteRunnable.java:56)

 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

 	at java.lang.Thread.run(Thread.java:750)

 Caused by: org.apache.dolphinscheduler.extract.base.exception.MethodInvocationException: Cannot find the ServerMethodInvoker of public abstract void org.apache.dolphinscheduler.extract.worker.ITaskInstanceExecutionEventAckListener.handleTaskInstanceExecutionRunningEventAck(org.apache.dolphinscheduler.extract.worker.transportor.TaskInstanceExecutionRunningEventAck)

 	at org.apache.dolphinscheduler.extract.base.exception.MethodInvocationException.of(MethodInvocationException.java:27)

 	at org.apache.dolphinscheduler.extract.base.client.SyncClientMethodInvoker.invoke(SyncClientMethodInvoker.java:48)

 	at org.apache.dolphinscheduler.extract.base.client.ClientInvocationHandler.invoke(ClientInvocationHandler.java:55)

 	at com.sun.proxy.$Proxy238.handleTaskInstanceExecutionRunningEventAck(Unknown Source)

 	at org.apache.dolphinscheduler.server.master.event.TaskRunningEventHandler.sendAckToWorker(TaskRunningEventHandler.java:115)

 	at org.apache.dolphinscheduler.server.master.event.TaskRunningEventHandler.handleTaskEvent(TaskRunningEventHandler.java:92)

 	... 6 common frames omitted

 [WI-20303][TI-38773] - [ERROR] 2024-10-29 13:28:44.586 +0800 o.a.d.s.m.p.q.TaskExecuteRunnable:[64] - Handle task event error, this event will be removed, event: TaskEvent(taskInstanceId=38773, workerAddress=dolphin-kksvpq-worker-0.dolphin-kksvpq-worker-headless:1234, state=TaskExecutionStatus{code=7, desc='success'}, startTime=Tue Oct 29 13:28:42 CST 2024, endTime=Tue Oct 29 13:28:43 CST 2024, executePath=/tmp/dolphinscheduler/exec/process/root/15067524653824/15426920977376_174/20303/38773, logPath=/opt/dolphinscheduler/logs/20241029/15426920977376/174/20303/38773.log, processId=45955, appIds=null, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=20303)

 org.apache.dolphinscheduler.server.master.event.TaskEventHandleError: Handle task result event error, the task instance is already finished, will discord this event

 	at org.apache.dolphinscheduler.server.master.event.TaskResultEventHandler.handleTaskEvent(TaskResultEventHandler.java:86)

 	at org.apache.dolphinscheduler.server.master.processor.queue.TaskExecuteRunnable.run(TaskExecuteRunnable.java:56)

 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

 	at java.lang.Thread.run(Thread.java:750)
 	

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lslcoded** [comment]
version 3.2.1

**Comment by SbloodyS** [comment]
This issue have been fixed in `dev`

**Comment by lslcoded** [comment]
有没有修复过的docker镜像 我们这边没有办法编译通过

**Comment by lslcoded** [comment]
Can the fixed version be made into an official image? Or could we update the official website's 3.2.1 image?

**Comment by lslcoded** [comment]
@SbloodyS 
Can the fixed version be made into an official image? Or could we update the official website's 3.2.1 image?

**Comment by SbloodyS** [comment]
> @SbloodyS Can the fixed version be made into an official image? Or could we update the official website's 3.2.1 image?

The new version of 3.3.0 will include this fix. We reconstructed this part of the logic in the `dev` branch, which is currently not supported by 3.2.X.

**Comment by lslcoded** [comment]
Could you please help us? Or point out which commit modified this part of the code?

**Comment by lslcoded** [comment]
![image](https://github.com/user-attachments/assets/cb66e1c9-7690-44d6-bb97-fca418b10805)
"The 3.3.0 image is not available! Where can I install the 3.3.0 version? We are using k8s helm for installation!"

**Comment by SbloodyS** [comment]
> Could you please help us? Or point out which commit modified this part of the code?

We refactored the whole logic in the `dev` branch with dozens of commits. It's impossible for 3.2.X to using it.

> "The 3.3.0 image is not available! Where can I install the 3.3.0 version? We are using k8s helm for installation!"

The version 3.3.0 haven't been release yet. It's better to use 3.1.9 in production environment. Currently 3.2.X is not recommanded in production environment since it's unstable.

**Comment by lslcoded** [comment]
Is the issue not present in version 3.1.9? If there's an issue with that as well, what's the point? When is version 3.3.0 expected to be released?

**Comment by lslcoded** [comment]
Is the issue not present in version 3.1.9? If there's an issue with that as well, what's the point? When is version 3.3.0 expected to be released?
