### ISSUE TITLE
[Bug] [WorkflowFailover] Workflow may stuck on state 'FAILOVER' in failover process

### ISSUE THREAD

**Issue by reele** [apache/dolphinscheduler#16878]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when master server in failover process, it find the workflows which the state are in `WorkflowExecutionStatus.NEED_FAILOVER_STATES`,
and `WorkflowFailover.failoverWorkflow` will create a failover command, save original execution state to command param, and set workflow's state to `FAILOVER`

then the server fetch command, set workflow's state to original state from command's `commandParam` in command handler, and continue run the workflow.

now if the server crashes before handle this failover command, workflow's state will stuck on `FAILOVER` (which not in `WorkflowExecutionStatus.NEED_FAILOVER_STATES`)

### What you expected to happen

i think exchange state with command may losing the original state with a very low probability
so first it better to do `deleteCommandOrThrow` and restore the execution state in same transaction,

Or just do failover without changing the original execution state.

### How to reproduce

kill master server before handle the failover command, and restart the master server

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
@reele I cannot clear understand, are you means when master handle the failover command and then master crash, will cuase the workflow instance loss state?

This stage is already in a transaction 
https://github.com/apache/dolphinscheduler/blob/566651c6c58672deaf438d29fcf2f644c67a9160/dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/runnable/WorkflowExecutionRunnableFactory.java#L48-L58

**Comment by reele** [comment]
Oh, sorry!! my fault !
I've been testing failover in some extreme situations and didn't notice this.
i will close this issue.
@ruanwenjun

**Comment by ruanwenjun** [comment]
> Oh, sorry!! my fault ! I've been testing failover in some extreme situations and didn't notice this. i will close this issue. @ruanwenjun

@reele So is there exist bug? fell free to tell me if you find and bug or find anything with problems.

**Comment by reele** [comment]
> > Oh, sorry!! my fault ! I've been testing failover in some extreme situations and didn't notice this. i will close this issue. @ruanwenjun
> 
> @reele So is there exist bug? fell free to tell me if you find and bug or find anything with problems.

i'm no sure, it seems not stuck on status, i'll do more test

**Comment by ruanwenjun** [comment]
> > > Oh, sorry!! my fault ! I've been testing failover in some extreme situations and didn't notice this. i will close this issue. @ruanwenjun
> > 
> > 
> > @reele So is there exist bug? fell free to tell me if you find and bug or find anything with problems.
> 
> i'm no sure, it seems not stuck on status, i'll do more test

Ok, If you have any idea about the design, you can discuss with me.

**Comment by reele** [comment]
@ruanwenjun 
finally i found the reason why the transaction didn't rollback
```java
    @Transactional
    public IWorkflowExecutionRunnable createWorkflowExecuteRunnable(Command command) {
        deleteCommandOrThrow(command);
        return doCreateWorkflowExecutionRunnable(command);
    }
```

the `@Transactional` proxy will not roll back if the exception was not captured inside of the `@Transactional` proxied function

if capture exception like this, the transaction will work:
```java
    @Transactional
    public IWorkflowExecutionRunnable createWorkflowExecuteRunnable(Command command) {
        try{
            deleteCommandOrThrow(command);
            return doCreateWorkflowExecutionRunnable(command);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
```

**Comment by ruanwenjun** [comment]
> [@ruanwenjun](https://github.com/ruanwenjun) finally i found the reason why the transaction didn't rollback
> 
>     @Transactional
>     public IWorkflowExecutionRunnable createWorkflowExecuteRunnable(Command command) {
>         deleteCommandOrThrow(command);
>         return doCreateWorkflowExecutionRunnable(command);
>     }
> the `@Transactional` proxy will not roll back if the exception was not captured inside of the `@Transactional` proxied function
> 
> if capture exception like this, the transaction will work:
> 
>     @Transactional
>     public IWorkflowExecutionRunnable createWorkflowExecuteRunnable(Command command) {
>         try{
>             deleteCommandOrThrow(command);
>             return doCreateWorkflowExecutionRunnable(command);
>         } catch (Exception e) {
>             throw new RuntimeException(e);
>         }
>     }

@reele It's strange, we don't have unchecked exception in this method, so all exception here is RuntimeException.

**Comment by reele** [comment]
@ruanwenjun 
my mistake...it's not the cause of exception.

use `@Transactional(propagation = Propagation.SUPPORTS)` will work:
```java
    @Transactional(propagation = Propagation.SUPPORTS)
    public IWorkflowExecutionRunnable createWorkflowExecuteRunnable(Command command) {
        deleteCommandOrThrow(command);
        return doCreateWorkflowExecutionRunnable(command);
    }
```
i'm still trying to determine why.

reproduce:
```
1.run a workflow with sleep
2.stop master
3.remove commandType field from workflow instance's command_param
4.start master
5.workflow instance's state field will stuck on 18
```


my case is migrate from 2.0.6 to dev, so after upgraded schema, workflow instance's command param missing `commandType`, so the failover command's execution is failed, but the database didn't rollback:
```log
[WI-0][TI-0] - 2025-03-20 18:08:23.924 ERROR [MasterCommandHandleThreadPool] o.a.d.s.m.e.c.CommandEngine:[184] - Failed bootstrap command {
  "id" : 4316023,
  "commandType" : "RECOVER_TOLERANCE_FAULT_PROCESS",
  "workflowDefinitionCode" : 10059785789984,
  "workflowDefinitionVersion" : 3,
  "workflowInstanceId" : 4257960,
  "commandParam" : "{\"commandType\":\"RECOVER_TOLERANCE_FAULT\",\"subWorkflowInstance\":false,\"startNodes\":null,\"commandParams\":null,\"timeZone\":null,\"workflowExecutionStatus\":\"RUNNING_EXECUTION\"}",
  "workflowInstancePriority" : "MEDIUM",
  "executorId" : 0,
  "taskDependType" : "TASK_POST",
  "failureStrategy" : "CONTINUE",
  "warningType" : "NONE",
  "warningGroupId" : null,
  "scheduleTime" : null,
  "startTime" : null,
  "updateTime" : "2025-03-20 18:08:22",
  "workerGroup" : null,
  "tenantCode" : "default",
  "environmentCode" : -1,
  "dryRun" : 0,
  "testFlag" : 0
} 
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Invalid command param : null
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalArgumentException: Invalid command param : null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at org.apache.dolphinscheduler.server.master.engine.command.handler.AbstractCommandHandler.parseStartNodesFromWorkflowInstance(AbstractCommandHandler.java:135)
	at org.apache.dolphinscheduler.server.master.engine.command.handler.WorkflowFailoverCommandHandler.assembleWorkflowExecutionGraph(WorkflowFailoverCommandHandler.java:134)
	at org.apache.dolphinscheduler.server.master.engine.command.handler.AbstractCommandHandler.handleCommand(AbstractCommandHandler.java:83)
	at org.apache.dolphinscheduler.server.master.engine.workflow.runnable.WorkflowExecutionRunnableFactory.doCreateWorkflowExecutionRunnable(WorkflowExecutionRunnableFactory.java:71)
	at org.apache.dolphinscheduler.server.master.engine.workflow.runnable.WorkflowExecutionRunnableFactory.createWorkflowExecuteRunnable(WorkflowExecutionRunnableFactory.java:56)
	at org.apache.dolphinscheduler.server.master.engine.workflow.runnable.WorkflowExecutionRunnableFactory$$FastClassBySpringCGLIB$$597b7266.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.apache.dolphinscheduler.server.master.engine.workflow.runnable.WorkflowExecutionRunnableFactory$$EnhancerBySpringCGLIB$$e1cd410c.createWorkflowExecuteRunnable(<generated>)
	at org.apache.dolphinscheduler.server.master.engine.command.CommandEngine.lambda$bootstrapCommand$2(CommandEngine.java:151)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	... 3 common frames omitted
```

**Comment by ruanwenjun** [comment]
@reele Hi, the transaction has been rollback, and the command is deleted by 
https://github.com/apache/dolphinscheduler/blob/1b28cd60d76818535254126faa96530b754867d7/dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/command/CommandEngine.java#L177-L185

**Comment by reele** [comment]
oh, this is my fault again... The command goes into error_command, it's ok.
