### ISSUE TITLE
[Bug] [Task] dolphinscheduler  keeps reporting a null error after it starts

### ISSUE THREAD

**Issue by heyuwei-1227** [apache/dolphinscheduler#16924]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The startup is successful, but the null pointer problem keeps reporting

### What you expected to happen

[ERROR] 2024-12-25 08:40:51.501 +0000 org.apache.dolphinscheduler.plugin.task.api.parser.TimePlaceholderUtils:[361] - [WorkflowInstance-0][TaskInstance-0] - null
java.util.EmptyStackException: null
        at java.util.Stack.peek(Stack.java:102)
        at java.util.Stack.pop(Stack.java:84)
        at org.apache.dolphinscheduler.plugin.task.api.parser.TimePlaceholderUtils.calculate(TimePlaceholderUtils.java:211)
        at org.apache.dolphinscheduler.plugin.task.api.parser.TimePlaceholderUtils.calculate(TimePlaceholderUtils.java:116)
        at org.apache.dolphinscheduler.plugin.task.api.parser.TimePlaceholderUtils.calcMinutes(TimePlaceholderUtils.java:569)
        at org.apache.dolphinscheduler.plugin.task.api.parser.TimePlaceholderUtils.calcMinutes(TimePlaceholderUtils.java:536)
        at org.apache.dolphinscheduler.plugin.task.api.parser.TimePlaceholderUtils.calcTimeExpression(TimePlaceholderUtils.java:389)
        at org.apache.dolphinscheduler.plugin.task.api.parser.TimePlaceholderUtils.calculateTime(TimePlaceholderUtils.java:357)
        at org.apache.dolphinscheduler.plugin.task.api.parser.TimePlaceholderUtils.getPlaceHolderTime(TimePlaceholderUtils.java:332)
        at org.apache.dolphinscheduler.plugin.task.api.utils.ParameterUtils.dateTemplateParse(ParameterUtils.java:123)
        at org.apache.dolphinscheduler.plugin.task.api.utils.ParameterUtils.convertParameterPlaceholders(ParameterUtils.java:73)
        at org.apache.dolphinscheduler.service.expand.CuringGlobalParams.convertParameterPlaceholders(CuringGlobalParams.java:60)
        at org.apache.dolphinscheduler.service.expand.CuringGlobalParams.curingGlobalParams(CuringGlobalParams.java:112)
        at org.apache.dolphinscheduler.service.process.ProcessServiceImpl.generateNewProcessInstance(ProcessServiceImpl.java:793)
        at org.apache.dolphinscheduler.service.process.ProcessServiceImpl.constructProcessInstance(ProcessServiceImpl.java:932)
        at org.apache.dolphinscheduler.service.process.ProcessServiceImpl.handleCommand(

[ERROR] 2024-12-25 08:40:52.501 +0000 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerBootstrap:[228] - [WorkflowInstance-0][TaskInstance-0] - Master handle command 8 error 
java.util.EmptyStackException: null
        at java.util.Stack.peek(Stack.java:102)
        at java.util.Stack.pop(Stack.java:84)
        at org.apache.dolphinscheduler.plugin.task.api.parser.TimePlaceholderUtils.calculate(TimePlaceholderUtils.java:211)
        at org.apache.dolphinscheduler.plugin.task.api.parser.TimePlaceholderUtils.calculate(TimePlaceholderUtils.java:116)
        at org.apache.dolphinscheduler.plugin.task.api.parser.TimePlaceholderUtils.calcMinutes(TimePlaceholderUtils.java:569)
        at org.apache.dolphinscheduler.plugin.task.api.parser.TimePlaceholderUtils.calcMinutes(TimePlaceholderUtils.java:536)
        at org.apache.dolphinscheduler.plugin.task.api.parser.TimePlaceholderUtils.calcTimeExpression(TimePlaceholderUtils.java:389)
        at org.apache.dolphinscheduler.plugin.task.api.parser.TimePlaceholderUtils.calculateTime(TimePlaceholderUtils.java:357)
        at org.apache.dolphinscheduler.plugin.task.api.parser.TimePlaceholderUtils.getPlaceHolderTime(TimePlaceholderUtils.java:332)
        at org.apache.dolphinscheduler.plugin.task.api.utils.ParameterUtils.dateTemplateParse(ParameterUtils.java:123)
        at org.apache.dolphinscheduler.plugin.task.api.utils.ParameterUtils.convertParameterPlaceholders(ParameterUtils.java:73)
        at org.apache.dolphinscheduler.service.expand.CuringGlobalParams.convertParameterPlaceholders(CuringGlobalParams.java:60)
        at org.apache.dolphinscheduler.service.expand.CuringGlobalParams.curingGlobalParams(CuringGlobalParams.java:112)
        at org.apache.dolphinscheduler.service.process.ProcessServiceImpl.generateNewProcessInstance(ProcessServiceImpl.java:793)
        at org.apache.dolphinscheduler.service.process.ProcessServiceImpl.constructProcessInstance(ProcessServiceImpl.java:932)
        at org.apache.dolphinscheduler.service.process.Proce

### How to reproduce

dolphinscheduler  version ：3.1.8   seatunnel version：2.3.5

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Fixed in `3.3.2`
