### ISSUE TITLE
[BUG] update crontab task error (更新定时任务时错误)

### ISSUE THREAD

**Issue by gumupaier** [apache/dolphinscheduler#2540]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
the crontab task update error

**Screenshots**

![image](https://user-images.githubusercontent.com/37896380/80348101-dd2b4700-889f-11ea-935d-ef614ea17c4d.png)

**Which version of Dolphin Scheduler:**
 -[1.2.1]

**Comment by xingchun-chen** [comment]
It may be caused by the database time zone

**Comment by gumupaier** [comment]
> It may be caused by the database time zone

![image](https://user-images.githubusercontent.com/37896380/80358793-89285e80-88af-11ea-9627-798e46e7fcd3.png)

How can I get it to work quickly in the container

the date change from UTC to CST. But problems remain

**Comment by gumupaier** [comment]
now i have a new error where click online the cron task

![image](https://user-images.githubusercontent.com/37896380/80359559-9265fb00-88b0-11ea-855c-7ddc5d316342.png)
![image](https://user-images.githubusercontent.com/37896380/80359614-a3167100-88b0-11ea-85a7-681fb4a43032.png)

**Comment by xingchun-chen** [comment]
@lgcareer You help look at this problem

**Comment by dailidong** [comment]
@gumupaier  it looks like your exception info is not complete information， please provide the entire exception info

**Comment by gumupaier** [comment]
> @gumupaier it looks like your exception info is not complete information， please provide the entire exception info

`[ERROR] 2020-04-27 09:57:55.867 org.apache.dolphinscheduler.api.controller.SchedulerController:[195] - publish schedule online error
java.lang.RuntimeException: set online failure
        at org.apache.dolphinscheduler.api.service.SchedulerService.setScheduleState(SchedulerService.java:393)
        at org.apache.dolphinscheduler.api.service.SchedulerService$$FastClassBySpringCGLIB$$628050e2.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
        at org.apache.dolphinscheduler.api.service.SchedulerService$$EnhancerBySpringCGLIB$$891c906.setScheduleState(<generated>)
        at org.apache.dolphinscheduler.api.controller.SchedulerController.online(SchedulerController.java:191)
        at sun.reflect.GeneratedMethodAccessor385.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:867)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
        at com.github.xiaoymin.swaggerbootstrapui.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:84)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at com.github.xiaoymin.swaggerbootstrapui.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:502)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by samz406** [comment]
hello
  According to your screenshot, the short time you choose is 2020-04-27 23:56:00 to 2020-04-27 23:56:02
cron expression is 0 0 * * *? *, It can be judged that the cron expression is executed once every hour. Then, according to your start time, the next execution time should be 2020-04-28 00:00:00, and your end time period is 2020-04-27 23:56:02, which is less than the next execution time . So adding Quartz job will fail. That is, the online failed.

**Solution**
1 You can adjust the end time period. Just include the next execution time of cron within the start and end time period.

2 When modifying the timing, set the "execution time" button to calculate the next five execution times. If there is data, the timing setting is correct, otherwise there is a problem with the timing setting.


根据你的截图，你选的时间短是2020-04-27 23:56:00 到 2020-04-27 23:56:02 
cron 表达式为 0 0 * * * ? *,可以判断cron表达式是一小时执行一次。如果按照你的的开始时间，下一次执行执行时间应该是2020-04-28 00:00:00，而你的结束时间段是 2020-04-27 23:56:02 ，小于下一次执行时间。所以添加Quartz job就会失败。也就是上线失败。

**解决办法**
1 你可以调整结束时间段。只要要包含cron下一次执行时间在起止时间段内。

2 在修改定时，单击“执行时间”按钮，可以计算接下来五次执行时间，如果有数据那么定时设置正确，否则定时设置就有问题。

![image](https://user-images.githubusercontent.com/3055810/80392079-42ebf300-88e1-11ea-897c-7043dae65caa.png)

**Comment by gumupaier** [comment]
> hello
> According to your screenshot, the short time you choose is 2020-04-27 23:56:00 to 2020-04-27 23:56:02
> cron expression is 0 0 * * *? *, It can be judged that the cron expression is executed once every hour. Then, according to your start time, the next execution time should be 2020-04-28 00:00:00, and your end time period is 2020-04-27 23:56:02, which is less than the next execution time . So adding Quartz job will fail. That is, the online failed.
> 
> **Solution**
> 1 You can adjust the end time period. Just include the next execution time of cron within the start and end time period.
> 
> 2 When modifying the timing, set the "execution time" button to calculate the next five execution times. If there is data, the timing setting is correct, otherwise there is a problem with the timing setting.
> 
> 根据你的截图，你选的时间短是2020-04-27 23:56:00 到 2020-04-27 23:56:02
> cron 表达式为 0 0 * * * ? *,可以判断cron表达式是一小时执行一次。如果按照你的的开始时间，下一次执行执行时间应该是2020-04-28 00:00:00，而你的结束时间段是 2020-04-27 23:56:02 ，小于下一次执行时间。所以添加Quartz job就会失败。也就是上线失败。
> 
> **解决办法**
> 1 你可以调整结束时间段。只要要包含cron下一次执行时间在起止时间段内。
> 
> 2 在修改定时，单击“执行时间”按钮，可以计算接下来五次执行时间，如果有数据那么定时设置正确，否则定时设置就有问题。
> 
> ![image](https://user-images.githubusercontent.com/3055810/80392079-42ebf300-88e1-11ea-897c-7043dae65caa.png)

I'm not sure if this is a bug and will be updated in a later release to address this issue.

If I only want to do it once at a certain point in time, this setup is a bit repetitive（不确定这是否属于bug，后续版本是否会针对这个问题进行更新。
如果我只想在某一时间点执行一次，这设置就有点重复了）

**Comment by xingchun-chen** [comment]
@lgcareer  When the next execution of the timer is greater than the end time, is it necessary to add a judgment

**Comment by gumupaier** [comment]
> @lgcareer When the next execution of the timer is greater than the end time, is it necessary to add a judgment

I think it is necessary to add a hint

**Comment by caishunfeng** [comment]
Hi @gumupaier This issue will be closed because no update for a long time. You can check it again by latest code and reopen this issue if need.
