### ISSUE TITLE
[question] Required field 'client_protocol' is unset! Struct:TOpenSessionReq

### ISSUE THREAD

**Issue by yyyStudyStudyStudy** [apache/dolphinscheduler#4406]
[ERROR] 2021-01-08 10:55:40.553 org.apache.dolphinscheduler.api.service.DataSourceService:[433] - Could not establish connection to jdbc:hive2://10.0.4.78:10000/vfs_dw: Required field 'client_protocol' is unset! Struct:TOpenSessionReq(client_protocol:null, configuration:{use:database=vfs_dw})
java.sql.SQLException: Could not establish connection to jdbc:hive2://10.0.4.78:10000/vfs_dw: Required field 'client_protocol' is unset! Struct:TOpenSessionReq(client_protocol:null, configuration:{use:database=vfs_dw})
        at org.apache.hive.jdbc.HiveConnection.openSession(HiveConnection.java:601)
        at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:172)
        at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:107)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at org.apache.dolphinscheduler.api.service.DataSourceService.getConnection(DataSourceService.java:430)
        at org.apache.dolphinscheduler.api.service.DataSourceService.checkConnection(DataSourceService.java:448)
        at org.apache.dolphinscheduler.api.service.DataSourceService$$FastClassBySpringCGLIB$$8d6cb828.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
        at org.apache.dolphinscheduler.api.service.DataSourceService$$EnhancerBySpringCGLIB$$a93ee4fc.checkConnection(<generated>)
        at org.apache.dolphinscheduler.api.controller.DataSourceController.connectDataSource(DataSourceController.java:284)
        at sun.reflect.GeneratedMethodAccessor147.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by dailidong** [comment]
This indicates a version of hive jdbc driver mismatch between client and server
referer:  https://stackoverflow.com/questions/24694415/required-field-client-protocol-is-unset

**Comment by CalvinKirs** [comment]
Has your problem been resolved?

**Comment by KeithTt** [comment]
![图片](https://github.com/apache/dolphinscheduler/assets/15189954/8ee56c8e-05f0-4570-aaa3-81ead481b088)

Meet this problem, version: 3.1.5

How to update the jar version in an already running cluster?

**Comment by DalongZhenZ** [comment]
so, for dolphinschduler , how to reslove this wrong? my cdh is 6.3.2 and hive is 2.1.1,i replace the hive-jdbc jar in client is 2.1.1,it's althourgh have this wrong
