### ISSUE TITLE
process instance can not be stopped

### ISSUE THREAD

**Issue by wengieeee** [apache/dolphinscheduler#4834]
when a parocess instance is running ,

I click the stop button,

It will wait for the end of my running task

https://github.com/apache/incubator-dolphinscheduler/issues/4824#issue-812566857

停止正在运行的process instance 不成功，会等待正在运行的task结束才kill，这与文档不符合？

版本：1.3.4

**Comment by dddyszy** [comment]
i meet the same situation,and i found that i need to install 'pstree'
![image](https://user-images.githubusercontent.com/20266837/108684730-3995dc00-752e-11eb-860e-a77977b90815.png)
check is these any error in dolphinscheduler-worker.log

**Comment by zhuangchong** [comment]
@Yanwenjingcn 
Comment the following four lines in the logback-worker.xml file, run the task again, and then check to see if the worker.log prints any exceptions

![image](https://user-images.githubusercontent.com/37063904/108705597-7ff83480-7548-11eb-9a77-8bbf1af1a86c.png)

**Comment by calvinjiang** [comment]
@Yanwenjingcn 
I encountered the same error like yours when I was stopping  a task that's the type of shell.

```
[INFO] 2021-07-15 16:18:43.324 org.apache.dolphinscheduler.server.worker.processor.TaskKillProcessor:[95] - received kill command : TaskKillRequestCommand{taskInstanceId=230}
[ERROR] 2021-07-15 16:18:43.328 org.apache.dolphinscheduler.server.worker.processor.TaskKillProcessor:[136] - kill task error
java.io.IOException: Cannot run program "pstree": error=2, 没有那个文件或目录
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at org.apache.dolphinscheduler.common.shell.AbstractShell.runCommand(AbstractShell.java:145)
        at org.apache.dolphinscheduler.common.shell.AbstractShell.run(AbstractShell.java:124)
        at org.apache.dolphinscheduler.common.shell.ShellExecutor.execute(ShellExecutor.java:127)
        at org.apache.dolphinscheduler.common.shell.ShellExecutor.execCommand(ShellExecutor.java:104)
        at org.apache.dolphinscheduler.common.shell.ShellExecutor.execCommand(ShellExecutor.java:87)
        at org.apache.dolphinscheduler.common.utils.OSUtils.exeShell(OSUtils.java:442)
        at org.apache.dolphinscheduler.common.utils.OSUtils.exeCmd(OSUtils.java:431)
        at org.apache.dolphinscheduler.server.utils.ProcessUtils.getPidsStr(ProcessUtils.java:421)
        at org.apache.dolphinscheduler.server.worker.processor.TaskKillProcessor.doKill(TaskKillProcessor.java:126)
        at org.apache.dolphinscheduler.server.worker.processor.TaskKillProcessor.process(TaskKillProcessor.java:97)
        at org.apache.dolphinscheduler.remote.handler.NettyServerHandler.lambda$processReceived$0(NettyServerHandler.java:129)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, 没有那个文件或目录
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 16 common frames omitted
```

Cause:
  This error should be caused by missing the command of pstree in your OS. 
  
Solution:
  You need to install it in your OS. Next line maybe useful for you:
  sudo  yum -y install psmisc
