### ISSUE TITLE
[Bug]Delete resource error in version 1.3.4

### ISSUE THREAD

**Issue by gaoyu2016** [apache/dolphinscheduler#4865]
[ERROR] 2021-02-24 18:41:18.263 org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[45] - 删除资源错误
org.apache.hadoop.security.AccessControlException: Permission denied: user=hdfs, access=WRITE, inode="/dolphinscheduler/maintain/resources/reindex.py":maintain:supergroup:drwxr-xr-x
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:319)
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:292)
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:216)
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:190)
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1720)
	at org.apache.hadoop.hdfs.server.namenode.FSDirDeleteOp.delete(FSDirDeleteOp.java:88)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.delete(FSNamesystem.java:3712)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.delete(NameNodeRpcServer.java:952)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.delete(ClientNamenodeProtocolServerSideTranslatorPB.java:611)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:969)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2049)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2045)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2043)

**Comment by gaoyu2016** [comment]
but -rwxrwxrwx   3 maintain supergroup      16567 2021-02-22 19:39 /dolphinscheduler/maintain/resources/reindex.py

**Comment by zhuangchong** [comment]
check the HDFS user permissions

```
org.apache.hadoop.security.AccessControlException: Permission denied: user=hdfs, access=WRITE, inode="/dolphinscheduler/maintain/resources/reindex.py":maintain:supergroup:drwxr-xr-x
```

**Comment by gaoyu2016** [comment]
改为-rwxrwxrwx了，为什么还不行？

**Comment by xingchun-chen** [comment]
![image](https://user-images.githubusercontent.com/55787491/109108722-05f5c480-776f-11eb-824c-1d3a30eeea5e.png)
Does user=hdfs have permission to this directory

**Comment by gaoyu2016** [comment]
OK! 我对目录设置了一下，可以了。谢谢！

**Comment by chengshiwen** [comment]
Close since this issue has been solved
