### ISSUE TITLE
spark-submit error: __spark_conf__.zip does not exist

### ISSUE THREAD

**Issue by BryantYYDS** [apache/dolphinscheduler#4907]
Exception in thread "main" org.apache.spark.SparkException: Application application_1614585492052_0012 failed 2 times due to AM Container for appattempt_1614585492052_0012_000002 exited with  exitCode: -1000
	Failing this attempt.Diagnostics: [2021-03-01 17:12:34.877]File file:/home/dolphinscheduler/.sparkStaging/application_1614585492052_0012/__spark_conf__.zip does not exist
	java.io.FileNotFoundException: File file:/home/dolphinscheduler/.sparkStaging/application_1614585492052_0012/__spark_conf__.zip does not exist

**Comment by chengshiwen** [comment]
@MrZhangZetao How do you submit the Spark job? Could you give us more details? The path prefix of `spark_conf.zip` on YARN should be `hdfs://` instead of `file:/home/dolphinscheduler`.

**Comment by BryantYYDS** [comment]
就在DS的调度上 , 正常调用spark jar 包 , 建一个spark任务 , 用相同的租户在物理机上执行是可以的 ,下面是完整的日志 . 
[INFO] 2021-03-01 17:12:27.754  - [taskAppId=TASK-4-39-41]:[115] - create dir success /tmp/dolphinscheduler/exec/process/4/4/39/41
[INFO] 2021-03-01 17:12:27.869  - [taskAppId=TASK-4-39-41]:[85] - shell task params {"rawScript":"$SPARK_HOME/bin/spark-submit  --master yarn-client --num-executors 2 --executor-cores 2 --executor-memory 2048M  --class test_f /data/dolphinscheduler_data/scala_test-1.0-SNAPSHOT.jar","localParams":[],"resourceList":[]}
[INFO] 2021-03-01 17:12:27.896  - [taskAppId=TASK-4-39-41]:[160] - raw script : $SPARK_HOME/bin/spark-submit  --master yarn-client --num-executors 2 --executor-cores 2 --executor-memory 2048M  --class test_f /data/dolphinscheduler_data/scala_test-1.0-SNAPSHOT.jar
[INFO] 2021-03-01 17:12:27.896  - [taskAppId=TASK-4-39-41]:[161] - task execute path : /tmp/dolphinscheduler/exec/process/4/4/39/41
[INFO] 2021-03-01 17:12:27.901  - [taskAppId=TASK-4-39-41]:[87] - tenantCode user:dolphinscheduler, task dir:4_39_41
[INFO] 2021-03-01 17:12:27.901  - [taskAppId=TASK-4-39-41]:[92] - create command file:/tmp/dolphinscheduler/exec/process/4/4/39/41/4_39_41.command
[INFO] 2021-03-01 17:12:27.902  - [taskAppId=TASK-4-39-41]:[111] - command : #!/bin/sh
BASEDIR=$(cd `dirname $0`; pwd)
cd $BASEDIR
source /data/dolphinscheduler/conf/env/dolphinscheduler_env.sh
/tmp/dolphinscheduler/exec/process/4/4/39/41/4_39_41_node.sh
[INFO] 2021-03-01 17:12:27.914  - [taskAppId=TASK-4-39-41]:[324] - task run command:
sudo -u dolphinscheduler sh /tmp/dolphinscheduler/exec/process/4/4/39/41/4_39_41.command
[INFO] 2021-03-01 17:12:27.920  - [taskAppId=TASK-4-39-41]:[205] - process start, process id is: 10033
[INFO] 2021-03-01 17:12:29.954  - [taskAppId=TASK-4-39-41]:[127] -  -> Warning: Master yarn-client is deprecated since 2.0. Please use master "yarn" with specified deploy mode instead.
[INFO] 2021-03-01 17:12:31.109  - [taskAppId=TASK-4-39-41]:[127] -  -> 21/03/01 17:12:30 INFO conf.HiveConf: Found configuration file file:/etc/hive/conf.cloudera.hive/hive-site.xml
	21/03/01 17:12:31 INFO spark.SparkContext: Running Spark version 2.4.0-cdh6.3.2
[INFO] 2021-03-01 17:12:32.158  - [taskAppId=TASK-4-39-41]:[127] -  -> 21/03/01 17:12:31 INFO logging.DriverLogger: Added a local log appender at: /tmp/spark-2509cd96-9e16-428d-8a42-94c4beef7779/__driver_logs__/driver.log
	21/03/01 17:12:31 INFO spark.SparkContext: Submitted application: test_f
	21/03/01 17:12:31 INFO spark.SecurityManager: Changing view acls to: dolphinscheduler
	21/03/01 17:12:31 INFO spark.SecurityManager: Changing modify acls to: dolphinscheduler
	21/03/01 17:12:31 INFO spark.SecurityManager: Changing view acls groups to: 
	21/03/01 17:12:31 INFO spark.SecurityManager: Changing modify acls groups to: 
	21/03/01 17:12:31 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(dolphinscheduler); groups with view permissions: Set(); users  with modify permissions: Set(dolphinscheduler); groups with modify permissions: Set()
	21/03/01 17:12:31 INFO util.Utils: Successfully started service 'sparkDriver' on port 10413.
	21/03/01 17:12:31 INFO spark.SparkEnv: Registering MapOutputTracker
	21/03/01 17:12:31 INFO spark.SparkEnv: Registering BlockManagerMaster
	21/03/01 17:12:31 INFO storage.BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
	21/03/01 17:12:31 INFO storage.BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
	21/03/01 17:12:31 INFO storage.DiskBlockManager: Created local directory at /tmp/blockmgr-12b7edb7-ab51-4cc1-a685-06548df2a208
	21/03/01 17:12:31 INFO memory.MemoryStore: MemoryStore started with capacity 366.3 MB
	21/03/01 17:12:31 INFO spark.SparkEnv: Registering OutputCommitCoordinator
	21/03/01 17:12:32 INFO util.log: Logging initialized @3491ms
	21/03/01 17:12:32 INFO server.Server: jetty-9.3.z-SNAPSHOT, build timestamp: 2018-09-05T05:11:46+08:00, git hash: 3ce520221d0240229c862b122d2b06c12a625732
[INFO] 2021-03-01 17:12:33.171  - [taskAppId=TASK-4-39-41]:[127] -  -> 21/03/01 17:12:32 INFO server.Server: Started @3595ms
	21/03/01 17:12:32 INFO server.AbstractConnector: Started ServerConnector@4201a617{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
	21/03/01 17:12:32 INFO util.Utils: Successfully started service 'SparkUI' on port 4040.
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@57dc9128{/jobs,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@126be319{/jobs/json,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@6c44052e{/jobs/job,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@1e34c607{/jobs/job/json,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@5215cd9a{/stages,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@36b6964d{/stages/json,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@31198ceb{/stages/stage,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@7726e185{/stages/stage/json,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@aa5455e{/stages/pool,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@282308c3{/stages/pool/json,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@5dda14d0{/storage,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@1db0ec27{/storage/json,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@3d9fc57a{/storage/rdd,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@d4ab71a{/storage/rdd/json,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@3b4ef7{/environment,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@1af05b03{/environment/json,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@5987e932{/executors,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@1ad777f{/executors/json,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@5bbbdd4b{/executors/threadDump,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@438bad7c{/executors/threadDump/json,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@25230246{/static,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@632aa1a3{/,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@20765ed5{/api,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@c1a4620{/jobs/job/kill,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@76b0ae1b{/stages/stage/kill,null,AVAILABLE,@Spark}
	21/03/01 17:12:32 INFO ui.SparkUI: Bound SparkUI to 0.0.0.0, and started at http://hosvrit390:4040
	21/03/01 17:12:32 INFO spark.SparkContext: Added JAR file:/data/dolphinscheduler_data/scala_test-1.0-SNAPSHOT.jar at spark://hosvrit390:10413/jars/scala_test-1.0-SNAPSHOT.jar with timestamp 1614589952358
	21/03/01 17:12:32 INFO yarn.SparkRackResolver: Got an error when resolving hostNames. Falling back to /default-rack for all
	21/03/01 17:12:32 INFO client.RMProxy: Connecting to ResourceManager at /192.168.1.14:8032
	21/03/01 17:12:33 INFO yarn.Client: Requesting a new application from cluster with 5 NodeManagers
[INFO] 2021-03-01 17:12:34.447  - [taskAppId=TASK-4-39-41]:[127] -  -> 21/03/01 17:12:33 INFO conf.Configuration: resource-types.xml not found
	21/03/01 17:12:33 INFO resource.ResourceUtils: Unable to find 'resource-types.xml'.
	21/03/01 17:12:33 INFO yarn.Client: Verifying our application has not requested more than the maximum memory capability of the cluster (20480 MB per container)
	21/03/01 17:12:33 INFO yarn.Client: Will allocate AM container, with 896 MB memory including 384 MB overhead
	21/03/01 17:12:33 INFO yarn.Client: Setting up container launch context for our AM
	21/03/01 17:12:33 INFO yarn.Client: Setting up the launch environment for our AM container
	21/03/01 17:12:33 INFO yarn.Client: Preparing resources for our AM container
	21/03/01 17:12:33 INFO yarn.SparkRackResolver: Got an error when resolving hostNames. Falling back to /default-rack for all
	21/03/01 17:12:33 INFO yarn.Client: Uploading resource file:/tmp/spark-2509cd96-9e16-428d-8a42-94c4beef7779/__spark_conf__6955750791632555999.zip -> file:/home/dolphinscheduler/.sparkStaging/application_1614585492052_0012/__spark_conf__.zip
	21/03/01 17:12:33 INFO spark.SecurityManager: Changing view acls to: dolphinscheduler
	21/03/01 17:12:33 INFO spark.SecurityManager: Changing modify acls to: dolphinscheduler
	21/03/01 17:12:33 INFO spark.SecurityManager: Changing view acls groups to: 
	21/03/01 17:12:33 INFO spark.SecurityManager: Changing modify acls groups to: 
	21/03/01 17:12:33 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(dolphinscheduler); groups with view permissions: Set(); users  with modify permissions: Set(dolphinscheduler); groups with modify permissions: Set()
	21/03/01 17:12:33 INFO yarn.Client: Submitting application application_1614585492052_0012 to ResourceManager
	21/03/01 17:12:33 INFO impl.YarnClientImpl: Submitted application application_1614585492052_0012
	21/03/01 17:12:34 INFO yarn.SparkRackResolver: Got an error when resolving hostNames. Falling back to /default-rack for all
[INFO] 2021-03-01 17:12:35.025  - [taskAppId=TASK-4-39-41]:[127] -  -> 21/03/01 17:12:35 INFO yarn.Client: Application report for application_1614585492052_0012 (state: FAILED)
	21/03/01 17:12:35 INFO yarn.Client: 
		 client token: N/A
		 diagnostics: Application application_1614585492052_0012 failed 2 times due to AM Container for appattempt_1614585492052_0012_000002 exited with  exitCode: -1000
	Failing this attempt.Diagnostics: [2021-03-01 17:12:34.877]File file:/home/dolphinscheduler/.sparkStaging/application_1614585492052_0012/__spark_conf__.zip does not exist
	java.io.FileNotFoundException: File file:/home/dolphinscheduler/.sparkStaging/application_1614585492052_0012/__spark_conf__.zip does not exist
		at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:641)
		at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:867)
		at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:631)
		at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:442)
		at org.apache.hadoop.yarn.util.FSDownload.verifyAndCopy(FSDownload.java:269)
		at org.apache.hadoop.yarn.util.FSDownload.access$000(FSDownload.java:67)
		at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:414)
		at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:411)
		at java.security.AccessController.doPrivileged(Native Method)
		at javax.security.auth.Subject.doAs(Subject.java:422)
		at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1875)
		at org.apache.hadoop.yarn.util.FSDownload.call(FSDownload.java:411)
		at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.doDownloadCall(ContainerLocalizer.java:242)
		at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.call(ContainerLocalizer.java:235)
		at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.call(ContainerLocalizer.java:223)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
	
	For more detailed output, check the application tracking page: http://hosvrit389:8088/cluster/app/application_1614585492052_0012 Then click on links to logs of each attempt.
	. Failing the application.
		 ApplicationMaster host: N/A
		 ApplicationMaster RPC port: -1
		 queue: root.users.dolphinscheduler
		 start time: 1614589953955
		 final status: FAILED
		 tracking URL: http://hosvrit389:8088/cluster/app/application_1614585492052_0012
		 user: dolphinscheduler
	21/03/01 17:12:35 INFO yarn.Client: Deleted staging directory file:/home/dolphinscheduler/.sparkStaging/application_1614585492052_0012
	21/03/01 17:12:35 ERROR cluster.YarnClientSchedulerBackend: The YARN application has already ended! It might have been killed or the Application Master may have failed to start. Check the YARN application logs for more details.
	21/03/01 17:12:35 ERROR spark.SparkContext: Error initializing SparkContext.
	org.apache.spark.SparkException: Application application_1614585492052_0012 failed 2 times due to AM Container for appattempt_1614585492052_0012_000002 exited with  exitCode: -1000
	Failing this attempt.Diagnostics: [2021-03-01 17:12:34.877]File file:/home/dolphinscheduler/.sparkStaging/application_1614585492052_0012/__spark_conf__.zip does not exist
	java.io.FileNotFoundException: File file:/home/dolphinscheduler/.sparkStaging/application_1614585492052_0012/__spark_conf__.zip does not exist
		at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:641)
		at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:867)
		at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:631)
		at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:442)
		at org.apache.hadoop.yarn.util.FSDownload.verifyAndCopy(FSDownload.java:269)
		at org.apache.hadoop.yarn.util.FSDownload.access$000(FSDownload.java:67)
		at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:414)
		at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:411)
		at java.security.AccessController.doPrivileged(Native Method)
		at javax.security.auth.Subject.doAs(Subject.java:422)
		at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1875)
		at org.apache.hadoop.yarn.util.FSDownload.call(FSDownload.java:411)
		at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.doDownloadCall(ContainerLocalizer.java:242)
		at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.call(ContainerLocalizer.java:235)
		at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.call(ContainerLocalizer.java:223)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
[INFO] 2021-03-01 17:12:35.252  - [taskAppId=TASK-4-39-41]:[127] -  -> 
	For more detailed output, check the application tracking page: http://hosvrit389:8088/cluster/app/application_1614585492052_0012 Then click on links to logs of each attempt.
	. Failing the application.
		at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.waitForApplication(YarnClientSchedulerBackend.scala:95)
		at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:62)
		at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:186)
		at org.apache.spark.SparkContext.<init>(SparkContext.scala:511)
		at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2549)
		at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:944)
		at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:935)
		at scala.Option.getOrElse(Option.scala:121)
		at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:935)
		at test_f$.main(test_f.scala:20)
		at test_f.main(test_f.scala)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
		at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:851)
		at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
		at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
		at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
		at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:926)
		at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:935)
		at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
	21/03/01 17:12:35 INFO server.AbstractConnector: Stopped Spark@4201a617{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
	21/03/01 17:12:35 INFO ui.SparkUI: Stopped Spark web UI at http://hosvrit390:4040
	21/03/01 17:12:35 WARN cluster.YarnSchedulerBackend$YarnSchedulerEndpoint: Attempted to request executors before the AM has registered!
	21/03/01 17:12:35 INFO cluster.YarnClientSchedulerBackend: Shutting down all executors
	21/03/01 17:12:35 INFO cluster.YarnSchedulerBackend$YarnDriverEndpoint: Asking each executor to shut down
	21/03/01 17:12:35 INFO cluster.YarnClientSchedulerBackend: Stopped
	21/03/01 17:12:35 INFO spark.MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
	21/03/01 17:12:35 INFO memory.MemoryStore: MemoryStore cleared
	21/03/01 17:12:35 INFO storage.BlockManager: BlockManager stopped
	21/03/01 17:12:35 INFO storage.BlockManagerMaster: BlockManagerMaster stopped
	21/03/01 17:12:35 WARN metrics.MetricsSystem: Stopping a MetricsSystem that is not running
	21/03/01 17:12:35 INFO scheduler.OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
	21/03/01 17:12:35 INFO spark.SparkContext: Successfully stopped SparkContext
	Exception in thread "main" org.apache.spark.SparkException: Application application_1614585492052_0012 failed 2 times due to AM Container for appattempt_1614585492052_0012_000002 exited with  exitCode: -1000
	Failing this attempt.Diagnostics: [2021-03-01 17:12:34.877]File file:/home/dolphinscheduler/.sparkStaging/application_1614585492052_0012/__spark_conf__.zip does not exist
	java.io.FileNotFoundException: File file:/home/dolphinscheduler/.sparkStaging/application_1614585492052_0012/__spark_conf__.zip does not exist
		at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:641)
		at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:867)
		at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:631)
		at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:442)
		at org.apache.hadoop.yarn.util.FSDownload.verifyAndCopy(FSDownload.java:269)
		at org.apache.hadoop.yarn.util.FSDownload.access$000(FSDownload.java:67)
		at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:414)
		at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:411)
		at java.security.AccessController.doPrivileged(Native Method)
		at javax.security.auth.Subject.doAs(Subject.java:422)
		at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1875)
		at org.apache.hadoop.yarn.util.FSDownload.call(FSDownload.java:411)
		at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.doDownloadCall(ContainerLocalizer.java:242)
		at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.call(ContainerLocalizer.java:235)
		at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.call(ContainerLocalizer.java:223)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
	
[INFO] 2021-03-01 17:12:35.380  - [taskAppId=TASK-4-39-41]:[127] -  -> For more detailed output, check the application tracking page: http://hosvrit389:8088/cluster/app/application_1614585492052_0012 Then click on links to logs of each attempt.
	. Failing the application.
		at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.waitForApplication(YarnClientSchedulerBackend.scala:95)
		at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:62)
		at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:186)
		at org.apache.spark.SparkContext.<init>(SparkContext.scala:511)
		at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2549)
		at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:944)
		at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:935)
		at scala.Option.getOrElse(Option.scala:121)
		at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:935)
		at test_f$.main(test_f.scala:20)
		at test_f.main(test_f.scala)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
		at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:851)
		at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
		at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
		at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
		at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:926)
		at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:935)
		at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
	21/03/01 17:12:35 INFO util.ShutdownHookManager: Shutdown hook called
	21/03/01 17:12:35 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-2509cd96-9e16-428d-8a42-94c4beef7779
	21/03/01 17:12:35 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-6f9a5720-b890-41a7-b29b-64edc5934599

**Comment by BryantYYDS** [comment]
@chengshiwen chengshiwen

**Comment by chengshiwen** [comment]
@MrZhangZetao Please check the following logs, the `__spark_conf__.zip` uploaded error.

```
yarn.SparkRackResolver: Got an error when resolving hostNames. Falling back to /default-rack for all
21/03/01 17:12:33 INFO yarn.Client: Uploading resource file:/tmp/spark-2509cd96-9e16-428d-8a42-94c4beef7779/__spark_conf__6955750791632555999.zip -> file:/home/dolphinscheduler/.sparkStaging/application_1614585492052_0012/spark_conf.zip
```

By the way, Please check if `SparkPi` can run normally (Pay attention to replace `spark-examples_2.11-2.4.7.jar` with the actual jar file):
```
$SPARK_HOME2/bin/spark-submit --master yarn --deploy-mode client --num-executors 1 --executor-cores 1 --executor-memory 1G --class org.apache.spark.examples.SparkPi $SPARK_HOME2/examples/jars/spark-examples_2.11-2.4.7.jar
```

**Comment by chengshiwen** [comment]
Close this issue since no updates for long time
