### ISSUE TITLE
[Question] java.io.FileNotFoundException: Properties file  does not exist when start flink task

### ISSUE THREAD

**Issue by HeChuanXUPT** [apache/dolphinscheduler#5003]
**Describe the question**
I want to do test for flink node. I have uploaded the jar file and a configuration file "sql.config" successfully, and I have set the flink node settings, include Main Package and Resources. 
But get exception when start a task.

**Which version of DolphinScheduler:**
 -[1.3.5-dolphinscheduler-bin]

**Additional context**
task log:
```
[INFO] 2021-03-08 15:55:38.559  - [taskAppId=TASK-5-14-15]:[115] - create dir success /tmp/dolphinscheduler/exec/process/3/5/14/15
[INFO] 2021-03-08 15:55:38.605  - [taskAppId=TASK-5-14-15]:[68] - flink task params {"mainArgs":"-config sql.config","programType":"JAVA","mainClass":"com.data.finkttest.DdlJob","deployMode":"local","taskManagerMemory":"2G","mainJar":{"id":2},"slot":1,"flinkVersion":">=1.10","taskManager":"2","localParams":[],"others":"-m 127.0.0.1:8081","resourceList":[{"res":"test1/CONF/sql.config","name":"sql.config","id":5}],"jobManagerMemory":"1G"}
[INFO] 2021-03-08 15:55:38.625  - [taskAppId=TASK-5-14-15]:[90] - param Map : {}
[INFO] 2021-03-08 15:55:38.626  - [taskAppId=TASK-5-14-15]:[94] - param args : -config sql.config
[INFO] 2021-03-08 15:55:38.626  - [taskAppId=TASK-5-14-15]:[111] - flink task args : [flink, run]
[INFO] 2021-03-08 15:55:38.626  - [taskAppId=TASK-5-14-15]:[118] - flink task command : flink run -m 127.0.0.1:8081 -c com.data.finkttest.DdlJob test1/TestJob-1.0-SNAPSHOT-jar-with-dependencies.jar -config sql.config
[INFO] 2021-03-08 15:55:38.626  - [taskAppId=TASK-5-14-15]:[87] - tenantCode user:dolphinscheduler, task dir:5_14_15
[INFO] 2021-03-08 15:55:38.627  - [taskAppId=TASK-5-14-15]:[92] - create command file:/tmp/dolphinscheduler/exec/process/3/5/14/15/5_14_15.command
[INFO] 2021-03-08 15:55:38.627  - [taskAppId=TASK-5-14-15]:[111] - command : #!/bin/sh
BASEDIR=$(cd `dirname $0`; pwd)
cd $BASEDIR
source /home/dolphinscheduler/data/conf/env/dolphinscheduler_env.sh
flink run -m 172.16.7.59:30081 -c com.data.finkttest.DdlJob test1/TestJob-1.0-SNAPSHOT-jar-with-dependencies.jar -config sql.config
[INFO] 2021-03-08 15:55:38.633  - [taskAppId=TASK-5-14-15]:[324] - task run command:
sudo -u dolphinscheduler sh /tmp/dolphinscheduler/exec/process/3/5/14/15/5_14_15.command
[INFO] 2021-03-08 15:55:38.633  - [taskAppId=TASK-5-14-15]:[205] - process start, process id is: 69021
[INFO] 2021-03-08 15:55:40.859  - [taskAppId=TASK-5-14-15]:[127] -  -> 
[INFO] 2021-03-08 15:55:40.900  - [taskAppId=TASK-5-14-15]:[127] -  -> ------------------------------------------------------------
	 The program finished with the following exception:
	
	org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Properties file /tmp/dolphinscheduler/exec/process/3/5/14/15/sql.config does not exist
		at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:302)
		at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:198)
		at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:149)
		at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:699)
		at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:232)
		at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:916)
		at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:992)
		at java.security.AccessController.doPrivileged(Native Method)
		at javax.security.auth.Subject.doAs(Subject.java:422)
		at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1876)
		at org.apache.flink.runtime.security.contexts.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
		at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:992)
	Caused by: java.io.FileNotFoundException: Properties file /tmp/dolphinscheduler/exec/process/3/5/14/15/sql.config does not exist
		at org.apache.flink.api.java.utils.ParameterTool.fromPropertiesFile(ParameterTool.java:120)
		at org.apache.flink.api.java.utils.ParameterTool.fromPropertiesFile(ParameterTool.java:107)
		at com.data.finkttest.DdlJob.main(DdlJob.java:43)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:288)
		... 11 more
[INFO] 2021-03-08 15:55:40.902  - [taskAppId=TASK-5-14-15]:[214] - process has exited, execute path:/tmp/dolphinscheduler/exec/process/3/5/14/15, processId:69021 ,exitStatusCode:0
```

check files, /tmp/dolphinscheduler/exec/process/3/5/14 is empty dir
```
$ cd /tmp/dolphinscheduler/exec/process/3/5/14
$ ls
$ 
```
**Requirement or improvement**
- file "sql.config" exist  on hdfs.
- flink node Deploy Mode: local
-

**Comment by chengshiwen** [comment]
@HeChuanXUPT Maybe you should use `flink run -m 172.16.7.59:30081 -c com.data.finkttest.DdlJob test1/TestJob-1.0-SNAPSHOT-jar-with-dependencies.jar -config hdfs://xxxx/path/to/sql.config`

In other words, you should set `main args` to `-config hdfs://xxxx/path/to/sql.config` and the hdfs is supported

**Comment by HeChuanXUPT** [comment]
@chengshiwen  I want to manage "sql.config" in Resources. So, the Resources config of flink node, what is it used for ? And how it works?

**Comment by chengshiwen** [comment]
@HeChuanXUPT If you want to keep the command `flink run -m 172.16.7.59:30081 -c com.data.finkttest.DdlJob test1/TestJob-1.0-SNAPSHOT-jar-with-dependencies.jar -config sql.config`, it's better to place the `sql.config` in Resources. And then, you need to choose the resource `sql.config` in flink task panel and DolphinScheduler will download the resource `sql.config` into flink execution directory, so `sql.config` can be read.

**Comment by HeChuanXUPT** [comment]
@chengshiwen Thanks, I have solved the problem.  The `sql.config`  has been upload already, but it is under test1/CONF directory and I must have to config the full path in flink node instead of only filename.

> Main Arguments: -config sql.config

to

> Main Arguments: -config test1/CONF/sql.config

**Comment by chengshiwen** [comment]
@HeChuanXUPT Hi, since this issue has been solved, so could you close it? thx~
