### ISSUE TITLE
[Bug][API] org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[45]

### ISSUE THREAD

**Issue by gaoyu2016** [apache/dolphinscheduler#5237]
org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[45] - 创建用户错误
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.common.utils.HadoopUtils.exists(HadoopUtils.java:358)
	at org.apache.dolphinscheduler.api.service.UsersService.createUser(UsersService.java:128)
	at org.apache.dolphinscheduler.api.service.UsersService$$FastClassBySpringCGLIB$$e4fd56f5.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)

**Comment by gaoyu2016** [comment]
1.3.4 version

**Comment by ruanwenjun** [comment]
It seems that the file system has not initialized successfully, you need to provide more effective error log information about `HadoopUtils`. It is also suggested you to upgrade to the latest version.

**Comment by gaoyu2016** [comment]
日志就这些，没有别的了。
org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[45] - 创建用户错误
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.common.utils.HadoopUtils.exists(HadoopUtils.java:358)
	at org.apache.dolphinscheduler.api.service.UsersService.createUser(UsersService.java:128)
	at org.apache.dolphinscheduler.api.service.UsersService$$FastClassBySpringCGLIB$$e4fd56f5.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at org.apache.dolphinscheduler.api.service.UsersService$$EnhancerBySpringCGLIB$$7c5b6236.createUser(<generated>)
	at org.apache.dolphinscheduler.api.controller.UsersController.createUser(UsersController.java:90)
	at sun.reflect.GeneratedMethodAccessor321.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:867)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at com.github.xiaoymin.swaggerbootstrapui.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:84)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at com.github.xiaoymin.swaggerbootstrapui.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

**Comment by chengshiwen** [comment]
@gaoyu2016 Did you configure `resource.storage.type` to `HDFS` or `S3` in `conf/common.properties`?

**Comment by gaoyu2016** [comment]
resource.storage.type=HDFS
配置过了。这个1.3.1没出现过这个问题，升级到1.3.4就出现过了。

**Comment by chengshiwen** [comment]
@gaoyu2016 Could you show us the content of `conf/common.properties`?

**Comment by gaoyu2016** [comment]
```
# resource.storage.type=HDFS
resource.storage.type=HDFS

# resource store on HDFS/S3 path, resource file will store to this hadoop hdfs path, self configuration, please make sure the directory exists on hdfs and have read write permissions。"/dolphinscheduler" is recommended
resource.upload.path=/dolphinscheduler

# user data local directory path, please make sure the directory exists and have read write permissions
#data.basedir.path=/tmp/dolphinscheduler

# whether kerberos starts
hadoop.security.authentication.startup.state=false

# java.security.krb5.conf.path=/home/maintain/ds-1.3.4/conf/krb5.conf
java.security.krb5.conf.path=/home/maintain/ds-1.3.4/conf/krb5.conf

# login user from keytab username
login.user.keytab.username=hdfs-mycluster@ESZ.COM

# loginUserFromKeytab path
login.user.keytab.path=/home/maintain/ds-1.3.4/conf/hdfs.headless.keytab

#resource.view.suffixs
#resource.view.suffixs=txt,log,sh,conf,cfg,py,java,sql,hql,xml,properties

# if resource.storage.type=HDFS
hdfs.root.user=maintain

# if resource.storage.type=HDFS
fs.defaultFS=hdfs://hadooptest:8020

# if resource.storage.type=HDFS
fs.s3a.endpoint=http://192.168.xx.xx:9010

# if resource.storage.type=HDFS
fs.s3a.access.key=xxxxxxxxxx

# if resource.storage.type=HDFS
fs.s3a.secret.key=xxxxxxxxxx

# if resourcemanager HA enable, please type the HA ips ; if resourcemanager is single, make this value empty
yarn.resourcemanager.ha.rm.ids=alibjhtest-pipe-sata1-vm,alibjhtest-pipe-sata2-vm

# if resourcemanager HA enable or not use resourcemanager, please keep the default value; If resourcemanager is single, you only need to replace ds1 to actual resourcemanager hostname.
yarn.application.status.address=http://yarnIp1:8088/ws/v1/cluster/apps/%s

# system env path
dolphinscheduler.env.path=/home/maintain/ds-1.3.4/conf/env/dolphinscheduler_env.sh
development.state=false
kerberos.expire.time=7
```

**Comment by gaoyu2016** [comment]
不知道是什么原因？看源码也不好定位。

**Comment by ruanwenjun** [comment]
@gaoyu2016 Is your hadoop turned on kerberos? You can try to set `hadoop.security.authentication.startup.state=true`

**Comment by gaoyu2016** [comment]
集群目前没有打开kerberos。

**Comment by zhuangchong** [comment]
@gaoyu2016

The current exception information is related to HDFS, please confirm whether the HDFS related parameter values in common.properties are correct.

**Comment by gaoyu2016** [comment]
参数正确。

**Comment by BoYiZhang** [comment]
There is a problem with the HDFS connection

Check configuration file:

core-site.xml and hdfs-site.xml

**Comment by gaoyu2016** [comment]
目前官方也解决不了，看来是一个严重的bug。

**Comment by BoYiZhang** [comment]
It's not a bug

1.3.4 has been released for 2 months, and we haven't received any questions like you

You can use remote debug mode to verify what the problem is

**Comment by gaoyu2016** [comment]
hfds-site:
<configuration>
    <property>
        <name>dfs.namenode.name.dir</name>
        <value>/home/maintain/hadoop/hdfs-data/namenode</value>
        <description>Path on the local filesystem where the NameNode stores the namespace and transaction logs persistently.</description>
    </property>
    <property>
        <name>dfs.datanode.data.dir</name>
        <value>
            /disk1/hadoop/hdfs-data/datanode,
            /disk2/hadoop/hdfs-data/datanode,
            /disk3/hadoop/hdfs-data/datanode,
            /disk4/hadoop/hdfs-data/datanode,
            /disk5/hadoop/hdfs-data/datanode,
            /disk6/hadoop/hdfs-data/datanode,
            /disk7/hadoop/hdfs-data/datanode,
            /disk8/hadoop/hdfs-data/datanode,
            /disk9/hadoop/hdfs-data/datanode,
            /disk10/hadoop/hdfs-data/datanode,
            /disk11/hadoop/hdfs-data/datanode,
            /disk12/hadoop/hdfs-data/datanode
        </value>
        <description>Comma separated list of paths on the local filesystem of a DataNode where it should store its blocks.</description>
    </property>
    <property>
        <name>dfs.hosts</name>
        <value>/home/maintain/hadoop/hadoop/curr_hadoop/etc/hadoop/includes</value>
    </property>
    <property>
        <name>dfs.hosts.exclude</name>
        <value>/home/maintain/hadoop/hadoop/curr_hadoop/etc/hadoop/excludes</value>
    </property>
    <property>
        <name>dfs.nameservices</name>
        <value>hadooptest</value>
        <description> the logical name for this new nameservice </description>
    </property>
    <property>
        <name>dfs.ha.namenodes.hadooptest</name>
        <value>nn1,nn2</value>
    </property>
    <property>
        <name>dfs.namenode.rpc-address.hadooptest.nn1</name>
        <value>alibjhtest-pipe-datanode1-vm:8020</value>
    </property>
    <property>
        <name>dfs.namenode.rpc-address.hadooptest.nn2</name>
        <value>alibjhtest-pipe-datanode2-vm:8020</value>
    </property>
    <property>
        <name>dfs.namenode.http-address.hadooptest.nn1</name>
        <value>alibjhtest-pipe-datanode1-vm:50070</value>
    </property>
    <property>
        <name>dfs.namenode.http-address.hadooptest.nn2</name>
        <value>alibjhtest-pipe-datanode2-vm:50070</value>
    </property>
    <property>
        <name>dfs.namenode.shared.edits.dir</name>
        <value>qjournal://alibjhtest-pipe-datanode3-vm:8485;alibjhtest-pipe-datanode4-vm:8485;alibjhtest-pipe-datanode5-vm:8485/hadooptest</value>
    </property>
    <property>
        <name>dfs.client.failover.proxy.provider.hadooptest</name>
        <value>org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider</value>
    </property>
    <property>
        <name>dfs.ha.fencing.methods</name>
        <value>sshfence</value>
    </property>
    <property>
        <name>dfs.ha.fencing.ssh.private-key-files</name>
        <value>/home/maintain/.ssh/authorized_keys</value>
    </property>
    <property>
        <name>dfs.journalnode.edits.dir</name>
        <value>/home/maintain/hadoop/hdfs-data/jn-nodes</value>
    </property>
    <property>
        <name>dfs.ha.automatic-failover.enabled</name>
        <value>true</value>
    </property>
    <property>
        <name>dfs.balance.bandwidthPerSec</name>
        <value>1048576</value>
    </property>
    <property>
        <name>dfs.webhdfs.enabled</name>
        <value>true</value>
    </property>
    <property>
        <name>dfs.support.append</name>
        <value>true</value>
    </property>
    <property>
        <name>dfs.datanode.fsdataset.volume.choosing.policy</name>
        <value>org.apache.hadoop.hdfs.server.datanode.fsdataset.AvailableSpaceVolumeChoosingPolicy</value>
    </property>
    <property>
        <name>dfs.namenode.handler.count</name>
        <value>10</value>
    </property>
    <property>
        <name>dfs.datanode.handler.count</name>
        <value>10</value>
    </property>
    <property>
        <name>ipc.server.read.threadpool.size</name>
        <value>10</value>
    </property>
    <property>
        <name>dfs.namenode.fs-limits.max-directory-items</name>
        <value>100</value>
    </property>
</configuration>

**Comment by gaoyu2016** [comment]
core-site:
<configuration>
    <property>
        <name>fs.defaultFS</name>
        <value>hdfs://hadooptest</value>
        <description>NameNode URI</description>
    </property>
    <property>
        <name>hadoop.tmp.dir</name>
        <value>/home/maintain/hadoop/tmp/hadoop/hadoop-${user.name}</value>
        <description>A base for other temporary directorise</description>
    </property>
    <property>
        <name>hadoop.proxyuser.maintain.hosts</name>
        <value>*</value>
    </property>
    <property>
        <name>hadoop.proxyuser.maintain.groups</name>
        <value>*</value>
    </property>
    <property>
        <name>ha.zookeeper.quorum</name>
        <value>alibjhtest-pipe-datanode3-vm:2181,alibjhtest-pipe-datanode4-vm:2181,alibjhtest-pipe-datanode5-vm:2181</value>
    </property>
    <property>
        <name>ha.zookeeper.session-timeout.ms</name>
        <value>180000</value>
    </property>
    <property>
        <name>ha.health-monitor.rpc-timeout.ms</name>
        <value>600000</value>
    </property>
    <property>
        <name>fs.trash.interval</name>
        <value>1440</value>
        <description>Number of minutes between trash checkpoints. If zero, the trash feature is disabled</description>
    </property>
    <property>
        <name>hadoop.http.filter.initializers</name>
        <value>org.apache.hadoop.security.HttpCrossOriginFilterInitializer</value>
    </property>
    <property>
        <name>io.file.buffer.size</name>
        <value>65536</value>
    </property>
    <property>
        <name>ipc.server.listen.queue.size</name>
        <value>65536</value>
        <description>Indicates the length of the listen queue for servers accepting client connections.</description>
    </property>
    <property>
        <name>io.compression.codecs</name>
        <value>
            org.apache.hadoop.io.compress.GzipCodec,
            org.apache.hadoop.io.compress.DefaultCodec,
            org.apache.hadoop.io.compress.BZip2Codec,
            org.apache.hadoop.io.compress.SnappyCodec
        </value>
    </property>
    <property>
	<name>ha.failover-controller.graceful-fence.rpc-timeout.ms</name>
	<value>20000</value>
   </property>
   <property>
	<name>ha.failover-controller.new-active.rpc-timeout.ms</name>
	<value>120000</value>
   </property>
   <property>
	<name>ha.failover-controller.graceful-fence.connection.retries</name>
	<value>2</value>
   </property>
</configuration>

**Comment by gaoyu2016** [comment]
配置文件没有任何问题。

**Comment by gaoyu2016** [comment]
how to use remote debug mode？

**Comment by gaoyu2016** [comment]
[ERROR] 2021-04-14 18:02:07.078 org.apache.dolphinscheduler.common.utils.HadoopUtils:[102] - null
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.common.utils.HadoopUtils.initHdfsPath(HadoopUtils.java:98)

**Comment by gaoyu2016** [comment]
[ERROR] 2021-04-14 18:52:09.020 org.apache.dolphinscheduler.common.utils.HadoopUtils:[172] - java.net.UnknownHostException: hadooptest
java.lang.IllegalArgumentException: java.net.UnknownHostException: hadooptest
	at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:378)
	at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:310)
	at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:176)

**Comment by gaoyu2016** [comment]
[ERROR] 2021-04-14 18:52:09.020 org.apache.dolphinscheduler.common.utils.HadoopUtils:[172] - java.net.UnknownHostException: hadooptest
java.lang.IllegalArgumentException: java.net.UnknownHostException: hadooptest
	at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:378)
	at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:310)
	at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:176)
