### ISSUE TITLE
[Bug][Flink] Flink Job can't stop on the web

### ISSUE THREAD

**Issue by gaogao110** [apache/dolphinscheduler#5398]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**
Flink Job can't stop on the web

**To Reproduce**
Steps to reproduce the behavior, for example:
1. start a flink task  and  flink task is running
2. Click on 'stop'
3. But the task did not stop
4. See worker log error :
kill -9 null 

details
`[INFO] 2021-04-26 19:21:00.192 org.apache.dolphinscheduler.server.worker.processor.TaskKillProcessor:[87] - received kill command : TaskKillRequestCommand{taskInstanceId=40}
[INFO] 2021-04-26 19:21:00.481 org.apache.dolphinscheduler.server.worker.processor.TaskKillProcessor:[120] - process id:12268, cmd:sudo kill -9
[ERROR] 2021-04-26 19:21:00.572 org.apache.dolphinscheduler.server.worker.processor.TaskKillProcessor:[132] - kill task error
org.apache.dolphinscheduler.common.shell.AbstractShell$ExitCodeException:
Usage:
 kill [options] <pid|name> [...]

Options:
 -a, --all              do not restrict the name-to-pid conversion to processes
                        with the same uid as the present process
 -s, --signal <sig>     send specified signal
 -q, --queue <sig>      use sigqueue(2) rather than kill(2)
 -p, --pid              print pids without signaling them
 -l, --list [=<signal>] list signal names, or convert one to a name
 -L, --table            list signal names and numbers

 -h, --help     display this help and exit
 -V, --version  output version information and exit

For more details see kill(1).

        at org.apache.dolphinscheduler.common.shell.AbstractShell.runCommand(AbstractShell.java:209)
        at org.apache.dolphinscheduler.common.shell.AbstractShell.run(AbstractShell.java:124)
`

**There is no non-null validation in the code**

**Expected behavior**
fix bug

**Which version of Dolphin Scheduler:**
 -[1.3.5]

**Comment by gaogao110** [comment]
I see this fixed in version 1.3.6
