### ISSUE TITLE
Can't get Kerberos realm

### ISSUE THREAD

**Issue by gaozhenfeng1** [apache/dolphinscheduler#5403]
I am using a big data platform with kerberos enabled and downloaded the client to my node，I configured these files according to the official website：common.properties，install_config.conf.
But the problem is:I can use the shell on the node to call my components normally,but using dolphinscheduler can not call.
Keep reporting this error : Can't get Kerberos realm.
How should I do？

**Comment by gaozhenfeng1** [comment]
[INFO] 2021-04-28 11:39:20.031  - [taskAppId=TASK-4-11-11]:[121] -  -> find: ‘/opt/apps/client/’: No such file or directory
	WARNING: Use "yarn jar" to launch YARN applications.
	java.lang.IllegalArgumentException: Can't get Kerberos realm
[INFO] 2021-04-28 11:39:20.074  - [taskAppId=TASK-4-11-11]:[121] -  -> 	at org.apache.hadoop.security.HadoopKerberosName.setConfiguration(HadoopKerberosName.java:65)
		at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:329)
		at org.apache.hadoop.security.UserGroupInformation.ensureInitialized(UserGroupInformation.java:314)
		at org.apache.hadoop.security.UserGroupInformation.doSubjectLogin(UserGroupInformation.java:1973)
		at org.apache.hadoop.security.UserGroupInformation.createLoginUser(UserGroupInformation.java:743)
		at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:693)
		at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:604)
		at org.apache.hadoop.mapreduce.task.JobContextImpl.<init>(JobContextImpl.java:72)
		at org.apache.hadoop.mapreduce.Job.<init>(Job.java:150)
		at org.apache.hadoop.mapreduce.Job.getInstance(Job.java:193)
		at org.apache.hadoop.mapreduce.Job.getInstance(Job.java:212)
		at org.apache.hadoop.examples.WordCount.main(WordCount.java:75)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:71)
		at org.apache.hadoop.util.ProgramDriver.run(ProgramDriver.java:144)
		at org.apache.hadoop.examples.ExampleDriver.main(ExampleDriver.java:74)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.hadoop.util.RunJar.run(RunJar.java:313)
		at org.apache.hadoop.util.RunJar.main(RunJar.java:227)
	Caused by: java.lang.reflect.InvocationTargetException
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.hadoop.security.authentication.util.KerberosUtil.getDefaultRealm(KerberosUtil.java:110)
		at org.apache.hadoop.security.HadoopKerberosName.setConfiguration(HadoopKerberosName.java:63)
		... 24 more
	Caused by: KrbException: Cannot locate default realm
		at sun.security.krb5.Config.getDefaultRealm(Config.java:1029)
		... 30 more
