### ISSUE TITLE
[Question] Can not access dolphinscheduler ui

### ISSUE THREAD

**Issue by zainal-abidin-assegaf** [apache/dolphinscheduler#5414]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
Can not access dolphinscheduler ui

![image](https://user-images.githubusercontent.com/22811935/116765881-ca6ac580-aa51-11eb-912f-0a18a18e2814.png)

**Which version of DolphinScheduler:**
v1.3.6

**Additional context**
DB postgressql:

![image](https://user-images.githubusercontent.com/22811935/116765922-03a33580-aa52-11eb-81be-1510bb35c796.png)

**Requirement or improvement**
Can not acces dolphinscheduler via:
- admin/7ad2410b2f4c074479a8937a28a22b8f
- admin/dolphinscheduler123

Please help, thank you.

**Comment by chengshiwen** [comment]
@4ss3g4f `user_password` is a field encrypted by md5, and `dolphinscheduler123` is the correct password. Please delete the row where `id=34` and check whether it is entered correctly?  You can copy and paste it and try again.  If the error still exists, please let us know the api log and the more details

**Comment by zainal-abidin-assegaf** [comment]
API logs:

```
[ERROR] 2021-05-01 13:10:27.762 com.alibaba.druid.pool.DruidDataSource:[2572] - create connection SQLException, url: jdbc:postgresql://10.100.234.124:5432/dolphinscheduler?characterEncoding=utf8, errorCode 0, state 08P01
org.postgresql.util.PSQLException: ERROR: no such user
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:438)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
	at org.postgresql.Driver.makeConnection(Driver.java:450)
	at org.postgresql.Driver.connect(Driver.java:252)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1578)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1644)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2570)
```

Seems like can not connect to postgres,
![image](https://user-images.githubusercontent.com/22811935/116773164-fef47680-aa7d-11eb-9870-c88a4f162a9f.png)

We have delete `id=34` from t_ds_user table, but still same error,
We used crunchydata postgres, should be no issue rught, any postgres implementation shoud work right ?? 

![image](https://user-images.githubusercontent.com/22811935/116773528-e71df200-aa7f-11eb-8b51-38fbd0ee57bd.png)

What is the problem, please help ??

**Comment by chengshiwen** [comment]
It seems that the error is `no such user`, did you created the db and user successfully?

**Comment by zainal-abidin-assegaf** [comment]
Yes, we already restored dolphinscheduler postgres sql file, and user admin has been created  and available at t_ds_user table, as you see from above screenshot

**Comment by chengshiwen** [comment]
Are all database environment variebles in docker-compose.yaml modified? Could you show us the content of the file?

**Comment by chengshiwen** [comment]
It seems that you used 1.3.5 version of docker-compose.yaml, but the 1.3.6 docker image is used. To solve the problem, replace apache/dolphinscheduler:latest with apache/dolphinscheduler:1.3.5 in docker-compose.yaml.
Or just use the latest 1.3.6 of docker-compose.yaml

Please refer to FAQ
1.3.5: https://dolphinscheduler.apache.org/zh-cn/docs/1.3.5/user_doc/docker-deployment.html
1.3.6 : https://dolphinscheduler.apache.org/zh-cn/docs/1.3.6/user_doc/docker-deployment.html

**Comment by zainal-abidin-assegaf** [comment]
here is the compose yaml file:

```
version: '3.7'

networks:
  bridge:
    external: true

services:

  dolphinscheduler-api:
    image: apache/dolphinscheduler:1.3.5
    command: api-server
    ports:
      - 12345:12345
    environment:
      TZ: Asia/Jakarta
      DOLPHINSCHEDULER_OPTS: "-Xms512m -Xmx512m -Xmn256m"
      DATABASE_TYPE: postgresql
      DATABASE_DRIVER: org.postgresql.Driver
      DATABASE_HOST: 10.100.234.124
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: QiLw{vZlFy7GEs3cVch-+5oU
      DATABASE_DATABASE: dolphinscheduler
      DATABASE_PARAMS: characterEncoding=utf8
      ZOOKEEPER_QUORUM: 10.100.151.100:2181
      RESOURCE_STORAGE_TYPE: HDFS
      RESOURCE_UPLOAD_PATH: /dolphinscheduler
      FS_DEFAULT_FS: file:///
    healthcheck:
      test: ["CMD", "/root/checkpoint.sh", "ApiApplicationServer"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - /home/core/dolphinscheduler/dolphinscheduler-logs:/opt/dolphinscheduler/logs
    networks:
      - bridge
    deploy:
      mode: replicated
      replicas: 1

  dolphinscheduler-alert:
    image: apache/dolphinscheduler:1.3.5
    command: alert-server
    ports:
      - 50052:50052
    environment:
      TZ: Asia/Jakarta
      ALERT_PLUGIN_DIR: lib/plugin/alert
      DOLPHINSCHEDULER_OPTS: "-Xms512m -Xmx512m -Xmn256m"
      DATABASE_TYPE: postgresql
      DATABASE_DRIVER: org.postgresql.Driver
      DATABASE_HOST: 10.100.234.124
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: QiLw{vZlFy7GEs3cVch-+5oU
      DATABASE_DATABASE: dolphinscheduler
      DATABASE_PARAMS: characterEncoding=utf8
    healthcheck:
      test: ["CMD", "/root/checkpoint.sh", "AlertServer"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - /home/core/dolphinscheduler/dolphinscheduler-logs:/opt/dolphinscheduler/logs
    networks:
      - bridge
    deploy:
      mode: replicated
      replicas: 1

  dolphinscheduler-master:
    image: apache/dolphinscheduler:1.3.5
    command: master-server
    ports:
      - 5678:5678
    environment:
      TZ: Asia/Jakarta
      MASTER_EXEC_THREADS: "100"
      MASTER_EXEC_TASK_NUM: "20"
      MASTER_HEARTBEAT_INTERVAL: "10"
      MASTER_TASK_COMMIT_RETRYTIMES: "5"
      MASTER_TASK_COMMIT_INTERVAL: "1000"
      MASTER_MAX_CPULOAD_AVG: "100"
      MASTER_RESERVED_MEMORY: "0.1"
      DOLPHINSCHEDULER_DATA_BASEDIR_PATH: /tmp/dolphinscheduler
      DOLPHINSCHEDULER_OPTS: "-Xms1g -Xmx1g -Xmn512m"
      DATABASE_TYPE: postgresql
      DATABASE_DRIVER: org.postgresql.Driver
      DATABASE_HOST: 10.100.234.124
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: QiLw{vZlFy7GEs3cVch-+5oU
      DATABASE_DATABASE: dolphinscheduler
      DATABASE_PARAMS: characterEncoding=utf8
      ZOOKEEPER_QUORUM: 10.100.151.100:2181
    healthcheck:
      test: ["CMD", "/root/checkpoint.sh", "MasterServer"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - /home/core/dolphinscheduler/dolphinscheduler-logs:/opt/dolphinscheduler/logs
    networks:
      - bridge
    deploy:
      mode: replicated
      replicas: 1

  dolphinscheduler-worker:
    image: apache/dolphinscheduler:1.3.5
    command: worker-server
    ports:
      - 1234:1234
      - 50051:50051
    environment:
      TZ: Asia/Jakarta
      WORKER_EXEC_THREADS: "100"
      WORKER_HEARTBEAT_INTERVAL: "10"
      WORKER_MAX_CPULOAD_AVG: "100"
      WORKER_RESERVED_MEMORY: "0.1"
      WORKER_GROUPS: "default"
      WORKER_HOST_WEIGHT: "100"
      ALERT_LISTEN_HOST: dolphinscheduler-alert
      HADOOP_HOME: "/opt/soft/hadoop"
      HADOOP_CONF_DIR: "/opt/soft/hadoop/etc/hadoop"
      SPARK_HOME1: "/opt/soft/spark1"
      SPARK_HOME2: "/opt/soft/spark2"
      #PYTHON_HOME: "/opt/soft/python"
      JAVA_HOME: "/usr/local/openjdk-8"
      HIVE_HOME: "/opt/soft/hive"
      FLINK_HOME: "/opt/soft/flink"
      DATAX_HOME: "/opt/soft/datax"
      DOLPHINSCHEDULER_DATA_BASEDIR_PATH: /tmp/dolphinscheduler
      DOLPHINSCHEDULER_OPTS: "-Xms1g -Xmx1g -Xmn512m"
      DATABASE_TYPE: postgresql
      DATABASE_DRIVER: org.postgresql.Driver
      DATABASE_HOST: 10.100.234.124
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: QiLw{vZlFy7GEs3cVch-+5oU
      DATABASE_DATABASE: dolphinscheduler
      DATABASE_PARAMS: characterEncoding=utf8
      ZOOKEEPER_QUORUM: 10.100.151.100:2181
      RESOURCE_STORAGE_TYPE: HDFS
      RESOURCE_UPLOAD_PATH: /dolphinscheduler
      FS_DEFAULT_FS: file:///
    healthcheck:
      test: ["CMD", "/root/checkpoint.sh", "WorkerServer"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - /home/core/dolphinscheduler/dolphinscheduler-worker-data:/tmp/dolphinscheduler
      - /home/core/dolphinscheduler/dolphinscheduler-logs:/opt/dolphinscheduler/logs
    networks:
      - bridge
    deploy:
      mode: replicated
      replicas: 1
```
dolphinscheduler-alert:
```
init env variables
generate app config
test postgresql service
nnect postgresql service
psql: ERROR:  no such user
```

dolphinscheduler-api logs:
```
init env variables
generate app config
connect remote zookeeper
test postgresql service
nnect postgresql service
psql: ERROR:  no such user
```

dolphinscheduler-master logs:
```
init env variables
generate app config
connect remote zookeeper
test postgresql service
nnect postgresql service
psql: ERROR:  no such user
```

dolphinscheduler-worker logs:
```
init env variables
generate app config
connect remote zookeeper
test postgresql service
nnect postgresql service
psql: ERROR:  no such user
```

**Comment by zainal-abidin-assegaf** [comment]
Used 1.3.6:

```
version: '3.7'

networks:
  bridge:
    external: true

services:

  dolphinscheduler-api:
    image: apache/dolphinscheduler:latest
    command: api-server
    networks:
      - bridge
    ports:
      - 12345:12345
    environment:
      TZ: Asia/Jakarta
    env_file: /home/core/dolphinscheduler/config.env.sh
    healthcheck:
      test: ["CMD", "/root/checkpoint.sh", "ApiApplicationServer"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - /home/core/dolphinscheduler/dolphinscheduler-logs:/opt/dolphinscheduler/logs
      - /home/core/dolphinscheduler/dolphinscheduler-shared-local:/opt/soft
      - /home/core/dolphinscheduler/dolphinscheduler-resource-local:/dolphinscheduler
    deploy:
      mode: replicated
      replicas: 1

  dolphinscheduler-alert:
    image: apache/dolphinscheduler:latest
    command: alert-server
    networks:
      - bridge
    environment:
      TZ: Asia/Jakarta
    env_file: /home/core/dolphinscheduler/config.env.sh
    healthcheck:
      test: ["CMD", "/root/checkpoint.sh", "AlertServer"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - /home/core/dolphinscheduler/dolphinscheduler-logs:/opt/dolphinscheduler/logs
    deploy:
      mode: replicated
      replicas: 1

  dolphinscheduler-master:
    image: apache/dolphinscheduler:latest
    command: master-server
    networks:
      - bridge
    environment:
      TZ: Asia/Jakarta
    env_file: /home/core/dolphinscheduler/config.env.sh
    healthcheck:
      test: ["CMD", "/root/checkpoint.sh", "MasterServer"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - /home/core/dolphinscheduler/dolphinscheduler-logs:/opt/dolphinscheduler/logs
      - /home/core/dolphinscheduler/dolphinscheduler-shared-local:/opt/soft
    deploy:
      mode: replicated
      replicas: 1

  dolphinscheduler-worker:
    image: apache/dolphinscheduler:latest
    command: worker-server
    networks:
      - bridge
    environment:
      TZ: Asia/Jakarta
    env_file: /home/core/dolphinscheduler/config.env.sh
    healthcheck:
      test: ["CMD", "/root/checkpoint.sh", "WorkerServer"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - /home/core/dolphinscheduler/dolphinscheduler-worker-data:/tmp/dolphinscheduler
      - /home/core/dolphinscheduler/dolphinscheduler-logs:/opt/dolphinscheduler/logs
      - /home/core/dolphinscheduler/dolphinscheduler-shared-local:/opt/soft
      - /home/core/dolphinscheduler/dolphinscheduler-resource-local:/dolphinscheduler
    deploy:
      mode: replicated
      replicas: 1
```
api logs:


```
Actions

      

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)


	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


	at java.lang.reflect.Method.invoke(Method.java:498)


	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)


	... 89 common frames omitted


Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is org.postgresql.util.PSQLException: ERROR: no such user


	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:82)


	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:80)


	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:67)


	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:336)


	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.prepareStatement(MybatisSimpleExecutor.java:93)


	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doQuery(MybatisSimpleExecutor.java:66)


	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)


	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)


	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:136)


	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)


	... 96 common frames omitted


Caused by: org.postgresql.util.PSQLException: ERROR: no such user


	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:438)


	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222)


	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)


	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)


	at org.postgresql.Driver.makeConnection(Driver.java:450)


	at org.postgresql.Driver.connect(Driver.java:252)


	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1578)


	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1644)


	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:918)


	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1300)


	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1296)


	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:109)


	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)


	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)


	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)


	... 105 common frames omitted


[ERROR] 2021-05-01 22:49:19.881 org.postgresql.Driver:[261] - Connection error: 


org.postgresql.util.PSQLException: ERROR: no such user


	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:438)


	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222)


	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)


	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)


	at org.postgresql.Driver.makeConnection(Driver.java:450)


	at org.postgresql.Driver.connect(Driver.java:252)


	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1578)


	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1644)


	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2570)


[ERROR] 2021-05-01 22:49:19.882 com.alibaba.druid.pool.DruidDataSource:[2572] - create connection SQLException, url: jdbc:postgresql://10.100.234.124:5432/dolphinscheduler?characterEncoding=utf8, errorCode 0, state 08P01


org.postgresql.util.PSQLException: ERROR: no such user


	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:438)


	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222)


	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)


	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)


	at org.postgresql.Driver.makeConnection(Driver.java:450)


	at org.postgresql.Driver.connect(Driver.java:252)


	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1578)


	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1644)


	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2570)


[ERROR] 2021-05-01 22:49:19.911 org.postgresql.Driver:[261] - Connection error: 


org.postgresql.util.PSQLException: ERROR: no such user


	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:438)


	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222)


	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)


	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)


	at org.postgresql.Driver.makeConnection(Driver.java:450)


	at org.postgresql.Driver.connect(Driver.java:252)


	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1578)


	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1644)


	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2570)


[ERROR] 2021-05-01 22:49:19.912 com.alibaba.druid.pool.DruidDataSource:[2572] - create connection SQLException, url: jdbc:postgresql://10.100.234.124:5432/dolphinscheduler?characterEncoding=utf8, errorCode 0, state 08P01


org.postgresql.util.PSQLException: ERROR: no such user


	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:438)


	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222)


	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)


	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)


	at org.postgresql.Driver.makeConnection(Driver.java:450)


	at org.postgresql.Driver.connect(Driver.java:252)


	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1578)


	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1644)


	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2570)


[ERROR] 2021-05-01 22:50:19.939 org.postgresql.Driver:[261] - Connection error: 


org.postgresql.util.PSQLException: ERROR: no such user


	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:438)


	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222)


	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)


	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)


	at org.postgresql.Driver.makeConnection(Driver.java:450)


	at org.postgresql.Driver.connect(Driver.java:252)


	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1578)


	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1644)


	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2570)


[ERROR] 2021-05-01 22:50:19.940 com.alibaba.druid.pool.DruidDataSource:[2572] - create connection SQLException, url: jdbc:postgresql://10.100.234.124:5432/dolphinscheduler?characterEncoding=utf8, errorCode 0, state 08P01


org.postgresql.util.PSQLException: ERROR: no such user


	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:438)


	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222)


	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)


	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)


	at org.postgresql.Driver.makeConnection(Driver.java:450)


	at org.postgresql.Driver.connect(Driver.java:252)


	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1578)


	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1644)


	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2570)
```

**Comment by chengshiwen** [comment]
@4ss3g4f Hi, it seems the postgresql connection problem. Could you check the command in Terminal on some host with `psql`?
```bash
PGPASSWORD=${DATABASE_PASSWORD} psql -h ${DATABASE_HOST} -p ${DATABASE_PORT} -U ${DATABASE_USERNAME} -d ${DATABASE_DATABASE} -tAc "select 1"
```
eg.
```bash
PGPASSWORD=QiLw{vZlFy7GEs3cVch-+5oU psql -h 10.100.234.124 -p 5432 -U postgres -d dolphinscheduler -tAc "select 1"
PGPASSWORD=QiLw{vZlFy7GEs3cVch-+5oU psql -h 10.100.234.124 -p 5432 -U postgres -d dolphinscheduler -tAc "SELECT * FROM public.t_ds_user"
```

**Comment by zainal-abidin-assegaf** [comment]
We can access now, it's postgres connection issue,

![image](https://user-images.githubusercontent.com/22811935/116805556-7e9f4580-ab51-11eb-8349-8c9977be3160.png)

Thank you
