### ISSUE TITLE
[Bug][Master] NPE occurs in complement operation

### ISSUE THREAD

**Issue by caoping6** [apache/dolphinscheduler#5496]
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.server.master.runner.MasterExecThread.executeComplementProcess(MasterExecThread.java:336) ~[classes/:na]
	at org.apache.dolphinscheduler.server.master.runner.MasterExecThread.run(MasterExecThread.java:219) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_291]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_291]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_291]

复线步骤：
1、运行时点击补数
2、调度日期选择多天，至少俩天
3、然后点运行
4、master节点报npe，如上

排查发现：
问题出现在MasterExecThread： 470行
这里查询完后导致processDefinition属性变为null。后面使用时报npe了
![image](https://user-images.githubusercontent.com/40586262/118631390-064bac00-b802-11eb-9c4c-02f8f710cd94.png)

branch: [dev]

**Comment by ruanwenjun** [comment]
@caoping6 Could you please provide more information?

**Comment by ruanwenjun** [comment]
@caoping6 Are you sure the version is 1.3.6-release?

**Comment by caoping6** [comment]
Sorry,It was discovered in dev

**Comment by ruanwenjun** [comment]
@caoping6 If you are sure this is a Bug, I think you can try to submit a pr to resolve 👍
