### ISSUE TITLE
START_FAILURE_TASK_PROCESS failed

### ISSUE THREAD

**Issue by Irving0689** [apache/dolphinscheduler#5522]
[INFO] 2021-05-19 10:06:26.147 org.apache.dolphinscheduler.api.controller.ProcessInstanceController:[101] - query all process instance list, login user:xxxxxx,project name:xxxxx, define id:0,search value:DAG_STG.STG_DMS_ORG,executor name:,state type:null,host:,start time:, end time:,page number:1, page size:50
[INFO] 2021-05-19 10:06:44.835 org.apache.dolphinscheduler.api.controller.ExecutorController:[151] - execute command, login user: xxxxxx, project:xxxxx, process instance id:26791, execute type:START_FAILURE_TASK_PROCESS
[ERROR] 2021-05-19 10:06:44.851 org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[45] - 操作工作流实例错误
java.lang.NullPointerException: null
at org.apache.dolphinscheduler.service.process.ProcessService.verifyIsNeedCreateCommand(ProcessService.java:215)
at org.apache.dolphinscheduler.service.process.ProcessService$$FastClassBySpringCGLIB$$ed138739.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
at org.apache.dolphinscheduler.service.process.ProcessService$$EnhancerBySpringCGLIB$$b9f88f81.verifyIsNeedCreateCommand(<generated>)
at org.apache.dolphinscheduler.api.service.ExecutorService.insertCommand(ExecutorService.java:376)
at org.apache.dolphinscheduler.api.service.ExecutorService.execute(ExecutorService.java:251)
at org.apache.dolphinscheduler.api.controller.ExecutorController.execute(ExecutorController.java:153)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
at jav

**Comment by Irving0689** [comment]
Failed to handle the workflow instance。

启动失败的任务失败，提示操作工作流实例失败

**Comment by CalvinKirs** [comment]
Which version?

**Comment by Irving0689** [comment]
> Which version?

1.3.6

**Comment by CalvinKirs** [comment]
> > Which version?
> 
> 1.3.6

Whether the processInstanceId is null in the command_param json outbound in the command table.

**Comment by CalvinKirs** [comment]
> > Which version?
> 
> 1.3.6
Whether the processInstanceId is null in the command_param json outbound in the command table.
Whether the processInstanceId is null in the command_param json outbound in the command table.

**Comment by Irving0689** [comment]
> > > Which version?
> > 
> > 
> > 1.3.6
> 
> Whether the processInstanceId is null in the command_param json outbound in the command table.

i'll check it.

**Comment by Irving0689** [comment]
> > > > Which version?
> > > 
> > > 
> > > 1.3.6
> > 
> > 
> > Whether the processInstanceId is null in the command_param json outbound in the command table.
> 
> i'll check it.

How should i to confirm this information？ 

select id from t_ds_process_definition where name like 'DAG_SPT.SPT_ODS_O_BILL_INFO%';

select * from t_ds_command where id = 226;

ruslut is NULL.

**Comment by Irving0689** [comment]
> > > > Which version?
> > > 
> > > 
> > > 1.3.6
> > 
> > 
> > Whether the processInstanceId is null in the command_param json outbound in the command table.
> 
> i'll check it.

How should i to check this information？

select id from t_ds_process_definition where name like 'DAG_SPT.SPT_ODS_O_BILL_INFO%';

select * from t_ds_command where id = 226;

ruslut is NULL.

**Comment by Irving0689** [comment]
> > > > Which version?
> > > 
> > > 
> > > 1.3.6
> > 
> > 
> > Whether the processInstanceId is null in the command_param json outbound in the command table.
> 
> i'll check it.

How should i to check this information？

select id from t_ds_process_definition where name like 'DAG_SPT.SPT_ODS_O_BILL_INFO%';

select * from t_ds_command where id = 226;

the result of the query is NULL.

**Comment by Tandoy** [comment]
@Irving0689 Hello, is there any progress on this issue, I also encountered it.
