### ISSUE TITLE
[Bug][worker] shell task can not run java command when develop.mode is false

### ISSUE THREAD

**Issue by cyx-code** [apache/dolphinscheduler#5524]
**Describe the bug**
When shell task's rawscript is 
"nohup java -version > /tmp/a.log &
while read line
do
    echo $line
done < /tmp/a.log"
and development.state=false
the a.log's content is "Error occurred during initialization of VM
	java.lang.Error: Properties init: Could not determine current working directory.
	at java.lang.System.initProperties(Native Method)
	at java.lang.System.initializeSystemClass(System.java:1168)"

**Which version of Dolphin Scheduler:**
 -[1.3.5-release]

**Requirement or improvement**
The cause of the error is that the execution directory has been deleted.

**Comment by cyx-code** [comment]
I found that delaying the deletion of the execution directory can solve this problem
