### ISSUE TITLE
[Bug][Master Server] Master Server was shutdown  but the process still in system

### ISSUE THREAD

**Issue by choucmei** [apache/dolphinscheduler#5559]
Master Server was shutdown  but the process still in system when i restart zookeeper cluster 
version:1.3.6
1.stop all the zookeeper servers , then start.
2. use jps command,will find the Master Server process
3. the dolphinscheduler-master log:
scheduler DolphinScheduler_$_slave.. shutdown complete.
Quartz service stopped, and halt all task
Quartz service stopped

**Comment by ruanwenjun** [comment]
@choucmei There should be a thread that did not exit, can you find out ?

**Comment by choucmei** [comment]
> @choucmei There should be a thread that did not exit, can you find out ?
I found some thread running,but i think the major promblem is ServerNodeManagerExecutor_1. 

```
"ServerNodeManagerExecutor_1" #97 daemon prio=5 os_prio=0 tid=0x00002ba94dab8800 nid=0x3e7 waiting on condition [0x00002baaec88f000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000741348bb0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by ruanwenjun** [comment]
@choucmei Great, there are a thread pool `executorService` in `ServerNodeManager` that doesn't close, can you submit a pr to fix it ?

**Comment by choucmei** [comment]
> @choucmei Great, there are a thread pool `executorService` in `ServerNodeManager` that doesn't close, can you submit a pr to fix it ?

yes,i can.
it will be my pleasure.
