### ISSUE TITLE
[Question] Load registry Plugin Failed !

### ISSUE THREAD

**Issue by docming** [apache/dolphinscheduler#5643]
**According to the official website developer tutorial, it seems that there is a problem with the reference address of registry plugin and POM**
 

> the following is the exception.

`Exception in thread "Master-Server" org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'masterServer': Unsatisfied dependency expressed through field 'masterRegistryClient'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'masterRegistryClient': Invocation of init method failed; nested exception is java.lang.RuntimeException: Load registry Plugin Failed !
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:598)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:376)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1402)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:591)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:866)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	at org.apache.dolphinscheduler.server.master.MasterServer.main(MasterServer.java:102)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'masterRegistryClient': Invocation of init method failed; nested exception is java.lang.RuntimeException: Load registry Plugin Failed !
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:413)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1761)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1196)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:595)
	... 17 more
Caused by: java.lang.RuntimeException: Load registry Plugin Failed !
	at org.apache.dolphinscheduler.service.registry.RegistryCenter.installRegistryPlugin(RegistryCenter.java:140)
	at org.apache.dolphinscheduler.service.registry.RegistryCenter.init(RegistryCenter.java:102)
	at org.apache.dolphinscheduler.server.master.registry.MasterRegistryClient.init(MasterRegistryClient.java:342)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	... 29 more
Caused by: java.lang.RuntimeException: Error loading pom: D:\dolphin\dolphinscheduler\dolphinscheduler-registry-plugin\dolphinscheduler-registry-zookeeper\pom.xml
	at io.airlift.resolver.ArtifactResolver.getMavenProject(ArtifactResolver.java:181)
	at io.airlift.resolver.ArtifactResolver.resolvePom(ArtifactResolver.java:131)
	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginLoader.buildPluginClassLoaderFromPom(DolphinPluginLoader.java:132)
	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginLoader.buildPluginClassLoader(DolphinPluginLoader.java:121)
	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginLoader.loadPlugin(DolphinPluginLoader.java:97)
	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginLoader.loadPlugins(DolphinPluginLoader.java:90)
	at org.apache.dolphinscheduler.service.registry.RegistryCenter.installRegistryPlugin(RegistryCenter.java:138)
	... 38 more
Caused by: org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.1.18.RELEASE from/to central (http://repo.maven.apache.org/maven2): Failed to transfer http://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.1.18.RELEASE/spring-boot-starter-parent-2.1.18.RELEASE.pom. Error code 501, HTTPS Required @ org.apache.dolphinscheduler:dolphinscheduler:1.3.6-SNAPSHOT, D:\dolphin\dolphinscheduler\pom.xml, line 165, column 25

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:176)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:102)
	at io.airlift.resolver.ArtifactResolver.getMavenProject(ArtifactResolver.java:177)
	... 44 more
Caused by: org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model for org.apache.dolphinscheduler:dolphinscheduler-registry-zookeeper:1.3.6-SNAPSHOT
[ERROR] Non-resolvable import POM: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.1.18.RELEASE from/to central (http://repo.maven.apache.org/maven2): Failed to transfer http://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.1.18.RELEASE/spring-boot-starter-parent-2.1.18.RELEASE.pom. Error code 501, HTTPS Required @ org.apache.dolphinscheduler:dolphinscheduler:1.3.6-SNAPSHOT, D:\dolphin\dolphinscheduler\pom.xml, line 165, column 25

	at org.apache.maven.model.building.DefaultModelProblemCollector.newModelBuildingException(DefaultModelProblemCollector.java:195)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:419)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:371)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:362)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:232)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:142)
	... 46 more`

**Comment by CalvinKirs** [comment]
First point: currently the registry is using a plug-in architecture, if you test locally, you need to mvn install the plug-in package first. Then you can find this directory dolphinscheduler/dolphinscheduler-dist/target/dolphinscheduler-dist-1.3.6-SNAPSHOT/lib/plugin/registry/zookeeper, you need to fill This path information in registry.plugin.dir, please refer to registry.properties for specific parameter configuration.

Second point: https://github.com/apache/dolphinscheduler/issues/5640
This look interested for you? dev many features without documentation, users are not very good at using, you can first copy down the 1.3.6, and then we add the dev documentation based on this

**Comment by docming** [comment]
> First point: currently the registry is using a plug-in architecture, if you test locally, you need to mvn install the plug-in package first. Then you can find this directory dolphinscheduler/dolphinscheduler-dist/target/dolphinscheduler-dist-1.3.6-SNAPSHOT/lib/plugin/registry/zookeeper, you need to fill This path information in registry.plugin.dir, please refer to registry.properties for specific parameter configuration.
> 
> Second point: #5640
> This look interested for you? dev many features without documentation, users are not very good at using, you can first copy down the 1.3.6, and then we add the dev documentation based on this

### the apache maven responsitory only can access by https now so it occurs this exception,how I define it anywhere?

> the following is exception

`[ERROR] Non-resolvable import POM: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.1.18.RELEASE from/to central (http://repo.maven.apache.org/maven2): Failed to transfer http://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.1.18.RELEASE/spring-boot-starter-parent-2.1.18.RELEASE.pom. Error code 501, HTTPS Required @ org.apache.dolphinscheduler:dolphinscheduler:1.3.6-SNAPSHOT, D:\dolphin\dolphinscheduler\pom.xml, line 165, column 25`

**Comment by CalvinKirs** [comment]
> > First point: currently the registry is using a plug-in architecture, if you test locally, you need to mvn install the plug-in package first. Then you can find this directory dolphinscheduler/dolphinscheduler-dist/target/dolphinscheduler-dist-1.3.6-SNAPSHOT/lib/plugin/registry/zookeeper, you need to fill This path information in registry.plugin.dir, please refer to registry.properties for specific parameter configuration.
> > Second point: #5640
> > This look interested for you? dev many features without documentation, users are not very good at using, you can first copy down the 1.3.6, and then we add the dev documentation based on this
> 
> ### the apache maven responsitory only can access by https so it occurs this exception,how I define it anywhere?
> > the following is exception
> 
> `[ERROR] Non-resolvable import POM: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.1.18.RELEASE from/to central (http://repo.maven.apache.org/maven2): Failed to transfer http://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.1.18.RELEASE/spring-boot-starter-parent-2.1.18.RELEASE.pom. Error code 501, HTTPS Required @ org.apache.dolphinscheduler:dolphinscheduler:1.3.6-SNAPSHOT, D:\dolphin\dolphinscheduler\pom.xml, line 165, column 25`

You can try to change the mirror address https://developer.aliyun.com/article/78124

**Comment by CalvinKirs** [comment]
Have you solved this problem? If it is solved, I will close it.
