### ISSUE TITLE
impala：AnalysisException: concat() unknown

### ISSUE THREAD

**Issue by KingdomTaoF** [apache/dolphinscheduler#5650]
when I use the sql task which connect to impala，then execute a sql ，sometimes it will  cause an error like that
“[ERROR] 2021-06-17 02:50:15.812  - [taskAppId=TASK-191-464735-1050514]:[336] - AnalysisException: concat() unknown

org.apache.hive.service.cli.HiveSQLException: AnalysisException: concat() unknown

	at org.apache.hive.jdbc.Utils.verifySuccess(Utils.java:264)
	at org.apache.hive.jdbc.Utils.verifySuccessWithInfo(Utils.java:250)
	at org.apache.hive.jdbc.HiveStatement.runAsyncOnServer(HiveStatement.java:309)
	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:250)
	at org.apache.hive.jdbc.HiveStatement.executeUpdate(HiveStatement.java:448)
	at org.apache.hive.jdbc.HivePreparedStatement.executeUpdate(HivePreparedStatement.java:119)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.executeFuncAndSql(SqlTask.java:324)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.handle(SqlTask.java:176)
	at org.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread.run(TaskScheduleThread.java:142)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)”

i don't know why，I guest  it is a bug when use hive driver to connect to impala.

**Comment by caishunfeng** [comment]
This pr was not update for a long time. So it wil be closed. If need, you can reopen it.
