### ISSUE TITLE
[Bug][log] java.util.ConcurrentModificationException: null  often appear in the log

### ISSUE THREAD

**Issue by wengieeee** [apache/dolphinscheduler#5722]
**Which version of Dolphin Scheduler:**
 -[1.3.6]

The following errors often appear in the log，It will not affect the success or failure of the task, but will affect the printing of the log

[ERROR] 2021-06-30 07:02:36.924  - [taskAppId=TASK-78-10550712-14319202]:[384] - null
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at java.lang.String.join(String.java:2503)
	at org.apache.dolphinscheduler.server.worker.task.AbstractTask.logHandle(AbstractTask.java:129)
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.flush(AbstractCommandExecutor.java:557)
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.lambda$parseProcessOutput$1(AbstractCommandExecutor.java:378)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by CalvinKirs** [comment]
please see #5528, I will release it in 1.3.7

**Comment by CalvinKirs** [comment]
You can test it first.

**Comment by CalvinKirs** [comment]
resolved in #5528
