### ISSUE TITLE
[Question] Is the shell task support windows OS?

### ISSUE THREAD

**Issue by echohlne** [apache/dolphinscheduler#5811]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
In pr #2842
It supports the ability to execute shell task in windows, but in the latest dev, this feature has been removed diretly and it would throws exception like this, it looks like  a bug :

```java
[INFO] 2021-07-12 19:59:14.299  - [taskAppId=TASK-545173233664_5-13-15]:[90] - tenantCode user:win, task dir:13_15
[INFO] 2021-07-12 19:59:14.300  - [taskAppId=TASK-545173233664_5-13-15]:[95] - create command file:/tmp/dolphinscheduler/exec/process/528073875456/545173233664_5/13/15/13_15.bat
[INFO] 2021-07-12 19:59:14.300  - [taskAppId=TASK-545173233664_5-13-15]:[114] - command : @echo off
cd /d %~dp0
call /etc/profile
/tmp/dolphinscheduler/exec/process/528073875456/545173233664_5/13/15/13_15_node.bat
[INFO] 2021-07-12 19:59:14.317  - [taskAppId=TASK-545173233664_5-13-15]:[321] - task run command:
cmd.exe /tmp/dolphinscheduler/exec/process/528073875456/545173233664_5/13/15/13_15.bat
[ERROR] 2021-07-12 19:59:14.318  - [taskAppId=TASK-545173233664_5-13-15]:[537] - Attempt to get long field "java.lang.ProcessImpl.handle" with illegal data type conversion to int
java.lang.IllegalArgumentException: Attempt to get long field "java.lang.ProcessImpl.handle" with illegal data type conversion to int
	at sun.reflect.UnsafeFieldAccessorImpl.newGetIllegalArgumentException(UnsafeFieldAccessorImpl.java:69)
	at sun.reflect.UnsafeFieldAccessorImpl.newGetIntIllegalArgumentException(UnsafeFieldAccessorImpl.java:132)
	at sun.reflect.UnsafeLongFieldAccessorImpl.getInt(UnsafeLongFieldAccessorImpl.java:56)
	at java.lang.reflect.Field.getInt(Field.java:574)
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.getProcessId(AbstractCommandExecutor.java:535)
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.run(AbstractCommandExecutor.java:183)
	at org.apache.dolphinscheduler.server.worker.task.datax.DataxTask.handle(DataxTask.java:168)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:159)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 2021-07-12 19:59:14.319  - [taskAppId=TASK-545173233664_5-13-15]:[197] - process start, process id is: 0
```

**If the shell task should't be supported in windows, maybe it's better to throw an unsupported exception?**

**Which version of DolphinScheduler:**
 -latest dev branch

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by echohlne** [comment]
cc @CalvinKirs ,  @dailidong

**Comment by CalvinKirs** [comment]
The original implementation seems to have license-related issues, so we deleted the relevant code.

**Comment by echohlne** [comment]
Thanks @CalvinKirs , if so ,what should we do next? 
In windows, the server would try to get `handle` by reflection, but the type of `handle` is long rather than int, the `getProcessId`
woudle always throws an exception.
```java
public static final String PID = OSUtils.isWindows() ? "handle" : "pid";
// AbstractCommandExecutor.java
private int getProcessId(Process process) {
        int processId = 0;

        try {
            Field f = process.getClass().getDeclaredField(Constants.PID);
            f.setAccessible(true);

            processId = f.getInt(process);
        } catch (Throwable e) {
            logger.error(e.getMessage(), e);
        }

        return processId;
    }
```

**Comment by CalvinKirs** [comment]
@dailidong I'm not quite sure of the exact context before, can you elaborate on that? or whether we need to support the shell under windows.

**Comment by echohlne** [comment]
friendly ping @dailidong   any idea about this issue?
