### ISSUE TITLE
[Bug][master server] Data too long for column 'app_link' in t_ds_task_instance cause job can not finished

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#5887]
```
[ERROR] 2021-07-26 16:34:15.197 org.apache.dolphinscheduler.server.master.processor.queue.TaskResponseService:[169] - worker response master error
org.springframework.dao.DataIntegrityViolationException: 
### Error updating database.  Cause: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'app_link' at row 1
### The error may exist in org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.java (best guess)
### The error may involve org.apache.dolphinscheduler.dao.mapper.TaskInstanceMapper.updateById-Inline
### The error occurred while setting parameters
### SQL: UPDATE t_ds_task_instance  SET flag=?, task_json=?, pid=?, app_link=?, task_type=?, task_instance_priority=?, log_path=?, host=?, start_time=?, worker_group=?, state=?, process_instance_id=?, process_definition_id=?, executor_id=?, alert_flag=?, execute_path=?, max_retry_times=?, retry_times=?, submit_time=?, name=?, retry_interval=?, end_time=?  WHERE id=?
### Cause: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'app_link' at row 1
; Data truncation: Data too long for column 'app_link' at row 1; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'app_link' at row 1
        at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:104)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:74)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
        at com.sun.proxy.$Proxy84.update(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:287)
        at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:63)
        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61)
        at com.sun.proxy.$Proxy91.updateById(Unknown Source)
        at org.apache.dolphinscheduler.service.process.ProcessService.updateTaskInstance(ProcessService.java:1258)
        at org.apache.dolphinscheduler.service.process.ProcessService.saveTaskInstance(ProcessService.java:1236)
        at org.apache.dolphinscheduler.service.process.ProcessService.changeTaskState(ProcessService.java:1477)
        at org.apache.dolphinscheduler.service.process.ProcessService$$FastClassBySpringCGLIB$$ed138739.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
        at org.apache.dolphinscheduler.service.process.ProcessService$$EnhancerBySpringCGLIB$$3190e0f0.changeTaskState(<generated>)
        at org.apache.dolphinscheduler.server.master.processor.queue.TaskResponseService.persist(TaskResponseService.java:159)
        at org.apache.dolphinscheduler.server.master.processor.queue.TaskResponseService.access$100(TaskResponseService.java:44)
        at org.apache.dolphinscheduler.server.master.processor.queue.TaskResponseService$TaskResponseWorker.run(TaskResponseService.java:114)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'app_link' at row 1
```

**Which version of Dolphin Scheduler:**
 -[1.3.5]

It is normal to change the field type to text.

**Comment by ruanwenjun** [comment]
It would be better to provide an example of the real app_link, I guess there may be some other problems with extract yarn app Ids. Some others meet this problem, when they submit a hive task.

**Comment by SbloodyS** [comment]
after change the field type to text, The status changes to success



[INFO] 2021-07-26 16:37:43.684 org.apache.dolphinscheduler.server.master.processor.TaskResponseProcessor:[71] - received command : TaskExecuteResponseCommand{taskInstanceId=90452, status=7, endTime=Mon Jul 26 16:34:15 CST 2021, processId=433787, appIds='application_1626400747313_10066,application_1626400747313_10070,application_1626400747313_10071,application_1626400747313_10073,application_1626400747313_10076,application_1626400747313_10078,application_1626400747313_10081,application_1626400747313_10083,application_1626400747313_10084'}
[INFO] 2021-07-26 16:37:47.089 org.apache.dolphinscheduler.server.master.runner.MasterTaskExecThread:[102] - task :shell_xzh_test_2 id:90452, process id:39197, exec thread completed 
[INFO] 2021-07-26 16:37:47.394 org.apache.dolphinscheduler.server.master.runner.MasterExecThread:[864] - task :shell_xzh_test_2, id:90452 complete, state is SUCCESS 
[INFO] 2021-07-26 16:37:48.396 org.apache.dolphinscheduler.server.master.runner.MasterExecThread:[764] - work flow process instance [id: 39197, name:shell_xzh_test_2-0-1627288175192], state change from RUNNING_EXECUTION to SUCCESS, cmd type: START_PROCESS
[INFO] 2021-07-26 16:37:48.401 org.apache.dolphinscheduler.server.master.runner.MasterExecThread:[925] - process:39197 end, state :SUCCESS

**Comment by chengshiwen** [comment]
@SbloodyS 1.3.6 release has fixed it
https://github.com/apache/dolphinscheduler/blob/e53d4a24a8984f713efd188c158719b142261285/sql/dolphinscheduler_mysql.sql#L704
