### ISSUE TITLE
[Bug][DATAX] DataX plug-in initialization error, this problem is usually caused by a DataX installation error, please contact your O&M to solve it

### ISSUE THREAD

**Issue by gaoyu2016** [apache/dolphinscheduler#5967]
[INFO] 2021-08-10 14:08:57.914  - [taskAppId=TASK-1123-2437672-2651427]:[127] -  -> 
        DataX (DATAX-OPENSOURCE-3.0), From Alibaba !
        Copyright (C) 2010-2017, Alibaba Group. All Rights Reserved.
        
        
        2021-08-10 14:08:56.904 [main] WARN  ConfigParser - 插件[null,null]加载失败，1s后重试... Exception:Code:[Framework-12], Description:[DataX插件初始化错误, 该问题通常是由于DataX安装错误引起，请联系您的运维解决 .].  - 插件加载失败，未完成指定插件加载:[null] 
        2021-08-10 14:08:57.913 [main] ERROR Engine - 
[INFO] 2021-08-10 14:08:57.938  - [taskAppId=TASK-1123-2437672-2651427]:[127] -  -> 
        经DataX智能分析,该任务最可能的错误原因是:
        com.alibaba.datax.common.exception.DataXException: Code:[Framework-12], Description:[DataX插件初始化错误, 该问题通常是由于DataX安装错误引起，请联系您的运维解决 .].  - 
插件加载失败，未完成指定插件加载:[null]
                at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
                at com.alibaba.datax.core.util.ConfigParser.parsePluginConfig(ConfigParser.java:142)
                at com.alibaba.datax.core.util.ConfigParser.parse(ConfigParser.java:63)
                at com.alibaba.datax.core.Engine.entry(Engine.java:137)
                at com.alibaba.datax.core.Engine.main(Engine.java:204)

**Comment by gaoyu2016** [comment]
job配置的json格式有问题。
