### ISSUE TITLE
[Bug][worker-server Service is down ] Bug title The worker service suddenly stopped，An error: io.grpc.internal.ManagedChannelImpl:[1116] - *~*~*~ Channel io.grpc.internal.ManagedChannelImpl-337 for target 10.8.2.52:50051 was not shutdown properly!!! ~*~*~*     Make sure to call shutdown()/shutdownNow() and awaitTermination(). java.lang.RuntimeException: ManagedChannel allocation site

### ISSUE THREAD

**Issue by git1071440198** [apache/dolphinscheduler#5972]
[INFO] 2021-08-10 16:13:43.221 org.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread:[156] - task instance id : 18363,task final status : SUCCESS
[INFO] 2021-08-10 16:16:44.880 org.apache.dolphinscheduler.server.worker.WorkerServer:[339] - get one kill command from tasks kill queue: 10.8.2.52-18366
[INFO] 2021-08-10 16:16:45.006 org.apache.dolphinscheduler.server.utils.ProcessUtils:[332] - process id:25742, cmd:kill -9 
[ERROR] 2021-08-10 16:16:46.011 io.grpc.internal.ManagedChannelImpl:[1116] - *~*~*~ Channel io.grpc.internal.ManagedChannelImpl-337 for target 10.8.2.52:50051 was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and awaitTermination().
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelImpl$ManagedChannelReference.<init>(ManagedChannelImpl.java:1065)
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:485)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:349)
	at org.apache.dolphinscheduler.server.rpc.LogClient.<init>(LogClient.java:71)
	at org.apache.dolphinscheduler.server.rpc.LogClient.<init>(LogClient.java:55)
	at org.apache.dolphinscheduler.server.utils.ProcessUtils.killYarnJob(ProcessUtils.java:370)
	at org.apache.dolphinscheduler.server.utils.ProcessUtils.kill(ProcessUtils.java:337)
	at org.apache.dolphinscheduler.server.worker.WorkerServer.killTask(WorkerServer.java:362)
	at org.apache.dolphinscheduler.server.worker.WorkerServer.access$400(WorkerServer.java:60)
	at org.apache.dolphinscheduler.server.worker.WorkerServer$3.run(WorkerServer.java:320)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] 2021-08-10 16:16:46.011 io.grpc.internal.ManagedChannelImpl:[1116] - *~*~*~ Channel io.grpc.internal.ManagedChannelImpl-333 for target 10.8.2.52:50051 was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and awaitTermination().
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelImpl$ManagedChannelReference.<init>(ManagedChannelImpl.java:1065)
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:485)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:349)
	at org.apache.dolphinscheduler.server.rpc.LogClient.<init>(LogClient.java:71)
	at org.apache.dolphinscheduler.server.rpc.LogClient.<init>(LogClient.java:55)
	at org.apache.dolphinscheduler.server.utils.ProcessUtils.killYarnJob(ProcessUtils.java:370)
	at org.apache.dolphinscheduler.server.utils.ProcessUtils.kill(ProcessUtils.java:337)
	at org.apache.dolphinscheduler.server.worker.WorkerServer.killTask(WorkerServer.java:362)
	at org.apache.dolphinscheduler.server.worker.WorkerServer.access$400(WorkerServer.java:60)
	at org.apache.dolphinscheduler.server.worker.WorkerServer$3.run(WorkerServer.java:320)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 2021-08-10 16:16:46.012 org.apache.dolphinscheduler.server.rpc.LogClient:[117] - view log path : /home/mjyu/opt/dolphinscheduler/logs/64/3309/18366.log
[INFO] 2021-08-10 16:16:46.048 org.apache.dolphinscheduler.common.queue.TaskQueueZkImpl:[339] - delete task:10.8.2.52-18366 from tasks set 
[INFO] 2021-08-10 16:18:29.092 org.apache.dolphinscheduler.server.worker.WorkerServer:[339] - get one kill command from tasks kill queue: 10.8.2.52-18335
[INFO] 2021-08-10 16:18:29.211 org.apache.dolphinscheduler.server.utils.ProcessUtils:[332] - process id:22434, cmd:kill -9 
[INFO] 2021-08-10 16:18:30.215 org.apache.dolphinscheduler.server.rpc.LogClient:[117] - view log path : /home/mjyu/opt/dolphinscheduler/logs/77/3307/18335.log
[INFO] 2021-08-10 16:18:30.245 org.apache.dolphinscheduler.common.queue.TaskQueueZkImpl:[339] - delete task:10.8.2.52-18335 from tasks set 
[INFO] 2021-08-10 16:18:31.246 org.apache.dolphinscheduler.server.worker.WorkerServer:[339] - get one kill command from tasks kill queue: 10.8.2.52-18336
[INFO] 2021-08-10 16:18:31.359 org.apache.dolphinscheduler.server.utils.ProcessUtils:[332] - process id:22448, cmd:kill -9 
[INFO] 2021-08-10 16:18:32.364 org.apache.dolphinscheduler.server.rpc.LogClient:[117] - view log path : /home/mjyu/opt/dolphinscheduler/logs/68/3308/18336.log
[ERROR] 2021-08-10 16:18:32.396 org.apache.dolphinscheduler.server.rpc.LogClient:[125] - view log  failed : UNKNOWN
io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:221)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:202)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:131)
	at org.apache.dolphinscheduler.rpc.LogViewServiceGrpc$LogViewServiceBlockingStub.viewLog(LogViewServiceGrpc.java:321)
	at org.apache.dolphinscheduler.server.rpc.LogClient.viewLog(LogClient.java:122)
	at org.apache.dolphinscheduler.server.utils.ProcessUtils.killYarnJob(ProcessUtils.java:372)
	at org.apache.dolphinscheduler.server.utils.ProcessUtils.kill(ProcessUtils.java:337)
	at org.apache.dolphinscheduler.server.worker.WorkerServer.killTask(WorkerServer.java:362)
	at org.apache.dolphinscheduler.server.worker.WorkerServer.access$400(WorkerServer.java:60)
	at org.apache.dolphinscheduler.server.worker.WorkerServer$3.run(WorkerServer.java:320)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 2021-08-10 16:18:32.397 org.apache.dolphinscheduler.common.queue.TaskQueueZkImpl:[339] - delete task:10.8.2.52-18336 from tasks set 
[INFO] 2021-08-10 16:18:32.397 org.apache.dolphinscheduler.server.worker.WorkerServer:[339] - get one kill command from tasks kill queue: 10.8.2.52-18339
[INFO] 2021-08-10 16:18:32.484 org.apache.dolphinscheduler.server.utils.ProcessUtils:[332] - process id:22490, cmd:kill -9 
[INFO] 2021-08-10 16:18:33.487 org.apache.dolphinscheduler.server.rpc.LogClient:[117] - view log path : /home/mjyu/opt/dolphinscheduler/logs/68/3308/18339.log
[ERROR] 2021-08-10 16:18:33.517 org.apache.dolphinscheduler.server.rpc.LogClient:[125] - view log  failed : UNKNOWN
io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:221)

**Comment by CalvinKirs** [comment]
which version?

**Comment by git1071440198** [comment]
version 1.2.0

**Comment by git1071440198** [comment]
> which version?

version 1.2.0
