### ISSUE TITLE
[Bug] Incompatible big sur system with M1 chip

### ISSUE THREAD

**Issue by bingexxx** [apache/dolphinscheduler#6031]
when I start the masterServer or workerServer locally with IDEA， it occurs this error: 

``` java
Exception in thread "MasterSchedulerThread" java.lang.UnsatisfiedLinkError: /private/var/folders/x8/xyx6h_fx61b57m5cqgpgb7d80000gn/T/jna-97543/jna4949441333799720080.tmp: dlopen(/private/var/folders/x8/xyx6h_fx61b57m5cqgpgb7d80000gn/T/jna-97543/jna4949441333799720080.tmp, 1): no suitable image found.  Did find:
	/private/var/folders/x8/xyx6h_fx61b57m5cqgpgb7d80000gn/T/jna-97543/jna4949441333799720080.tmp: no matching architecture in universal wrapper
	/private/var/folders/x8/xyx6h_fx61b57m5cqgpgb7d80000gn/T/jna-97543/jna4949441333799720080.tmp: no matching architecture in universal wrapper
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1088)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:947)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.Structure.<clinit>(Structure.java:2130)
	at oshi.hardware.platform.mac.MacGlobalMemory.<init>(MacGlobalMemory.java:46)
	at oshi.hardware.platform.mac.MacHardwareAbstractionLayer.getMemory(MacHardwareAbstractionLayer.java:65)
	at org.apache.dolphinscheduler.common.utils.OSUtils.availablePhysicalMemorySize(OSUtils.java:90)
	at org.apache.dolphinscheduler.common.utils.OSUtils.checkResource(OSUtils.java:440)
	at org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService.run(MasterSchedulerService.java:122)
```

my system is: 
![image](https://user-images.githubusercontent.com/22575306/130552606-08cc46ad-2113-4c9d-a7ba-d0c0557b75d5.png)

The branch is 1.3.8-release and start it with vm options -Dlogging.config=classpath:logback-master.xml -Ddruid.mysql.usePingMethod=false

**Comment by ruanwenjun** [comment]
This issue seems caused by `oshi`.
And `oshi` has already support M1 https://github.com/oshi/oshi/blob/master/FAQ.md#does-oshi-work-on-apple-m1-hardware.
In the 1.3.8-release and dev branch, we use `oshi` 3.9.1, and the `jna` is 4.5.2, so it doesn't support M1, I think we can upgrade the `oshi` version.

@bingexxx Could you please upgrade the oshi version to 5.8.1 and try again?
You can set the version in ${rootProject}/pom.xml
```java
<oshi.core.version>5.8.1</oshi.core.version>
```
