### ISSUE TITLE
[Bug][dolphinscheduler-standalone-server] StandaloneServer run failed on Windows system 

### ISSUE THREAD

**Issue by QuakeWang** [apache/dolphinscheduler#6091]
Since the directory separator is not the same for different operating systems, reading the pom.xml file of registry in Windows system fails.
The error message is as follows :
```
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 2: ../dolphinscheduler/dolphinscheduler-standalone-server/target/classes/\../../../dolphinscheduler-registry-plugin/dolphinscheduler-registry-zookeeper/pom.xml
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at org.apache.dolphinscheduler.server.StandaloneServer.main(StandaloneServer.java:75)
```

**Comment by CalvinKirs** [comment]
can you submit a pr for this?

**Comment by QuakeWang** [comment]
Ok, I will fix it soon. : )

**Comment by CalvinKirs** [comment]
> Ok, I will fix it soon. : )

If you have submitted a pr and need a review, please ping me.

**Comment by Tandoy** [comment]
+1

**Comment by kezhenxu94** [comment]
We totally get rid of pom.xml now so this is not a problem anymore
