### ISSUE TITLE
[Question] DS scheduling task fails instantaneously

### ISSUE THREAD

**Issue by KelvinChi** [apache/dolphinscheduler#6106]
**I run DS on:**
CentOS Linux release 7.8.2003 (Core)
DS Version: 1.3.1

**Below is the log I got:**
```log
[WARN] 2021-09-02 09:00:03.068 org.apache.dolphinscheduler.server.master.dispatch.host.LowerWeightHostManager:[159] - load is too high or availablePhysicalMemorySize(G) is too low, it's availablePhysicalMemorySize(G):6.54,loadAvg:15.36
[WARN] 2021-09-02 09:00:08.071 org.apache.dolphinscheduler.server.master.dispatch.host.LowerWeightHostManager:[159] - load is too high or availablePhysicalMemorySize(G) is too low, it's availablePhysicalMemorySize(G):6.54,loadAvg:15.36
[ERROR] 2021-09-02 09:00:09.467 org.apache.dolphinscheduler.server.registry.HeartBeatTask:[81] - error write heartbeat info
java.lang.NoClassDefFoundError: Could not initialize class oshi.jna.platform.linux.Libc
        at oshi.hardware.platform.linux.LinuxCentralProcessor.getSystemLoadAverage(LinuxCentralProcessor.java:191)
        at oshi.hardware.common.AbstractCentralProcessor.getSystemLoadAverage(AbstractCentralProcessor.java:449)
        at org.apache.dolphinscheduler.common.utils.OSUtils.loadAverage(OSUtils.java:114)
        at org.apache.dolphinscheduler.server.registry.HeartBeatTask.run(HeartBeatTask.java:57)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Descripbe:**
All scheduling task fail instantaneously!

**Comment by KelvinChi** [comment]
Actually I figured out this issue by myself. When I used vim in the DS node, I found it notice me "write to ~/.viminfo failed"，then I tested `mkdir a`, I got **"mkdir: cannot create directory 'a': No space left on device"**. Well, `df -h`, there had enough space, then **`df -i`**. THERE IS! I had no nodes space left in my server.

OK, now use `for i in ./*; do find $i| wc -l| xargs -i echo -n {}; echo " $i"; done| sort -k 1 -h| tail -n 15` to find out which folder contains many small files. Delete it. DONE!
