### ISSUE TITLE
Queue full

### ISSUE THREAD

**Issue by cxin-william** [apache/dolphinscheduler#6117]
[INFO] 2021-09-07 15:29:33.699  - [taskAppId=TASK-62-64-7123]:[87] - tenantCode user:ETL, task dir:62_64_7123
[INFO] 2021-09-07 15:29:33.699  - [taskAppId=TASK-62-64-7123]:[92] - create command file:/tmp/dolphinscheduler/exec/process/2/62/64/7123/62_64_7123.command
[INFO] 2021-09-07 15:29:33.700  - [taskAppId=TASK-62-64-7123]:[111] - command : #!/bin/sh
BASEDIR=$(cd `dirname $0`; pwd)
cd $BASEDIR
source /opt/soft/dolphinscheduler/conf/env/dolphinscheduler_env.sh
/tmp/dolphinscheduler/exec/process/2/62/64/7123/62_64_7123_node.sh
[INFO] 2021-09-07 15:29:33.720  - [taskAppId=TASK-62-64-7123]:[324] - task run command:
sudo -u ETL sh /tmp/dolphinscheduler/exec/process/2/62/64/7123/62_64_7123.command
[INFO] 2021-09-07 15:29:33.751  - [taskAppId=TASK-62-64-7123]:[209] - process start, process id is: 15700
[INFO] 2021-09-07 15:29:35.728  - [taskAppId=TASK-62-64-7123]:[138] -  -> 
	  ___      _     _            
	 / _ \    | |   | |           
	/ /_\ \ __| | __| | __ ___  __
	|  _  |/ _` |/ _` |/ _` \ \/ /
	| | | | (_| | (_| | (_| |>  < 
	\_| |_/\__,_|\__,_|\__,_/_/\_\
	
	:: Addax version ::    (v4.0.2)
	
[ERROR] 2021-09-07 15:29:35.824  - [taskAppId=TASK-62-64-7123]:[359] - Queue full
java.lang.IllegalStateException: Queue full
	at java.util.AbstractQueue.add(AbstractQueue.java:98)
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.lambda$parseProcessOutput$0(AbstractCommandExecutor.java:356)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 2021-09-07 15:29:36.729  - [taskAppId=TASK-62-64-7123]:[138] -  -> [36m2021-09-07 15:29:35.774[0;39m [32m[        main][0;39m [34mINFO [0;39m [35mVMInfo              [0;39m - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl

I ran into this problem when I used the Datax task

**Comment by ruanwenjun** [comment]
@cxin-william Which version? 1.3.7?

**Comment by cxin-william** [comment]
yes,and Version 1.3.6 has this problem

`[36m2021-09-08 09:17:49.714[0;39m [32m[0-0-43-writer][0;39m [1;31mERROR[0;39m [35mRetryUtil           [0;39m - Exception when calling callable, 异常Msg:Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：java.sql.SQLException: Cannot create PoolableConnectionFactory (FATAL: remaining connection slots are reserved for non-replication superuser connections)
        com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：java.sql.SQLException: Cannot create PoolableConnectionFactory (FATAL: remaining connection slots are reserved for non-replication superuser connections)
                at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
                at com.wgzhao.addax.rdbms.util.RdbmsException.asConnException(RdbmsException.java:61)
                at com.wgzhao.addax.rdbms.util.DBUtil.connect(DBUtil.java:295)
                at com.wgzhao.addax.rdbms.util.DBUtil.lambda$getConnection$2(DBUtil.java:230)
                at com.wgzhao.addax.common.util.RetryUtil$Retry.call(RetryUtil.java:202)
                at com.wgzhao.addax.common.util.RetryUtil$Retry.doRetry(RetryUtil.java:147)
                at com.wgzhao.addax.common.util.RetryUtil.executeWithRetry(RetryUtil.java:59)
                at com.wgzhao.addax.rdbms.util.DBUtil.getConnection(DBUtil.java:230)
                at com.wgzhao.addax.rdbms.util.DBUtil.getConnection(DBUtil.java:223)
                at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.prepare(CommonRdbmsWriter.java:262)
                at com.wgzhao.addax.plugin.writer.greenplumwriter.GreenplumWriter$Task.prepare(GreenplumWriter.java:98)
                at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:75)
                at java.lang.Thread.run(Thread.java:748)'`

**Comment by cxin-william** [comment]
yes，It seems that 1.3.6 is ok

**Comment by ruanwenjun** [comment]
@cxin-william Please use 1.3.8, 1.3.7 has been deleted, because there are some serious bugs.

**Comment by cxin-william** [comment]
okay~,thaks very very very very very very very very very very very very very very much
