### ISSUE TITLE
[Bug] [dev package] Server start error

### ISSUE THREAD

**Issue by xiaohui0318** [apache/dolphinscheduler#6176]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I used dev branch to compile code package, and then called start-all.sh, master node, worker node failed to start.The following is the master log：
```
[ERROR] 2021-09-11 13:43:01.780 org.springframework.boot.SpringApplication:[823] - Application run failed
java.lang.IllegalStateException: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.action.AppenderAction - Could not create an Appender of type [org.apache.skywalking.apm.toolkit.log.logback.v1.x.log.GRPCLogClientAppender]. ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.apache.skywalking.apm.toolkit.log.logback.v1.x.log.GRPCLogClientAppender
ERROR in ch.qos.logback.core.joran.spi.Interpreter@77:123 - ActionException in Action for tag [appender] ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.apache.skywalking.apm.toolkit.log.logback.v1.x.log.GRPCLogClientAppender
ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an appender named [SKYWALKING-LOG]. Did you define it below instead of above in the configuration file?
ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - See http://logback.qos.ch/codes.html#appender_order for more details.
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:301)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:264)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:226)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:203)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:342)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	at org.apache.dolphinscheduler.server.master.MasterServer.main(MasterServer.java:112)
Caused by: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.action.AppenderAction - Could not create an Appender of type [org.apache.skywalking.apm.toolkit.log.logback.v1.x.log.GRPCLogClientAppender]. ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.apache.skywalking.apm.toolkit.log.logback.v1.x.log.GRPCLogClientAppender
ERROR in ch.qos.logback.core.joran.spi.Interpreter@77:123 - ActionException in Action for tag [appender] ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.apache.skywalking.apm.toolkit.log.logback.v1.x.log.GRPCLogClientAppender
ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an appender named [SKYWALKING-LOG]. Did you define it below instead of above in the configuration file?
ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - See http://logback.qos.ch/codes.html#appender_order for more details.
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:167)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithSpecificConfig(AbstractLoggingSystem.java:66)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:57)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:118)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:294)
	... 13 common frames omitted
```

### What you expected to happen

master server and worker server should start ok.

### How to reproduce

1. download branch dev codes
2. mvn -U install package -Prelease -Dmaven.test.skip=true
3. config 
4. start

### Anything else

nothing

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
which version?

**Comment by xiaohui0318** [comment]
> which version?

dev Latest

**Comment by xiaohui0318** [comment]
Delete SKYWALKING-LOG in logback-*.xml ,then start success
