### ISSUE TITLE
Task Plugin Not Found,Please Check Config File

### ISSUE THREAD

**Issue by lugela** [apache/dolphinscheduler#6255]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Use idea to start the workserver in the dev environment. The outgoing error is：

Caused by: org.apache.dolphinscheduler.spi.exception.PluginNotFoundException: Task Plugin Not Found,Please Check Config File
	at org.apache.dolphinscheduler.server.worker.WorkerServer.initTaskPlugin(WorkerServer.java:193)
	at org.apache.dolphinscheduler.server.worker.WorkerServer.run(WorkerServer.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	... 16 more

### DolphinScheduler Version

dev

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tandoy** [comment]
you can try two steps:
1.`mvn -U install package -Prelease -Dmaven.test.skip=true`
2.modify in worker.properties：`task.plugin.dir=./dolphinscheduler-dist/target/dolphinscheduler-dist-1.3.6-SNAPSHOT/lib/plugin/task`

**Comment by CalvinKirs** [comment]
done
