### ISSUE TITLE
[Bug] [dolphinescheduler-server] Queue full

### ISSUE THREAD

**Issue by FantasticMM** [apache/dolphinscheduler#6332]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

java.lang.IllegalStateException: Queue full
 at java.util.AbstractQueue.add(AbstractQueue.java:98)
 at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.lambda$parseProcessOutput$3(AbstractCommandExecutor.java:356)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)

is this because AbstractCommandExecutor.clear() method didn't clear queue?
I notice since 1.3.7 logBuffer become a LinkedBlockingQueue, and in AbstractCommandExecutor.clear() miss logBuffer.clear().
I'll take two photos for compare 1.3.6 and 1.3.8
1.3.6
![image](https://user-images.githubusercontent.com/54891165/134654003-26a37a28-f650-4bfc-99ba-5d4179e493c1.png)

1.3.8
![image](https://user-images.githubusercontent.com/54891165/134654091-94e5ce6c-ce1e-4886-8e9b-f22d66088ed9.png)

### What you expected to happen

I think there miss a line of code logBuffer.clear()

### How to reproduce

I do not konw actually , my colleague just run task normally, and failed

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
This should be fixed according to https://github.com/apache/dolphinscheduler/blob/b71f6aea7af899da41bd958caa30d68d89a9aec4/dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java#L291-L302
