### ISSUE TITLE
[Question] [StandaloneServer] Zookeeper check key is existed error

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#6416]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I develop in standalone server, according to [our docs][1]. I could start standalone but it would sometime error, and error message as below:

FYI, I use our latest code in our dev branch, and change database from H2 to my local MySQL

```log
2021-09-29 17:31:04.845  INFO 6357 --- [tResponseWorker] o.a.d.s.m.p.queue.TaskResponseService    : StateEventResponseWorker stopped
2021-09-29 17:31:04.846  INFO 6357 --- [tResponseWorker] o.a.d.s.m.p.q.StateEventResponseService  : StateEventResponseWorker stopped
2021-09-29 17:31:04.857  INFO 6357 --- [tBeatExecutor_1] o.e.jetty.server.AbstractConnector       : Stopped ServerConnector@384f0e32{HTTP/1.1, (http/1.1)}{0.0.0.0:12345}
2021-09-29 17:31:04.857  INFO 6357 --- [tBeatExecutor_1] org.eclipse.jetty.server.session         : node0 Stopped scavenging
2021-09-29 17:31:04.858  INFO 6357 --- [tBeatExecutor_1] o.e.j.s.h.ContextHandler.application     : Destroying Spring FrameworkServlet 'dispatcherServlet'
2021-09-29 17:31:04.859  INFO 6357 --- [tBeatExecutor_1] o.e.jetty.server.handler.ContextHandler  : Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@6520625f{application,/dolphinscheduler,[file:///private/var/folders/yj/f8xj7l6x4bqf6z26bg2xhb5c0000gn/T/jetty-docbase.2042296424170317544.12345/, jar:file:/Users/zhongjiajie/.m2/repository/io/springfox/springfox-swagger-ui/2.9.2/springfox-swagger-ui-2.9.2.jar!/META-INF/resources, jar:file:/Users/zhongjiajie/.m2/repository/com/github/xiaoymin/swagger-bootstrap-ui/1.9.3/swagger-bootstrap-ui-1.9.3.jar!/META-INF/resources],STOPPED}
2021-09-29 17:31:06.015 ERROR 6357 --- [tBeatExecutor_1] o.a.d.server.registry.HeartBeatTask      : error write heartbeat info

org.apache.dolphinscheduler.spi.register.RegistryException: zookeeper check key is existed error
	at org.apache.dolphinscheduler.plugin.registry.zookeeper.ZookeeperRegistry.isExisted(ZookeeperRegistry.java:207) ~[na:na]
	at org.apache.dolphinscheduler.service.registry.RegistryCenter.isExisted(RegistryCenter.java:177) ~[classes/:na]
	at org.apache.dolphinscheduler.service.registry.RegistryClient.checkIsDeadServer(RegistryClient.java:345) ~[classes/:na]
	at org.apache.dolphinscheduler.server.registry.HeartBeatTask.run(HeartBeatTask.java:82) ~[classes/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_231]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308) [na:1.8.0_231]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) [na:1.8.0_231]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_231]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_231]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_231]
Caused by: java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:823) ~[curator-client-4.3.0.jar:na]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkState(CuratorFrameworkImpl.java:432) ~[curator-framework-4.3.0.jar:4.3.0]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkExists(CuratorFrameworkImpl.java:459) ~[curator-framework-4.3.0.jar:4.3.0]
	at org.apache.dolphinscheduler.plugin.registry.zookeeper.ZookeeperRegistry.isExisted(ZookeeperRegistry.java:205) ~[na:na]
	... 11 common frames omitted

2021-09-29 17:31:06.754 ERROR 6357 --- [      Thread-47] o.a.d.alert.runner.AlertSender           : send alert msg fail,no bind plugin instance.
2021-09-29 17:31:12.478  INFO 6357 --- [ SessionTracker] o.a.zookeeper.server.ZooKeeperServer     : Expiring session 0x10000b1c71d0001, timeout of 6000ms exceeded
2021-09-29 17:31:12.479  INFO 6357 --- [0 cport:56950):] o.a.z.server.PrepRequestProcessor        : Processed session termination for sessionid: 0x10000b1c71d0001
2021-09-29 17:31:16.008 ERROR 6357 --- [tBeatExecutor_1] o.a.d.server.registry.HeartBeatTask      : error write heartbeat info

org.apache.dolphinscheduler.spi.register.RegistryException: zookeeper check key is existed error
	at org.apache.dolphinscheduler.plugin.registry.zookeeper.ZookeeperRegistry.isExisted(ZookeeperRegistry.java:207) ~[na:na]
	at org.apache.dolphinscheduler.service.registry.RegistryCenter.isExisted(RegistryCenter.java:177) ~[classes/:na]
	at org.apache.dolphinscheduler.service.registry.RegistryClient.checkIsDeadServer(RegistryClient.java:345) ~[classes/:na]
	at org.apache.dolphinscheduler.server.registry.HeartBeatTask.run(HeartBeatTask.java:82) ~[classes/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_231]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308) [na:1.8.0_231]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) [na:1.8.0_231]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_231]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_231]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_231]
Caused by: java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:823) ~[curator-client-4.3.0.jar:na]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkState(CuratorFrameworkImpl.java:432) ~[curator-framework-4.3.0.jar:4.3.0]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkExists(CuratorFrameworkImpl.java:459) ~[curator-framework-4.3.0.jar:4.3.0]
	at org.apache.dolphinscheduler.plugin.registry.zookeeper.ZookeeperRegistry.isExisted(ZookeeperRegistry.java:205) ~[na:na]
	... 11 common frames omitted
```

[1]: https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/dev_quick_start.html

### What you expected to happen

zookeeper should not error

### How to reproduce

I just create a process definition with some of shell task and run it

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
@CalvinKirs Could you take a look when you have free time

**Comment by CalvinKirs** [comment]
java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]

It looks like zk is down

**Comment by zhongjiajie** [comment]
I use standalone server, seem it use build in zookeeper. Did high CPU load would cause zk down?

**Comment by CalvinKirs** [comment]
> I use standalone server, seem it use build in zookeeper. Did high CPU load would cause zk down?

I can’t confirm without complete information. You can search the relevant logs to confirm.

**Comment by zhongjiajie** [comment]
Ok, I would look the complete logs to check it

**Comment by zhongjiajie** [comment]
It seem it my CPU too high, I would close this issue

**Comment by 1248363645** [comment]
[ERROR] 2023-05-31 05:26:52.872 org.apache.dolphinscheduler.server.registry.HeartBeatTask:[95] - error write heartbeat info
org.apache.dolphinscheduler.registry.api.RegistryException: zookeeper check key is existed error有人知道怎么解决吗

**Comment by bluewaterstar** [comment]
还有ds进程残留，kill掉后，重启ds即可
