### ISSUE TITLE
[Bug] [deploy] dolphinscheduler-2.0.0-alpha jdk1.8 abnormal

### ISSUE THREAD

**Issue by felixlin47** [apache/dolphinscheduler#6632]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

version: dolphinscheduler-2.0.0-alpha
An error occurs during the running process:

`[ERROR] 2021-10-29 10:42:17.668 org.apache.dolphinscheduler.common.utils.DateUtils:[136] - error while parse date:1635474935597
java.time.format.DateTimeParseException: Text '1635474935597' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.LocalDateTime.parse(LocalDateTime.java:492)
	at org.apache.dolphinscheduler.common.utils.DateUtils.parse(DateUtils.java:133)
	at org.apache.dolphinscheduler.common.utils.DateUtils.stringToDate(DateUtils.java:148)
	at org.apache.dolphinscheduler.api.service.impl.WorkerGroupServiceImpl.getWorkerGroups(WorkerGroupServiceImpl.java:284)
	at org.apache.dolphinscheduler.api.service.impl.WorkerGroupServiceImpl.queryAllGroupPaging(WorkerGroupServiceImpl.java:186)
	at org.apache.dolphinscheduler.api.service.impl.WorkerGroupServiceImpl$$FastClassBySpringCGLIB$$35aefd7a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at org.apache.dolphinscheduler.api.service.impl.WorkerGroupServiceImpl$$EnhancerBySpringCGLIB$$1f39b5c6.queryAllGroupPaging(<generated>)
	at org.apache.dolphinscheduler.api.controller.WorkerGroupController.queryAllWorkerGroupsPaging(WorkerGroupController.java:122)
	at org.apache.dolphinscheduler.api.controller.WorkerGroupController$$FastClassBySpringCGLIB$$2d4d455a.invoke(<generated>)`

`[ERROR] 2021-10-29 10:42:17.670 org.apache.dolphinscheduler.common.utils.DateUtils:[136] - error while parse date:1635474945176
java.time.format.DateTimeParseException: Text '1635474945176' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.LocalDateTime.parse(LocalDateTime.java:492)
	at org.apache.dolphinscheduler.common.utils.DateUtils.parse(DateUtils.java:133)
	at org.apache.dolphinscheduler.common.utils.DateUtils.stringToDate(DateUtils.java:148)
	at org.apache.dolphinscheduler.api.service.impl.WorkerGroupServiceImpl.getWorkerGroups(WorkerGroupServiceImpl.java:285)
	at org.apache.dolphinscheduler.api.service.impl.WorkerGroupServiceImpl.queryAllGroupPaging(WorkerGroupServiceImpl.java:186)
	at org.apache.dolphinscheduler.api.service.impl.WorkerGroupServiceImpl$$FastClassBySpringCGLIB$$35aefd7a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at org.apache.dolphinscheduler.api.service.impl.WorkerGroupServiceImpl$$EnhancerBySpringCGLIB$$1f39b5c6.queryAllGroupPaging(<generated>)
	at org.apache.dolphinscheduler.api.controller.WorkerGroupController.queryAllWorkerGroupsPaging(WorkerGroupController.java:122)
	at org.apache.dolphinscheduler.api.controller.WorkerGroupController$$FastClassBySpringCGLIB$$2d4d455a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)`

### What you expected to happen

Is there a specific JDK version required for dolphinscheduler-2.0.0-alpha

### How to reproduce

jdk: jdk1.8.0_301

### Anything else

Every time

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
@felixlin47 

I understand that this is a bug of JDK1.8, similar to the following situation: https://bugs.openjdk.java.net/browse/JDK-8031085. Would you like to submit a PR and use another method to implement this function?

**Comment by zhuangchong** [comment]
Fixed #7205
