### ISSUE TITLE
[Bug] [Master] Failed to operate workflow node separately

### ISSUE THREAD

**Issue by shangeyao** [apache/dolphinscheduler#6657]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/42203474/139636648-2b175530-996c-48bb-82ff-46b8a6ea39ba.png)
Failed to operate workflow node alone. No new task instance is generated.
version: dev
There are no problems in the version of 2.0-alpha-release.

### What you expected to happen

 Operate workflow node separately and generate new task instance.

### How to reproduce

Operate workflow node separately.

### Anything else
```java
[ERROR] 2021-11-01 15:30:35.452 org.apache.dolphinscheduler.dao.utils.DagHelper:[112] - start node name [a] is not in task node list [[TaskNode{id='null', code=851434614521856, version=1, name='a', desc='', type='SHELL', runFlag='NORMAL', loc='null', maxRetryTimes=0, retryInterval=1, params='{"resourceList":[],"localParams":[],"rawScript":"echo \"a\"","waitStartTimeout":{},"switchResult":{}}', preTasks='[]', preTaskNodeList=null, extras='null', depList=[], dependence='{}', conditionResult='{"successNode":[""],"failedNode":[""]}', taskInstancePriority=MEDIUM, workerGroup='default', environmentCode=-1, timeout='{"enable":false,"strategy":null,"interval":0}', delayTime=0}]] 
[ERROR] 2021-11-01 15:30:35.452 org.apache.dolphinscheduler.dao.utils.DagHelper:[112] - start node name [a] is not in task node list [[TaskNode{id='null', code=851434614521856, version=1, name='a', desc='', type='SHELL', runFlag='NORMAL', loc='null', maxRetryTimes=0, retryInterval=1, params='{"resourceList":[],"localParams":[],"rawScript":"echo \"a\"","waitStartTimeout":{},"switchResult":{}}', preTasks='[]', preTaskNodeList=null, extras='null', depList=[], dependence='{}', conditionResult='{"successNode":[""],"failedNode":[""]}', taskInstancePriority=MEDIUM, workerGroup='default', environmentCode=-1, timeout='{"enable":false,"strategy":null,"interval":0}', delayTime=0}]] 
[ERROR] 2021-11-01 15:30:35.453 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[512] - processDag is null
[ERROR] 2021-11-01 15:30:35.453 org.apache.dolphinscheduler.dao.utils.DagHelper:[112] - start node name [job_b1] is not in task node list [[TaskNode{id='null', code=851435467538432, version=1, name='job_b1', desc='', type='SHELL', runFlag='NORMAL', loc='null', maxRetryTimes=0, retryInterval=1, params='{"resourceList":[],"localParams":[],"rawScript":"echo \"b1\"","waitStartTimeout":{},"switchResult":{}}', preTasks='[851437597130752]', preTaskNodeList=null, extras='null', depList=[851437597130752], dependence='{}', conditionResult='{"successNode":[""],"failedNode":[""]}', taskInstancePriority=MEDIUM, workerGroup='default', environmentCode=-1, timeout='{"enable":false,"strategy":null,"interval":0}', delayTime=0}, TaskNode{id='null', code=851437597130752, version=2, name='depend_a', desc='', type='DEPENDENT', runFlag='NORMAL', loc='null', maxRetryTimes=0, retryInterval=1, params='{"waitStartTimeout":{"strategy":"FAILED","interval":null,"checkInterval":null,"enable":false},"switchResult":{}}', preTasks='[]', preTaskNodeList=null, extras='null', depList=[], dependence='{"relation":"AND","dependTaskList":[{"relation":"AND","dependItemList":[{"projectCode":851275541217280,"definitionCode":851435217125376,"depTasks":"a","cycle":"day","dateValue":"today"}]}]}', conditionResult='{"successNode":[""],"failedNode":[""]}', taskInstancePriority=MEDIUM, workerGroup='default', environmentCode=-1, timeout='{"enable":false,"strategy":null,"interval":0}', delayTime=0}, TaskNode{id='null', code=851436591874048, version=1, name='job_b2', desc='', type='SHELL', runFlag='NORMAL', loc='null', maxRetryTimes=0, retryInterval=1, params='{"resourceList":[],"localParams":[],"rawScript":"echo \"b2\"","waitStartTimeout":{},"switchResult":{}}', preTasks='[851437597130752]', preTaskNodeList=null, extras='null', depList=[851437597130752], dependence='{}', conditionResult='{"successNode":[""],"failedNode":[""]}', taskInstancePriority=MEDIUM, workerGroup='default', environmentCode=-1, timeout='{"enable":false,"strategy":null,"interval":0}', delayTime=0}]] 
[ERROR] 2021-11-01 15:30:35.453 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[512] - processDag is null
[ERROR] 2021-11-01 15:30:35.453 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[512] - processDag is null
[ERROR] 2021-11-01 15:30:35.454 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[195] - handler error:
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.dao.utils.DagHelper.parsePostNodes(DagHelper.java:301)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.submitPostNode(WorkflowExecuteThread.java:797)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.startProcess(WorkflowExecuteThread.java:464)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.run(WorkflowExecuteThread.java:192)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] 2021-11-01 15:30:35.454 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[195] - handler error:
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.dao.utils.DagHelper.parsePostNodes(DagHelper.java:301)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.submitPostNode(WorkflowExecuteThread.java:797)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.startProcess(WorkflowExecuteThread.java:464)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.run(WorkflowExecuteThread.java:192)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] 2021-11-01 15:30:35.454 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[195] - handler error:
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.dao.utils.DagHelper.parsePostNodes(DagHelper.java:301)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.submitPostNode(WorkflowExecuteThread.java:797)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.startProcess(WorkflowExecuteThread.java:464)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.run(WorkflowExecuteThread.java:192)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
```
### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by boy-xiaozhang** [comment]
hi, this error is the dev code has a judgment logic, I will fix it today @dailidong Can you assign this problem to me

**Comment by davidzollo** [comment]
> hi, this error is the dev code has a judgment logic, I will fix it today @dailidong Can you assign this problem to me

done
