### ISSUE TITLE
[Question] [JdbcDataSourceProvider] Get jdbcUrl without adding other parameters

### ISSUE THREAD

**Issue by jon-qj** [apache/dolphinscheduler#7011]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Get jdbcUrl without adding other parameters
![image](https://user-images.githubusercontent.com/39773194/143546272-9b164d37-554e-483f-9e60-7d28d03cd35e.png)
and something goes wrong:

java.sql.SQLException: Could not open client transport with JDBC Uri: jdbc:hive2://bigdata001:2181/default;principal=hive/_HOST@BIGDATA: null
........
Caused by: org.apache.thrift.transport.TTransportException: null
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132) ~[libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86) ~[libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.transport.TSaslTransport.receiveSaslMessage(TSaslTransport.java:178) ~[libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:277) ~[libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:37) ~[libthrift-0.9.3.jar:0.9.3]
	at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport$1.run(TUGIAssumingTransport.java:52) ~[hive-shims-common-2.1.0.jar:2.1.0]
	at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport$1.run(TUGIAssumingTransport.java:49) ~[hive-shims-common-2.1.0.jar:2.1.0]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_291]
	at javax.security.auth.Subject.doAs(Subject.java:422) ~[na:1.8.0_291]
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698) ~[hadoop-common-2.7.3.jar:na]
	at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport.open(TUGIAssumingTransport.java:49) ~[hive-shims-common-2.1.0.jar:2.1.0]
	at org.apache.hive.jdbc.HiveConnection.openTransport(HiveConnection.java:195) ~[hive-jdbc-2.1.0.jar:2.1.0]
	... 120 common frames omitted

### What you expected to happen

jdbcUrl is connected successfully

### How to reproduce

As shown by dev branch.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
The other parameter will be added when the connection pool is generated
