### ISSUE TITLE
[Bug] [MasterServer] NPE when run switch task

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#7062]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

```
[INFO] 2021-11-30 14:18:48.516 org.apache.dolphinscheduler.service.process.ProcessService:[1122] - start submit task : switch, instance id:1570, state: RUNNING_EXECUTION
[INFO] 2021-11-30 14:18:48.517 org.apache.dolphinscheduler.service.process.ProcessService:[1136] - end submit task to db successfully:1723 switch state:SUBMITTED_SUCCESS complete, instance id:1570 state: RUNNING_EXECUTION  
[ERROR] 2021-11-30 14:18:48.521 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[770] - submit standby task error
java.lang.NullPointerException: null
        at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.setTaskExecutionLogger(BaseTaskProcessor.java:227)
        at org.apache.dolphinscheduler.server.master.runner.task.SwitchTaskProcessor.submit(SwitchTaskProcessor.java:78)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.submitTaskExec(WorkflowExecuteThread.java:747)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.submitStandByTask(WorkflowExecuteThread.java:1410)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.submitPostNode(WorkflowExecuteThread.java:1019)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.taskFinished(WorkflowExecuteThread.java:410)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.taskStateChangeHandler(WorkflowExecuteThread.java:366)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.stateEventHandler(WorkflowExecuteThread.java:311)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.handleEvents(WorkflowExecuteThread.java:258)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.run(WorkflowExecuteThread.java:239)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
I found that the taskInstance of BaseProcessor is null.

### What you expected to happen

task run without NPE exception.

### How to reproduce

run switch task.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
this issue is for dev, not 2.0.1-release @lenboo
