### ISSUE TITLE
[BUG][DOCKER] docker compose api server failed 

### ISSUE THREAD

**Issue by abdulle-sabaf** [apache/dolphinscheduler#7088]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

OS: Centos 7 kernel 3.10.0
memory: 8G
Followed the instruction at [https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/installation/docker.html](https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/installation/docker.html) 
with Docker 20.10.7 and Docker Compose 2.2.1
Success in starting PostgreSQL, Zookeeper, the master and the worker server, failed to start the API server (keep restarting). Logs show that the connection to 127.0.0.1:5432 was refused.

### What you expected to happen

Failed to connect the api at 127.0.0.1:12345/dolphinscheduler.

### How to reproduce

Follow the instruction at [https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/installation/docker.html](https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/installation/docker.html) 

### Version

2.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MichaelPorter0** [comment]
I have the same problem：
![1638516442](https://user-images.githubusercontent.com/38281116/144562416-a42ffe2f-3bc9-4db8-b90e-c09359feaaf5.png)
The api cannot up
This is the problem with PostgreSQL, I also can not connect to PostgreSQL,but i can confirm my PostgreSQL is start;
![1638516597(1)](https://user-images.githubusercontent.com/38281116/144562736-d1dc1e3a-7a97-441b-85c8-e4a5d8a49335.png)

**Comment by calvinjiang** [comment]
Seems like the PostgreSQL server can not be connected by the other containers. I have the same problem.

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/apache/dolphinscheduler/dao/datasource/SpringConnectionFactory.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.druid.pool.DruidDataSource]: Factory method 'dataSource' threw exception; nested exception is org.postgresql.util.PSQLException: Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627)

at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456)

at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1318)

at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1158)

at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554)

at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)

at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)

at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)

at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)

at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)

at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.resolveBeanReference(ConfigurationClassEnhancer.java:394)

at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:366)

at org.apache.dolphinscheduler.dao.datasource.SpringConnectionFactory$$EnhancerBySpringCGLIB$$8ade7aaf.dataSource(<generated>)

at org.apache.dolphinscheduler.dao.datasource.SpringConnectionFactory.sqlSessionFactory(SpringConnectionFactory.java:138)

at org.apache.dolphinscheduler.dao.datasource.SpringConnectionFactory$$EnhancerBySpringCGLIB$$8ade7aaf.CGLIB$sqlSessionFactory$0(<generated>)

at org.apache.dolphinscheduler.dao.datasource.SpringConnectionFactory$$EnhancerBySpringCGLIB$$8ade7aaf$$FastClassBySpringCGLIB$$3f556205.invoke(<generated>)

at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)

at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)

at org.apache.dolphinscheduler.dao.datasource.SpringConnectionFactory$$EnhancerBySpringCGLIB$$8ade7aaf.sqlSessionFactory(<generated>)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)

... 68 more

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.druid.pool.DruidDataSource]: Factory method 'dataSource' threw exception; nested exception is org.postgresql.util.PSQLException: Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)

at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)

... 91 more

Caused by: org.postgresql.util.PSQLException: Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:280)

at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)

at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)

at org.postgresql.Driver.makeConnection(Driver.java:454)

at org.postgresql.Driver.connect(Driver.java:256)

at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1652)

at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1718)

at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:914)

at org.apache.dolphinscheduler.dao.datasource.SpringConnectionFactory.dataSource(SpringConnectionFactory.java:108)

at org.apache.dolphinscheduler.dao.datasource.SpringConnectionFactory$$EnhancerBySpringCGLIB$$8ade7aaf.CGLIB$dataSource$5(<generated>)

at org.apache.dolphinscheduler.dao.datasource.SpringConnectionFactory$$EnhancerBySpringCGLIB$$8ade7aaf$$FastClassBySpringCGLIB$$3f556205.invoke(<generated>)

at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)

at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)

at org.apache.dolphinscheduler.dao.datasource.SpringConnectionFactory$$EnhancerBySpringCGLIB$$8ade7aaf.dataSource(<generated>)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)

... 92 more

Caused by: java.net.ConnectException: Connection refused (Connection refused)

at java.net.PlainSocketImpl.socketConnect(Native Method)

at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)

at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)

at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)

at java.net.Socket.connect(Socket.java:607)

at org.postgresql.core.PGStream.<init>(PGStream.java:70)

at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:91)

at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)

... 110 more
```

**Comment by calvinjiang** [comment]
The issue is probably caused by the wrong settings of ip address to PostgreSQL. 

In a master/worker/api container , it can not connect another container through '127.0.0.1:5432'. 
```
Connection to 127.0.0.1:5432 refused
```

**Comment by calvinjiang** [comment]
I will try to fix the issue.

**Comment by graphnj** [comment]
1. in docker-compose.yml set container_name to ds_postgresql or other fixed name.
2. change 127.0.0.1:5432 in container to ds_postgresql:5432 in container of apache/dolphinscheduler:2.0.0
3. commit this container to images local.
4. change image's tag in docker-compose.yml to new images.

can work now

本质只要将镜像中conf/datasource.properties的spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/dolphinscheduler改为
spring.datasource.url=jdbc:postgresql://ds-postgresql:5432/dolphinscheduler
ds-postgresql为定义的容器名

**Comment by opcooc** [comment]
same question!!!

**Comment by MichaelPorter0** [comment]
> 1. in docker-compose.yml set container_name to ds_postgresql or other fixed name.
> 2. change 127.0.0.1:5432 in container to ds_postgresql:5432 in container of apache/dolphinscheduler:2.0.0
> 3. commit this container to images local.
> 4. change image's tag in docker-compose.yml to new images.
> 
> can work now
> 
> 本质只要将镜像中conf/datasource.properties的spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/dolphinscheduler改为 spring.datasource.url=jdbc:postgresql://ds-postgresql:5432/dolphinscheduler ds-postgresql为定义的容器名

It seems to be effective, but a new problem has arisen
![企业微信截图_1639030438356](https://user-images.githubusercontent.com/38281116/145344015-e3255379-da9c-407f-a64e-c02e6a38f6d4.png)

**Comment by HeChuanXUPT** [comment]
same problem, this should be tested before it is released.

https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/guide/installation/docker.html

球球大佬们赶紧修复啊，官网的示例都走不下去了
