### ISSUE TITLE
[Bug] [DOCKER] apache/dolphinscheduler:2.0.0 image , column "state" not exist in t_ds_user

### ISSUE THREAD

**Issue by graphnj** [apache/dolphinscheduler#7196]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

[INFO] 2021-12-05 18:42:23.832 org.apache.dolphinscheduler.api.aspect.AccessLogAspect:[76] - REQUEST TRANCE_ID:01aadf72-c476-4cae-9ebb-4decaaa17686, LOGIN_USER:NOT LOGIN, URI:/dolphinscheduler/login, METHOD:POST, HANDLER:org.apache.dolphinscheduler.api.controller.LoginController.login, ARGS:{userName=admin}
[ERROR] 2021-12-05 18:42:23.838 org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[46] - 用户登录失败
org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: column "state" does not exist
  Position: 124
### Cause: org.postgresql.util.PSQLException: ERROR: column "state" does not exist
  Position: 124
; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: column "state" does not exist
  Position: 124
        at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:101)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:74)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
        at com.sun.proxy.$Proxy101.selectOne(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:159)
        at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:89)
        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61)
        at com.sun.proxy.$Proxy106.queryUserByNamePassword(Unknown Source)
        at org.apache.dolphinscheduler.api.service.impl.UsersServiceImpl.queryUser(UsersServiceImpl.java:287)
        at org.apache.dolphinscheduler.api.service.impl.UsersServiceImpl$$FastClassBySpringCGLIB$$ac00af33.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
        at org.apache.dolphinscheduler.api.service.impl.UsersServiceImpl$$EnhancerBySpringCGLIB$$1302d40b.queryUser(<generated>)
        at org.apache.dolphinscheduler.api.security.impl.pwd.PasswordAuthenticator.login(PasswordAuthenticator.java:32)
        at org.apache.dolphinscheduler.api.security.impl.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:60)
        at org.apache.dolphinscheduler.api.controller.LoginController.login(LoginController.java:104)
        at org.apache.dolphinscheduler.api.controller.LoginController$$FastClassBySpringCGLIB$$a36f5ae2.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpo

### What you expected to happen

login system normal.

### How to reproduce

use dolphinscheduler:2.0.0 docker image, and exec docker-compose up -d.

其实应该先解决掉连接pg库127.0.0.1连不上，那个问题

### Version

2.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I will fix this issue.

**Comment by calvinjiang** [comment]
It's easy to fix the issue with connection between docker contains.  But there are a few problems in the whole process of initializing database. So I need to fix the process of initializing database first.

**Comment by caishunfeng** [comment]
The bug had been fixed and this issue will be closed.
