### ISSUE TITLE
[Bug] [2.0.0-release]  Failed to create tenant using S3a Minio

### ISSUE THREAD

**Issue by putianhui** [apache/dolphinscheduler#7236]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I failed to create tenant when using store as S3a Minio。
The following is my configuration。
```bash
# cat conf/config/install_config.conf |egrep -v "^#|^$"
ips="survey-cdh01,survey-cdh02,survey-cdh03"
sshPort="22"
masters="survey-cdh01,survey-cdh02"
workers="survey-cdh01,survey-cdh02,survey-cdh03"
alertServer="survey-cdh01"
apiServers="survey-cdh01"
installPath="/data/apache-dolphinscheduler-1.3.9/dolphinscheduler"
deployUser="root"
dataBasedirPath="/tmp/dolphinscheduler"
javaHome="/usr/java/jdk1.8.0_181-cloudera"
apiServerPort="12345"
dbtype="mysql"
dbhost="survey-cdh01:3306"
username="dolphinscheduler"
password="dolphinscheduler"
dbname="dolphinscheduler"
registryPluginDir="lib/plugin/registry/zookeeper"
registryPluginName="zookeeper"
registryServers="survey-cdh01:2181,survey-cdh02:2181,survey-cdh03:2181"
zkRoot="/dolphinscheduler"
alertPluginDir="lib/plugin/alert"
taskPluginDir="lib/plugin/task"

resourceStorageType="S3"
resourceUploadPath="/dolphinscheduler"
defaultFS="s3a://dolphinscheduler"
s3Endpoint="http://survey-minio.xxx.com"
s3AccessKey="root"
s3SecretKey="rootroot"

resourceManagerHttpAddressPort="8088"
yarnHaIps="192.168.xx.xx,192.168.xx.xx"
singleYarnIp="yarnIp1"
hdfsRootUser="root"
kerberosStartUp="false"
krb5ConfPath="$installPath/conf/krb5.conf"
keytabUserName="hdfs-mycluster\\@ESZ.COM"
keytabPath="$installPath/conf/hdfs.headless.keytab"
kerberosExpireTime="2"
sudoEnable="false"
workerTenantAutoCreate="true"
```
Survey-minio.xxx.com is my Minio server API address,The bucket and directory exist on the Minio server.

![image](https://user-images.githubusercontent.com/68322685/144990293-2d20a949-13bb-488c-9726-f44e1c4fb372.png)

An error occurs when I create a tenant on the console。
![image](https://user-images.githubusercontent.com/68322685/144990544-f339976f-7185-4f73-9dca-041d48cce644.png)

dolphinscheduler-api.log The error information is as follows
```bash
# tail -200 logs/dolphinscheduler-api.log
[INFO] 2021-12-07 16:07:05.645 org.apache.dolphinscheduler.api.aspect.AccessLogAspect:[76] - REQUEST TRANCE_ID:e5437c60-1991-4da7-8c39-6246bec365e3, LOGIN_USER:admin, URI:/dolphinscheduler/queues/list, METHOD:GET, HANDLER:org.apache.dolphinscheduler.api.controller.QueueController.queryList, ARGS:{}
[INFO] 2021-12-07 16:07:09.564 org.apache.dolphinscheduler.api.aspect.AccessLogAspect:[76] - REQUEST TRANCE_ID:278cfb2f-67d3-4342-aba6-3c5ba47bd625, LOGIN_USER:admin, URI:/dolphinscheduler/tenants/verify-code, METHOD:GET, HANDLER:org.apache.dolphinscheduler.api.controller.TenantController.verifyTenantCode, ARGS:{tenantCode=root}
[INFO] 2021-12-07 16:07:09.668 org.apache.dolphinscheduler.api.aspect.AccessLogAspect:[76] - REQUEST TRANCE_ID:3ef77ec2-d16e-4e35-b347-17e60dbbe5f9, LOGIN_USER:admin, URI:/dolphinscheduler/tenants, METHOD:POST, HANDLER:org.apache.dolphinscheduler.api.controller.TenantController.createTenant, ARGS:{queueId=1, description=, tenantCode=root}
[ERROR] 2021-12-07 16:07:09.673 org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[46] - 创建租户错误
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.common.utils.HadoopUtils.mkdir(HadoopUtils.java:277)
	at org.apache.dolphinscheduler.api.service.impl.BaseServiceImpl.createTenantDirIfNotExists(BaseServiceImpl.java:135)
	at org.apache.dolphinscheduler.api.service.impl.TenantServiceImpl.createTenant(TenantServiceImpl.java:116)
	at org.apache.dolphinscheduler.api.service.impl.TenantServiceImpl$$FastClassBySpringCGLIB$$fcc8d845.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:752)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at org.apache.dolphinscheduler.api.service.impl.TenantServiceImpl$$EnhancerBySpringCGLIB$$89fb9fab.createTenant(<generated>)
	at org.apache.dolphinscheduler.api.controller.TenantController.createTenant(TenantController.java:91)
	at org.apache.dolphinscheduler.api.controller.TenantController$$FastClassBySpringCGLIB$$24aaa089.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:752)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at org.apache.dolphinscheduler.api.aspect.AccessLogAspect.doAround(AccessLogAspect.java:87)
	at sun.reflect.GeneratedMethodAccessor147.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at org.apache.dolphinscheduler.api.controller.TenantController$$EnhancerBySpringCGLIB$$527efca8.createTenant(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1633)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:97)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1609)
	at com.github.xiaoymin.swaggerbootstrapui.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:84)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1609)
	at com.github.xiaoymin.swaggerbootstrapui.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1609)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1609)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1609)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:94)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1609)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1609)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:561)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1612)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1582)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:766)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.lang.Thread.run(Thread.java:748)
```

### What you expected to happen

I failed to create tenant when using store as S3a Minio。

### How to reproduce

I failed to create tenant when using store as S3a Minio。

### Version

2.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by putianhui** [comment]
I used the demo to test the 'dolphinscheduler' under 'dolphinscheduler' and the user and password 'root / rootroot'. The account has access rights
![image](https://user-images.githubusercontent.com/68322685/144991978-454f1ac1-e277-40c8-a611-6547c8c554d9.png)

**Comment by putianhui** [comment]
dolphinscheduler is MinIO bucketname，survey-minio.zxkw-local.com is MinIO API。
Why is' bucketname 'spliced in front of the Minio domain name in the error log
最终请求的MinIO server地址是dolphinscheduler.survey-minio.zxkw-local.com


error log 
```bash
[INFO] 2021-12-07 16:32:51.918 com.amazonaws.http.AmazonHttpClient:[448] - Unable to execute HTTP request: dolphinscheduler.survey-minio.zxkw-local.com
java.net.UnknownHostException: dolphinscheduler.survey-minio.zxkw-local.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.resolveHostname(DefaultClientConnectionOperator.java:259)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:384)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:232)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3528)
	at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1031)
	at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:994)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:297)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:172)
```

**Comment by liqiquan** [comment]
我遇到了同样的问题，正在解决中。你可以尝试直接使用ip地址，s3Endpoint=192.168.xxx.xxx:xxxx,这样应该是可以正常运行的。
原因：org.apache.hadoop:hadoop-ws:2.7.3
AmazonS3Client.java的validIP()方法中，强制判断endpoint的host必须是ip，不能是域名，否则就会倒装拼接host：bucket + endpoind。也就会出现奇怪的域名：dolphinscheduler.survey-minio.zxkw-local.com
可能的解决方法：
方法一：minio搭建的方式有问题，minio应该是可以支持这种倒装域名的
方式二：升级hadoop-aws的版本到高版本，例如2.8.5，加入新的参数配置fs.s3a.path.style.access=ture，禁止倒装拼接域名

I ran into the same problem and it is being solved. You can try to use the ip address directly, s3Endpoint=192.168.xxx.xxx:xxxx, it should work normally.
Reason: org.apache.hadoop:hadoop-ws:2.7.3
In the validIP() method of AmazonS3Client.java, it is mandatory to judge that the host of the endpoint must be an ip, not a domain name, otherwise the host will be flipped and spliced: bucket + endpoind. There will also be a strange domain name: dolphinscheduler.survey-minio.zxkw-local.com
Possible solutions:
Method 1: There is a problem with the way minio is built, minio should be able to support this flipped domain name
Method 2: Upgrade the hadoop-aws version to a higher version, such as 2.8.5, add a new parameter configuration fs.s3a.path.style.access=ture, and prohibit flipping and splicing domain names

**Comment by putianhui** [comment]
> 
感谢你!
我的MinIO是一个分布式的，使用Nginx做了一个负载均衡。
假如使用IP:Port方式，可能就没办法保证高可用了。

Thank you!
My Minio is distributed and uses nginx for load balancing.
If you use IP: port mode, you may not be able to ensure high availability.
