### ISSUE TITLE
[Bug] [Master] java.lang.IllegalStateException: Duplicate key TaskDefinition

### ISSUE THREAD

**Issue by devosend** [apache/dolphinscheduler#7313]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

```
java.lang.IllegalStateException: Duplicate key TaskDefinition{id=21, code=3799787826304, name='n1', version=1, description='', projectCode=3799785146368, userId=3, taskType=SHELL, taskParams='{"resourceList":[],"localParams":[],"rawScript":"echo \"hello\"","dependence":{},"conditionResult":{"successNode":[],"failedNode":[]},"waitStartTimeout":{},"switchResult":{}}', taskParamList=null, taskParamMap=null, flag=YES, taskPriority=MEDIUM, userName='null', projectName='null', workerGroup='default', failRetryTimes=0, environmentCode='-1', failRetryInterval=1, timeoutFlag=CLOSE, timeoutNotifyStrategy=null, timeout=0, delayTime=0, resourceIds='', createTime=Fri Dec 10 14:06:10 CST 2021, updateTime=Fri Dec 10 14:06:10 CST 2021}
	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133) ~[na:1.8.0_231]
	at java.util.HashMap.merge(HashMap.java:1254) ~[na:1.8.0_231]
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320) ~[na:1.8.0_231]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[na:1.8.0_231]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_231]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_231]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_231]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_231]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_231]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_231]
	at org.apache.dolphinscheduler.service.process.ProcessService.transformTask(ProcessService.java:2480) ~[classes/:na]
	at org.apache.dolphinscheduler.service.process.ProcessService$$FastClassBySpringCGLIB$$ed138739.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.12.jar:5.3.12]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.3.12.jar:5.3.12]
	at org.apache.dolphinscheduler.service.process.ProcessService$$EnhancerBySpringCGLIB$$900ffd86.transformTask(<generated>) ~[classes/:na]
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.buildFlowDag(WorkflowExecuteThread.java:733) ~[classes/:na]
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.startProcess(WorkflowExecuteThread.java:666) ~[classes/:na]
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.run(WorkflowExecuteThread.java:259) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_231]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_231]
```

### What you expected to happen

shell task execution.

### How to reproduce

Run DS with Standalone. create three sample shell task like this.
![image](https://user-images.githubusercontent.com/8847400/145526265-4c2b757e-b6cc-4076-8b83-ca2073313a7c.png)

online and run this workflow.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
#7333

**Comment by lenboo** [comment]
close duplicate issue.
