### ISSUE TITLE
[Bug] [sql] duplicate key value violates unique constraint "t_ds_error_command_pkey" in v2.0.1

### ISSUE THREAD

**Issue by wangbowen1024** [apache/dolphinscheduler#7504]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

```
[ERROR] 2021-12-20 16:22:52.859 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[178] - master scheduler thread error
org.springframework.dao.DuplicateKeyException: 
### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "t_ds_error_command_pkey"
  Detail: Key (id)=(12) already exists.
### The error may exist in org/apache/dolphinscheduler/dao/mapper/ErrorCommandMapper.java (best guess)
### The error may involve org.apache.dolphinscheduler.dao.mapper.ErrorCommandMapper.insert-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO t_ds_error_command  ( id,  warning_type, command_type, dry_run, environment_code, executor_id, update_time, warning_group_id, task_depend_type, message, process_definition_code, failure_strategy, start_time,  command_param, process_instance_priority )  VALUES  ( ?,  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,  ?, ? )
### Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "t_ds_error_command_pkey"
  Detail: Key (id)=(12) already exists.
; ERROR: duplicate key value violates unique constraint "t_ds_error_command_pkey"
  Detail: Key (id)=(12) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "t_ds_error_command_pkey"
  Detail: Key (id)=(12) already exists.
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:247)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:74)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
        at com.sun.proxy.$Proxy83.insert(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:271)
        at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:58)
        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61)
        at com.sun.proxy.$Proxy96.insert(Unknown Source)
        at org.apache.dolphinscheduler.service.process.ProcessService.moveToErrorCommand(ProcessService.java:240)
        at org.apache.dolphinscheduler.service.process.ProcessService$$FastClassBySpringCGLIB$$ed138739.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
        at org.apache.dolphinscheduler.service.process.ProcessService$$EnhancerBySpringCGLIB$$50904475.moveToErrorCommand(<generated>)
        at org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService.scheduleProcess(MasterSchedulerService.java:222)
        at org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService.run(MasterSchedulerService.java:176)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "t_ds_error_command_pkey"
  Detail: Key (id)=(12) already exists.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
        at sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
        at com.sun.proxy.$Proxy111.update(Unknown Source)
        at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:54)
        at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
        at sun.reflect.GeneratedMethodAccessor237.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
        ... 12 common frames omitted
```

### What you expected to happen

i think pg sql have some problem

### How to reproduce

After running for a while, I'm not sure if IT's just me

### Version

2.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangbowen1024** [comment]
and i find v1.4.0 in t_ds_version table, so it's right?

**Comment by lenboo** [comment]
> and i find v1.4.0 in t_ds_version table, so it's right?

i think we can fix it in 2.0.2

**Comment by wangbowen1024** [comment]
> > and i find v1.4.0 in t_ds_version table, so it's right?
> 
> i think we can fix it in 2.0.2

emmm,I don't mean the problem with the version information.
I traced the source code and logs again and noticed that the`MasterSchedulerService` was executing 2 times:
`find one command: id: 3, type: START_PROCESS` . the logs :
```
[INFO] 2021-12-21 00:00:20.326 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[250] - find command 4, slot:0 :
[INFO] 2021-12-21 00:00:20.327 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[192] - find one command: id: 4, type: START_PROCESS
[INFO] 2021-12-21 00:00:20.361 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[216] - handle command end, command 4 process 510 start...
[INFO] 2021-12-21 00:00:20.362 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[250] - find command 4, slot:0 :
[INFO] 2021-12-21 00:00:20.362 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[192] - find one command: id: 4, type: START_PROCESS
[ERROR] 2021-12-21 00:00:20.366 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[221] - scan command error 
org.apache.dolphinscheduler.service.exceptions.ServiceException: delete command fail, id:4
        at org.apache.dolphinscheduler.service.process.ProcessService.deleteCommandWithCheck(ProcessService.java:2479)
        at org.apache.dolphinscheduler.service.process.ProcessService.handleCommand(ProcessService.java:228)
        at org.apache.dolphinscheduler.service.process.ProcessService$$FastClassBySpringCGLIB$$ed138739.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
        at org.apache.dolphinscheduler.service.process.ProcessService$$EnhancerBySpringCGLIB$$50904475.handleCommand(<generated>)
        at org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService.scheduleProcess(MasterSchedulerService.java:194)
        at org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService.run(MasterSchedulerService.java:176)
[INFO] 2021-12-21 00:00:20.370 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[1170] - add task to stand by list: ppp
[ERROR] 2021-12-21 00:00:20.372 org.apache.dolphinscheduler.service.process.ProcessService:[1043] - task commit to mysql failed
java.lang.NullPointerException: null
        at org.apache.dolphinscheduler.service.process.ProcessService.submitTask(ProcessService.java:1061)
        at org.apache.dolphinscheduler.service.process.ProcessService.submitTask(ProcessService.java:1032)
        at org.apache.dolphinscheduler.service.process.ProcessService$$FastClassBySpringCGLIB$$ed138739.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
        at org.apache.dolphinscheduler.service.process.ProcessService$$EnhancerBySpringCGLIB$$50904475.submitTask(<generated>)
        at org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor.submit(CommonTaskProcessor.java:68)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.submitTaskExec(WorkflowExecuteThread.java:620)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.submitStandByTask(WorkflowExecuteThread.java:1273)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.submitPostNode(WorkflowExecuteThread.java:888)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.startProcess(WorkflowExecuteThread.java:505)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.run(WorkflowExecuteThread.java:227)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[ERROR] 2021-12-21 00:00:20.374 org.apache.dolphinscheduler.service.process.ProcessService:[1043] - task commit to mysql failed
java.lang.NullPointerException: null
        at org.apache.dolphinscheduler.service.process.ProcessService.submitTask(ProcessService.java:1061)
        at org.apache.dolphinscheduler.service.process.ProcessService.submitTask(ProcessService.java:1032)
        at org.apache.dolphinscheduler.service.process.ProcessService$$FastClassBySpringCGLIB$$ed138739.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
        at org.apache.dolphinscheduler.service.process.ProcessService$$EnhancerBySpringCGLIB$$50904475.submitTask(<generated>)
```
so, i have 2 problem:
1. why the master will select 2 of the same command?
2. ` task commit to mysql failed` i use pg, why have show mysql? and null?

do you know?

**Comment by wangbowen1024** [comment]
supplement：
the mysql i maybe know why:
```java
 catch (Exception e) {
    logger.error("task commit to mysql failed", e);
}
```

but i think the 2 times run the same command is key point

**Comment by wangbowen1024** [comment]
i show src **v1.3.6** about MasterSchedulerService.java, i see the zk lock before `findOneCommand()` and `handleCommand()`:
![image](https://user-images.githubusercontent.com/48642743/146813212-7c806fb9-21a1-48df-b35f-b0444577fac0.png)

**but in v2.0.1**:
![image](https://user-images.githubusercontent.com/48642743/146813414-1b41dd5c-47de-47b2-98f4-3b982462037e.png)

I guess there's something wrong here? I don't have the skills to prove it. Can someone take a look at it? thank you

**Comment by wangbowen1024** [comment]
**by the way, the doc show** :

![image](https://user-images.githubusercontent.com/48642743/146815230-8d40be3b-4f76-44d1-9710-265b3f8567c8.png)

**Comment by lenboo** [comment]
> i show src **v1.3.6** about MasterSchedulerService.java, i see the zk lock before `findOneCommand()` and `handleCommand()`: ![image](https://user-images.githubusercontent.com/48642743/146813212-7c806fb9-21a1-48df-b35f-b0444577fac0.png)
> 
> **but in v2.0.1**: ![image](https://user-images.githubusercontent.com/48642743/146813414-1b41dd5c-47de-47b2-98f4-3b982462037e.png)
> 
> I guess there's something wrong here? I don't have the skills to prove it. Can someone take a look at it? thank you

yes, we split by command-id for different masters, instead of using the zk lock in version 1.x

**Comment by wangbowen1024** [comment]
This problem disappeared after I changed a PG databases, so I thought it was a database problem, so I closed this problem
