### ISSUE TITLE
[Bug] [Docker] Cannot build docker container with docker-compose 2.X

### ISSUE THREAD

**Issue by HomminLee** [apache/dolphinscheduler#7712]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

docker version: 20.10.12
docker-compose version: v2.1.1

After pull `dolphinscheduler.docker.scarf.sh/apache/dolphinscheduler:latest`, I use command `docker-compose up -d` to build docker containers, but I get exception log:

```
unexpected character "-" in variable name near "-Xmx1g -Xmn512m\nMASTER_EXEC_THREADS=100\nMASTER_EXEC_TASK_NUM=20\nMASTER_DISPATCH_TASK_NUM=3\nMASTER_HOST_SELECTOR=LowerWeight\nMASTER_HEARTBEAT_INTERVAL=10\nMASTER_TASK_COMMIT_RETRYTIMES=5\nMASTER_TASK_COMMIT_INTERVAL=1000\nMASTER_MAX_CPULOAD_AVG=-1\nMASTER_RESERVED_MEMORY=0.3...
...
```

> BTW, I change docker-compose version to 1.29.2, command `docker-compose up -d` will work well.

I read the `config.env.sh`, I think this may be the effect of blank space. (The jvm properties contain blank space, like `MASTER_SERVER_OPTS=-Xms1g -Xmx1g -Xmn512m`)

### What you expected to happen

Quickly install DolphinScheduler by docker-compose.

### How to reproduce

Install docker(version=20.10.12)
Install docker-compose(version=v2.1.1)

Follow this step: https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/installation/docker.html
You will get error when run command `docker-compose up -d`.

### Version

2.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by janeHe13** [comment]
After the above PR test, the docker-compose runs with an error
![image](https://user-images.githubusercontent.com/95271106/149718416-c64515ba-e75d-473b-959a-9cf5766788d7.png)
![image](https://user-images.githubusercontent.com/95271106/149718198-2444a490-5df8-4556-9ae0-6ae0754f737b.png)

**Comment by janeHe13** [comment]
An error will be reported if add ""or '', but it is OK if  do not add a symbol

**Comment by ahvahsky2008** [comment]
Same issue

**Comment by kezhenxu94** [comment]
> After the above PR test, the docker-compose runs with an error
> ![image](https://user-images.githubusercontent.com/95271106/149718416-c64515ba-e75d-473b-959a-9cf5766788d7.png)
> ![image](https://user-images.githubusercontent.com/95271106/149718198-2444a490-5df8-4556-9ae0-6ae0754f737b.png)

I cannot reproduce this after adding the quotes (`"`), I saw you are using a `rc` version of docker-compose, can you try with a stable version?

**Comment by davidzollo** [comment]
is this issue been solved or not?

**Comment by kezhenxu94** [comment]
> is this issue been solved or not?

This is not a reproducible error, we need more information from the user.

**Comment by pipinet** [comment]
@kezhenxu94 
Database migration did not succeed

```log
$ docker-compose up
Creating volume "dolphinscheduler_dolphinscheduler-postgresql" with default driver
Creating volume "dolphinscheduler_dolphinscheduler-zookeeper" with default driver
Creating volume "dolphinscheduler_dolphinscheduler-worker-data" with default driver
Creating volume "dolphinscheduler_dolphinscheduler-logs" with default driver
Creating volume "dolphinscheduler_dolphinscheduler-shared-local" with default driver
Creating volume "dolphinscheduler_dolphinscheduler-resource-local" with default driver
Creating dolphinscheduler_dolphinscheduler-zookeeper_1  ... done
Creating dolphinscheduler_dolphinscheduler-postgresql_1 ... done
Creating dolphinscheduler_dolphinscheduler-schema-initializer_1 ... done

ERROR: for dolphinscheduler-api  Container "888519df87ac" exited with code 1.

ERROR: for dolphinscheduler-master  Container "888519df87ac" exited with code 1.

ERROR: for dolphinscheduler-worker  Container "888519df87ac" exited with code 1.

ERROR: for dolphinscheduler-alert  Container "888519df87ac" exited with code 1.
ERROR: Encountered errors while bringing up the project.
```


```log
$ docker-compose logs -f
dolphinscheduler-schema-initializer_1  | 2022-02-26 12:10:05.383  INFO 9 --- [           main] o.a.d.common.utils.ScriptRunner          : sql: create index process_task_relation_log_idx_project_code_process_definition_code on t_ds_process_task_relation_log (project_code,process_definition_code)
dolphinscheduler-schema-initializer_1  | 2022-02-26 12:10:05.386  INFO 9 --- [           main] o.a.d.common.utils.ScriptRunner          : --
dolphinscheduler-schema-initializer_1  | 2022-02-26 12:10:05.386  INFO 9 --- [           main] o.a.d.common.utils.ScriptRunner          : -- Table structure for table t_ds_process_instance
dolphinscheduler-schema-initializer_1  | 2022-02-26 12:10:05.386  INFO 9 --- [           main] o.a.d.common.utils.ScriptRunner          : --
dolphinscheduler-schema-initializer_1  | 2022-02-26 12:10:05.386  INFO 9 --- [           main] o.a.d.common.utils.ScriptRunner          : sql: DROP TABLE IF EXISTS t_ds_process_instance
dolphinscheduler-schema-initializer_1  | 2022-02-26 12:10:05.395 ERROR 9 --- [           main] o.a.d.common.utils.ScriptRunner          : SQLException
dolphinscheduler-schema-initializer_1  |
dolphinscheduler-schema-initializer_1  | org.postgresql.util.PSQLException: ERROR: cannot drop table t_ds_process_instance because other objects depend on it
dolphinscheduler-schema-initializer_1  |   Detail: constraint foreign_key_instance_id on table t_ds_task_instance depends on table t_ds_process_instance
dolphinscheduler-schema-initializer_1  |   Hint: Use DROP ... CASCADE to drop the dependent objects too.
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94) ~[HikariCP-4.0.3.jar:na]
dolphinscheduler-schema-initializer_1  | 	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-4.0.3.jar:na]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.common.utils.ScriptRunner.runScript(ScriptRunner.java:118) [dolphinscheduler-common-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.common.utils.ScriptRunner.runScript(ScriptRunner.java:73) [dolphinscheduler-common-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.tools.datasource.dao.UpgradeDao.runInitSql(UpgradeDao.java:107) [dolphinscheduler-tools-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.tools.datasource.dao.UpgradeDao.initSchema(UpgradeDao.java:93) [dolphinscheduler-tools-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.tools.datasource.DolphinSchedulerManager.initDolphinSchedulerSchema(DolphinSchedulerManager.java:78) [dolphinscheduler-tools-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.tools.datasource.DolphinSchedulerManager.initDolphinScheduler(DolphinSchedulerManager.java:58) [dolphinscheduler-tools-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.tools.datasource.InitDolphinScheduler$InitRunner.run(InitDolphinScheduler.java:45) [dolphinscheduler-tools-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  | 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791) [spring-boot-2.5.6.jar:2.5.6]
dolphinscheduler-schema-initializer_1  | 	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775) [spring-boot-2.5.6.jar:2.5.6]
dolphinscheduler-schema-initializer_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) [spring-boot-2.5.6.jar:2.5.6]
dolphinscheduler-schema-initializer_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) [spring-boot-2.5.6.jar:2.5.6]
dolphinscheduler-schema-initializer_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) [spring-boot-2.5.6.jar:2.5.6]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.tools.datasource.CreateDolphinScheduler.main(CreateDolphinScheduler.java:30) [dolphinscheduler-tools-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  |
dolphinscheduler-schema-initializer_1  | 2022-02-26 12:10:05.395 ERROR 9 --- [           main] o.a.d.common.utils.ScriptRunner          : Error executing: DROP TABLE IF EXISTS t_ds_process_instance
dolphinscheduler-schema-initializer_1  | 2022-02-26 12:10:05.396 ERROR 9 --- [           main] o.a.d.tools.datasource.dao.UpgradeDao    : ERROR: cannot drop table t_ds_process_instance because other objects depend on it
dolphinscheduler-schema-initializer_1  |   Detail: constraint foreign_key_instance_id on table t_ds_task_instance depends on table t_ds_process_instance
dolphinscheduler-schema-initializer_1  |   Hint: Use DROP ... CASCADE to drop the dependent objects too.
dolphinscheduler-schema-initializer_1  |
dolphinscheduler-schema-initializer_1  | org.postgresql.util.PSQLException: ERROR: cannot drop table t_ds_process_instance because other objects depend on it
dolphinscheduler-schema-initializer_1  |   Detail: constraint foreign_key_instance_id on table t_ds_task_instance depends on table t_ds_process_instance
dolphinscheduler-schema-initializer_1  |   Hint: Use DROP ... CASCADE to drop the dependent objects too.
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94) ~[HikariCP-4.0.3.jar:na]
dolphinscheduler-schema-initializer_1  | 	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-4.0.3.jar:na]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.common.utils.ScriptRunner.runScript(ScriptRunner.java:118) ~[dolphinscheduler-common-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.common.utils.ScriptRunner.runScript(ScriptRunner.java:73) ~[dolphinscheduler-common-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.tools.datasource.dao.UpgradeDao.runInitSql(UpgradeDao.java:107) [dolphinscheduler-tools-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.tools.datasource.dao.UpgradeDao.initSchema(UpgradeDao.java:93) [dolphinscheduler-tools-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.tools.datasource.DolphinSchedulerManager.initDolphinSchedulerSchema(DolphinSchedulerManager.java:78) [dolphinscheduler-tools-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.tools.datasource.DolphinSchedulerManager.initDolphinScheduler(DolphinSchedulerManager.java:58) [dolphinscheduler-tools-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.tools.datasource.InitDolphinScheduler$InitRunner.run(InitDolphinScheduler.java:45) [dolphinscheduler-tools-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  | 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791) [spring-boot-2.5.6.jar:2.5.6]
dolphinscheduler-schema-initializer_1  | 	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775) [spring-boot-2.5.6.jar:2.5.6]
dolphinscheduler-schema-initializer_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) [spring-boot-2.5.6.jar:2.5.6]
dolphinscheduler-schema-initializer_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) [spring-boot-2.5.6.jar:2.5.6]
dolphinscheduler-schema-initializer_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) [spring-boot-2.5.6.jar:2.5.6]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.tools.datasource.CreateDolphinScheduler.main(CreateDolphinScheduler.java:30) [dolphinscheduler-tools-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  |
dolphinscheduler-schema-initializer_1  | 2022-02-26 12:10:05.398  INFO 9 --- [           main] ConditionEvaluationReportLoggingListener :
dolphinscheduler-schema-initializer_1  |
dolphinscheduler-schema-initializer_1  | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
dolphinscheduler-schema-initializer_1  | 2022-02-26 12:10:05.423 ERROR 9 --- [           main] o.s.boot.SpringApplication               : Application run failed
dolphinscheduler-schema-initializer_1  |
dolphinscheduler-schema-initializer_1  | java.lang.IllegalStateException: Failed to execute CommandLineRunner
dolphinscheduler-schema-initializer_1  | 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:794) [spring-boot-2.5.6.jar:2.5.6]
dolphinscheduler-schema-initializer_1  | 	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775) [spring-boot-2.5.6.jar:2.5.6]
dolphinscheduler-schema-initializer_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) [spring-boot-2.5.6.jar:2.5.6]
dolphinscheduler-schema-initializer_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) [spring-boot-2.5.6.jar:2.5.6]
dolphinscheduler-schema-initializer_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) [spring-boot-2.5.6.jar:2.5.6]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.tools.datasource.CreateDolphinScheduler.main(CreateDolphinScheduler.java:30) [dolphinscheduler-tools-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  | Caused by: java.lang.RuntimeException: ERROR: cannot drop table t_ds_process_instance because other objects depend on it
dolphinscheduler-schema-initializer_1  |   Detail: constraint foreign_key_instance_id on table t_ds_task_instance depends on table t_ds_process_instance
dolphinscheduler-schema-initializer_1  |   Hint: Use DROP ... CASCADE to drop the dependent objects too.
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.tools.datasource.dao.UpgradeDao.runInitSql(UpgradeDao.java:110) ~[dolphinscheduler-tools-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.tools.datasource.dao.UpgradeDao.initSchema(UpgradeDao.java:93) ~[dolphinscheduler-tools-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.tools.datasource.DolphinSchedulerManager.initDolphinSchedulerSchema(DolphinSchedulerManager.java:78) ~[dolphinscheduler-tools-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.tools.datasource.DolphinSchedulerManager.initDolphinScheduler(DolphinSchedulerManager.java:58) ~[dolphinscheduler-tools-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.tools.datasource.InitDolphinScheduler$InitRunner.run(InitDolphinScheduler.java:45) ~[dolphinscheduler-tools-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  | 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791) [spring-boot-2.5.6.jar:2.5.6]
dolphinscheduler-schema-initializer_1  | 	... 5 common frames omitted
dolphinscheduler-schema-initializer_1  | Caused by: org.postgresql.util.PSQLException: ERROR: cannot drop table t_ds_process_instance because other objects depend on it
dolphinscheduler-schema-initializer_1  |   Detail: constraint foreign_key_instance_id on table t_ds_task_instance depends on table t_ds_process_instance
dolphinscheduler-schema-initializer_1  |   Hint: Use DROP ... CASCADE to drop the dependent objects too.
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266) ~[postgresql-42.2.5.jar:42.2.5]
dolphinscheduler-schema-initializer_1  | 	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94) ~[HikariCP-4.0.3.jar:na]
dolphinscheduler-schema-initializer_1  | 	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-4.0.3.jar:na]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.common.utils.ScriptRunner.runScript(ScriptRunner.java:118) ~[dolphinscheduler-common-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.common.utils.ScriptRunner.runScript(ScriptRunner.java:73) ~[dolphinscheduler-common-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  | 	at org.apache.dolphinscheduler.tools.datasource.dao.UpgradeDao.runInitSql(UpgradeDao.java:107) ~[dolphinscheduler-tools-2.0.4-SNAPSHOT.jar:2.0.4-SNAPSHOT]
dolphinscheduler-schema-initializer_1  | 	... 10 common frames omitted
dolphinscheduler-schema-initializer_1  |
dolphinscheduler-schema-initializer_1  | 2022-02-26 12:10:05.426  INFO 9 --- [           main] com.zaxxer.hikari.HikariDataSource       : DolphinScheduler - Shutdown initiated...
dolphinscheduler-schema-initializer_1  | 2022-02-26 12:10:05.432  INFO 9 --- [           main] com.zaxxer.hikari.HikariDataSource       : DolphinScheduler - Shutdown completed.
dolphinscheduler_dolphinscheduler-schema-initializer_1 exited with code 1
```

**Comment by HomminLee** [comment]
I try to use the latest version(2.3.3) of docker-compose and find compose work will. Then change version to 2.1.1, error still occurs.
So, I think the reason for this error is related to docker-compose and has nothing to do with dolphinscheduler. Colse the issue.
If anyone get same error message, can try change docker-compose version.
