### ISSUE TITLE
[Bug] [Master] Failed to pass global parameters between parent and sub process

### ISSUE THREAD

**Issue by you10906** [apache/dolphinscheduler#7753]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When the parent process has global parameters, but the sub process does not have global parameters, a null pointer error will be triggered
`[ERROR] 2021-12-31 14:06:44.898 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[215] - scan command error
java.lang.UnsupportedOperationException: null
        at java.util.AbstractList.add(AbstractList.java:148)
        at java.util.AbstractList.add(AbstractList.java:108)
        at org.apache.dolphinscheduler.service.process.ProcessService.joinGlobalParams(ProcessService.java:1025)
        at org.apache.dolphinscheduler.service.process.ProcessService.setSubProcessParam(ProcessService.java:992)
        at org.apache.dolphinscheduler.service.process.ProcessService.handleCommand(ProcessService.java:226)
        at org.apache.dolphinscheduler.service.process.ProcessService$$FastClassBySpringCGLIB$$ed138739.invoke(<generated>)
`

### What you expected to happen

Global parameters are passed normally

### How to reproduce

Configure two processes, where the sub process has no global parameters, and the parent process  has global parameters

### Version

2.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
I will check this issue.
