### ISSUE TITLE
[Bug] [Master] state handle error caused by NPE in WorkflowExecuteThread

### ISSUE THREAD

**Issue by shangeyao** [apache/dolphinscheduler#7867]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I created a workflow including switch node. 
![image](https://user-images.githubusercontent.com/42203474/148483306-99c992d3-c83b-488d-a211-24c36812307c.png)
![image](https://user-images.githubusercontent.com/42203474/148484169-56e1057c-f02b-45e7-b051-608b83eec362.png)

Then it caused an error.

> `[INFO] 2022-01-07 10:48:22.745 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[257] - process event: State Event :key: null type: TASK_STATE_CHANGE executeStatus: SUCCESS task instance id: 648 process instance id: 505 context: null
[INFO] 2022-01-07 10:48:22.746 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[334] - work flow 505 task 648 state:SUCCESS 
[ERROR] 2022-01-07 10:48:22.747 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[220] - state handle error:
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.dao.utils.DagHelper.skipTaskNode4Switch(DagHelper.java:401)
	at org.apache.dolphinscheduler.dao.utils.DagHelper.parseSwitchTask(DagHelper.java:393)
	at org.apache.dolphinscheduler.dao.utils.DagHelper.parsePostNodes(DagHelper.java:298)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.submitPostNode(WorkflowExecuteThread.java:895)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.taskFinished(WorkflowExecuteThread.java:365)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.taskStateChangeHandler(WorkflowExecuteThread.java:318)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.stateEventHandler(WorkflowExecuteThread.java:268)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.handleEvents(WorkflowExecuteThread.java:216)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.run(WorkflowExecuteThread.java:197)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)`

In addition, task C failed to execute normally.

### What you expected to happen

The state of workflow can change successfully.

### How to reproduce

Above.

### Anything else

Version: 2.0.2.

### Version

2.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
I can't reproduce at local.
BTW, the code line does not match with 2.0.2, so maybe it's other reason.
