### ISSUE TITLE
[Bug] [task-api]  java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration

### ISSUE THREAD

**Issue by AntAndfish** [apache/dolphinscheduler#7878]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

运行hive sql任务时报错，Worker报错日志如下：

[ERROR] 2022-01-07 16:07:59.425 org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread:[210] - task scheduler failure
java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
	at org.apache.dolphinscheduler.plugin.task.util.CommonUtils.loadKerberosConf(CommonUtils.java:84)
	at org.apache.dolphinscheduler.plugin.task.datasource.hive.HiveDatasourceProcessor.getConnection(HiveDatasourceProcessor.java:129)
	at org.apache.dolphinscheduler.plugin.task.datasource.DatasourceUtil.getConnection(DatasourceUtil.java:59)
	at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.executeFuncAndSql(SqlTask.java:184)
	at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.handle(SqlTask.java:155)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:192)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 2022-01-07 16:09:44.639 org.apache.dolphinscheduler.service.log.LogClientService:[117] - view log path D:\projects\dolphinscheduler\logs\1051736946229248_1\165\245.log
[INFO] 2022-01-07 16:09:44.642 org.apache.dolphinscheduler.remote.NettyRemotingClient:[390] - netty client closed

![Uploading image.png…]()

### What you expected to happen

normal run

### How to reproduce

![image](https://user-images.githubusercontent.com/28626264/148515355-318f574d-9141-4cf9-9626-bcc374c7ba8c.png)

### Version

2.0.1

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dachn** [comment]
i got the same problems when is run hive sql in 2.0.0:


[ERROR] 2022-04-16 17:33:41.835 org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread:[210] - task scheduler failure
java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
        at org.apache.dolphinscheduler.plugin.task.util.CommonUtils.loadKerberosConf(CommonUtils.java:84)
        at org.apache.dolphinscheduler.plugin.task.datasource.hive.HiveDatasourceProcessor.getConnection(HiveDatasourceProcessor.java:129)
        at org.apache.dolphinscheduler.plugin.task.datasource.DatasourceUtil.getConnection(DatasourceUtil.java:59)
        at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.executeFuncAndSql(SqlTask.java:184)
        at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.handle(SqlTask.java:155)
        at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:192)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[INFO] 2022-04-16 17:33:42.835 org.apache.dolphinscheduler.service.log.LogClientService:[117] - view log path /dolphinscheduler-2.0.0/logs/5205789032448_1/11348/20123.log。

but i found the jar(hadoop-common-2.7.3.jar) exists in lib path:
lib]# ls |grep hadoop
hadoop-annotations-2.7.3.jar
hadoop-auth-2.7.3.jar
hadoop-aws-2.7.3.jar
hadoop-client-2.7.3.jar
**hadoop-common-2.7.3.jar**
hadoop-hdfs-2.7.3.jar
hadoop-mapreduce-client-app-2.7.3.jar
hadoop-mapreduce-client-common-2.7.3.jar
hadoop-mapreduce-client-core-2.7.3.jar
hadoop-mapreduce-client-jobclient-2.7.3.jar
hadoop-mapreduce-client-shuffle-2.7.3.jar
hadoop-yarn-api-2.7.3.jar
hadoop-yarn-client-2.7.3.jar
hadoop-yarn-common-2.7.3.jar
hadoop-yarn-server-common-2.7.3.jar
parquet-hadoop-bundle-1.8.1.jar

i don't know why it cannot load the jar?

**Comment by gubinjie** [comment]
Is there a solution for this?
