### ISSUE TITLE
[Bug] [Datasource] Failed to execute connection test query (ORA-00923: requested FROM keyword not found

### ISSUE THREAD

**Issue by Skylar-Chen-1** [apache/dolphinscheduler#8117]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Running a oracle procedure Task ,rasing error:
"Failed to execute connection test query"
`[ERROR] 2022-01-19 13:04:32.277 com.zaxxer.hikari.pool.PoolBase:[471] - HikariPool-23 - Failed to execute connection test query (ORA-00923: 未找到要求的 FROM 关键字
).
[ERROR] 2022-01-19 13:04:32.278 com.zaxxer.hikari.pool.HikariPool:[498] - HikariPool-23 - Error thrown while acquiring connection from data source
java.sql.SQLSyntaxErrorException: ORA-00923: 未找到要求的 FROM 关键字

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:195)
	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:876)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1175)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1296)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1916)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1878)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:318)
	at com.zaxxer.hikari.pool.PoolBase.executeSql(PoolBase.java:583)
	at com.zaxxer.hikari.pool.PoolBase.checkValidationSupport(PoolBase.java:467)
	at com.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:447)
	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:416)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:376)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:431)
	at org.apache.dolphinscheduler.plugin.datasource.api.client.CommonDataSourceClient.checkClient(CommonDataSourceClient.java:104)
	at org.apache.dolphinscheduler.plugin.datasource.api.client.CommonDataSourceClient.<init>(CommonDataSourceClient.java:55)
	at org.apache.dolphinscheduler.plugin.datasource.oracle.OracleDataSourceClient.<init>(OracleDataSourceClient.java:27)
	at org.apache.dolphinscheduler.plugin.datasource.oracle.OracleDataSourceChannel.createDataSourceClient(OracleDataSourceChannel.java:29)
	at org.apache.dolphinscheduler.plugin.datasource.api.plugin.DataSourceClientProvider.lambda$getConnection$0(DataSourceClientProvider.java:64)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.apache.dolphinscheduler.plugin.datasource.api.plugin.DataSourceClientProvider.getConnection(DataSourceClientProvider.java:58)
	at org.apache.dolphinscheduler.plugin.task.procedure.ProcedureTask.handle(ProcedureTask.java:102)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:189)
`
seem like this is what happend:
1, 2.0.2:  [OracleConnectionParam] add params:  【validationQuery】
2，in ProcedureTask.handle() ，“DataSourceUtils.buildConnectionParams()” will get an empty "validationQuery"
3，OracleDataSourceChannel.createDataSourceClient  will use default  validationQuery = "select 1"
4， boom ~~~~

### What you expected to happen

fix this BUG 

### How to reproduce

test a ProceduerTask with a Oracle datasource

### Version

2.0.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jim-parsons** [comment]
i checked the latest code of branch dev , class `OracleDataSourceProcessor` do has the right connection query test from method `getValidationQuery` and it returns `select 1 from dual`

**Comment by Skylar-Chen-1** [comment]
I got the problem: 
my DataSource is setup with DS1.7.x  ,and the  datasource config string just like this:
`{
  "database": "dg1",
  "password": "******",
  "address": "jdbc:oracle:thin:@//172.XXXX",
  "connectType": "ORACLE_SERVICE_NAME",
  "jdbcUrl": "jdbc:oracle:thin:@//172.XXXXXX:1521/dg1",
  "user": "XXX"
}`

**Comment by caishunfeng** [comment]
> I got the problem: my DataSource is setup with DS1.7.x ,and the datasource config string just like this: `{ "database": "dg1", "password": "******", "address": "jdbc:oracle:thin:@//172.XXXX", "connectType": "ORACLE_SERVICE_NAME", "jdbcUrl": "jdbc:oracle:thin:@//172.XXXXXX:1521/dg1", "user": "XXX" }`

@Skylar-Chen-1 can you check this issue in 2.0.3?

**Comment by caishunfeng** [comment]
close by #8889
