### ISSUE TITLE
[Improvement][Document] Standalone Deployment doc should instruct users to configure sudo without password

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#8295]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* In the `Installation` session of ds doc, `Standalone Deployment` currently does not instruct users to configure `sudo` without password while `Pseudo-Cluster Deployment` does, which may cause confusion and is not user-friendly.
* As a new user to ds, after reading the installation doc, I thought in `standalone` mode, I didn't need to configure `sudo` without password. As a result of this misunderstanding, I failed to run shell tasks and spent some time debugging. There could be  error log like below:

```
org.apache.dolphinscheduler.common.shell.AbstractShell$ExitCodeException: sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper

	at org.apache.dolphinscheduler.common.shell.AbstractShell.runCommand(AbstractShell.java:207)
	at org.apache.dolphinscheduler.common.shell.AbstractShell.run(AbstractShell.java:122)
	at org.apache.dolphinscheduler.common.shell.ShellExecutor.execute(ShellExecutor.java:126)
	at org.apache.dolphinscheduler.common.shell.ShellExecutor.execCommand(ShellExecutor.java:103)
	at org.apache.dolphinscheduler.common.shell.ShellExecutor.execCommand(ShellExecutor.java:86)
	at org.apache.dolphinscheduler.common.utils.OSUtils.exeShell(OSUtils.java:400)
	at org.apache.dolphinscheduler.common.utils.OSUtils.exeCmd(OSUtils.java:389)
	at org.apache.dolphinscheduler.common.utils.OSUtils.createMacUser(OSUtils.java:308)
	at org.apache.dolphinscheduler.common.utils.OSUtils.createUser(OSUtils.java:268)
	at org.apache.dolphinscheduler.common.utils.OSUtils.createUserIfAbsent(OSUtils.java:248)
	at org.apache.dolphinscheduler.server.worker.processor.TaskExecuteProcessor.process(TaskExecuteProcessor.java:143)
	at org.apache.dolphinscheduler.remote.handler.NettyServerHandler.lambda$processReceived$0(NettyServerHandler.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
I think standalone maybe could just ignore the rule `sudo`, I would task a look later

**Comment by EricGao888** [comment]
> Reference in new issue



> I think standalone maybe could just ignore the rule `sudo`, I would task a look later

```
[INFO] 2022-02-07 14:31:49.336 org.apache.dolphinscheduler.common.utils.OSUtils:[304] - create mac os user: eric
[INFO] 2022-02-07 14:31:49.336 org.apache.dolphinscheduler.common.utils.OSUtils:[307] - create user command: sudo sysadminctl -addUser eric -password eric
[ERROR] 2022-02-07 14:31:49.393 org.apache.dolphinscheduler.common.utils.OSUtils:[276] - sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
```

* From the log above, it seems the cmd `sudo sysadminctl -addUser eric -password eric` causes the exception.
* I tried to run the cmd without sudo, got some error message like this `sysadminctl[84263:9559332] sysadminctl should be run as root, or in interactive mode! (Error Domain=NSOSStatusErrorDomain Code=-60007 "errAuthorizationInteractionNotAllowed: The authorization was denied since no user interaction was possible. ")`

**Comment by thredreams** [comment]
I encountered the same problem. I solved it by manually linking to the container to update apt and installing sudo.

**Comment by EricGao888** [comment]
> I encountered the same problem. I solved it by manually linking to the container to update apt and installing sudo.

@rickchengx Have u ever encountered this issue?

**Comment by klboke** [comment]
> From the log above, it seems the cmd sudo sysadminctl -addUser eric -password eric causes the exception.

This is right, if the mac is only used for the development environment, you can create a tenant name with the same name as your mac user name
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/18591662/209070258-e8f61368-261e-4b03-bde3-3de08d9db39f.png">
