### ISSUE TITLE
[Bug] [API] Update process definition error

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#8296]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

```
[ERROR] 2022-02-07 17:44:03.394 org.apache.dolphinscheduler.api.service.impl.ProcessDefinitionServiceImpl:[332] - error:
java.lang.IllegalStateException: Duplicate key TaskDefinition{id=0, code=3909232388448, name='依赖检查', version=1, description='', projectCode=0, userId=0, taskType=DEPENDENT, taskParams='{"dependence":{"relation":"AND","dependTaskList":[{"relation":"AND","dependItemList":[{"projectCode":3909232228064,"definitionCode":3909232229350,"depTaskCode":0,"cycle":"day","dateValue":"today"}]},{"relation":"AND","dependItemList":[{"projectCode":3909232228064,"definitionCode":3909232232293,"depTaskCode":0,"cycle":"day","dateValue":"today"},{"projectCode":3909232228064,"definitionCode":3909232229346,"depTaskCode":0,"cycle":"day","dateValue":"today"},{"projectCode":3909232228064,"definitionCode":3909232230758,"depTaskCode":0,"cycle":"day","dateValue":"today"},{"projectCode":3909232228064,"definitionCode":3909232230759,"depTaskCode":0,"cycle":"day","dateValue":"today"},{"projectCode":3909232228064,"definitionCode":3909232230765,"depTaskCode":0,"cycle":"day","dateValue":"today"},{"projectCode":3909232228064,"definitionCode":3909232230761,"depTaskCode":0,"cycle":"day","dateValue":"today"},{"projectCode":3909232228064,"definitionCode":3909232230760,"depTaskCode":0,"cycle":"day","dateValue":"today"},{"projectCode":3909232228064,"definitionCode":3909232230887,"depTaskCode":0,"cycle":"day","dateValue":"today"},{"projectCode":3909232228064,"definitionCode":3909232230506,"depTaskCode":0,"cycle":"day","dateValue":"today"},{"projectCode":3909232228064,"definitionCode":3909232230517,"depTaskCode":0,"cycle":"day","dateValue":"today"},{"projectCode":3909232228064,"definitionCode":3909232230259,"depTaskCode":0,"cycle":"day","dateValue":"today"},{"projectCode":3909232228064,"definitionCode":3909232231796,"depTaskCode":0,"cycle":"day","dateValue":"today"},{"projectCode":3909232228064,"definitionCode":3909232230263,"depTaskCode":0,"cycle":"day","dateValue":"today"},{"projectCode":3909232228064,"definitionCode":3909232230628,"depTaskCode":0,"cycle":"day","dateValue":"today"}]}]},"conditionResult":{"successNode":[],"failedNode":[]},"waitStartTimeout":{"strategy":"FAILED","interval":null,"checkInterval":null,"enable":false},"switchResult":{}}', taskParamList=null, taskParamMap=null, flag=YES, taskPriority=MEDIUM, userName='null', projectName='null', workerGroup='offline-cluster', failRetryTimes=720, environmentCode='-1', failRetryInterval=1, timeoutFlag=CLOSE, timeoutNotifyStrategy=null, timeout=0, delayTime=0, resourceIds='null', createTime=null, updateTime=null}
        at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
        at java.util.HashMap.merge(HashMap.java:1255)
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at org.apache.dolphinscheduler.service.process.ProcessService.transformTask(ProcessService.java:2517)
        at org.apache.dolphinscheduler.service.process.ProcessService$$FastClassBySpringCGLIB$$ed138739.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
        at org.apache.dolphinscheduler.service.process.ProcessService$$EnhancerBySpringCGLIB$$a43f595c.transformTask(<generated>)
        at org.apache.dolphinscheduler.api.service.impl.ProcessDefinitionServiceImpl.checkTaskRelationList(ProcessDefinitionServiceImpl.java:305)
        at org.apache.dolphinscheduler.api.service.impl.ProcessDefinitionServiceImpl.updateProcessDefinition(ProcessDefinitionServiceImpl.java:528)
        at org.apache.dolphinscheduler.api.service.impl.ProcessDefinitionServiceImpl$$FastClassBySpringCGLIB$$e8e34ed9.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
        at org.apache.dolphinscheduler.api.service.impl.ProcessDefinitionServiceImpl$$EnhancerBySpringCGLIB$$1978743c.updateProcessDefinition(<generated>)
        at org.apache.dolphinscheduler.api.controller.ProcessDefinitionController.updateProcessDefinition(ProcessDefinitionController.java:249)
        at org.apache.dolphinscheduler.api.controller.ProcessDefinitionController$$FastClassBySpringCGLIB$$dc9bf5db.invoke(<generated>)
```

### What you expected to happen

update successfully.

### How to reproduce

update successfully.

### Version

2.0.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jim-parsons** [comment]
see this #8043

**Comment by SbloodyS** [comment]
> see this #8043

Thanks. I think it's different. My problems looks similar to #8173. And I've found the problems. I will submit a PR to fix this problem tomorrow.
