### ISSUE TITLE
[Bug] [Worker Server] shell task error java.nio.file.NoSuchFileException

### ISSUE THREAD

**Issue by shangeyao** [apache/dolphinscheduler#8311]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened
```

[INFO] 2022-02-09 04:15:03.388 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[138] - task execute path : /data/dolphinscheduler/exec/process/853772144123904/853777148452864_2/308426/645680
[ERROR] 2022-02-09 04:15:03.389 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[103] - shell task error
java.nio.file.NoSuchFileException: /data/dolphinscheduler/exec/process/853772144123904/853777148452864_2/308426/645680/308426_645680_node.sh
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.createFile(Files.java:632)
	at org.apache.dolphinscheduler.plugin.task.shell.ShellTask.buildCommand(ShellTask.java:146)
	at org.apache.dolphinscheduler.plugin.task.shell.ShellTask.handle(ShellTask.java:96)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:193)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### What you expected to happen

Shell task created all files successfully.

### How to reproduce

The bug appears accidentally. It is speculated that too many files are created at the same time.

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Yao-MR** [comment]
hi @shangeyao can you share more information? such as the unix or windows?

**Comment by Yao-MR-zz** [comment]
hi @shangeyao  @caishunfeng can you make a review ?

**Comment by caishunfeng** [comment]
> hi @shangeyao @caishunfeng can you make a review ?

OK, I had reviewed the pr and merged it. Thanks for your contribution.
