### ISSUE TITLE
[Bug] [Shell] Use shell to call .sh script, call hive -e in .sh script and report ERROR XBM0H

### ISSUE THREAD

**Issue by jchen811** [apache/dolphinscheduler#8916]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Logging initialized using configuration in jar:file:/opt/apps/ecm/service/hive/2.3.7-1.1.7/package/apache-hive-2.3.7-1.1.7-bin/lib/hive-common-2.3.7.jar!/hive-log4j2.properties Async: true
[INFO] 2022-03-15 19:02:30.423 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[66] -  -> Tue Mar 15 19:02:30 CST 2022 Thread[7c9892df-bfd0-4355-b9d8-76fd1286442c main,5,main] java.io.FileNotFoundException: derby.log (权限不够)
[INFO] 2022-03-15 19:02:31.425 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[66] -  -> Tue Mar 15 19:02:30 CST 2022 Thread[7c9892df-bfd0-4355-b9d8-76fd1286442c main,5,main] Cleanup action starting
	ERROR XBM0H: Directory /tmp/dolphinscheduler/exec/process/4641209403712/4840693783232_3/161/263/metastore_db cannot be created.
		at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
		at org.apache.derby.impl.services.monitor.StorageFactoryService$10.run(Unknown Source)
		at java.security.AccessController.doPrivileged(Native Method)
		at org.apache.derby.impl.services.monitor.StorageFactoryService.createServiceRoot(Unknown Source)
		at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(Unknown Source)
		at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(Unknown Source)
		at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Unknown Source)
		at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(Unknown Source)
		at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
		at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
		at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)

### What you expected to happen

Logging initialized using configuration in jar:file:/opt/apps/ecm/service/hive/2.3.7-1.1.7/package/apache-hive-2.3.7-1.1.7-bin/lib/hive-common-2.3.7.jar!/hive-log4j2.properties Async: true
[INFO] 2022-03-15 19:02:30.423 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[66] -  -> Tue Mar 15 19:02:30 CST 2022 Thread[7c9892df-bfd0-4355-b9d8-76fd1286442c main,5,main] java.io.FileNotFoundException: derby.log (权限不够)
[INFO] 2022-03-15 19:02:31.425 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[66] -  -> Tue Mar 15 19:02:30 CST 2022 Thread[7c9892df-bfd0-4355-b9d8-76fd1286442c main,5,main] Cleanup action starting
	ERROR XBM0H: Directory /tmp/dolphinscheduler/exec/process/4641209403712/4840693783232_3/161/263/metastore_db cannot be created.
		at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
		at org.apache.derby.impl.services.monitor.StorageFactoryService$10.run(Unknown Source)
		at java.security.AccessController.doPrivileged(Native Method)
		at org.apache.derby.impl.services.monitor.StorageFactoryService.createServiceRoot(Unknown Source)
		at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(Unknown Source)
		at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(Unknown Source)
		at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Unknown Source)
		at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(Unknown Source)
		at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
		at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
		at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)

### How to reproduce

使用shell调用shell脚本
shell脚本里引用hive -e "hive sql"

### Version

2.0.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
> java.io.FileNotFoundException: derby.log (权限不够)

please check the permission of the tenant you use.
