### ISSUE TITLE
[Bug] [Python] tutorial.py don't work

### ISSUE THREAD

**Issue by jieguangzhou** [apache/dolphinscheduler#8919]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Traceback (most recent call last):
  File "src/pydolphinscheduler/examples/tutorial.py", line 66, in <module>
    pd.run()
  File "/home/lucky/WhaleOps/dolphinscheduler/dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/process_definition.py", line 322, in run
    self.submit()
  File "/home/lucky/WhaleOps/dolphinscheduler/dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/process_definition.py", line 357, in submit
    self._ensure_side_model_exists()
  File "/home/lucky/WhaleOps/dolphinscheduler/dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/process_definition.py", line 336, in _ensure_side_model_exists
    self.user.create_if_not_exists()
  File "/home/lucky/WhaleOps/dolphinscheduler/dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/side/user.py", line 67, in create_if_not_exists
    self.status,
  File "/home/lucky/env/dolphin/lib/python3.7/site-packages/py4j-0.10.9.3-py3.7.egg/py4j/java_gateway.py", line 1322, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/lucky/env/dolphin/lib/python3.7/site-packages/py4j-0.10.9.3-py3.7.egg/py4j/protocol.py", line 332, in get_return_value
    format(target_id, ".", name, value))
py4j.protocol.Py4JError: An error occurred while calling t.createUser. Trace:
py4j.Py4JException: Method createUser([class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.Long, class java.lang.String, class java.lang.String, class java.lang.Integer]) does not exist
        at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
        at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
        at py4j.Gateway.invoke(Gateway.java:274)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)

<img width="1563" alt="image" src="https://user-images.githubusercontent.com/31528124/158382894-002534e7-1f34-40b5-9c7c-c583bd294900.png">

### What you expected to happen

Maybe Python code is out of sync with Java code

### How to reproduce

python src/pydolphinscheduler/examples/tutorial.py

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Hi @jieguangzhou could you make sure about this? we have an integration test to submit example to python gateway server to test whether our example(almost all of them) work or not. And in https://github.com/apache/dolphinscheduler/pull/8966 it work correctly.

**Comment by zhongjiajie** [comment]
Hi, I check the latest code in dev branch, it work correctly, so I add `wontfix` label on it and close it. you could reopen it if you miss the same issue.

To verify that, please make sure you install latest pydolphinscheduler in the source code instead of pypi by command `pip install -e .`
