### ISSUE TITLE
[Bug] [Server] Master/Worker cannot be started on Mac OS M1

### ISSUE THREAD

**Issue by brave-lee** [apache/dolphinscheduler#9530]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/ll/jzj5vhjj10b_n85w42gkgd240000gn/T/jna-107020/jna404055612302368313.tmp: dlopen(/private/var/folders/ll/jzj5vhjj10b_n85w42gkgd240000gn/T/jna-107020/jna404055612302368313.tmp, 0x0001): tried: '/private/var/folders/ll/jzj5vhjj10b_n85w42gkgd240000gn/T/jna-107020/jna404055612302368313.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), '/usr/lib/jna404055612302368313.tmp' (no such file)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)
	at java.lang.Runtime.load0(Runtime.java:811)
	at java.lang.System.load(System.java:1088)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:947)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.Structure.<clinit>(Structure.java:2130)
	at oshi.hardware.platform.mac.MacCentralProcessor.<clinit>(MacCentralProcessor.java:53)
	at oshi.hardware.platform.mac.MacHardwareAbstractionLayer.getProcessor(MacHardwareAbstractionLayer.java:54)
	at org.apache.dolphinscheduler.common.utils.OSUtils.cpuUsage(OSUtils.java:129)
	at org.apache.dolphinscheduler.common.utils.HeartBeat.fillSystemInfo(HeartBeat.java:176)
	at org.apache.dolphinscheduler.common.utils.HeartBeat.encodeHeartBeat(HeartBeat.java:204)
	at org.apache.dolphinscheduler.server.registry.HeartBeatTask.getHeartBeatInfo(HeartBeatTask.java:72)
	at org.apache.dolphinscheduler.server.worker.registry.WorkerRegistryClient.registry(WorkerRegistryClient.java:119)

### What you expected to happen

Master/Worker can start normally at Mac OS M1.

### How to reproduce

Master/Worker starts on Mac OS M1.

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by brave-lee** [comment]
I found that this problem has been solved through #8390 PR in dev, and I will close this issue.
