### ISSUE TITLE
[Bug] [Upgrade module] upgrade 1.3.5 to 3.0.0 alpha execute SQL failed

### ISSUE THREAD

**Issue by syncwt** [apache/dolphinscheduler#9941]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When do `sh tools/bin/upgrade-schema.sh` some error happened at list :
```shell
2022-05-07 18:14:03.436  INFO 6277 --- [           main] o.a.d.common.utils.ScriptRunner          : sql: alter table t_ds_task_definition_log add `task_group_id` int(11) DEFAULT NULL COMMENT 'task group id' AFTER `resource_ids`
2022-05-07 18:14:03.439 ERROR 6277 --- [           main] o.a.d.common.utils.ScriptRunner          : SQLException

com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'task_group_id'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_322]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_322]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_322]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_322]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.Util.getInstance(Util.java:386) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1054) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4237) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4169) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2617) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2778) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2819) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2768) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:894) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:732) ~[mysql-connector-java-5.1.27.jar:na]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-4.0.3.jar:na]
	at org.apache.dolphinscheduler.common.utils.ScriptRunner.runScript(ScriptRunner.java:118) [dolphinscheduler-common-3.0.0-alpha.jar:3.0.0-alpha]
	at org.apache.dolphinscheduler.common.utils.ScriptRunner.runScript(ScriptRunner.java:73) [dolphinscheduler-common-3.0.0-alpha.jar:3.0.0-alpha]
	at org.apache.dolphinscheduler.tools.datasource.dao.UpgradeDao.upgradeDolphinSchedulerDDL(UpgradeDao.java:366) [dolphinscheduler-tools-3.0.0-alpha.jar:3.0.0-alpha]
	at org.apache.dolphinscheduler.tools.datasource.dao.UpgradeDao.upgradeDolphinScheduler(UpgradeDao.java:147) [dolphinscheduler-tools-3.0.0-alpha.jar:3.0.0-alpha]
	at org.apache.dolphinscheduler.tools.datasource.DolphinSchedulerManager.upgradeDolphinScheduler(DolphinSchedulerManager.java:109) [dolphinscheduler-tools-3.0.0-alpha.jar:3.0.0-alpha]
	at org.apache.dolphinscheduler.tools.datasource.CreateDolphinScheduler$CreateRunner.run(CreateDolphinScheduler.java:46) [dolphinscheduler-tools-3.0.0-alpha.jar:3.0.0-alpha]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791) [spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775) [spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) [spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) [spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) [spring-boot-2.5.6.jar:2.5.6]
	at org.apache.dolphinscheduler.tools.datasource.UpgradeDolphinScheduler.main(UpgradeDolphinScheduler.java:30) [dolphinscheduler-tools-3.0.0-alpha.jar:3.0.0-alpha]

2022-05-07 18:14:03.439 ERROR 6277 --- [           main] o.a.d.common.utils.ScriptRunner          : Error executing: alter table t_ds_task_definition_log add `task_group_id` int(11) DEFAULT NULL COMMENT 'task group id' AFTER `resource_ids`
2022-05-07 18:14:03.440 ERROR 6277 --- [           main] o.a.d.tools.datasource.dao.UpgradeDao    : Duplicate column name 'task_group_id'

com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'task_group_id'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_322]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_322]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_322]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_322]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.Util.getInstance(Util.java:386) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1054) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4237) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4169) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2617) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2778) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2819) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2768) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:894) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:732) ~[mysql-connector-java-5.1.27.jar:na]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-4.0.3.jar:na]
	at org.apache.dolphinscheduler.common.utils.ScriptRunner.runScript(ScriptRunner.java:118) ~[dolphinscheduler-common-3.0.0-alpha.jar:3.0.0-alpha]
	at org.apache.dolphinscheduler.common.utils.ScriptRunner.runScript(ScriptRunner.java:73) ~[dolphinscheduler-common-3.0.0-alpha.jar:3.0.0-alpha]
	at org.apache.dolphinscheduler.tools.datasource.dao.UpgradeDao.upgradeDolphinSchedulerDDL(UpgradeDao.java:366) [dolphinscheduler-tools-3.0.0-alpha.jar:3.0.0-alpha]
	at org.apache.dolphinscheduler.tools.datasource.dao.UpgradeDao.upgradeDolphinScheduler(UpgradeDao.java:147) [dolphinscheduler-tools-3.0.0-alpha.jar:3.0.0-alpha]
	at org.apache.dolphinscheduler.tools.datasource.DolphinSchedulerManager.upgradeDolphinScheduler(DolphinSchedulerManager.java:109) [dolphinscheduler-tools-3.0.0-alpha.jar:3.0.0-alpha]
	at org.apache.dolphinscheduler.tools.datasource.CreateDolphinScheduler$CreateRunner.run(CreateDolphinScheduler.java:46) [dolphinscheduler-tools-3.0.0-alpha.jar:3.0.0-alpha]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791) [spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775) [spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) [spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) [spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) [spring-boot-2.5.6.jar:2.5.6]
	at org.apache.dolphinscheduler.tools.datasource.UpgradeDolphinScheduler.main(UpgradeDolphinScheduler.java:30) [dolphinscheduler-tools-3.0.0-alpha.jar:3.0.0-alpha]

2022-05-07 18:14:03.443  INFO 6277 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-05-07 18:14:03.458 ERROR 6277 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:794) [spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775) [spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) [spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) [spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) [spring-boot-2.5.6.jar:2.5.6]
	at org.apache.dolphinscheduler.tools.datasource.UpgradeDolphinScheduler.main(UpgradeDolphinScheduler.java:30) [dolphinscheduler-tools-3.0.0-alpha.jar:3.0.0-alpha]
Caused by: java.lang.RuntimeException: Duplicate column name 'task_group_id'
	at org.apache.dolphinscheduler.tools.datasource.dao.UpgradeDao.upgradeDolphinSchedulerDDL(UpgradeDao.java:374) ~[dolphinscheduler-tools-3.0.0-alpha.jar:3.0.0-alpha]
	at org.apache.dolphinscheduler.tools.datasource.dao.UpgradeDao.upgradeDolphinScheduler(UpgradeDao.java:147) ~[dolphinscheduler-tools-3.0.0-alpha.jar:3.0.0-alpha]
	at org.apache.dolphinscheduler.tools.datasource.DolphinSchedulerManager.upgradeDolphinScheduler(DolphinSchedulerManager.java:109) ~[dolphinscheduler-tools-3.0.0-alpha.jar:3.0.0-alpha]
	at org.apache.dolphinscheduler.tools.datasource.CreateDolphinScheduler$CreateRunner.run(CreateDolphinScheduler.java:46) ~[dolphinscheduler-tools-3.0.0-alpha.jar:3.0.0-alpha]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791) [spring-boot-2.5.6.jar:2.5.6]
	... 5 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'task_group_id'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_322]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_322]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_322]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_322]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.Util.getInstance(Util.java:386) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1054) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4237) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4169) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2617) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2778) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2819) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2768) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:894) ~[mysql-connector-java-5.1.27.jar:na]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:732) ~[mysql-connector-java-5.1.27.jar:na]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-4.0.3.jar:na]
	at org.apache.dolphinscheduler.common.utils.ScriptRunner.runScript(ScriptRunner.java:118) ~[dolphinscheduler-common-3.0.0-alpha.jar:3.0.0-alpha]
	at org.apache.dolphinscheduler.common.utils.ScriptRunner.runScript(ScriptRunner.java:73) ~[dolphinscheduler-common-3.0.0-alpha.jar:3.0.0-alpha]
	at org.apache.dolphinscheduler.tools.datasource.dao.UpgradeDao.upgradeDolphinSchedulerDDL(UpgradeDao.java:366) ~[dolphinscheduler-tools-3.0.0-alpha.jar:3.0.0-alpha]
	... 9 common frames omitted

2022-05-07 18:14:03.460  INFO 6277 --- [           main] com.zaxxer.hikari.HikariDataSource       : DolphinScheduler - Shutdown initiated...
2022-05-07 18:14:03.463  INFO 6277 --- [           main] com.zaxxer.hikari.HikariDataSource       : DolphinScheduler - Shutdown completed.
```

### What you expected to happen

no  error ,work well.

### How to reproduce

rerun upgrade shell

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
you tarball is dwonload from https://dolphinscheduler.apache.org/en-us/download/download.html or build by yourself?

**Comment by syncwt** [comment]
> you tarball is dwonload from https://dolphinscheduler.apache.org/en-us/download/download.html or build by yourself?

download from ‘https://dolphinscheduler.apache.org/zh-cn/download/download.html’ .3.0.0-alpha with Total Binary Distribution format,And download site is 'https://www.apache.org/dyn/closer.lua/dolphinscheduler/3.0.0-alpha/apache-dolphinscheduler-3.0.0-alpha-bin.tar.gz'

**Comment by syncwt** [comment]
It works well when I upgrade '1.3.5' to '2.0.5-release'. Please check the DDL of upgrading's script and create more test case.
Otherwise , the current document of upgrading was replaced by new version, maybe the  older version should be saved.

**Comment by syncwt** [comment]
> It works well when I upgrade '1.3.5' to '2.0.5-release'. Please check the DDL of upgrading's script and create more test case. Otherwise , the current document of upgrading was replaced by new version, maybe the older version should be saved.

**Comment by zhongjiajie** [comment]
@syncwt version 3.0.0 DDL have some bug, and we will fix it in 300-beta. BTW, you could see the history doc in https://dolphinscheduler.apache.org/en-us/docs/release/history-versions.html

**Comment by zhongjiajie** [comment]
remove stale

**Comment by zhongjiajie** [comment]
duplicate to #10377 , will try to fix in that issue
